%TEST_SPECTRATRIMMER

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	st = SpectraTrimmer();
	 
	% get('ELCLASS')
	if isa(SpectraTrimmer, 'ConcreteElement')
		assert(strcmp(SpectraTrimmer().get('ELCLASS'), 'SpectraTrimmer'), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'SpectraTrimmer().get(''ELCLASS'') should return ''SpectraTrimmer''.')
	end
	 
	% getBuild()
	assert(SpectraTrimmer.getBuild() == 1 && SpectraTrimmer.getBuild() > 0, ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'SpectraTrimmer.getBuild() should return the SpectraTrimmer build number.')
	assert(st.getBuild() == 1 && st.getBuild() > 0 , ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'st.getBuild() should return the SpectraTrimmer build number.')
	assert(Element.getBuild(st) == 1 && Element.getBuild(st) > 0, ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(st) should return the SpectraTrimmer build number.')
	assert(Element.getBuild('SpectraTrimmer') == 1 && Element.getBuild('SpectraTrimmer') > 0, ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''SpectraTrimmer'') should return the SpectraTrimmer build number.')
	 
	% getClass()
	assert(strcmp(SpectraTrimmer.getClass(), 'SpectraTrimmer'), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'SpectraTrimmer.getClass() should return ''SpectraTrimmer''.')
	assert(strcmp(st.getClass(), 'SpectraTrimmer'), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'st.getClass() should return ''SpectraTrimmer''.')
	assert(strcmp(Element.getClass(st), 'SpectraTrimmer'), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(st) should return ''SpectraTrimmer''.')
	assert(strcmp(Element.getClass('SpectraTrimmer'), 'SpectraTrimmer'), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''SpectraTrimmer'') should return ''SpectraTrimmer''.')
	 
	% getSubclasses()
	assert(isequal(SpectraTrimmer.getSubclasses(), subclasses('SpectraTrimmer', [], [], true)), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'SpectraTrimmer.getSubclasses() should return the same result as subclasses(''SpectraTrimmer'', [], [], true).')
	assert(isequal(st.getSubclasses(), subclasses('SpectraTrimmer', [], [], true)), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''SpectraTrimmer'', [], [], true).')
	assert(isequal(Element.getSubclasses(st), subclasses('SpectraTrimmer', [], [], true)), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(st) should return the same result as subclasses(''SpectraTrimmer'', [], [], true).')
	assert(isequal(Element.getSubclasses('SpectraTrimmer'), subclasses('SpectraTrimmer', [], [], true)), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''SpectraTrimmer'') should return the same result as subclasses(''SpectraTrimmer'', [], [], true).')
	 
	% getProps()
	assert(isempty(SpectraTrimmer.getProps()) || isequal(SpectraTrimmer.getProps(), 1:1:length(SpectraTrimmer.getProps())), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'SpectraTrimmer.getProps() should return a row vector [1:1:N].')
	assert(isempty(SpectraTrimmer.getProps()) || isequal(st.getProps(), 1:1:length(SpectraTrimmer.getProps())), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'st.getProps() should return a row vector [1:1:N].')
	assert(isempty(SpectraTrimmer.getProps()) || isequal(Element.getProps(st), 1:1:length(SpectraTrimmer.getProps())), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(st) should return a row vector [1:1:N].')
	assert(isempty(SpectraTrimmer.getProps()) || isequal(Element.getProps('SpectraTrimmer'), 1:1:length(SpectraTrimmer.getProps())), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''SpectraTrimmer'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) SpectraTrimmer.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(SpectraTrimmer.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SpectraTrimmer.getProps())), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'SpectraTrimmer.getProps(category) does not work.')
	tmp = cellfun(@(category) st.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(SpectraTrimmer.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SpectraTrimmer.getProps())), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'st.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(st, category), categories, 'UniformOutput', false);
	assert(isempty(SpectraTrimmer.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SpectraTrimmer.getProps())), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(st, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('SpectraTrimmer', category), categories, 'UniformOutput', false);
	assert(isempty(SpectraTrimmer.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(SpectraTrimmer.getProps())), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''SpectraTrimmer'', category) does not work.')
	 
	% getPropNumber()
	assert(SpectraTrimmer.getPropNumber() == length(SpectraTrimmer.getProps()), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'SpectraTrimmer.getPropNumber() should return the number of properties.')
	assert(st.getPropNumber() == length(SpectraTrimmer.getProps()), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'st.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(st) == length(SpectraTrimmer.getProps()), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(st) should return the number of properties.')
	assert(Element.getPropNumber('SpectraTrimmer') == length(SpectraTrimmer.getProps()), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''SpectraTrimmer'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) SpectraTrimmer.getPropNumber(category), categories)) == SpectraTrimmer.getPropNumber(), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'SpectraTrimmer.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) st.getPropNumber(category), categories)) == SpectraTrimmer.getPropNumber(), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'st.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(st, category), categories)) == SpectraTrimmer.getPropNumber(), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(st, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('SpectraTrimmer', category), categories)) == SpectraTrimmer.getPropNumber(), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''SpectraTrimmer'', category) does not work.')
	 
	% existsProp(prop)
	assert(~SpectraTrimmer.existsProp(NaN), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'SpectraTrimmer.existsProp(prop) does not work.')
	assert(~st.existsProp(NaN), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'st.existsProp(prop) does not work.')
	assert(~Element.existsProp(st, NaN), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(st, prop) does not work.')
	assert(~Element.existsProp('SpectraTrimmer', NaN), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''SpectraTrimmer'', prop) does not work.')
	 
	assert_with_error('SpectraTrimmer.existsProp(NaN)', [BRAPH2.STR ':SpectraTrimmer:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':SpectraTrimmer:' BRAPH2.WRONG_INPUT], st)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':SpectraTrimmer:' BRAPH2.WRONG_INPUT], st)
	assert_with_error('Element.existsProp(''SpectraTrimmer'', NaN)', [BRAPH2.STR ':SpectraTrimmer:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		assert(SpectraTrimmer.existsProp(prop), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'SpectraTrimmer.existsProp(prop) does not work.')
		assert(st.existsProp(prop), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'st.existsProp(prop) does not work.')
		assert(Element.existsProp(st, prop), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(st, prop) does not work.')
		assert(Element.existsProp('SpectraTrimmer', prop), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''SpectraTrimmer'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~SpectraTrimmer.existsTag(''), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'SpectraTrimmer.existsTag(tag) does not work.')
	assert(~st.existsTag(''), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'st.existsTag(tag) does not work.')
	assert(~Element.existsTag(st, ''), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(st, tag) does not work.')
	assert(~Element.existsTag('SpectraTrimmer', ''), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''SpectraTrimmer'', tag) does not work.')
	 
	assert_with_error('SpectraTrimmer.existsTag('''')', [BRAPH2.STR ':SpectraTrimmer:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':SpectraTrimmer:' BRAPH2.WRONG_INPUT], st)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':SpectraTrimmer:' BRAPH2.WRONG_INPUT], st)
	assert_with_error('Element.existsTag(''SpectraTrimmer'', '''')', [BRAPH2.STR ':SpectraTrimmer:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		tag = st.getPropTag(prop);
		assert(SpectraTrimmer.existsTag(tag), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'SpectraTrimmer.existsTag(tag) does not work.')
		assert(st.existsTag(tag), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'st.existsTag(tag) does not work.')
		assert(Element.existsTag(st, tag), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(st, tga) does not work.')
		assert(Element.existsTag('SpectraTrimmer', tag), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''SpectraTrimmer'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		assert(SpectraTrimmer.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'SpectraTrimmer.getPropProp(prop) does not work.')
		assert(st.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'st.getPropProp(prop) does not work.')
		assert(Element.getPropProp(st, prop) == prop, ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(st, prop) does not work.')
		assert(Element.getPropProp('SpectraTrimmer', prop) == prop, ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''SpectraTrimmer'', prop) does not work.')
	 
		tag = st.getPropTag(prop);
		assert(SpectraTrimmer.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'SpectraTrimmer.getPropProp(tag) does not work.')
		assert(st.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'st.getPropProp(tag) does not work.')
		assert(Element.getPropProp(st, tag) == prop, ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(st, tag) does not work.')
		assert(Element.getPropProp('SpectraTrimmer', prop) == prop, ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''SpectraTrimmer'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		tag = st.getPropTag(prop);
	 
		assert(strcmp(SpectraTrimmer.getPropTag(prop), tag), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'SpectraTrimmer.getPropTag(prop) does not work.')
		assert(strcmp(st.getPropTag(prop), tag), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'st.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(st, prop), tag), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(st, prop) does not work.')
		assert(strcmp(Element.getPropTag('SpectraTrimmer', prop), tag), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''SpectraTrimmer'', prop) does not work.')
	 
		assert(strcmp(SpectraTrimmer.getPropTag(tag), tag), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'SpectraTrimmer.getPropTag(tag) does not work.')
		assert(strcmp(st.getPropTag(tag), tag), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'st.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(st, tag), tag), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(st, tag) does not work.')
		assert(strcmp(Element.getPropTag('SpectraTrimmer', prop), tag), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''SpectraTrimmer'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		tag = st.getPropTag(prop);
	 
		assert(Category.existsCategory(SpectraTrimmer.getPropCategory(prop)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'SpectraTrimmer.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(st.getPropCategory(prop)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'st.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(st, prop)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(st, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(st, prop)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''SpectraTrimmer'', prop) does not work.')
	 
		assert(Category.existsCategory(SpectraTrimmer.getPropCategory(tag)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'SpectraTrimmer.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(st.getPropCategory(tag)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'st.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(st, tag)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(st, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(st, tag)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''SpectraTrimmer'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		tag = st.getPropTag(prop);
	 
		assert(Format.existsFormat(SpectraTrimmer.getPropFormat(prop)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'SpectraTrimmer.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(st.getPropFormat(prop)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'st.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(st, prop)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(st, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(st, prop)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''SpectraTrimmer'', prop) does not work.')
	 
		assert(Format.existsFormat(SpectraTrimmer.getPropFormat(tag)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'SpectraTrimmer.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(st.getPropFormat(tag)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'st.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(st, tag)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(st, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(st, tag)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''SpectraTrimmer'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		tag = st.getPropTag(prop);
	 
		assert(ischar(SpectraTrimmer.getPropDescription(prop)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'SpectraTrimmer.getPropDescription(prop) does not work.')
		assert(ischar(st.getPropDescription(prop)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'st.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(st, prop)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(st, prop) does not work.')
		assert(ischar(Element.getPropDescription(st, prop)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''SpectraTrimmer'', prop) does not work.')
	 
		assert(ischar(SpectraTrimmer.getPropDescription(tag)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'SpectraTrimmer.getPropDescription(tag) does not work.')
		assert(ischar(st.getPropDescription(tag)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'st.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(st, tag)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(st, tag) does not work.')
		assert(ischar(Element.getPropDescription(st, tag)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''SpectraTrimmer'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		tag = st.getPropTag(prop);
	 
		settings = SpectraTrimmer.getPropSettings(prop);
		settings = st.getPropSettings(prop);
		settings = Element.getPropSettings(st, prop);
		settings = Element.getPropSettings('SpectraTrimmer', prop);
	 
		settings = SpectraTrimmer.getPropSettings(tag);
		settings = st.getPropSettings(tag);
		settings = Element.getPropSettings(st, tag);
		settings = Element.getPropSettings('SpectraTrimmer', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		tag = st.getPropTag(prop);
	 
		default = SpectraTrimmer.getPropDefault(prop);
		default = st.getPropDefault(prop);
		default = Element.getPropDefault(st, prop);
		default = Element.getPropDefault('SpectraTrimmer', prop);
	 
		default = SpectraTrimmer.getPropDefault(tag);
		default = st.getPropDefault(tag);
		default = Element.getPropDefault(st, tag);
		default = Element.getPropDefault('SpectraTrimmer', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		tag = st.getPropTag(prop);
	 
		conditioned_default = SpectraTrimmer.getPropDefaultConditioned(prop);
		conditioned_default = st.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(st, prop);
		conditioned_default = Element.getPropDefaultConditioned('SpectraTrimmer', prop);
	 
		conditioned_default = SpectraTrimmer.getPropDefaultConditioned(tag);
		conditioned_default = st.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(st, tag);
		conditioned_default = Element.getPropDefaultConditioned('SpectraTrimmer', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		tag = st.getPropTag(prop);
	 
		assert(~SpectraTrimmer.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'SpectraTrimmer.checkProp(prop, value) does not work.')
		assert(~st.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'st.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(st, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(st, prop, value) does not work.')
		assert(~Element.checkProp('SpectraTrimmer', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SpectraTrimmer'', prop, value) does not work.')
	 
		assert_with_error('SpectraTrimmer.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SpectraTrimmer:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SpectraTrimmer:' BRAPH2.WRONG_INPUT], prop, st)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SpectraTrimmer:' BRAPH2.WRONG_INPUT], prop, st)
		assert_with_error('Element.checkProp(''SpectraTrimmer'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SpectraTrimmer:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~SpectraTrimmer.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'SpectraTrimmer.checkProp(tag, value) does not work.')
		assert(~st.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'st.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(st, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(st, tag, value) does not work.')
		assert(~Element.checkProp('SpectraTrimmer', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SpectraTrimmer'', tag, value) does not work.')
	 
		assert_with_error('SpectraTrimmer.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SpectraTrimmer:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SpectraTrimmer:' BRAPH2.WRONG_INPUT], tag, st)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SpectraTrimmer:' BRAPH2.WRONG_INPUT], tag, st)
		assert_with_error('Element.checkProp(''SpectraTrimmer'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':SpectraTrimmer:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(SpectraTrimmer.checkProp(prop, Element.getPropDefaultConditioned(SpectraTrimmer, prop)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'SpectraTrimmer.checkProp(prop, <conditioned default value>) does not work.')
		assert(st.checkProp(prop, Element.getPropDefaultConditioned(SpectraTrimmer, prop)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'st.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(st, prop, Element.getPropDefaultConditioned(SpectraTrimmer, prop)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(st, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('SpectraTrimmer', prop, Element.getPropDefaultConditioned(SpectraTrimmer, prop)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SpectraTrimmer'', prop, <conditioned default value>) does not work.')
	 
		assert(SpectraTrimmer.checkProp(tag, Element.getPropDefaultConditioned(SpectraTrimmer, prop)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'SpectraTrimmer.checkProp(tag, <conditioned default value>) does not work.')
		assert(st.checkProp(tag, Element.getPropDefaultConditioned(SpectraTrimmer, prop)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'st.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(st, tag, Element.getPropDefaultConditioned(SpectraTrimmer, prop)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(st, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('SpectraTrimmer', tag, Element.getPropDefaultConditioned(SpectraTrimmer, prop)), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''SpectraTrimmer'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SpectraTrimmer( ...
		SpectraTrimmer.ELCLASS, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.NAME, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.DESCRIPTION, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.TEMPLATE, SpectraTrimmer.getPropDefault(SpectraTrimmer.TEMPLATE), ...
		SpectraTrimmer.ID, SpectraTrimmer.getPropDefault(SpectraTrimmer.ID), ...
		SpectraTrimmer.LABEL, SpectraTrimmer.getPropDefault(SpectraTrimmer.LABEL), ...
		SpectraTrimmer.NOTES, SpectraTrimmer.getPropDefault(SpectraTrimmer.NOTES), ...
		SpectraTrimmer.TOSTRING, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_IN, SpectraTrimmer.getPropDefault(SpectraTrimmer.RE_IN), ...
		SpectraTrimmer.SP_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.SP_DICT_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.REPF, SpectraTrimmer.getPropDefault(SpectraTrimmer.REPF), ...
		SpectraTrimmer.START_WAVELENGTH, SpectraTrimmer.getPropDefault(SpectraTrimmer.START_WAVELENGTH), ...
		SpectraTrimmer.STOP_WAVELENGTH, SpectraTrimmer.getPropDefault(SpectraTrimmer.STOP_WAVELENGTH) ...
		);
	 
	for prop = 1:1:SpectraTrimmer.getPropNumber()
	 
		% excluded props
		if any(prop == [SpectraTrimmer.TEMPLATE SpectraTrimmer.REPF])
			continue
		end
	 
		TAG = upper(SpectraTrimmer.getPropTag(prop));
		switch SpectraTrimmer.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					st.getr(prop) == SpectraTrimmer.getNoValue(), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['Being a ' SpectraTrimmer.getCategoryName(SpectraTrimmer.getPropCategory(prop)) ', SpectraTrimmer.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SpectraTrimmer.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					st.getr(TAG) == SpectraTrimmer.getNoValue(), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['Being a ' SpectraTrimmer.getCategoryName(SpectraTrimmer.getPropCategory(prop)) ', SpectraTrimmer.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SpectraTrimmer.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(st.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(st.getPropSettings(prop))
					assert( ...
						st.checkFormat(st.getPropFormat(prop), st.get(prop)), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						['SpectraTrimmer.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						st.checkFormat(st.getPropFormat(prop), st.get(prop), st.getPropSettings(prop)), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						['SpectraTrimmer.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					st.getr(prop) == SpectraTrimmer.getNoValue(), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['Being a ' SpectraTrimmer.getCategoryName(SpectraTrimmer.getPropCategory(prop)) ', SpectraTrimmer.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SpectraTrimmer.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					st.getr(TAG) == SpectraTrimmer.getNoValue(), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['Being a ' SpectraTrimmer.getCategoryName(SpectraTrimmer.getPropCategory(prop)) ', SpectraTrimmer.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in SpectraTrimmer.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':SpectraTrimmer']);
				assert( ...
					~isa(st.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(st.getPropSettings(prop))
					assert( ...
						st.checkFormat(st.getPropFormat(prop), st.get(prop)), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						['SpectraTrimmer.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						st.checkFormat(st.getPropFormat(prop), st.get(prop), st.getPropSettings(prop)), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						['SpectraTrimmer.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(st.getr(prop), SpectraTrimmer.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by SpectraTrimmer.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in SpectraTrimmer.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(st.getr(TAG), SpectraTrimmer.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.getr(' TAG ') must be inizialized to its default value ' ...
					'given by SpectraTrimmer.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in SpectraTrimmer.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SpectraTrimmer( ...
		SpectraTrimmer.ELCLASS, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.NAME, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.DESCRIPTION, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.TEMPLATE, SpectraTrimmer.getPropDefault(SpectraTrimmer.TEMPLATE), ...
		SpectraTrimmer.ID, SpectraTrimmer.getPropDefault(SpectraTrimmer.ID), ...
		SpectraTrimmer.LABEL, SpectraTrimmer.getPropDefault(SpectraTrimmer.LABEL), ...
		SpectraTrimmer.NOTES, SpectraTrimmer.getPropDefault(SpectraTrimmer.NOTES), ...
		SpectraTrimmer.TOSTRING, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_IN, SpectraTrimmer.getPropDefault(SpectraTrimmer.RE_IN), ...
		SpectraTrimmer.SP_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.SP_DICT_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.REPF, SpectraTrimmer.getPropDefault(SpectraTrimmer.REPF), ...
		SpectraTrimmer.START_WAVELENGTH, SpectraTrimmer.getPropDefault(SpectraTrimmer.START_WAVELENGTH), ...
		SpectraTrimmer.STOP_WAVELENGTH, SpectraTrimmer.getPropDefault(SpectraTrimmer.STOP_WAVELENGTH) ...
		);
	 
	for prop = 1:1:SpectraTrimmer.getPropNumber()
	 
		% excluded props
		if any(prop == [SpectraTrimmer.TEMPLATE SpectraTrimmer.REPF])
			continue
		end
	 
		TAG = upper(SpectraTrimmer.getPropTag(prop));
		switch SpectraTrimmer.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(st.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(st.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					st.checkFormat(st.getPropFormat(prop), st.getr(prop),st.getPropSettings(prop)), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':SpectraTrimmer']);
				assert( ...
					~isa(st.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':SpectraTrimmer']);
	% 			assert( ...
	% 				~isa(st.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
	% 				['SpectraTrimmer.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(st.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
	% 				['SpectraTrimmer.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				st.checkFormat(st.getPropFormat(prop), st.getr(prop),st.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
	% 				['SpectraTrimmer.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':SpectraTrimmer']);
				assert( ...
					~isa(st.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(st.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					st.checkFormat(st.getPropFormat(prop), st.getr(prop),st.getPropSettings(prop)), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if st.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:SpectraTrimmer');
					delete(ancestor(st.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(SpectraTrimmer.getProps(Category.RESULT))
		for prop = 1:1:SpectraTrimmer.getPropNumber()
	 
			% excluded props
			if any(prop == [SpectraTrimmer.TEMPLATE SpectraTrimmer.REPF])
				continue
			end
	 
			switch SpectraTrimmer.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						st.isLocked(prop), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						['SpectraTrimmer.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~st.isLocked(prop), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						['SpectraTrimmer.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SpectraTrimmer();
	 
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		TAG = upper(SpectraTrimmer.getPropTag(prop));
		assert( ...
			~st.isLocked(prop), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			['SpectraTrimmer.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~st.isLocked(TAG), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			['SpectraTrimmer.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	st.lock()
	 
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		switch SpectraTrimmer.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					st.isLocked(prop), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~st.isLocked(prop), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SpectraTrimmer();
	 
	warning_backup = warning('off', 'BRAPH2:SpectraTrimmer');
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		st.lock(prop)
		switch SpectraTrimmer.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					st.isLocked(prop), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~st.isLocked(prop), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SpectraTrimmer();
	 
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		TAG = upper(SpectraTrimmer.getPropTag(prop));
		assert( ...
			st.isChecked(prop), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			['SpectraTrimmer.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			st.isChecked(TAG), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			['SpectraTrimmer.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	st.unchecked()
	 
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		assert( ...
			~st.isChecked(prop), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			['SpectraTrimmer.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	st.checked()
	 
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		assert( ...
			st.isChecked(prop), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			['SpectraTrimmer.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic SpectraTrimmer
	st_0 = SpectraTrimmer( ...
		SpectraTrimmer.ELCLASS, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.NAME, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.DESCRIPTION, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.TEMPLATE, SpectraTrimmer.getPropDefault(SpectraTrimmer.TEMPLATE), ...
		SpectraTrimmer.ID, SpectraTrimmer.getPropDefault(SpectraTrimmer.ID), ...
		SpectraTrimmer.LABEL, SpectraTrimmer.getPropDefault(SpectraTrimmer.LABEL), ...
		SpectraTrimmer.NOTES, SpectraTrimmer.getPropDefault(SpectraTrimmer.NOTES), ...
		SpectraTrimmer.TOSTRING, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_IN, SpectraTrimmer.getPropDefault(SpectraTrimmer.RE_IN), ...
		SpectraTrimmer.SP_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.SP_DICT_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.REPF, SpectraTrimmer.getPropDefault(SpectraTrimmer.REPF), ...
		SpectraTrimmer.START_WAVELENGTH, SpectraTrimmer.getPropDefault(SpectraTrimmer.START_WAVELENGTH), ...
		SpectraTrimmer.STOP_WAVELENGTH, SpectraTrimmer.getPropDefault(SpectraTrimmer.STOP_WAVELENGTH) ...
		);
	 
	% SpectraTrimmer with 1st callbacks
	st_1 = SpectraTrimmer( ...
		SpectraTrimmer.ELCLASS, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.NAME, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.DESCRIPTION, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.TEMPLATE, st_0.getCallback(4), ..., ...
		SpectraTrimmer.ID, st_0.getCallback(5), ..., ...
		SpectraTrimmer.LABEL, SpectraTrimmer.getPropDefault(SpectraTrimmer.LABEL), ...
		SpectraTrimmer.NOTES, SpectraTrimmer.getPropDefault(SpectraTrimmer.NOTES), ...
		SpectraTrimmer.TOSTRING, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_IN, st_0.getCallback(9), ..., ...
		SpectraTrimmer.SP_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.SP_DICT_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.REPF, st_0.getCallback(13), ..., ...
		SpectraTrimmer.START_WAVELENGTH, st_0.getCallback(14), ..., ...
		SpectraTrimmer.STOP_WAVELENGTH, st_0.getCallback(15) ... ...
		);
	 
	prop_number = SpectraTrimmer.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(SpectraTrimmer.getPropTag(prop));
		switch SpectraTrimmer.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(st_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(st_1.get(prop), st_0.get(prop)) && ~isa(st_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(st_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% SpectraTrimmer with 2nd callbacks
	st_2 = SpectraTrimmer( ...
		SpectraTrimmer.ELCLASS, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.NAME, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.DESCRIPTION, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.TEMPLATE, st_1.getCallback(4), ..., ...
		SpectraTrimmer.ID, st_1.getCallback(5), ..., ...
		SpectraTrimmer.LABEL, SpectraTrimmer.getPropDefault(SpectraTrimmer.LABEL), ...
		SpectraTrimmer.NOTES, SpectraTrimmer.getPropDefault(SpectraTrimmer.NOTES), ...
		SpectraTrimmer.TOSTRING, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_IN, st_1.getCallback(9), ..., ...
		SpectraTrimmer.SP_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.SP_DICT_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.REPF, st_1.getCallback(13), ..., ...
		SpectraTrimmer.START_WAVELENGTH, st_1.getCallback(14), ..., ...
		SpectraTrimmer.STOP_WAVELENGTH, st_1.getCallback(15) ... ...
		);
	 
	prop_number = SpectraTrimmer.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(SpectraTrimmer.getPropTag(prop));
		switch SpectraTrimmer.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(st_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(st_2.get(prop), st_0.get(prop)) && ~isa(st_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(st_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% SpectraTrimmer with 3rd callbacks
	st_3 = SpectraTrimmer( ...
		SpectraTrimmer.ELCLASS, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.NAME, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.DESCRIPTION, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.TEMPLATE, st_2.getCallback(4), ..., ...
		SpectraTrimmer.ID, st_2.getCallback(5), ..., ...
		SpectraTrimmer.LABEL, SpectraTrimmer.getPropDefault(SpectraTrimmer.LABEL), ...
		SpectraTrimmer.NOTES, SpectraTrimmer.getPropDefault(SpectraTrimmer.NOTES), ...
		SpectraTrimmer.TOSTRING, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_IN, st_2.getCallback(9), ..., ...
		SpectraTrimmer.SP_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.SP_DICT_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.REPF, st_2.getCallback(13), ..., ...
		SpectraTrimmer.START_WAVELENGTH, st_2.getCallback(14), ..., ...
		SpectraTrimmer.STOP_WAVELENGTH, st_2.getCallback(15) ... ...
		);
	 
	prop_number = SpectraTrimmer.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(SpectraTrimmer.getPropTag(prop));
		switch SpectraTrimmer.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(st_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(st_3.get(prop), st_0.get(prop)) && ~isa(st_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(st_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	st = SpectraTrimmer();
	 
	st_copy = st.copy();
	 
	assert(st_copy ~= st, ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'SpectraTrimmer.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(st_copy, st), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'SpectraTrimmer.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		value = st.getr(prop);
		value_copy = st_copy.getr(prop);
		switch SpectraTrimmer.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					'SpectraTrimmer.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
							'SpectraTrimmer.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
							'SpectraTrimmer.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					st_copy.isLocked(prop) == st.isLocked(prop), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					'SpectraTrimmer.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					st_copy.isChecked(prop) == st.isChecked(prop), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					'SpectraTrimmer.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					st_copy.getPropSeed(prop) == st.getPropSeed(prop), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					'SpectraTrimmer.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	st = SpectraTrimmer( ...
		SpectraTrimmer.ELCLASS, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.NAME, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.DESCRIPTION, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.TEMPLATE, SpectraTrimmer.getPropDefault(SpectraTrimmer.TEMPLATE), ...
		SpectraTrimmer.ID, SpectraTrimmer.getPropDefault(SpectraTrimmer.ID), ...
		SpectraTrimmer.LABEL, SpectraTrimmer.getPropDefault(SpectraTrimmer.LABEL), ...
		SpectraTrimmer.NOTES, SpectraTrimmer.getPropDefault(SpectraTrimmer.NOTES), ...
		SpectraTrimmer.TOSTRING, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_IN, SpectraTrimmer.getPropDefault(SpectraTrimmer.RE_IN), ...
		SpectraTrimmer.SP_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.SP_DICT_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.REPF, SpectraTrimmer.getPropDefault(SpectraTrimmer.REPF), ...
		SpectraTrimmer.START_WAVELENGTH, SpectraTrimmer.getPropDefault(SpectraTrimmer.START_WAVELENGTH), ...
		SpectraTrimmer.STOP_WAVELENGTH, SpectraTrimmer.getPropDefault(SpectraTrimmer.STOP_WAVELENGTH) ...
		);
	 
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		if SpectraTrimmer.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':SpectraTrimmer']);
			% st.memorize(prop);
			% warning(warning_backup)
		elseif SpectraTrimmer.getPropCategory(prop) == Category.EVANESCENT && st.getPropFormat(prop) == Format.HANDLE
			st.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:SpectraTrimmer');
			delete(ancestor(st.get(prop), 'figure'))
			warning(warning_backup)
		else
			st.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	st_copy = st.copy();
	 
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		value = st.getr(prop);
		value_copy = st_copy.getr(prop);
		switch SpectraTrimmer.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					'SpectraTrimmer.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
							'SpectraTrimmer.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
							'SpectraTrimmer.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						st_copy.isLocked(prop) == st.isLocked(prop), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						st_copy.isChecked(prop) == st.isChecked(prop), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						st_copy.getPropSeed(prop) == st.getPropSeed(prop), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	st_0 = SpectraTrimmer( ...
		SpectraTrimmer.ELCLASS, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.NAME, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.DESCRIPTION, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.TEMPLATE, SpectraTrimmer.getPropDefault(SpectraTrimmer.TEMPLATE), ...
		SpectraTrimmer.ID, SpectraTrimmer.getPropDefault(SpectraTrimmer.ID), ...
		SpectraTrimmer.LABEL, SpectraTrimmer.getPropDefault(SpectraTrimmer.LABEL), ...
		SpectraTrimmer.NOTES, SpectraTrimmer.getPropDefault(SpectraTrimmer.NOTES), ...
		SpectraTrimmer.TOSTRING, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_IN, SpectraTrimmer.getPropDefault(SpectraTrimmer.RE_IN), ...
		SpectraTrimmer.SP_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.SP_DICT_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.REPF, SpectraTrimmer.getPropDefault(SpectraTrimmer.REPF), ...
		SpectraTrimmer.START_WAVELENGTH, SpectraTrimmer.getPropDefault(SpectraTrimmer.START_WAVELENGTH), ...
		SpectraTrimmer.STOP_WAVELENGTH, SpectraTrimmer.getPropDefault(SpectraTrimmer.STOP_WAVELENGTH) ...
		);
	 
	st = SpectraTrimmer( ...
		SpectraTrimmer.ELCLASS, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.NAME, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.DESCRIPTION, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.TEMPLATE, st_0.getCallback(4), ..., ...
		SpectraTrimmer.ID, st_0.getCallback(5), ..., ...
		SpectraTrimmer.LABEL, SpectraTrimmer.getPropDefault(SpectraTrimmer.LABEL), ...
		SpectraTrimmer.NOTES, SpectraTrimmer.getPropDefault(SpectraTrimmer.NOTES), ...
		SpectraTrimmer.TOSTRING, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_IN, st_0.getCallback(9), ..., ...
		SpectraTrimmer.SP_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.SP_DICT_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.REPF, st_0.getCallback(13), ..., ...
		SpectraTrimmer.START_WAVELENGTH, st_0.getCallback(14), ..., ...
		SpectraTrimmer.STOP_WAVELENGTH, st_0.getCallback(15) ... ...
		);
	 
	st_copy = st.copy();
	st_0_copy = st_copy.getr('ID').get('EL');
	 
	for prop = 1:1:SpectraTrimmer.getPropNumber()
		value = st.getr(prop);
		value_copy = st_copy.getr(prop);
		switch SpectraTrimmer.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					'SpectraTrimmer.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
							'SpectraTrimmer.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
							'SpectraTrimmer.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == st_0.getCallback(prop), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer.copy() does not work. The callback should be obtained from SpectraTrimmer.getCallback().' ...
						)
					assert( ...
						value_copy == st_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer.copy() does not work. The callback should be obtained from SpectraTrimmer.getCallback().' ...
						)
				end
	 
					assert( ...
						st_copy.isLocked(prop) == st.isLocked(prop), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						st_copy.isChecked(prop) == st.isChecked(prop), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						st_copy.getPropSeed(prop) == st.getPropSeed(prop), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st_template = SpectraTrimmer();
	st = SpectraTrimmer('TEMPLATE', st_template);
	 
	for prop = 1:1:SpectraTrimmer.getPropNumber()
	 
		% excluded props
		if any(prop == [SpectraTrimmer.TEMPLATE SpectraTrimmer.REPF])
			continue
		end
	 
		TAG = upper(SpectraTrimmer.getPropTag(prop));
		switch SpectraTrimmer.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == SpectraTrimmer.TEMPLATE
					assert( ...
						isa(st.getr(prop), 'SpectraTrimmer'), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer TEMPLATE does not work. SpectraTrimmer.getr(''TEMPLATE'') should be a SpectraTrimmer element.' ...
						)
					assert( ...
						isa(st_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						'SpectraTrimmer TEMPLATE does not work. SpectraTrimmer_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(st.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						['SpectraTrimmer TEMPLATE does not work. SpectraTrimmer.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						st.getr(prop).get('EL') == st_template && st.getr(prop).get('PROP') == prop && strcmp(st.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						['SpectraTrimmer TEMPLATE does not work. SpectraTrimmer.getr(' TAG ') should be a Callback to st_template.' TAG '.'] ...
						)
					assert( ...
						isa(st_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
						['SpectraTrimmer TEMPLATE does not work. SpectraTrimmer_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(st.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer TEMPLATE does not work. SpectraTrimmer.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(st_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
					['SpectraTrimmer TEMPLATE does not work. SpectraTrimmer_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SpectraTrimmer( ...
		SpectraTrimmer.ELCLASS, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.NAME, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.DESCRIPTION, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.TEMPLATE, SpectraTrimmer.getPropDefault(SpectraTrimmer.TEMPLATE), ...
		SpectraTrimmer.ID, SpectraTrimmer.getPropDefault(SpectraTrimmer.ID), ...
		SpectraTrimmer.LABEL, SpectraTrimmer.getPropDefault(SpectraTrimmer.LABEL), ...
		SpectraTrimmer.NOTES, SpectraTrimmer.getPropDefault(SpectraTrimmer.NOTES), ...
		SpectraTrimmer.TOSTRING, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_IN, SpectraTrimmer.getPropDefault(SpectraTrimmer.RE_IN), ...
		SpectraTrimmer.SP_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.SP_DICT_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.REPF, SpectraTrimmer.getPropDefault(SpectraTrimmer.REPF), ...
		SpectraTrimmer.START_WAVELENGTH, SpectraTrimmer.getPropDefault(SpectraTrimmer.START_WAVELENGTH), ...
		SpectraTrimmer.STOP_WAVELENGTH, SpectraTrimmer.getPropDefault(SpectraTrimmer.STOP_WAVELENGTH) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'spectratrimmer_to_be_erased.b2'];
	 
	Element.save(st, filename)
	 
	st_loaded = Element.load(filename);
	 
	assert( ...
		isequal(st.copy(), st_loaded), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'SpectraTrimmer.save(st) and/or SpectraTrimmer.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	st = SpectraTrimmer( ...
		SpectraTrimmer.ELCLASS, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.NAME, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.DESCRIPTION, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.TEMPLATE, SpectraTrimmer.getPropDefault(SpectraTrimmer.TEMPLATE), ...
		SpectraTrimmer.ID, SpectraTrimmer.getPropDefault(SpectraTrimmer.ID), ...
		SpectraTrimmer.LABEL, SpectraTrimmer.getPropDefault(SpectraTrimmer.LABEL), ...
		SpectraTrimmer.NOTES, SpectraTrimmer.getPropDefault(SpectraTrimmer.NOTES), ...
		SpectraTrimmer.TOSTRING, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_IN, SpectraTrimmer.getPropDefault(SpectraTrimmer.RE_IN), ...
		SpectraTrimmer.SP_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.SP_DICT_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.RE_OUT, SpectraTrimmer.getNoValue(), ...
		SpectraTrimmer.REPF, SpectraTrimmer.getPropDefault(SpectraTrimmer.REPF), ...
		SpectraTrimmer.START_WAVELENGTH, SpectraTrimmer.getPropDefault(SpectraTrimmer.START_WAVELENGTH), ...
		SpectraTrimmer.STOP_WAVELENGTH, SpectraTrimmer.getPropDefault(SpectraTrimmer.STOP_WAVELENGTH) ...
		);
	 
	[json, struct, el_list] = encodeJSON(st);
	[st_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(st_dec ~= st, ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		'SpectraTrimmer.encodeJSON() or SpectraTrimmer.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) SpectraTrimmer.getPropFormat(prop), num2cell(SpectraTrimmer.getProps())) == Format.HANDLE) && all(cellfun(@(prop) SpectraTrimmer.getPropFormat(prop), num2cell(SpectraTrimmer.getProps())) == Format.NET)
		assert(isequal(st_dec, st), ...
			[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
			'SpectraTrimmer.encodeJSON() or SpectraTrimmer.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':SpectraTrimmer:' BRAPH2.FAIL_TEST], ...
		[' When testing SpectraTrimmer no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 13: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

