%TEST_RAMANEXPERIMENTPF

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':RamanExperimentPF'])
	
	categories = num2cell(Category.getCategories());
	pf = RamanExperimentPF();
	 
	% get('ELCLASS')
	if isa(RamanExperimentPF, 'ConcreteElement')
		assert(strcmp(RamanExperimentPF().get('ELCLASS'), 'RamanExperimentPF'), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'RamanExperimentPF().get(''ELCLASS'') should return ''RamanExperimentPF''.')
	end
	 
	% getBuild()
	assert(RamanExperimentPF.getBuild() == 1 && RamanExperimentPF.getBuild() > 0, ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'RamanExperimentPF.getBuild() should return the RamanExperimentPF build number.')
	assert(pf.getBuild() == 1 && pf.getBuild() > 0 , ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'pf.getBuild() should return the RamanExperimentPF build number.')
	assert(Element.getBuild(pf) == 1 && Element.getBuild(pf) > 0, ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(pf) should return the RamanExperimentPF build number.')
	assert(Element.getBuild('RamanExperimentPF') == 1 && Element.getBuild('RamanExperimentPF') > 0, ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''RamanExperimentPF'') should return the RamanExperimentPF build number.')
	 
	% getClass()
	assert(strcmp(RamanExperimentPF.getClass(), 'RamanExperimentPF'), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'RamanExperimentPF.getClass() should return ''RamanExperimentPF''.')
	assert(strcmp(pf.getClass(), 'RamanExperimentPF'), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'pf.getClass() should return ''RamanExperimentPF''.')
	assert(strcmp(Element.getClass(pf), 'RamanExperimentPF'), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(pf) should return ''RamanExperimentPF''.')
	assert(strcmp(Element.getClass('RamanExperimentPF'), 'RamanExperimentPF'), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''RamanExperimentPF'') should return ''RamanExperimentPF''.')
	 
	% getSubclasses()
	assert(isequal(RamanExperimentPF.getSubclasses(), subclasses('RamanExperimentPF', [], [], true)), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'RamanExperimentPF.getSubclasses() should return the same result as subclasses(''RamanExperimentPF'', [], [], true).')
	assert(isequal(pf.getSubclasses(), subclasses('RamanExperimentPF', [], [], true)), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''RamanExperimentPF'', [], [], true).')
	assert(isequal(Element.getSubclasses(pf), subclasses('RamanExperimentPF', [], [], true)), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(pf) should return the same result as subclasses(''RamanExperimentPF'', [], [], true).')
	assert(isequal(Element.getSubclasses('RamanExperimentPF'), subclasses('RamanExperimentPF', [], [], true)), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''RamanExperimentPF'') should return the same result as subclasses(''RamanExperimentPF'', [], [], true).')
	 
	% getProps()
	assert(isempty(RamanExperimentPF.getProps()) || isequal(RamanExperimentPF.getProps(), 1:1:length(RamanExperimentPF.getProps())), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'RamanExperimentPF.getProps() should return a row vector [1:1:N].')
	assert(isempty(RamanExperimentPF.getProps()) || isequal(pf.getProps(), 1:1:length(RamanExperimentPF.getProps())), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'pf.getProps() should return a row vector [1:1:N].')
	assert(isempty(RamanExperimentPF.getProps()) || isequal(Element.getProps(pf), 1:1:length(RamanExperimentPF.getProps())), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(pf) should return a row vector [1:1:N].')
	assert(isempty(RamanExperimentPF.getProps()) || isequal(Element.getProps('RamanExperimentPF'), 1:1:length(RamanExperimentPF.getProps())), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''RamanExperimentPF'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) RamanExperimentPF.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(RamanExperimentPF.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(RamanExperimentPF.getProps())), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'RamanExperimentPF.getProps(category) does not work.')
	tmp = cellfun(@(category) pf.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(RamanExperimentPF.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(RamanExperimentPF.getProps())), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'pf.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(pf, category), categories, 'UniformOutput', false);
	assert(isempty(RamanExperimentPF.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(RamanExperimentPF.getProps())), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(pf, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('RamanExperimentPF', category), categories, 'UniformOutput', false);
	assert(isempty(RamanExperimentPF.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(RamanExperimentPF.getProps())), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''RamanExperimentPF'', category) does not work.')
	 
	% getPropNumber()
	assert(RamanExperimentPF.getPropNumber() == length(RamanExperimentPF.getProps()), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'RamanExperimentPF.getPropNumber() should return the number of properties.')
	assert(pf.getPropNumber() == length(RamanExperimentPF.getProps()), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'pf.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(pf) == length(RamanExperimentPF.getProps()), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(pf) should return the number of properties.')
	assert(Element.getPropNumber('RamanExperimentPF') == length(RamanExperimentPF.getProps()), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''RamanExperimentPF'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) RamanExperimentPF.getPropNumber(category), categories)) == RamanExperimentPF.getPropNumber(), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'RamanExperimentPF.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) pf.getPropNumber(category), categories)) == RamanExperimentPF.getPropNumber(), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'pf.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(pf, category), categories)) == RamanExperimentPF.getPropNumber(), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(pf, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('RamanExperimentPF', category), categories)) == RamanExperimentPF.getPropNumber(), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''RamanExperimentPF'', category) does not work.')
	 
	% existsProp(prop)
	assert(~RamanExperimentPF.existsProp(NaN), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'RamanExperimentPF.existsProp(prop) does not work.')
	assert(~pf.existsProp(NaN), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'pf.existsProp(prop) does not work.')
	assert(~Element.existsProp(pf, NaN), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(pf, prop) does not work.')
	assert(~Element.existsProp('RamanExperimentPF', NaN), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''RamanExperimentPF'', prop) does not work.')
	 
	assert_with_error('RamanExperimentPF.existsProp(NaN)', [BRAPH2.STR ':RamanExperimentPF:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':RamanExperimentPF:' BRAPH2.WRONG_INPUT], pf)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':RamanExperimentPF:' BRAPH2.WRONG_INPUT], pf)
	assert_with_error('Element.existsProp(''RamanExperimentPF'', NaN)', [BRAPH2.STR ':RamanExperimentPF:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		assert(RamanExperimentPF.existsProp(prop), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'RamanExperimentPF.existsProp(prop) does not work.')
		assert(pf.existsProp(prop), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'pf.existsProp(prop) does not work.')
		assert(Element.existsProp(pf, prop), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(pf, prop) does not work.')
		assert(Element.existsProp('RamanExperimentPF', prop), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''RamanExperimentPF'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~RamanExperimentPF.existsTag(''), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'RamanExperimentPF.existsTag(tag) does not work.')
	assert(~pf.existsTag(''), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'pf.existsTag(tag) does not work.')
	assert(~Element.existsTag(pf, ''), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(pf, tag) does not work.')
	assert(~Element.existsTag('RamanExperimentPF', ''), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''RamanExperimentPF'', tag) does not work.')
	 
	assert_with_error('RamanExperimentPF.existsTag('''')', [BRAPH2.STR ':RamanExperimentPF:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':RamanExperimentPF:' BRAPH2.WRONG_INPUT], pf)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':RamanExperimentPF:' BRAPH2.WRONG_INPUT], pf)
	assert_with_error('Element.existsTag(''RamanExperimentPF'', '''')', [BRAPH2.STR ':RamanExperimentPF:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		tag = pf.getPropTag(prop);
		assert(RamanExperimentPF.existsTag(tag), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'RamanExperimentPF.existsTag(tag) does not work.')
		assert(pf.existsTag(tag), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'pf.existsTag(tag) does not work.')
		assert(Element.existsTag(pf, tag), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(pf, tga) does not work.')
		assert(Element.existsTag('RamanExperimentPF', tag), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''RamanExperimentPF'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		assert(RamanExperimentPF.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'RamanExperimentPF.getPropProp(prop) does not work.')
		assert(pf.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'pf.getPropProp(prop) does not work.')
		assert(Element.getPropProp(pf, prop) == prop, ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(pf, prop) does not work.')
		assert(Element.getPropProp('RamanExperimentPF', prop) == prop, ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''RamanExperimentPF'', prop) does not work.')
	 
		tag = pf.getPropTag(prop);
		assert(RamanExperimentPF.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'RamanExperimentPF.getPropProp(tag) does not work.')
		assert(pf.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'pf.getPropProp(tag) does not work.')
		assert(Element.getPropProp(pf, tag) == prop, ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(pf, tag) does not work.')
		assert(Element.getPropProp('RamanExperimentPF', prop) == prop, ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''RamanExperimentPF'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		tag = pf.getPropTag(prop);
	 
		assert(strcmp(RamanExperimentPF.getPropTag(prop), tag), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'RamanExperimentPF.getPropTag(prop) does not work.')
		assert(strcmp(pf.getPropTag(prop), tag), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'pf.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(pf, prop), tag), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(pf, prop) does not work.')
		assert(strcmp(Element.getPropTag('RamanExperimentPF', prop), tag), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''RamanExperimentPF'', prop) does not work.')
	 
		assert(strcmp(RamanExperimentPF.getPropTag(tag), tag), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'RamanExperimentPF.getPropTag(tag) does not work.')
		assert(strcmp(pf.getPropTag(tag), tag), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'pf.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(pf, tag), tag), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(pf, tag) does not work.')
		assert(strcmp(Element.getPropTag('RamanExperimentPF', prop), tag), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''RamanExperimentPF'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		tag = pf.getPropTag(prop);
	 
		assert(Category.existsCategory(RamanExperimentPF.getPropCategory(prop)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'RamanExperimentPF.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(pf.getPropCategory(prop)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'pf.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pf, prop)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(pf, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pf, prop)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''RamanExperimentPF'', prop) does not work.')
	 
		assert(Category.existsCategory(RamanExperimentPF.getPropCategory(tag)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'RamanExperimentPF.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(pf.getPropCategory(tag)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'pf.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pf, tag)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(pf, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pf, tag)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''RamanExperimentPF'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		tag = pf.getPropTag(prop);
	 
		assert(Format.existsFormat(RamanExperimentPF.getPropFormat(prop)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'RamanExperimentPF.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(pf.getPropFormat(prop)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'pf.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pf, prop)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(pf, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pf, prop)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''RamanExperimentPF'', prop) does not work.')
	 
		assert(Format.existsFormat(RamanExperimentPF.getPropFormat(tag)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'RamanExperimentPF.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(pf.getPropFormat(tag)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'pf.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pf, tag)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(pf, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pf, tag)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''RamanExperimentPF'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		tag = pf.getPropTag(prop);
	 
		assert(ischar(RamanExperimentPF.getPropDescription(prop)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'RamanExperimentPF.getPropDescription(prop) does not work.')
		assert(ischar(pf.getPropDescription(prop)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'pf.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(pf, prop)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(pf, prop) does not work.')
		assert(ischar(Element.getPropDescription(pf, prop)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''RamanExperimentPF'', prop) does not work.')
	 
		assert(ischar(RamanExperimentPF.getPropDescription(tag)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'RamanExperimentPF.getPropDescription(tag) does not work.')
		assert(ischar(pf.getPropDescription(tag)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'pf.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(pf, tag)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(pf, tag) does not work.')
		assert(ischar(Element.getPropDescription(pf, tag)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''RamanExperimentPF'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		tag = pf.getPropTag(prop);
	 
		settings = RamanExperimentPF.getPropSettings(prop);
		settings = pf.getPropSettings(prop);
		settings = Element.getPropSettings(pf, prop);
		settings = Element.getPropSettings('RamanExperimentPF', prop);
	 
		settings = RamanExperimentPF.getPropSettings(tag);
		settings = pf.getPropSettings(tag);
		settings = Element.getPropSettings(pf, tag);
		settings = Element.getPropSettings('RamanExperimentPF', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		tag = pf.getPropTag(prop);
	 
		default = RamanExperimentPF.getPropDefault(prop);
		default = pf.getPropDefault(prop);
		default = Element.getPropDefault(pf, prop);
		default = Element.getPropDefault('RamanExperimentPF', prop);
	 
		default = RamanExperimentPF.getPropDefault(tag);
		default = pf.getPropDefault(tag);
		default = Element.getPropDefault(pf, tag);
		default = Element.getPropDefault('RamanExperimentPF', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		tag = pf.getPropTag(prop);
	 
		conditioned_default = RamanExperimentPF.getPropDefaultConditioned(prop);
		conditioned_default = pf.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(pf, prop);
		conditioned_default = Element.getPropDefaultConditioned('RamanExperimentPF', prop);
	 
		conditioned_default = RamanExperimentPF.getPropDefaultConditioned(tag);
		conditioned_default = pf.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(pf, tag);
		conditioned_default = Element.getPropDefaultConditioned('RamanExperimentPF', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		tag = pf.getPropTag(prop);
	 
		assert(~RamanExperimentPF.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'RamanExperimentPF.checkProp(prop, value) does not work.')
		assert(~pf.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'pf.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(pf, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pf, prop, value) does not work.')
		assert(~Element.checkProp('RamanExperimentPF', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''RamanExperimentPF'', prop, value) does not work.')
	 
		assert_with_error('RamanExperimentPF.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':RamanExperimentPF:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':RamanExperimentPF:' BRAPH2.WRONG_INPUT], prop, pf)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':RamanExperimentPF:' BRAPH2.WRONG_INPUT], prop, pf)
		assert_with_error('Element.checkProp(''RamanExperimentPF'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':RamanExperimentPF:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~RamanExperimentPF.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'RamanExperimentPF.checkProp(tag, value) does not work.')
		assert(~pf.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'pf.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(pf, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pf, tag, value) does not work.')
		assert(~Element.checkProp('RamanExperimentPF', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''RamanExperimentPF'', tag, value) does not work.')
	 
		assert_with_error('RamanExperimentPF.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':RamanExperimentPF:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':RamanExperimentPF:' BRAPH2.WRONG_INPUT], tag, pf)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':RamanExperimentPF:' BRAPH2.WRONG_INPUT], tag, pf)
		assert_with_error('Element.checkProp(''RamanExperimentPF'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':RamanExperimentPF:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(RamanExperimentPF.checkProp(prop, Element.getPropDefaultConditioned(RamanExperimentPF, prop)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'RamanExperimentPF.checkProp(prop, <conditioned default value>) does not work.')
		assert(pf.checkProp(prop, Element.getPropDefaultConditioned(RamanExperimentPF, prop)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'pf.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(pf, prop, Element.getPropDefaultConditioned(RamanExperimentPF, prop)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pf, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('RamanExperimentPF', prop, Element.getPropDefaultConditioned(RamanExperimentPF, prop)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''RamanExperimentPF'', prop, <conditioned default value>) does not work.')
	 
		assert(RamanExperimentPF.checkProp(tag, Element.getPropDefaultConditioned(RamanExperimentPF, prop)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'RamanExperimentPF.checkProp(tag, <conditioned default value>) does not work.')
		assert(pf.checkProp(tag, Element.getPropDefaultConditioned(RamanExperimentPF, prop)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'pf.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(pf, tag, Element.getPropDefaultConditioned(RamanExperimentPF, prop)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pf, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('RamanExperimentPF', tag, Element.getPropDefaultConditioned(RamanExperimentPF, prop)), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''RamanExperimentPF'', tag, <conditioned default value>) does not work.')
	 
	end
	 
	
	warning('on', [BRAPH2.STR ':RamanExperimentPF'])
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':RamanExperimentPF'])
	
	pf = RamanExperimentPF( ...
		RamanExperimentPF.ELCLASS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.NAME, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DESCRIPTION, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.TEMPLATE, RamanExperimentPF.getPropDefault(RamanExperimentPF.TEMPLATE), ...
		RamanExperimentPF.ID, RamanExperimentPF.getPropDefault(RamanExperimentPF.ID), ...
		RamanExperimentPF.LABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.LABEL), ...
		RamanExperimentPF.NOTES, RamanExperimentPF.getPropDefault(RamanExperimentPF.NOTES), ...
		RamanExperimentPF.TOSTRING, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.WAITBAR, RamanExperimentPF.getPropDefault(RamanExperimentPF.WAITBAR), ...
		RamanExperimentPF.H_WAITBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAWN, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.PARENT, RamanExperimentPF.getPropDefault(RamanExperimentPF.PARENT), ...
		RamanExperimentPF.BKGCOLOR, RamanExperimentPF.getPropDefault(RamanExperimentPF.BKGCOLOR), ...
		RamanExperimentPF.H, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.SHOW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.HIDE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DELETE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.CLOSE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_POSITION, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_POSITION), ...
		RamanExperimentPF.H_TOOLBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_TOOLS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AXES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AXIS, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_AXIS), ...
		RamanExperimentPF.LISTENER_ST_AXIS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.RE, RamanExperimentPF.getPropDefault(RamanExperimentPF.RE), ...
		RamanExperimentPF.SELECTED_SP, RamanExperimentPF.getPropDefault(RamanExperimentPF.SELECTED_SP), ...
		RamanExperimentPF.SETUP, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AREA, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_AREA), ...
		RamanExperimentPF.LISTENER_ST_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_LINE, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_LINE), ...
		RamanExperimentPF.LISTENER_ST_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.LINES, RamanExperimentPF.getPropDefault(RamanExperimentPF.LINES), ...
		RamanExperimentPF.LINE_DICT, RamanExperimentPF.getPropDefault(RamanExperimentPF.LINE_DICT), ...
		RamanExperimentPF.H_TITLE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_TITLE, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_TITLE), ...
		RamanExperimentPF.H_XLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_XLABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_XLABEL), ...
		RamanExperimentPF.H_YLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_YLABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_YLABEL) ...
		);
	 
	for prop = 1:1:RamanExperimentPF.getPropNumber()
	 
		% excluded props
		if any(prop == [RamanExperimentPF.PARENT RamanExperimentPF.H RamanExperimentPF.ST_POSITION RamanExperimentPF.ST_AXIS RamanExperimentPF.ST_AREA RamanExperimentPF.ST_LINE RamanExperimentPF.ST_TITLE RamanExperimentPF.ST_XLABEL RamanExperimentPF.ST_YLABEL])
			continue
		end
	 
		TAG = upper(RamanExperimentPF.getPropTag(prop));
		switch RamanExperimentPF.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					pf.getr(prop) == RamanExperimentPF.getNoValue(), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['Being a ' RamanExperimentPF.getCategoryName(RamanExperimentPF.getPropCategory(prop)) ', RamanExperimentPF.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in RamanExperimentPF.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					pf.getr(TAG) == RamanExperimentPF.getNoValue(), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['Being a ' RamanExperimentPF.getCategoryName(RamanExperimentPF.getPropCategory(prop)) ', RamanExperimentPF.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in RamanExperimentPF.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(pf.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(pf.getPropSettings(prop))
					assert( ...
						pf.checkFormat(pf.getPropFormat(prop), pf.get(prop)), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						['RamanExperimentPF.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						pf.checkFormat(pf.getPropFormat(prop), pf.get(prop), pf.getPropSettings(prop)), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						['RamanExperimentPF.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					pf.getr(prop) == RamanExperimentPF.getNoValue(), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['Being a ' RamanExperimentPF.getCategoryName(RamanExperimentPF.getPropCategory(prop)) ', RamanExperimentPF.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in RamanExperimentPF.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					pf.getr(TAG) == RamanExperimentPF.getNoValue(), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['Being a ' RamanExperimentPF.getCategoryName(RamanExperimentPF.getPropCategory(prop)) ', RamanExperimentPF.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in RamanExperimentPF.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':RamanExperimentPF']);
				assert( ...
					~isa(pf.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(pf.getPropSettings(prop))
					assert( ...
						pf.checkFormat(pf.getPropFormat(prop), pf.get(prop)), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						['RamanExperimentPF.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						pf.checkFormat(pf.getPropFormat(prop), pf.get(prop), pf.getPropSettings(prop)), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						['RamanExperimentPF.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(pf.getr(prop), RamanExperimentPF.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by RamanExperimentPF.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in RamanExperimentPF.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(pf.getr(TAG), RamanExperimentPF.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.getr(' TAG ') must be inizialized to its default value ' ...
					'given by RamanExperimentPF.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in RamanExperimentPF.getr(' TAG ').'] ...
					)
		end
	end
	
	warning('on', [BRAPH2.STR ':RamanExperimentPF'])
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':RamanExperimentPF'])
	
	pf = RamanExperimentPF( ...
		RamanExperimentPF.ELCLASS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.NAME, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DESCRIPTION, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.TEMPLATE, RamanExperimentPF.getPropDefault(RamanExperimentPF.TEMPLATE), ...
		RamanExperimentPF.ID, RamanExperimentPF.getPropDefault(RamanExperimentPF.ID), ...
		RamanExperimentPF.LABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.LABEL), ...
		RamanExperimentPF.NOTES, RamanExperimentPF.getPropDefault(RamanExperimentPF.NOTES), ...
		RamanExperimentPF.TOSTRING, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.WAITBAR, RamanExperimentPF.getPropDefault(RamanExperimentPF.WAITBAR), ...
		RamanExperimentPF.H_WAITBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAWN, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.PARENT, RamanExperimentPF.getPropDefault(RamanExperimentPF.PARENT), ...
		RamanExperimentPF.BKGCOLOR, RamanExperimentPF.getPropDefault(RamanExperimentPF.BKGCOLOR), ...
		RamanExperimentPF.H, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.SHOW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.HIDE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DELETE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.CLOSE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_POSITION, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_POSITION), ...
		RamanExperimentPF.H_TOOLBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_TOOLS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AXES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AXIS, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_AXIS), ...
		RamanExperimentPF.LISTENER_ST_AXIS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.RE, RamanExperimentPF.getPropDefault(RamanExperimentPF.RE), ...
		RamanExperimentPF.SELECTED_SP, RamanExperimentPF.getPropDefault(RamanExperimentPF.SELECTED_SP), ...
		RamanExperimentPF.SETUP, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AREA, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_AREA), ...
		RamanExperimentPF.LISTENER_ST_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_LINE, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_LINE), ...
		RamanExperimentPF.LISTENER_ST_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.LINES, RamanExperimentPF.getPropDefault(RamanExperimentPF.LINES), ...
		RamanExperimentPF.LINE_DICT, RamanExperimentPF.getPropDefault(RamanExperimentPF.LINE_DICT), ...
		RamanExperimentPF.H_TITLE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_TITLE, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_TITLE), ...
		RamanExperimentPF.H_XLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_XLABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_XLABEL), ...
		RamanExperimentPF.H_YLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_YLABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_YLABEL) ...
		);
	 
	for prop = 1:1:RamanExperimentPF.getPropNumber()
	 
		% excluded props
		if any(prop == [RamanExperimentPF.PARENT RamanExperimentPF.H RamanExperimentPF.ST_POSITION RamanExperimentPF.ST_AXIS RamanExperimentPF.ST_AREA RamanExperimentPF.ST_LINE RamanExperimentPF.ST_TITLE RamanExperimentPF.ST_XLABEL RamanExperimentPF.ST_YLABEL])
			continue
		end
	 
		TAG = upper(RamanExperimentPF.getPropTag(prop));
		switch RamanExperimentPF.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(pf.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(pf.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(pf.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(pf.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					pf.checkFormat(pf.getPropFormat(prop), pf.getr(prop),pf.getPropSettings(prop)), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':RamanExperimentPF']);
				assert( ...
					~isa(pf.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(pf.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':RamanExperimentPF']);
	% 			assert( ...
	% 				~isa(pf.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
	% 				['RamanExperimentPF.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(pf.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
	% 				['RamanExperimentPF.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				pf.checkFormat(pf.getPropFormat(prop), pf.getr(prop),pf.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
	% 				['RamanExperimentPF.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':RamanExperimentPF']);
				assert( ...
					~isa(pf.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(pf.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(pf.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(pf.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					pf.checkFormat(pf.getPropFormat(prop), pf.getr(prop),pf.getPropSettings(prop)), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if pf.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:RamanExperimentPF');
					delete(ancestor(pf.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(RamanExperimentPF.getProps(Category.RESULT))
		for prop = 1:1:RamanExperimentPF.getPropNumber()
	 
			% excluded props
			if any(prop == [RamanExperimentPF.PARENT RamanExperimentPF.H RamanExperimentPF.ST_POSITION RamanExperimentPF.ST_AXIS RamanExperimentPF.ST_AREA RamanExperimentPF.ST_LINE RamanExperimentPF.ST_TITLE RamanExperimentPF.ST_XLABEL RamanExperimentPF.ST_YLABEL])
				continue
			end
	 
			switch RamanExperimentPF.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						pf.isLocked(prop), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						['RamanExperimentPF.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~pf.isLocked(prop), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						['RamanExperimentPF.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
	
	warning('on', [BRAPH2.STR ':RamanExperimentPF'])
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':RamanExperimentPF'])
	
	pf = RamanExperimentPF();
	 
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		TAG = upper(RamanExperimentPF.getPropTag(prop));
		assert( ...
			~pf.isLocked(prop), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			['RamanExperimentPF.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~pf.isLocked(TAG), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			['RamanExperimentPF.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	pf.lock()
	 
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		switch RamanExperimentPF.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					pf.isLocked(prop), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~pf.isLocked(prop), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
	
	warning('on', [BRAPH2.STR ':RamanExperimentPF'])
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':RamanExperimentPF'])
	
	pf = RamanExperimentPF();
	 
	warning_backup = warning('off', 'BRAPH2:RamanExperimentPF');
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		pf.lock(prop)
		switch RamanExperimentPF.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					pf.isLocked(prop), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~pf.isLocked(prop), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
	
	warning('on', [BRAPH2.STR ':RamanExperimentPF'])
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':RamanExperimentPF'])
	
	pf = RamanExperimentPF();
	 
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		TAG = upper(RamanExperimentPF.getPropTag(prop));
		assert( ...
			pf.isChecked(prop), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			['RamanExperimentPF.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			pf.isChecked(TAG), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			['RamanExperimentPF.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	pf.unchecked()
	 
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		assert( ...
			~pf.isChecked(prop), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			['RamanExperimentPF.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	pf.checked()
	 
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		assert( ...
			pf.isChecked(prop), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			['RamanExperimentPF.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
	
	warning('on', [BRAPH2.STR ':RamanExperimentPF'])
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':RamanExperimentPF'])
	
	% basic RamanExperimentPF
	pf_0 = RamanExperimentPF( ...
		RamanExperimentPF.ELCLASS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.NAME, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DESCRIPTION, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.TEMPLATE, RamanExperimentPF.getPropDefault(RamanExperimentPF.TEMPLATE), ...
		RamanExperimentPF.ID, RamanExperimentPF.getPropDefault(RamanExperimentPF.ID), ...
		RamanExperimentPF.LABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.LABEL), ...
		RamanExperimentPF.NOTES, RamanExperimentPF.getPropDefault(RamanExperimentPF.NOTES), ...
		RamanExperimentPF.TOSTRING, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.WAITBAR, RamanExperimentPF.getPropDefault(RamanExperimentPF.WAITBAR), ...
		RamanExperimentPF.H_WAITBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAWN, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.PARENT, RamanExperimentPF.getPropDefault(RamanExperimentPF.PARENT), ...
		RamanExperimentPF.BKGCOLOR, RamanExperimentPF.getPropDefault(RamanExperimentPF.BKGCOLOR), ...
		RamanExperimentPF.H, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.SHOW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.HIDE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DELETE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.CLOSE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_POSITION, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_POSITION), ...
		RamanExperimentPF.H_TOOLBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_TOOLS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AXES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AXIS, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_AXIS), ...
		RamanExperimentPF.LISTENER_ST_AXIS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.RE, RamanExperimentPF.getPropDefault(RamanExperimentPF.RE), ...
		RamanExperimentPF.SELECTED_SP, RamanExperimentPF.getPropDefault(RamanExperimentPF.SELECTED_SP), ...
		RamanExperimentPF.SETUP, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AREA, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_AREA), ...
		RamanExperimentPF.LISTENER_ST_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_LINE, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_LINE), ...
		RamanExperimentPF.LISTENER_ST_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.LINES, RamanExperimentPF.getPropDefault(RamanExperimentPF.LINES), ...
		RamanExperimentPF.LINE_DICT, RamanExperimentPF.getPropDefault(RamanExperimentPF.LINE_DICT), ...
		RamanExperimentPF.H_TITLE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_TITLE, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_TITLE), ...
		RamanExperimentPF.H_XLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_XLABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_XLABEL), ...
		RamanExperimentPF.H_YLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_YLABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_YLABEL) ...
		);
	 
	% RamanExperimentPF with 1st callbacks
	pf_1 = RamanExperimentPF( ...
		RamanExperimentPF.ELCLASS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.NAME, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DESCRIPTION, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.TEMPLATE, pf_0.getCallback(4), ..., ...
		RamanExperimentPF.ID, pf_0.getCallback(5), ..., ...
		RamanExperimentPF.LABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.LABEL), ...
		RamanExperimentPF.NOTES, RamanExperimentPF.getPropDefault(RamanExperimentPF.NOTES), ...
		RamanExperimentPF.TOSTRING, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.WAITBAR, pf_0.getCallback(9), ..., ...
		RamanExperimentPF.H_WAITBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAWN, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.PARENT, pf_0.getCallback(13), ..., ...
		RamanExperimentPF.BKGCOLOR, pf_0.getCallback(14), ..., ...
		RamanExperimentPF.H, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.SHOW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.HIDE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DELETE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.CLOSE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_POSITION, pf_0.getCallback(20), ..., ...
		RamanExperimentPF.H_TOOLBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_TOOLS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AXES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AXIS, pf_0.getCallback(24), ..., ...
		RamanExperimentPF.LISTENER_ST_AXIS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.RE, RamanExperimentPF.getPropDefault(RamanExperimentPF.RE), ...
		RamanExperimentPF.SELECTED_SP, pf_0.getCallback(27), ..., ...
		RamanExperimentPF.SETUP, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AREA, pf_0.getCallback(30), ..., ...
		RamanExperimentPF.LISTENER_ST_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_LINE, pf_0.getCallback(33), ..., ...
		RamanExperimentPF.LISTENER_ST_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.LINES, pf_0.getCallback(36), ..., ...
		RamanExperimentPF.LINE_DICT, pf_0.getCallback(37), ..., ...
		RamanExperimentPF.H_TITLE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_TITLE, pf_0.getCallback(39), ..., ...
		RamanExperimentPF.H_XLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_XLABEL, pf_0.getCallback(41), ..., ...
		RamanExperimentPF.H_YLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_YLABEL, pf_0.getCallback(43) ... ...
		);
	 
	prop_number = RamanExperimentPF.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(RamanExperimentPF.getPropTag(prop));
		switch RamanExperimentPF.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(pf_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(pf_1.get(prop), pf_0.get(prop)) && ~isa(pf_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(pf_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% RamanExperimentPF with 2nd callbacks
	pf_2 = RamanExperimentPF( ...
		RamanExperimentPF.ELCLASS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.NAME, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DESCRIPTION, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.TEMPLATE, pf_1.getCallback(4), ..., ...
		RamanExperimentPF.ID, pf_1.getCallback(5), ..., ...
		RamanExperimentPF.LABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.LABEL), ...
		RamanExperimentPF.NOTES, RamanExperimentPF.getPropDefault(RamanExperimentPF.NOTES), ...
		RamanExperimentPF.TOSTRING, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.WAITBAR, pf_1.getCallback(9), ..., ...
		RamanExperimentPF.H_WAITBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAWN, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.PARENT, pf_1.getCallback(13), ..., ...
		RamanExperimentPF.BKGCOLOR, pf_1.getCallback(14), ..., ...
		RamanExperimentPF.H, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.SHOW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.HIDE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DELETE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.CLOSE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_POSITION, pf_1.getCallback(20), ..., ...
		RamanExperimentPF.H_TOOLBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_TOOLS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AXES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AXIS, pf_1.getCallback(24), ..., ...
		RamanExperimentPF.LISTENER_ST_AXIS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.RE, RamanExperimentPF.getPropDefault(RamanExperimentPF.RE), ...
		RamanExperimentPF.SELECTED_SP, pf_1.getCallback(27), ..., ...
		RamanExperimentPF.SETUP, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AREA, pf_1.getCallback(30), ..., ...
		RamanExperimentPF.LISTENER_ST_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_LINE, pf_1.getCallback(33), ..., ...
		RamanExperimentPF.LISTENER_ST_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.LINES, pf_1.getCallback(36), ..., ...
		RamanExperimentPF.LINE_DICT, pf_1.getCallback(37), ..., ...
		RamanExperimentPF.H_TITLE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_TITLE, pf_1.getCallback(39), ..., ...
		RamanExperimentPF.H_XLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_XLABEL, pf_1.getCallback(41), ..., ...
		RamanExperimentPF.H_YLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_YLABEL, pf_1.getCallback(43) ... ...
		);
	 
	prop_number = RamanExperimentPF.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(RamanExperimentPF.getPropTag(prop));
		switch RamanExperimentPF.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(pf_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(pf_2.get(prop), pf_0.get(prop)) && ~isa(pf_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(pf_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% RamanExperimentPF with 3rd callbacks
	pf_3 = RamanExperimentPF( ...
		RamanExperimentPF.ELCLASS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.NAME, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DESCRIPTION, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.TEMPLATE, pf_2.getCallback(4), ..., ...
		RamanExperimentPF.ID, pf_2.getCallback(5), ..., ...
		RamanExperimentPF.LABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.LABEL), ...
		RamanExperimentPF.NOTES, RamanExperimentPF.getPropDefault(RamanExperimentPF.NOTES), ...
		RamanExperimentPF.TOSTRING, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.WAITBAR, pf_2.getCallback(9), ..., ...
		RamanExperimentPF.H_WAITBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAWN, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.PARENT, pf_2.getCallback(13), ..., ...
		RamanExperimentPF.BKGCOLOR, pf_2.getCallback(14), ..., ...
		RamanExperimentPF.H, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.SHOW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.HIDE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DELETE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.CLOSE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_POSITION, pf_2.getCallback(20), ..., ...
		RamanExperimentPF.H_TOOLBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_TOOLS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AXES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AXIS, pf_2.getCallback(24), ..., ...
		RamanExperimentPF.LISTENER_ST_AXIS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.RE, RamanExperimentPF.getPropDefault(RamanExperimentPF.RE), ...
		RamanExperimentPF.SELECTED_SP, pf_2.getCallback(27), ..., ...
		RamanExperimentPF.SETUP, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AREA, pf_2.getCallback(30), ..., ...
		RamanExperimentPF.LISTENER_ST_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_LINE, pf_2.getCallback(33), ..., ...
		RamanExperimentPF.LISTENER_ST_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.LINES, pf_2.getCallback(36), ..., ...
		RamanExperimentPF.LINE_DICT, pf_2.getCallback(37), ..., ...
		RamanExperimentPF.H_TITLE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_TITLE, pf_2.getCallback(39), ..., ...
		RamanExperimentPF.H_XLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_XLABEL, pf_2.getCallback(41), ..., ...
		RamanExperimentPF.H_YLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_YLABEL, pf_2.getCallback(43) ... ...
		);
	 
	prop_number = RamanExperimentPF.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(RamanExperimentPF.getPropTag(prop));
		switch RamanExperimentPF.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(pf_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(pf_3.get(prop), pf_0.get(prop)) && ~isa(pf_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(pf_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	
	warning('on', [BRAPH2.STR ':RamanExperimentPF'])
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':RamanExperimentPF'])
	
	% copy empty element
	pf = RamanExperimentPF();
	 
	pf_copy = pf.copy();
	 
	assert(pf_copy ~= pf, ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'RamanExperimentPF.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(pf_copy, pf), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'RamanExperimentPF.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		value = pf.getr(prop);
		value_copy = pf_copy.getr(prop);
		switch RamanExperimentPF.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					'RamanExperimentPF.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
							'RamanExperimentPF.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
							'RamanExperimentPF.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					pf_copy.isLocked(prop) == pf.isLocked(prop), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					'RamanExperimentPF.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					pf_copy.isChecked(prop) == pf.isChecked(prop), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					'RamanExperimentPF.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					pf_copy.getPropSeed(prop) == pf.getPropSeed(prop), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					'RamanExperimentPF.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	pf = RamanExperimentPF( ...
		RamanExperimentPF.ELCLASS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.NAME, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DESCRIPTION, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.TEMPLATE, RamanExperimentPF.getPropDefault(RamanExperimentPF.TEMPLATE), ...
		RamanExperimentPF.ID, RamanExperimentPF.getPropDefault(RamanExperimentPF.ID), ...
		RamanExperimentPF.LABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.LABEL), ...
		RamanExperimentPF.NOTES, RamanExperimentPF.getPropDefault(RamanExperimentPF.NOTES), ...
		RamanExperimentPF.TOSTRING, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.WAITBAR, RamanExperimentPF.getPropDefault(RamanExperimentPF.WAITBAR), ...
		RamanExperimentPF.H_WAITBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAWN, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.PARENT, RamanExperimentPF.getPropDefault(RamanExperimentPF.PARENT), ...
		RamanExperimentPF.BKGCOLOR, RamanExperimentPF.getPropDefault(RamanExperimentPF.BKGCOLOR), ...
		RamanExperimentPF.H, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.SHOW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.HIDE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DELETE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.CLOSE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_POSITION, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_POSITION), ...
		RamanExperimentPF.H_TOOLBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_TOOLS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AXES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AXIS, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_AXIS), ...
		RamanExperimentPF.LISTENER_ST_AXIS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.RE, RamanExperimentPF.getPropDefault(RamanExperimentPF.RE), ...
		RamanExperimentPF.SELECTED_SP, RamanExperimentPF.getPropDefault(RamanExperimentPF.SELECTED_SP), ...
		RamanExperimentPF.SETUP, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AREA, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_AREA), ...
		RamanExperimentPF.LISTENER_ST_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_LINE, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_LINE), ...
		RamanExperimentPF.LISTENER_ST_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.LINES, RamanExperimentPF.getPropDefault(RamanExperimentPF.LINES), ...
		RamanExperimentPF.LINE_DICT, RamanExperimentPF.getPropDefault(RamanExperimentPF.LINE_DICT), ...
		RamanExperimentPF.H_TITLE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_TITLE, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_TITLE), ...
		RamanExperimentPF.H_XLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_XLABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_XLABEL), ...
		RamanExperimentPF.H_YLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_YLABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_YLABEL) ...
		);
	 
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		if RamanExperimentPF.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':RamanExperimentPF']);
			% pf.memorize(prop);
			% warning(warning_backup)
		elseif RamanExperimentPF.getPropCategory(prop) == Category.EVANESCENT && pf.getPropFormat(prop) == Format.HANDLE
			pf.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:RamanExperimentPF');
			delete(ancestor(pf.get(prop), 'figure'))
			warning(warning_backup)
		else
			pf.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	pf_copy = pf.copy();
	 
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		value = pf.getr(prop);
		value_copy = pf_copy.getr(prop);
		switch RamanExperimentPF.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					'RamanExperimentPF.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
							'RamanExperimentPF.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
							'RamanExperimentPF.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						pf_copy.isLocked(prop) == pf.isLocked(prop), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pf_copy.isChecked(prop) == pf.isChecked(prop), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pf_copy.getPropSeed(prop) == pf.getPropSeed(prop), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	pf_0 = RamanExperimentPF( ...
		RamanExperimentPF.ELCLASS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.NAME, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DESCRIPTION, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.TEMPLATE, RamanExperimentPF.getPropDefault(RamanExperimentPF.TEMPLATE), ...
		RamanExperimentPF.ID, RamanExperimentPF.getPropDefault(RamanExperimentPF.ID), ...
		RamanExperimentPF.LABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.LABEL), ...
		RamanExperimentPF.NOTES, RamanExperimentPF.getPropDefault(RamanExperimentPF.NOTES), ...
		RamanExperimentPF.TOSTRING, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.WAITBAR, RamanExperimentPF.getPropDefault(RamanExperimentPF.WAITBAR), ...
		RamanExperimentPF.H_WAITBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAWN, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.PARENT, RamanExperimentPF.getPropDefault(RamanExperimentPF.PARENT), ...
		RamanExperimentPF.BKGCOLOR, RamanExperimentPF.getPropDefault(RamanExperimentPF.BKGCOLOR), ...
		RamanExperimentPF.H, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.SHOW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.HIDE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DELETE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.CLOSE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_POSITION, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_POSITION), ...
		RamanExperimentPF.H_TOOLBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_TOOLS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AXES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AXIS, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_AXIS), ...
		RamanExperimentPF.LISTENER_ST_AXIS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.RE, RamanExperimentPF.getPropDefault(RamanExperimentPF.RE), ...
		RamanExperimentPF.SELECTED_SP, RamanExperimentPF.getPropDefault(RamanExperimentPF.SELECTED_SP), ...
		RamanExperimentPF.SETUP, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AREA, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_AREA), ...
		RamanExperimentPF.LISTENER_ST_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_LINE, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_LINE), ...
		RamanExperimentPF.LISTENER_ST_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.LINES, RamanExperimentPF.getPropDefault(RamanExperimentPF.LINES), ...
		RamanExperimentPF.LINE_DICT, RamanExperimentPF.getPropDefault(RamanExperimentPF.LINE_DICT), ...
		RamanExperimentPF.H_TITLE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_TITLE, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_TITLE), ...
		RamanExperimentPF.H_XLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_XLABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_XLABEL), ...
		RamanExperimentPF.H_YLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_YLABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_YLABEL) ...
		);
	 
	pf = RamanExperimentPF( ...
		RamanExperimentPF.ELCLASS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.NAME, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DESCRIPTION, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.TEMPLATE, pf_0.getCallback(4), ..., ...
		RamanExperimentPF.ID, pf_0.getCallback(5), ..., ...
		RamanExperimentPF.LABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.LABEL), ...
		RamanExperimentPF.NOTES, RamanExperimentPF.getPropDefault(RamanExperimentPF.NOTES), ...
		RamanExperimentPF.TOSTRING, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.WAITBAR, pf_0.getCallback(9), ..., ...
		RamanExperimentPF.H_WAITBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAWN, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.PARENT, pf_0.getCallback(13), ..., ...
		RamanExperimentPF.BKGCOLOR, pf_0.getCallback(14), ..., ...
		RamanExperimentPF.H, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.SHOW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.HIDE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DELETE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.CLOSE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_POSITION, pf_0.getCallback(20), ..., ...
		RamanExperimentPF.H_TOOLBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_TOOLS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AXES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AXIS, pf_0.getCallback(24), ..., ...
		RamanExperimentPF.LISTENER_ST_AXIS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.RE, RamanExperimentPF.getPropDefault(RamanExperimentPF.RE), ...
		RamanExperimentPF.SELECTED_SP, pf_0.getCallback(27), ..., ...
		RamanExperimentPF.SETUP, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AREA, pf_0.getCallback(30), ..., ...
		RamanExperimentPF.LISTENER_ST_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_LINE, pf_0.getCallback(33), ..., ...
		RamanExperimentPF.LISTENER_ST_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.LINES, pf_0.getCallback(36), ..., ...
		RamanExperimentPF.LINE_DICT, pf_0.getCallback(37), ..., ...
		RamanExperimentPF.H_TITLE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_TITLE, pf_0.getCallback(39), ..., ...
		RamanExperimentPF.H_XLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_XLABEL, pf_0.getCallback(41), ..., ...
		RamanExperimentPF.H_YLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_YLABEL, pf_0.getCallback(43) ... ...
		);
	 
	pf_copy = pf.copy();
	pf_0_copy = pf_copy.getr('ID').get('EL');
	 
	for prop = 1:1:RamanExperimentPF.getPropNumber()
		value = pf.getr(prop);
		value_copy = pf_copy.getr(prop);
		switch RamanExperimentPF.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					'RamanExperimentPF.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
							'RamanExperimentPF.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
							'RamanExperimentPF.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == pf_0.getCallback(prop), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF.copy() does not work. The callback should be obtained from RamanExperimentPF.getCallback().' ...
						)
					assert( ...
						value_copy == pf_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF.copy() does not work. The callback should be obtained from RamanExperimentPF.getCallback().' ...
						)
				end
	 
					assert( ...
						pf_copy.isLocked(prop) == pf.isLocked(prop), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pf_copy.isChecked(prop) == pf.isChecked(prop), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pf_copy.getPropSeed(prop) == pf.getPropSeed(prop), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	
	warning('on', [BRAPH2.STR ':RamanExperimentPF'])
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':RamanExperimentPF'])
	
	pf_template = RamanExperimentPF();
	pf = RamanExperimentPF('TEMPLATE', pf_template);
	 
	for prop = 1:1:RamanExperimentPF.getPropNumber()
	 
		% excluded props
		if any(prop == [RamanExperimentPF.PARENT RamanExperimentPF.H RamanExperimentPF.ST_POSITION RamanExperimentPF.ST_AXIS RamanExperimentPF.ST_AREA RamanExperimentPF.ST_LINE RamanExperimentPF.ST_TITLE RamanExperimentPF.ST_XLABEL RamanExperimentPF.ST_YLABEL])
			continue
		end
	 
		TAG = upper(RamanExperimentPF.getPropTag(prop));
		switch RamanExperimentPF.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == RamanExperimentPF.TEMPLATE
					assert( ...
						isa(pf.getr(prop), 'RamanExperimentPF'), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF TEMPLATE does not work. RamanExperimentPF.getr(''TEMPLATE'') should be a RamanExperimentPF element.' ...
						)
					assert( ...
						isa(pf_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						'RamanExperimentPF TEMPLATE does not work. RamanExperimentPF_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(pf.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						['RamanExperimentPF TEMPLATE does not work. RamanExperimentPF.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						pf.getr(prop).get('EL') == pf_template && pf.getr(prop).get('PROP') == prop && strcmp(pf.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						['RamanExperimentPF TEMPLATE does not work. RamanExperimentPF.getr(' TAG ') should be a Callback to pf_template.' TAG '.'] ...
						)
					assert( ...
						isa(pf_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
						['RamanExperimentPF TEMPLATE does not work. RamanExperimentPF_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(pf.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF TEMPLATE does not work. RamanExperimentPF.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(pf_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
					['RamanExperimentPF TEMPLATE does not work. RamanExperimentPF_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
	
	warning('on', [BRAPH2.STR ':RamanExperimentPF'])
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':RamanExperimentPF'])
	
	pf = RamanExperimentPF( ...
		RamanExperimentPF.ELCLASS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.NAME, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DESCRIPTION, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.TEMPLATE, RamanExperimentPF.getPropDefault(RamanExperimentPF.TEMPLATE), ...
		RamanExperimentPF.ID, RamanExperimentPF.getPropDefault(RamanExperimentPF.ID), ...
		RamanExperimentPF.LABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.LABEL), ...
		RamanExperimentPF.NOTES, RamanExperimentPF.getPropDefault(RamanExperimentPF.NOTES), ...
		RamanExperimentPF.TOSTRING, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.WAITBAR, RamanExperimentPF.getPropDefault(RamanExperimentPF.WAITBAR), ...
		RamanExperimentPF.H_WAITBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAWN, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.PARENT, RamanExperimentPF.getPropDefault(RamanExperimentPF.PARENT), ...
		RamanExperimentPF.BKGCOLOR, RamanExperimentPF.getPropDefault(RamanExperimentPF.BKGCOLOR), ...
		RamanExperimentPF.H, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.SHOW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.HIDE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DELETE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.CLOSE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_POSITION, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_POSITION), ...
		RamanExperimentPF.H_TOOLBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_TOOLS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AXES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AXIS, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_AXIS), ...
		RamanExperimentPF.LISTENER_ST_AXIS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.RE, RamanExperimentPF.getPropDefault(RamanExperimentPF.RE), ...
		RamanExperimentPF.SELECTED_SP, RamanExperimentPF.getPropDefault(RamanExperimentPF.SELECTED_SP), ...
		RamanExperimentPF.SETUP, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AREA, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_AREA), ...
		RamanExperimentPF.LISTENER_ST_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_LINE, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_LINE), ...
		RamanExperimentPF.LISTENER_ST_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.LINES, RamanExperimentPF.getPropDefault(RamanExperimentPF.LINES), ...
		RamanExperimentPF.LINE_DICT, RamanExperimentPF.getPropDefault(RamanExperimentPF.LINE_DICT), ...
		RamanExperimentPF.H_TITLE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_TITLE, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_TITLE), ...
		RamanExperimentPF.H_XLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_XLABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_XLABEL), ...
		RamanExperimentPF.H_YLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_YLABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_YLABEL) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'ramanexperimentpf_to_be_erased.b2'];
	 
	Element.save(pf, filename)
	 
	pf_loaded = Element.load(filename);
	 
	assert( ...
		isequal(pf.copy(), pf_loaded), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'RamanExperimentPF.save(pf) and/or RamanExperimentPF.load() do not work.' ...
		)
	 
	delete(filename)
	
	warning('on', [BRAPH2.STR ':RamanExperimentPF'])
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':RamanExperimentPF'])
	
	pf = RamanExperimentPF( ...
		RamanExperimentPF.ELCLASS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.NAME, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DESCRIPTION, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.TEMPLATE, RamanExperimentPF.getPropDefault(RamanExperimentPF.TEMPLATE), ...
		RamanExperimentPF.ID, RamanExperimentPF.getPropDefault(RamanExperimentPF.ID), ...
		RamanExperimentPF.LABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.LABEL), ...
		RamanExperimentPF.NOTES, RamanExperimentPF.getPropDefault(RamanExperimentPF.NOTES), ...
		RamanExperimentPF.TOSTRING, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.WAITBAR, RamanExperimentPF.getPropDefault(RamanExperimentPF.WAITBAR), ...
		RamanExperimentPF.H_WAITBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DRAWN, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.PARENT, RamanExperimentPF.getPropDefault(RamanExperimentPF.PARENT), ...
		RamanExperimentPF.BKGCOLOR, RamanExperimentPF.getPropDefault(RamanExperimentPF.BKGCOLOR), ...
		RamanExperimentPF.H, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.SHOW, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.HIDE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.DELETE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.CLOSE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_POSITION, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_POSITION), ...
		RamanExperimentPF.H_TOOLBAR, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_TOOLS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AXES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AXIS, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_AXIS), ...
		RamanExperimentPF.LISTENER_ST_AXIS, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.RE, RamanExperimentPF.getPropDefault(RamanExperimentPF.RE), ...
		RamanExperimentPF.SELECTED_SP, RamanExperimentPF.getPropDefault(RamanExperimentPF.SELECTED_SP), ...
		RamanExperimentPF.SETUP, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_AREA, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_AREA), ...
		RamanExperimentPF.LISTENER_ST_AREA, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_LINE, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_LINE), ...
		RamanExperimentPF.LISTENER_ST_LINE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.H_LINES, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.LINES, RamanExperimentPF.getPropDefault(RamanExperimentPF.LINES), ...
		RamanExperimentPF.LINE_DICT, RamanExperimentPF.getPropDefault(RamanExperimentPF.LINE_DICT), ...
		RamanExperimentPF.H_TITLE, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_TITLE, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_TITLE), ...
		RamanExperimentPF.H_XLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_XLABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_XLABEL), ...
		RamanExperimentPF.H_YLABEL, RamanExperimentPF.getNoValue(), ...
		RamanExperimentPF.ST_YLABEL, RamanExperimentPF.getPropDefault(RamanExperimentPF.ST_YLABEL) ...
		);
	 
	[json, struct, el_list] = encodeJSON(pf);
	[pf_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(pf_dec ~= pf, ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		'RamanExperimentPF.encodeJSON() or RamanExperimentPF.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) RamanExperimentPF.getPropFormat(prop), num2cell(RamanExperimentPF.getProps())) == Format.HANDLE) && all(cellfun(@(prop) RamanExperimentPF.getPropFormat(prop), num2cell(RamanExperimentPF.getProps())) == Format.NET)
		assert(isequal(pf_dec, pf), ...
			[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
			'RamanExperimentPF.encodeJSON() or RamanExperimentPF.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
	
	warning('on', [BRAPH2.STR ':RamanExperimentPF'])
end

%% Test 12: Remove Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':RamanExperimentPF'])
	
	warning('off', [BRAPH2.STR ':RamanExperimentPF'])
	assert(length(findall(0, 'type', 'figure')) == 5)
	delete(findall(0, 'type', 'figure'))
	warning('on', [BRAPH2.STR ':RamanExperimentPF'])
	
	warning('on', [BRAPH2.STR ':RamanExperimentPF'])
end

%% Test 13: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':RamanExperimentPF'])
	
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':RamanExperimentPF:' BRAPH2.FAIL_TEST], ...
		[' When testing RamanExperimentPF no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
	
	warning('on', [BRAPH2.STR ':RamanExperimentPF'])
end

%% Test 14: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':RamanExperimentPF'])
	
	delete(findall(0, 'type', 'figure'))
	
	warning('on', [BRAPH2.STR ':RamanExperimentPF'])
end

