%TEST_PANELPROPRVECTORDATE

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropRVectorDate'])
	
	categories = num2cell(Category.getCategories());
	pr = PanelPropRVectorDate();
	 
	% get('ELCLASS')
	if isa(PanelPropRVectorDate, 'ConcreteElement')
		assert(strcmp(PanelPropRVectorDate().get('ELCLASS'), 'PanelPropRVectorDate'), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'PanelPropRVectorDate().get(''ELCLASS'') should return ''PanelPropRVectorDate''.')
	end
	 
	% getBuild()
	assert(PanelPropRVectorDate.getBuild() == 1 && PanelPropRVectorDate.getBuild() > 0, ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'PanelPropRVectorDate.getBuild() should return the PanelPropRVectorDate build number.')
	assert(pr.getBuild() == 1 && pr.getBuild() > 0 , ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'pr.getBuild() should return the PanelPropRVectorDate build number.')
	assert(Element.getBuild(pr) == 1 && Element.getBuild(pr) > 0, ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(pr) should return the PanelPropRVectorDate build number.')
	assert(Element.getBuild('PanelPropRVectorDate') == 1 && Element.getBuild('PanelPropRVectorDate') > 0, ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''PanelPropRVectorDate'') should return the PanelPropRVectorDate build number.')
	 
	% getClass()
	assert(strcmp(PanelPropRVectorDate.getClass(), 'PanelPropRVectorDate'), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'PanelPropRVectorDate.getClass() should return ''PanelPropRVectorDate''.')
	assert(strcmp(pr.getClass(), 'PanelPropRVectorDate'), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'pr.getClass() should return ''PanelPropRVectorDate''.')
	assert(strcmp(Element.getClass(pr), 'PanelPropRVectorDate'), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(pr) should return ''PanelPropRVectorDate''.')
	assert(strcmp(Element.getClass('PanelPropRVectorDate'), 'PanelPropRVectorDate'), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''PanelPropRVectorDate'') should return ''PanelPropRVectorDate''.')
	 
	% getSubclasses()
	assert(isequal(PanelPropRVectorDate.getSubclasses(), subclasses('PanelPropRVectorDate', [], [], true)), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'PanelPropRVectorDate.getSubclasses() should return the same result as subclasses(''PanelPropRVectorDate'', [], [], true).')
	assert(isequal(pr.getSubclasses(), subclasses('PanelPropRVectorDate', [], [], true)), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''PanelPropRVectorDate'', [], [], true).')
	assert(isequal(Element.getSubclasses(pr), subclasses('PanelPropRVectorDate', [], [], true)), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(pr) should return the same result as subclasses(''PanelPropRVectorDate'', [], [], true).')
	assert(isequal(Element.getSubclasses('PanelPropRVectorDate'), subclasses('PanelPropRVectorDate', [], [], true)), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''PanelPropRVectorDate'') should return the same result as subclasses(''PanelPropRVectorDate'', [], [], true).')
	 
	% getProps()
	assert(isempty(PanelPropRVectorDate.getProps()) || isequal(PanelPropRVectorDate.getProps(), 1:1:length(PanelPropRVectorDate.getProps())), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'PanelPropRVectorDate.getProps() should return a row vector [1:1:N].')
	assert(isempty(PanelPropRVectorDate.getProps()) || isequal(pr.getProps(), 1:1:length(PanelPropRVectorDate.getProps())), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'pr.getProps() should return a row vector [1:1:N].')
	assert(isempty(PanelPropRVectorDate.getProps()) || isequal(Element.getProps(pr), 1:1:length(PanelPropRVectorDate.getProps())), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(pr) should return a row vector [1:1:N].')
	assert(isempty(PanelPropRVectorDate.getProps()) || isequal(Element.getProps('PanelPropRVectorDate'), 1:1:length(PanelPropRVectorDate.getProps())), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''PanelPropRVectorDate'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) PanelPropRVectorDate.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(PanelPropRVectorDate.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(PanelPropRVectorDate.getProps())), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'PanelPropRVectorDate.getProps(category) does not work.')
	tmp = cellfun(@(category) pr.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(PanelPropRVectorDate.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(PanelPropRVectorDate.getProps())), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'pr.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(pr, category), categories, 'UniformOutput', false);
	assert(isempty(PanelPropRVectorDate.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(PanelPropRVectorDate.getProps())), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(pr, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('PanelPropRVectorDate', category), categories, 'UniformOutput', false);
	assert(isempty(PanelPropRVectorDate.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(PanelPropRVectorDate.getProps())), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''PanelPropRVectorDate'', category) does not work.')
	 
	% getPropNumber()
	assert(PanelPropRVectorDate.getPropNumber() == length(PanelPropRVectorDate.getProps()), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'PanelPropRVectorDate.getPropNumber() should return the number of properties.')
	assert(pr.getPropNumber() == length(PanelPropRVectorDate.getProps()), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'pr.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(pr) == length(PanelPropRVectorDate.getProps()), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(pr) should return the number of properties.')
	assert(Element.getPropNumber('PanelPropRVectorDate') == length(PanelPropRVectorDate.getProps()), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''PanelPropRVectorDate'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) PanelPropRVectorDate.getPropNumber(category), categories)) == PanelPropRVectorDate.getPropNumber(), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'PanelPropRVectorDate.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) pr.getPropNumber(category), categories)) == PanelPropRVectorDate.getPropNumber(), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'pr.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(pr, category), categories)) == PanelPropRVectorDate.getPropNumber(), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(pr, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('PanelPropRVectorDate', category), categories)) == PanelPropRVectorDate.getPropNumber(), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''PanelPropRVectorDate'', category) does not work.')
	 
	% existsProp(prop)
	assert(~PanelPropRVectorDate.existsProp(NaN), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'PanelPropRVectorDate.existsProp(prop) does not work.')
	assert(~pr.existsProp(NaN), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'pr.existsProp(prop) does not work.')
	assert(~Element.existsProp(pr, NaN), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(pr, prop) does not work.')
	assert(~Element.existsProp('PanelPropRVectorDate', NaN), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''PanelPropRVectorDate'', prop) does not work.')
	 
	assert_with_error('PanelPropRVectorDate.existsProp(NaN)', [BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.WRONG_INPUT], pr)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.WRONG_INPUT], pr)
	assert_with_error('Element.existsProp(''PanelPropRVectorDate'', NaN)', [BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		assert(PanelPropRVectorDate.existsProp(prop), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'PanelPropRVectorDate.existsProp(prop) does not work.')
		assert(pr.existsProp(prop), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'pr.existsProp(prop) does not work.')
		assert(Element.existsProp(pr, prop), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(pr, prop) does not work.')
		assert(Element.existsProp('PanelPropRVectorDate', prop), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''PanelPropRVectorDate'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~PanelPropRVectorDate.existsTag(''), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'PanelPropRVectorDate.existsTag(tag) does not work.')
	assert(~pr.existsTag(''), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'pr.existsTag(tag) does not work.')
	assert(~Element.existsTag(pr, ''), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(pr, tag) does not work.')
	assert(~Element.existsTag('PanelPropRVectorDate', ''), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''PanelPropRVectorDate'', tag) does not work.')
	 
	assert_with_error('PanelPropRVectorDate.existsTag('''')', [BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.WRONG_INPUT], pr)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.WRONG_INPUT], pr)
	assert_with_error('Element.existsTag(''PanelPropRVectorDate'', '''')', [BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		tag = pr.getPropTag(prop);
		assert(PanelPropRVectorDate.existsTag(tag), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'PanelPropRVectorDate.existsTag(tag) does not work.')
		assert(pr.existsTag(tag), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'pr.existsTag(tag) does not work.')
		assert(Element.existsTag(pr, tag), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(pr, tga) does not work.')
		assert(Element.existsTag('PanelPropRVectorDate', tag), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''PanelPropRVectorDate'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		assert(PanelPropRVectorDate.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'PanelPropRVectorDate.getPropProp(prop) does not work.')
		assert(pr.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'pr.getPropProp(prop) does not work.')
		assert(Element.getPropProp(pr, prop) == prop, ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(pr, prop) does not work.')
		assert(Element.getPropProp('PanelPropRVectorDate', prop) == prop, ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''PanelPropRVectorDate'', prop) does not work.')
	 
		tag = pr.getPropTag(prop);
		assert(PanelPropRVectorDate.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'PanelPropRVectorDate.getPropProp(tag) does not work.')
		assert(pr.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'pr.getPropProp(tag) does not work.')
		assert(Element.getPropProp(pr, tag) == prop, ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(pr, tag) does not work.')
		assert(Element.getPropProp('PanelPropRVectorDate', prop) == prop, ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''PanelPropRVectorDate'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		assert(strcmp(PanelPropRVectorDate.getPropTag(prop), tag), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'PanelPropRVectorDate.getPropTag(prop) does not work.')
		assert(strcmp(pr.getPropTag(prop), tag), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'pr.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(pr, prop), tag), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(pr, prop) does not work.')
		assert(strcmp(Element.getPropTag('PanelPropRVectorDate', prop), tag), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''PanelPropRVectorDate'', prop) does not work.')
	 
		assert(strcmp(PanelPropRVectorDate.getPropTag(tag), tag), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'PanelPropRVectorDate.getPropTag(tag) does not work.')
		assert(strcmp(pr.getPropTag(tag), tag), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'pr.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(pr, tag), tag), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(pr, tag) does not work.')
		assert(strcmp(Element.getPropTag('PanelPropRVectorDate', prop), tag), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''PanelPropRVectorDate'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		assert(Category.existsCategory(PanelPropRVectorDate.getPropCategory(prop)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'PanelPropRVectorDate.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(pr.getPropCategory(prop)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'pr.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pr, prop)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(pr, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pr, prop)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''PanelPropRVectorDate'', prop) does not work.')
	 
		assert(Category.existsCategory(PanelPropRVectorDate.getPropCategory(tag)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'PanelPropRVectorDate.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(pr.getPropCategory(tag)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'pr.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pr, tag)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(pr, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pr, tag)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''PanelPropRVectorDate'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		assert(Format.existsFormat(PanelPropRVectorDate.getPropFormat(prop)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'PanelPropRVectorDate.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(pr.getPropFormat(prop)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'pr.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pr, prop)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(pr, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pr, prop)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''PanelPropRVectorDate'', prop) does not work.')
	 
		assert(Format.existsFormat(PanelPropRVectorDate.getPropFormat(tag)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'PanelPropRVectorDate.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(pr.getPropFormat(tag)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'pr.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pr, tag)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(pr, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pr, tag)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''PanelPropRVectorDate'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		assert(ischar(PanelPropRVectorDate.getPropDescription(prop)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'PanelPropRVectorDate.getPropDescription(prop) does not work.')
		assert(ischar(pr.getPropDescription(prop)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'pr.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(pr, prop)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(pr, prop) does not work.')
		assert(ischar(Element.getPropDescription(pr, prop)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''PanelPropRVectorDate'', prop) does not work.')
	 
		assert(ischar(PanelPropRVectorDate.getPropDescription(tag)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'PanelPropRVectorDate.getPropDescription(tag) does not work.')
		assert(ischar(pr.getPropDescription(tag)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'pr.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(pr, tag)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(pr, tag) does not work.')
		assert(ischar(Element.getPropDescription(pr, tag)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''PanelPropRVectorDate'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		settings = PanelPropRVectorDate.getPropSettings(prop);
		settings = pr.getPropSettings(prop);
		settings = Element.getPropSettings(pr, prop);
		settings = Element.getPropSettings('PanelPropRVectorDate', prop);
	 
		settings = PanelPropRVectorDate.getPropSettings(tag);
		settings = pr.getPropSettings(tag);
		settings = Element.getPropSettings(pr, tag);
		settings = Element.getPropSettings('PanelPropRVectorDate', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		default = PanelPropRVectorDate.getPropDefault(prop);
		default = pr.getPropDefault(prop);
		default = Element.getPropDefault(pr, prop);
		default = Element.getPropDefault('PanelPropRVectorDate', prop);
	 
		default = PanelPropRVectorDate.getPropDefault(tag);
		default = pr.getPropDefault(tag);
		default = Element.getPropDefault(pr, tag);
		default = Element.getPropDefault('PanelPropRVectorDate', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		conditioned_default = PanelPropRVectorDate.getPropDefaultConditioned(prop);
		conditioned_default = pr.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(pr, prop);
		conditioned_default = Element.getPropDefaultConditioned('PanelPropRVectorDate', prop);
	 
		conditioned_default = PanelPropRVectorDate.getPropDefaultConditioned(tag);
		conditioned_default = pr.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(pr, tag);
		conditioned_default = Element.getPropDefaultConditioned('PanelPropRVectorDate', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		assert(~PanelPropRVectorDate.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'PanelPropRVectorDate.checkProp(prop, value) does not work.')
		assert(~pr.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'pr.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(pr, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pr, prop, value) does not work.')
		assert(~Element.checkProp('PanelPropRVectorDate', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''PanelPropRVectorDate'', prop, value) does not work.')
	 
		assert_with_error('PanelPropRVectorDate.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.WRONG_INPUT], prop, pr)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.WRONG_INPUT], prop, pr)
		assert_with_error('Element.checkProp(''PanelPropRVectorDate'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~PanelPropRVectorDate.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'PanelPropRVectorDate.checkProp(tag, value) does not work.')
		assert(~pr.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'pr.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(pr, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pr, tag, value) does not work.')
		assert(~Element.checkProp('PanelPropRVectorDate', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''PanelPropRVectorDate'', tag, value) does not work.')
	 
		assert_with_error('PanelPropRVectorDate.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.WRONG_INPUT], tag, pr)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.WRONG_INPUT], tag, pr)
		assert_with_error('Element.checkProp(''PanelPropRVectorDate'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(PanelPropRVectorDate.checkProp(prop, Element.getPropDefaultConditioned(PanelPropRVectorDate, prop)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'PanelPropRVectorDate.checkProp(prop, <conditioned default value>) does not work.')
		assert(pr.checkProp(prop, Element.getPropDefaultConditioned(PanelPropRVectorDate, prop)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'pr.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(pr, prop, Element.getPropDefaultConditioned(PanelPropRVectorDate, prop)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pr, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('PanelPropRVectorDate', prop, Element.getPropDefaultConditioned(PanelPropRVectorDate, prop)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''PanelPropRVectorDate'', prop, <conditioned default value>) does not work.')
	 
		assert(PanelPropRVectorDate.checkProp(tag, Element.getPropDefaultConditioned(PanelPropRVectorDate, prop)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'PanelPropRVectorDate.checkProp(tag, <conditioned default value>) does not work.')
		assert(pr.checkProp(tag, Element.getPropDefaultConditioned(PanelPropRVectorDate, prop)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'pr.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(pr, tag, Element.getPropDefaultConditioned(PanelPropRVectorDate, prop)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pr, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('PanelPropRVectorDate', tag, Element.getPropDefaultConditioned(PanelPropRVectorDate, prop)), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''PanelPropRVectorDate'', tag, <conditioned default value>) does not work.')
	 
	end
	 
	
	warning('on', [BRAPH2.STR ':PanelPropRVectorDate'])
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropRVectorDate'])
	
	pr = PanelPropRVectorDate( ...
		PanelPropRVectorDate.ELCLASS, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.NAME, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DESCRIPTION, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.TEMPLATE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.TEMPLATE), ...
		PanelPropRVectorDate.ID, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.ID), ...
		PanelPropRVectorDate.LABEL, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.LABEL), ...
		PanelPropRVectorDate.NOTES, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.NOTES), ...
		PanelPropRVectorDate.TOSTRING, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.WAITBAR, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.WAITBAR), ...
		PanelPropRVectorDate.H_WAITBAR, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAWN, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.PARENT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.PARENT), ...
		PanelPropRVectorDate.BKGCOLOR, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.BKGCOLOR), ...
		PanelPropRVectorDate.H, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.SHOW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.HIDE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DELETE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.CLOSE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.X_DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.UPDATE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.REDRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.EL, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.EL), ...
		PanelPropRVectorDate.PROP, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.PROP), ...
		PanelPropRVectorDate.HEIGHT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.HEIGHT), ...
		PanelPropRVectorDate.TITLE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.TITLE), ...
		PanelPropRVectorDate.LABEL_TITLE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.GUI_CB, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.GUI_CB), ...
		PanelPropRVectorDate.LISTENER_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CALC, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_DEL, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_SET, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_MEMORIZED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_LOCKED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.ENABLE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.ENABLE), ...
		PanelPropRVectorDate.EDITFIELD, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.FORMAT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.FORMAT) ...
		);
	 
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
	 
		% excluded props
		if any(prop == [PanelPropRVectorDate.PARENT PanelPropRVectorDate.H PanelPropRVectorDate.LISTENER_CB PanelPropRVectorDate.EDITFIELD])
			continue
		end
	 
		TAG = upper(PanelPropRVectorDate.getPropTag(prop));
		switch PanelPropRVectorDate.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					pr.getr(prop) == PanelPropRVectorDate.getNoValue(), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['Being a ' PanelPropRVectorDate.getCategoryName(PanelPropRVectorDate.getPropCategory(prop)) ', PanelPropRVectorDate.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in PanelPropRVectorDate.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					pr.getr(TAG) == PanelPropRVectorDate.getNoValue(), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['Being a ' PanelPropRVectorDate.getCategoryName(PanelPropRVectorDate.getPropCategory(prop)) ', PanelPropRVectorDate.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in PanelPropRVectorDate.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(pr.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(pr.getPropSettings(prop))
					assert( ...
						pr.checkFormat(pr.getPropFormat(prop), pr.get(prop)), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						['PanelPropRVectorDate.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						pr.checkFormat(pr.getPropFormat(prop), pr.get(prop), pr.getPropSettings(prop)), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						['PanelPropRVectorDate.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					pr.getr(prop) == PanelPropRVectorDate.getNoValue(), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['Being a ' PanelPropRVectorDate.getCategoryName(PanelPropRVectorDate.getPropCategory(prop)) ', PanelPropRVectorDate.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in PanelPropRVectorDate.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					pr.getr(TAG) == PanelPropRVectorDate.getNoValue(), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['Being a ' PanelPropRVectorDate.getCategoryName(PanelPropRVectorDate.getPropCategory(prop)) ', PanelPropRVectorDate.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in PanelPropRVectorDate.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':PanelPropRVectorDate']);
				assert( ...
					~isa(pr.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(pr.getPropSettings(prop))
					assert( ...
						pr.checkFormat(pr.getPropFormat(prop), pr.get(prop)), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						['PanelPropRVectorDate.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						pr.checkFormat(pr.getPropFormat(prop), pr.get(prop), pr.getPropSettings(prop)), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						['PanelPropRVectorDate.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(pr.getr(prop), PanelPropRVectorDate.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by PanelPropRVectorDate.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in PanelPropRVectorDate.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(pr.getr(TAG), PanelPropRVectorDate.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.getr(' TAG ') must be inizialized to its default value ' ...
					'given by PanelPropRVectorDate.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in PanelPropRVectorDate.getr(' TAG ').'] ...
					)
		end
	end
	
	warning('on', [BRAPH2.STR ':PanelPropRVectorDate'])
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropRVectorDate'])
	
	pr = PanelPropRVectorDate( ...
		PanelPropRVectorDate.ELCLASS, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.NAME, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DESCRIPTION, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.TEMPLATE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.TEMPLATE), ...
		PanelPropRVectorDate.ID, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.ID), ...
		PanelPropRVectorDate.LABEL, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.LABEL), ...
		PanelPropRVectorDate.NOTES, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.NOTES), ...
		PanelPropRVectorDate.TOSTRING, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.WAITBAR, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.WAITBAR), ...
		PanelPropRVectorDate.H_WAITBAR, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAWN, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.PARENT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.PARENT), ...
		PanelPropRVectorDate.BKGCOLOR, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.BKGCOLOR), ...
		PanelPropRVectorDate.H, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.SHOW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.HIDE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DELETE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.CLOSE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.X_DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.UPDATE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.REDRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.EL, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.EL), ...
		PanelPropRVectorDate.PROP, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.PROP), ...
		PanelPropRVectorDate.HEIGHT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.HEIGHT), ...
		PanelPropRVectorDate.TITLE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.TITLE), ...
		PanelPropRVectorDate.LABEL_TITLE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.GUI_CB, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.GUI_CB), ...
		PanelPropRVectorDate.LISTENER_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CALC, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_DEL, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_SET, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_MEMORIZED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_LOCKED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.ENABLE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.ENABLE), ...
		PanelPropRVectorDate.EDITFIELD, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.FORMAT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.FORMAT) ...
		);
	 
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
	 
		% excluded props
		if any(prop == [PanelPropRVectorDate.PARENT PanelPropRVectorDate.H PanelPropRVectorDate.LISTENER_CB PanelPropRVectorDate.EDITFIELD])
			continue
		end
	 
		TAG = upper(PanelPropRVectorDate.getPropTag(prop));
		switch PanelPropRVectorDate.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(pr.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(pr.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					pr.checkFormat(pr.getPropFormat(prop), pr.getr(prop),pr.getPropSettings(prop)), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':PanelPropRVectorDate']);
				assert( ...
					~isa(pr.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':PanelPropRVectorDate']);
	% 			assert( ...
	% 				~isa(pr.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
	% 				['PanelPropRVectorDate.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(pr.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
	% 				['PanelPropRVectorDate.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				pr.checkFormat(pr.getPropFormat(prop), pr.getr(prop),pr.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
	% 				['PanelPropRVectorDate.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':PanelPropRVectorDate']);
				assert( ...
					~isa(pr.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(pr.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					pr.checkFormat(pr.getPropFormat(prop), pr.getr(prop),pr.getPropSettings(prop)), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if pr.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:PanelPropRVectorDate');
					delete(ancestor(pr.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(PanelPropRVectorDate.getProps(Category.RESULT))
		for prop = 1:1:PanelPropRVectorDate.getPropNumber()
	 
			% excluded props
			if any(prop == [PanelPropRVectorDate.PARENT PanelPropRVectorDate.H PanelPropRVectorDate.LISTENER_CB PanelPropRVectorDate.EDITFIELD])
				continue
			end
	 
			switch PanelPropRVectorDate.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						pr.isLocked(prop), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						['PanelPropRVectorDate.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~pr.isLocked(prop), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						['PanelPropRVectorDate.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
	
	warning('on', [BRAPH2.STR ':PanelPropRVectorDate'])
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropRVectorDate'])
	
	pr = PanelPropRVectorDate();
	 
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		TAG = upper(PanelPropRVectorDate.getPropTag(prop));
		assert( ...
			~pr.isLocked(prop), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			['PanelPropRVectorDate.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~pr.isLocked(TAG), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			['PanelPropRVectorDate.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	pr.lock()
	 
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		switch PanelPropRVectorDate.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					pr.isLocked(prop), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~pr.isLocked(prop), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
	
	warning('on', [BRAPH2.STR ':PanelPropRVectorDate'])
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropRVectorDate'])
	
	pr = PanelPropRVectorDate();
	 
	warning_backup = warning('off', 'BRAPH2:PanelPropRVectorDate');
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		pr.lock(prop)
		switch PanelPropRVectorDate.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					pr.isLocked(prop), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~pr.isLocked(prop), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
	
	warning('on', [BRAPH2.STR ':PanelPropRVectorDate'])
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropRVectorDate'])
	
	pr = PanelPropRVectorDate();
	 
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		TAG = upper(PanelPropRVectorDate.getPropTag(prop));
		assert( ...
			pr.isChecked(prop), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			['PanelPropRVectorDate.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			pr.isChecked(TAG), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			['PanelPropRVectorDate.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	pr.unchecked()
	 
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		assert( ...
			~pr.isChecked(prop), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			['PanelPropRVectorDate.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	pr.checked()
	 
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		assert( ...
			pr.isChecked(prop), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			['PanelPropRVectorDate.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
	
	warning('on', [BRAPH2.STR ':PanelPropRVectorDate'])
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropRVectorDate'])
	
	% basic PanelPropRVectorDate
	pr_0 = PanelPropRVectorDate( ...
		PanelPropRVectorDate.ELCLASS, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.NAME, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DESCRIPTION, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.TEMPLATE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.TEMPLATE), ...
		PanelPropRVectorDate.ID, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.ID), ...
		PanelPropRVectorDate.LABEL, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.LABEL), ...
		PanelPropRVectorDate.NOTES, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.NOTES), ...
		PanelPropRVectorDate.TOSTRING, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.WAITBAR, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.WAITBAR), ...
		PanelPropRVectorDate.H_WAITBAR, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAWN, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.PARENT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.PARENT), ...
		PanelPropRVectorDate.BKGCOLOR, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.BKGCOLOR), ...
		PanelPropRVectorDate.H, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.SHOW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.HIDE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DELETE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.CLOSE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.X_DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.UPDATE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.REDRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.EL, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.EL), ...
		PanelPropRVectorDate.PROP, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.PROP), ...
		PanelPropRVectorDate.HEIGHT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.HEIGHT), ...
		PanelPropRVectorDate.TITLE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.TITLE), ...
		PanelPropRVectorDate.LABEL_TITLE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.GUI_CB, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.GUI_CB), ...
		PanelPropRVectorDate.LISTENER_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CALC, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_DEL, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_SET, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_MEMORIZED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_LOCKED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.ENABLE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.ENABLE), ...
		PanelPropRVectorDate.EDITFIELD, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.FORMAT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.FORMAT) ...
		);
	 
	% PanelPropRVectorDate with 1st callbacks
	pr_1 = PanelPropRVectorDate( ...
		PanelPropRVectorDate.ELCLASS, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.NAME, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DESCRIPTION, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.TEMPLATE, pr_0.getCallback(4), ..., ...
		PanelPropRVectorDate.ID, pr_0.getCallback(5), ..., ...
		PanelPropRVectorDate.LABEL, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.LABEL), ...
		PanelPropRVectorDate.NOTES, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.NOTES), ...
		PanelPropRVectorDate.TOSTRING, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.WAITBAR, pr_0.getCallback(9), ..., ...
		PanelPropRVectorDate.H_WAITBAR, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAWN, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.PARENT, pr_0.getCallback(13), ..., ...
		PanelPropRVectorDate.BKGCOLOR, pr_0.getCallback(14), ..., ...
		PanelPropRVectorDate.H, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.SHOW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.HIDE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DELETE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.CLOSE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.X_DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.UPDATE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.REDRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.EL, pr_0.getCallback(23), ..., ...
		PanelPropRVectorDate.PROP, pr_0.getCallback(24), ..., ...
		PanelPropRVectorDate.HEIGHT, pr_0.getCallback(25), ..., ...
		PanelPropRVectorDate.TITLE, pr_0.getCallback(26), ..., ...
		PanelPropRVectorDate.LABEL_TITLE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.GUI_CB, pr_0.getCallback(29), ..., ...
		PanelPropRVectorDate.LISTENER_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CALC, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_DEL, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_SET, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_MEMORIZED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_LOCKED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.ENABLE, pr_0.getCallback(36), ..., ...
		PanelPropRVectorDate.EDITFIELD, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.FORMAT, pr_0.getCallback(38) ... ...
		);
	 
	prop_number = PanelPropRVectorDate.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(PanelPropRVectorDate.getPropTag(prop));
		switch PanelPropRVectorDate.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(pr_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(pr_1.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(pr_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% PanelPropRVectorDate with 2nd callbacks
	pr_2 = PanelPropRVectorDate( ...
		PanelPropRVectorDate.ELCLASS, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.NAME, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DESCRIPTION, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.TEMPLATE, pr_1.getCallback(4), ..., ...
		PanelPropRVectorDate.ID, pr_1.getCallback(5), ..., ...
		PanelPropRVectorDate.LABEL, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.LABEL), ...
		PanelPropRVectorDate.NOTES, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.NOTES), ...
		PanelPropRVectorDate.TOSTRING, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.WAITBAR, pr_1.getCallback(9), ..., ...
		PanelPropRVectorDate.H_WAITBAR, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAWN, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.PARENT, pr_1.getCallback(13), ..., ...
		PanelPropRVectorDate.BKGCOLOR, pr_1.getCallback(14), ..., ...
		PanelPropRVectorDate.H, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.SHOW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.HIDE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DELETE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.CLOSE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.X_DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.UPDATE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.REDRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.EL, pr_1.getCallback(23), ..., ...
		PanelPropRVectorDate.PROP, pr_1.getCallback(24), ..., ...
		PanelPropRVectorDate.HEIGHT, pr_1.getCallback(25), ..., ...
		PanelPropRVectorDate.TITLE, pr_1.getCallback(26), ..., ...
		PanelPropRVectorDate.LABEL_TITLE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.GUI_CB, pr_1.getCallback(29), ..., ...
		PanelPropRVectorDate.LISTENER_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CALC, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_DEL, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_SET, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_MEMORIZED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_LOCKED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.ENABLE, pr_1.getCallback(36), ..., ...
		PanelPropRVectorDate.EDITFIELD, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.FORMAT, pr_1.getCallback(38) ... ...
		);
	 
	prop_number = PanelPropRVectorDate.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(PanelPropRVectorDate.getPropTag(prop));
		switch PanelPropRVectorDate.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(pr_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(pr_2.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(pr_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% PanelPropRVectorDate with 3rd callbacks
	pr_3 = PanelPropRVectorDate( ...
		PanelPropRVectorDate.ELCLASS, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.NAME, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DESCRIPTION, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.TEMPLATE, pr_2.getCallback(4), ..., ...
		PanelPropRVectorDate.ID, pr_2.getCallback(5), ..., ...
		PanelPropRVectorDate.LABEL, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.LABEL), ...
		PanelPropRVectorDate.NOTES, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.NOTES), ...
		PanelPropRVectorDate.TOSTRING, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.WAITBAR, pr_2.getCallback(9), ..., ...
		PanelPropRVectorDate.H_WAITBAR, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAWN, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.PARENT, pr_2.getCallback(13), ..., ...
		PanelPropRVectorDate.BKGCOLOR, pr_2.getCallback(14), ..., ...
		PanelPropRVectorDate.H, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.SHOW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.HIDE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DELETE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.CLOSE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.X_DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.UPDATE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.REDRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.EL, pr_2.getCallback(23), ..., ...
		PanelPropRVectorDate.PROP, pr_2.getCallback(24), ..., ...
		PanelPropRVectorDate.HEIGHT, pr_2.getCallback(25), ..., ...
		PanelPropRVectorDate.TITLE, pr_2.getCallback(26), ..., ...
		PanelPropRVectorDate.LABEL_TITLE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.GUI_CB, pr_2.getCallback(29), ..., ...
		PanelPropRVectorDate.LISTENER_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CALC, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_DEL, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_SET, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_MEMORIZED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_LOCKED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.ENABLE, pr_2.getCallback(36), ..., ...
		PanelPropRVectorDate.EDITFIELD, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.FORMAT, pr_2.getCallback(38) ... ...
		);
	 
	prop_number = PanelPropRVectorDate.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(PanelPropRVectorDate.getPropTag(prop));
		switch PanelPropRVectorDate.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(pr_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(pr_3.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(pr_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	
	warning('on', [BRAPH2.STR ':PanelPropRVectorDate'])
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropRVectorDate'])
	
	% copy empty element
	pr = PanelPropRVectorDate();
	 
	pr_copy = pr.copy();
	 
	assert(pr_copy ~= pr, ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'PanelPropRVectorDate.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(pr_copy, pr), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'PanelPropRVectorDate.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		value = pr.getr(prop);
		value_copy = pr_copy.getr(prop);
		switch PanelPropRVectorDate.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					'PanelPropRVectorDate.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
							'PanelPropRVectorDate.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
							'PanelPropRVectorDate.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					pr_copy.isLocked(prop) == pr.isLocked(prop), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					'PanelPropRVectorDate.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					pr_copy.isChecked(prop) == pr.isChecked(prop), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					'PanelPropRVectorDate.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					pr_copy.getPropSeed(prop) == pr.getPropSeed(prop), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					'PanelPropRVectorDate.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	pr = PanelPropRVectorDate( ...
		PanelPropRVectorDate.ELCLASS, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.NAME, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DESCRIPTION, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.TEMPLATE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.TEMPLATE), ...
		PanelPropRVectorDate.ID, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.ID), ...
		PanelPropRVectorDate.LABEL, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.LABEL), ...
		PanelPropRVectorDate.NOTES, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.NOTES), ...
		PanelPropRVectorDate.TOSTRING, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.WAITBAR, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.WAITBAR), ...
		PanelPropRVectorDate.H_WAITBAR, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAWN, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.PARENT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.PARENT), ...
		PanelPropRVectorDate.BKGCOLOR, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.BKGCOLOR), ...
		PanelPropRVectorDate.H, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.SHOW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.HIDE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DELETE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.CLOSE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.X_DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.UPDATE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.REDRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.EL, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.EL), ...
		PanelPropRVectorDate.PROP, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.PROP), ...
		PanelPropRVectorDate.HEIGHT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.HEIGHT), ...
		PanelPropRVectorDate.TITLE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.TITLE), ...
		PanelPropRVectorDate.LABEL_TITLE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.GUI_CB, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.GUI_CB), ...
		PanelPropRVectorDate.LISTENER_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CALC, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_DEL, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_SET, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_MEMORIZED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_LOCKED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.ENABLE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.ENABLE), ...
		PanelPropRVectorDate.EDITFIELD, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.FORMAT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.FORMAT) ...
		);
	 
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		if PanelPropRVectorDate.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':PanelPropRVectorDate']);
			% pr.memorize(prop);
			% warning(warning_backup)
		elseif PanelPropRVectorDate.getPropCategory(prop) == Category.EVANESCENT && pr.getPropFormat(prop) == Format.HANDLE
			pr.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:PanelPropRVectorDate');
			delete(ancestor(pr.get(prop), 'figure'))
			warning(warning_backup)
		else
			pr.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	pr_copy = pr.copy();
	 
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		value = pr.getr(prop);
		value_copy = pr_copy.getr(prop);
		switch PanelPropRVectorDate.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					'PanelPropRVectorDate.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
							'PanelPropRVectorDate.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
							'PanelPropRVectorDate.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						pr_copy.isLocked(prop) == pr.isLocked(prop), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pr_copy.isChecked(prop) == pr.isChecked(prop), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pr_copy.getPropSeed(prop) == pr.getPropSeed(prop), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	pr_0 = PanelPropRVectorDate( ...
		PanelPropRVectorDate.ELCLASS, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.NAME, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DESCRIPTION, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.TEMPLATE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.TEMPLATE), ...
		PanelPropRVectorDate.ID, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.ID), ...
		PanelPropRVectorDate.LABEL, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.LABEL), ...
		PanelPropRVectorDate.NOTES, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.NOTES), ...
		PanelPropRVectorDate.TOSTRING, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.WAITBAR, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.WAITBAR), ...
		PanelPropRVectorDate.H_WAITBAR, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAWN, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.PARENT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.PARENT), ...
		PanelPropRVectorDate.BKGCOLOR, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.BKGCOLOR), ...
		PanelPropRVectorDate.H, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.SHOW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.HIDE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DELETE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.CLOSE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.X_DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.UPDATE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.REDRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.EL, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.EL), ...
		PanelPropRVectorDate.PROP, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.PROP), ...
		PanelPropRVectorDate.HEIGHT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.HEIGHT), ...
		PanelPropRVectorDate.TITLE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.TITLE), ...
		PanelPropRVectorDate.LABEL_TITLE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.GUI_CB, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.GUI_CB), ...
		PanelPropRVectorDate.LISTENER_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CALC, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_DEL, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_SET, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_MEMORIZED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_LOCKED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.ENABLE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.ENABLE), ...
		PanelPropRVectorDate.EDITFIELD, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.FORMAT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.FORMAT) ...
		);
	 
	pr = PanelPropRVectorDate( ...
		PanelPropRVectorDate.ELCLASS, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.NAME, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DESCRIPTION, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.TEMPLATE, pr_0.getCallback(4), ..., ...
		PanelPropRVectorDate.ID, pr_0.getCallback(5), ..., ...
		PanelPropRVectorDate.LABEL, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.LABEL), ...
		PanelPropRVectorDate.NOTES, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.NOTES), ...
		PanelPropRVectorDate.TOSTRING, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.WAITBAR, pr_0.getCallback(9), ..., ...
		PanelPropRVectorDate.H_WAITBAR, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAWN, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.PARENT, pr_0.getCallback(13), ..., ...
		PanelPropRVectorDate.BKGCOLOR, pr_0.getCallback(14), ..., ...
		PanelPropRVectorDate.H, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.SHOW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.HIDE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DELETE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.CLOSE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.X_DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.UPDATE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.REDRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.EL, pr_0.getCallback(23), ..., ...
		PanelPropRVectorDate.PROP, pr_0.getCallback(24), ..., ...
		PanelPropRVectorDate.HEIGHT, pr_0.getCallback(25), ..., ...
		PanelPropRVectorDate.TITLE, pr_0.getCallback(26), ..., ...
		PanelPropRVectorDate.LABEL_TITLE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.GUI_CB, pr_0.getCallback(29), ..., ...
		PanelPropRVectorDate.LISTENER_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CALC, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_DEL, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_SET, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_MEMORIZED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_LOCKED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.ENABLE, pr_0.getCallback(36), ..., ...
		PanelPropRVectorDate.EDITFIELD, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.FORMAT, pr_0.getCallback(38) ... ...
		);
	 
	pr_copy = pr.copy();
	pr_0_copy = pr_copy.getr('ID').get('EL');
	 
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
		value = pr.getr(prop);
		value_copy = pr_copy.getr(prop);
		switch PanelPropRVectorDate.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					'PanelPropRVectorDate.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
							'PanelPropRVectorDate.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
							'PanelPropRVectorDate.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == pr_0.getCallback(prop), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate.copy() does not work. The callback should be obtained from PanelPropRVectorDate.getCallback().' ...
						)
					assert( ...
						value_copy == pr_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate.copy() does not work. The callback should be obtained from PanelPropRVectorDate.getCallback().' ...
						)
				end
	 
					assert( ...
						pr_copy.isLocked(prop) == pr.isLocked(prop), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pr_copy.isChecked(prop) == pr.isChecked(prop), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pr_copy.getPropSeed(prop) == pr.getPropSeed(prop), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	
	warning('on', [BRAPH2.STR ':PanelPropRVectorDate'])
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropRVectorDate'])
	
	pr_template = PanelPropRVectorDate();
	pr = PanelPropRVectorDate('TEMPLATE', pr_template);
	 
	for prop = 1:1:PanelPropRVectorDate.getPropNumber()
	 
		% excluded props
		if any(prop == [PanelPropRVectorDate.PARENT PanelPropRVectorDate.H PanelPropRVectorDate.LISTENER_CB PanelPropRVectorDate.EDITFIELD])
			continue
		end
	 
		TAG = upper(PanelPropRVectorDate.getPropTag(prop));
		switch PanelPropRVectorDate.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == PanelPropRVectorDate.TEMPLATE
					assert( ...
						isa(pr.getr(prop), 'PanelPropRVectorDate'), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate TEMPLATE does not work. PanelPropRVectorDate.getr(''TEMPLATE'') should be a PanelPropRVectorDate element.' ...
						)
					assert( ...
						isa(pr_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						'PanelPropRVectorDate TEMPLATE does not work. PanelPropRVectorDate_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(pr.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						['PanelPropRVectorDate TEMPLATE does not work. PanelPropRVectorDate.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						pr.getr(prop).get('EL') == pr_template && pr.getr(prop).get('PROP') == prop && strcmp(pr.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						['PanelPropRVectorDate TEMPLATE does not work. PanelPropRVectorDate.getr(' TAG ') should be a Callback to pr_template.' TAG '.'] ...
						)
					assert( ...
						isa(pr_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
						['PanelPropRVectorDate TEMPLATE does not work. PanelPropRVectorDate_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate TEMPLATE does not work. PanelPropRVectorDate.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(pr_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
					['PanelPropRVectorDate TEMPLATE does not work. PanelPropRVectorDate_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
	
	warning('on', [BRAPH2.STR ':PanelPropRVectorDate'])
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropRVectorDate'])
	
	pr = PanelPropRVectorDate( ...
		PanelPropRVectorDate.ELCLASS, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.NAME, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DESCRIPTION, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.TEMPLATE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.TEMPLATE), ...
		PanelPropRVectorDate.ID, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.ID), ...
		PanelPropRVectorDate.LABEL, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.LABEL), ...
		PanelPropRVectorDate.NOTES, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.NOTES), ...
		PanelPropRVectorDate.TOSTRING, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.WAITBAR, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.WAITBAR), ...
		PanelPropRVectorDate.H_WAITBAR, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAWN, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.PARENT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.PARENT), ...
		PanelPropRVectorDate.BKGCOLOR, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.BKGCOLOR), ...
		PanelPropRVectorDate.H, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.SHOW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.HIDE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DELETE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.CLOSE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.X_DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.UPDATE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.REDRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.EL, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.EL), ...
		PanelPropRVectorDate.PROP, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.PROP), ...
		PanelPropRVectorDate.HEIGHT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.HEIGHT), ...
		PanelPropRVectorDate.TITLE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.TITLE), ...
		PanelPropRVectorDate.LABEL_TITLE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.GUI_CB, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.GUI_CB), ...
		PanelPropRVectorDate.LISTENER_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CALC, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_DEL, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_SET, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_MEMORIZED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_LOCKED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.ENABLE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.ENABLE), ...
		PanelPropRVectorDate.EDITFIELD, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.FORMAT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.FORMAT) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'panelproprvectordate_to_be_erased.b2'];
	 
	Element.save(pr, filename)
	 
	pr_loaded = Element.load(filename);
	 
	assert( ...
		isequal(pr.copy(), pr_loaded), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'PanelPropRVectorDate.save(pr) and/or PanelPropRVectorDate.load() do not work.' ...
		)
	 
	delete(filename)
	
	warning('on', [BRAPH2.STR ':PanelPropRVectorDate'])
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropRVectorDate'])
	
	pr = PanelPropRVectorDate( ...
		PanelPropRVectorDate.ELCLASS, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.NAME, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DESCRIPTION, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.TEMPLATE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.TEMPLATE), ...
		PanelPropRVectorDate.ID, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.ID), ...
		PanelPropRVectorDate.LABEL, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.LABEL), ...
		PanelPropRVectorDate.NOTES, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.NOTES), ...
		PanelPropRVectorDate.TOSTRING, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.WAITBAR, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.WAITBAR), ...
		PanelPropRVectorDate.H_WAITBAR, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DRAWN, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.PARENT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.PARENT), ...
		PanelPropRVectorDate.BKGCOLOR, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.BKGCOLOR), ...
		PanelPropRVectorDate.H, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.SHOW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.HIDE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.DELETE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.CLOSE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.X_DRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.UPDATE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.REDRAW, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.EL, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.EL), ...
		PanelPropRVectorDate.PROP, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.PROP), ...
		PanelPropRVectorDate.HEIGHT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.HEIGHT), ...
		PanelPropRVectorDate.TITLE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.TITLE), ...
		PanelPropRVectorDate.LABEL_TITLE, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.GUI_CB, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.GUI_CB), ...
		PanelPropRVectorDate.LISTENER_CB, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_CALC, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.BUTTON_DEL, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_SET, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_MEMORIZED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.LISTENER_LOCKED, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.ENABLE, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.ENABLE), ...
		PanelPropRVectorDate.EDITFIELD, PanelPropRVectorDate.getNoValue(), ...
		PanelPropRVectorDate.FORMAT, PanelPropRVectorDate.getPropDefault(PanelPropRVectorDate.FORMAT) ...
		);
	 
	[json, struct, el_list] = encodeJSON(pr);
	[pr_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(pr_dec ~= pr, ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		'PanelPropRVectorDate.encodeJSON() or PanelPropRVectorDate.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) PanelPropRVectorDate.getPropFormat(prop), num2cell(PanelPropRVectorDate.getProps())) == Format.HANDLE) && all(cellfun(@(prop) PanelPropRVectorDate.getPropFormat(prop), num2cell(PanelPropRVectorDate.getProps())) == Format.NET)
		assert(isequal(pr_dec, pr), ...
			[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
			'PanelPropRVectorDate.encodeJSON() or PanelPropRVectorDate.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
	
	warning('on', [BRAPH2.STR ':PanelPropRVectorDate'])
end

%% Test 12: Remove Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropRVectorDate'])
	
	warning('off', [BRAPH2.STR ':PanelPropRVectorDate'])
	assert(length(findall(0, 'type', 'figure')) == 1)
	delete(findall(0, 'type', 'figure'))
	warning('on', [BRAPH2.STR ':PanelPropRVectorDate'])
	
	warning('on', [BRAPH2.STR ':PanelPropRVectorDate'])
end

%% Test 13: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropRVectorDate'])
	
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':PanelPropRVectorDate:' BRAPH2.FAIL_TEST], ...
		[' When testing PanelPropRVectorDate no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
	
	warning('on', [BRAPH2.STR ':PanelPropRVectorDate'])
end

%% Test 14: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':PanelPropRVectorDate'])
	
	delete(findall(0, 'type', 'figure'))
	
	warning('on', [BRAPH2.STR ':PanelPropRVectorDate'])
end

