%TEST_DISTAPPP_ID

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':DistapPP_ID'])
	
	categories = num2cell(Category.getCategories());
	pr = DistapPP_ID();
	 
	% get('ELCLASS')
	if isa(DistapPP_ID, 'ConcreteElement')
		assert(strcmp(DistapPP_ID().get('ELCLASS'), 'DistapPP_ID'), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'DistapPP_ID().get(''ELCLASS'') should return ''DistapPP_ID''.')
	end
	 
	% getBuild()
	assert(DistapPP_ID.getBuild() == 1 && DistapPP_ID.getBuild() > 0, ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'DistapPP_ID.getBuild() should return the DistapPP_ID build number.')
	assert(pr.getBuild() == 1 && pr.getBuild() > 0 , ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'pr.getBuild() should return the DistapPP_ID build number.')
	assert(Element.getBuild(pr) == 1 && Element.getBuild(pr) > 0, ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(pr) should return the DistapPP_ID build number.')
	assert(Element.getBuild('DistapPP_ID') == 1 && Element.getBuild('DistapPP_ID') > 0, ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''DistapPP_ID'') should return the DistapPP_ID build number.')
	 
	% getClass()
	assert(strcmp(DistapPP_ID.getClass(), 'DistapPP_ID'), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'DistapPP_ID.getClass() should return ''DistapPP_ID''.')
	assert(strcmp(pr.getClass(), 'DistapPP_ID'), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'pr.getClass() should return ''DistapPP_ID''.')
	assert(strcmp(Element.getClass(pr), 'DistapPP_ID'), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(pr) should return ''DistapPP_ID''.')
	assert(strcmp(Element.getClass('DistapPP_ID'), 'DistapPP_ID'), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''DistapPP_ID'') should return ''DistapPP_ID''.')
	 
	% getSubclasses()
	assert(isequal(DistapPP_ID.getSubclasses(), subclasses('DistapPP_ID', [], [], true)), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'DistapPP_ID.getSubclasses() should return the same result as subclasses(''DistapPP_ID'', [], [], true).')
	assert(isequal(pr.getSubclasses(), subclasses('DistapPP_ID', [], [], true)), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''DistapPP_ID'', [], [], true).')
	assert(isequal(Element.getSubclasses(pr), subclasses('DistapPP_ID', [], [], true)), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(pr) should return the same result as subclasses(''DistapPP_ID'', [], [], true).')
	assert(isequal(Element.getSubclasses('DistapPP_ID'), subclasses('DistapPP_ID', [], [], true)), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''DistapPP_ID'') should return the same result as subclasses(''DistapPP_ID'', [], [], true).')
	 
	% getProps()
	assert(isempty(DistapPP_ID.getProps()) || isequal(DistapPP_ID.getProps(), 1:1:length(DistapPP_ID.getProps())), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'DistapPP_ID.getProps() should return a row vector [1:1:N].')
	assert(isempty(DistapPP_ID.getProps()) || isequal(pr.getProps(), 1:1:length(DistapPP_ID.getProps())), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'pr.getProps() should return a row vector [1:1:N].')
	assert(isempty(DistapPP_ID.getProps()) || isequal(Element.getProps(pr), 1:1:length(DistapPP_ID.getProps())), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(pr) should return a row vector [1:1:N].')
	assert(isempty(DistapPP_ID.getProps()) || isequal(Element.getProps('DistapPP_ID'), 1:1:length(DistapPP_ID.getProps())), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''DistapPP_ID'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) DistapPP_ID.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(DistapPP_ID.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(DistapPP_ID.getProps())), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'DistapPP_ID.getProps(category) does not work.')
	tmp = cellfun(@(category) pr.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(DistapPP_ID.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(DistapPP_ID.getProps())), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'pr.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(pr, category), categories, 'UniformOutput', false);
	assert(isempty(DistapPP_ID.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(DistapPP_ID.getProps())), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(pr, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('DistapPP_ID', category), categories, 'UniformOutput', false);
	assert(isempty(DistapPP_ID.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(DistapPP_ID.getProps())), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''DistapPP_ID'', category) does not work.')
	 
	% getPropNumber()
	assert(DistapPP_ID.getPropNumber() == length(DistapPP_ID.getProps()), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'DistapPP_ID.getPropNumber() should return the number of properties.')
	assert(pr.getPropNumber() == length(DistapPP_ID.getProps()), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'pr.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(pr) == length(DistapPP_ID.getProps()), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(pr) should return the number of properties.')
	assert(Element.getPropNumber('DistapPP_ID') == length(DistapPP_ID.getProps()), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''DistapPP_ID'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) DistapPP_ID.getPropNumber(category), categories)) == DistapPP_ID.getPropNumber(), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'DistapPP_ID.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) pr.getPropNumber(category), categories)) == DistapPP_ID.getPropNumber(), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'pr.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(pr, category), categories)) == DistapPP_ID.getPropNumber(), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(pr, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('DistapPP_ID', category), categories)) == DistapPP_ID.getPropNumber(), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''DistapPP_ID'', category) does not work.')
	 
	% existsProp(prop)
	assert(~DistapPP_ID.existsProp(NaN), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'DistapPP_ID.existsProp(prop) does not work.')
	assert(~pr.existsProp(NaN), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'pr.existsProp(prop) does not work.')
	assert(~Element.existsProp(pr, NaN), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(pr, prop) does not work.')
	assert(~Element.existsProp('DistapPP_ID', NaN), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''DistapPP_ID'', prop) does not work.')
	 
	assert_with_error('DistapPP_ID.existsProp(NaN)', [BRAPH2.STR ':DistapPP_ID:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':DistapPP_ID:' BRAPH2.WRONG_INPUT], pr)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':DistapPP_ID:' BRAPH2.WRONG_INPUT], pr)
	assert_with_error('Element.existsProp(''DistapPP_ID'', NaN)', [BRAPH2.STR ':DistapPP_ID:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:DistapPP_ID.getPropNumber()
		assert(DistapPP_ID.existsProp(prop), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'DistapPP_ID.existsProp(prop) does not work.')
		assert(pr.existsProp(prop), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'pr.existsProp(prop) does not work.')
		assert(Element.existsProp(pr, prop), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(pr, prop) does not work.')
		assert(Element.existsProp('DistapPP_ID', prop), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''DistapPP_ID'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~DistapPP_ID.existsTag(''), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'DistapPP_ID.existsTag(tag) does not work.')
	assert(~pr.existsTag(''), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'pr.existsTag(tag) does not work.')
	assert(~Element.existsTag(pr, ''), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(pr, tag) does not work.')
	assert(~Element.existsTag('DistapPP_ID', ''), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''DistapPP_ID'', tag) does not work.')
	 
	assert_with_error('DistapPP_ID.existsTag('''')', [BRAPH2.STR ':DistapPP_ID:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':DistapPP_ID:' BRAPH2.WRONG_INPUT], pr)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':DistapPP_ID:' BRAPH2.WRONG_INPUT], pr)
	assert_with_error('Element.existsTag(''DistapPP_ID'', '''')', [BRAPH2.STR ':DistapPP_ID:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:DistapPP_ID.getPropNumber()
		tag = pr.getPropTag(prop);
		assert(DistapPP_ID.existsTag(tag), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'DistapPP_ID.existsTag(tag) does not work.')
		assert(pr.existsTag(tag), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'pr.existsTag(tag) does not work.')
		assert(Element.existsTag(pr, tag), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(pr, tga) does not work.')
		assert(Element.existsTag('DistapPP_ID', tag), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''DistapPP_ID'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:DistapPP_ID.getPropNumber()
		assert(DistapPP_ID.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'DistapPP_ID.getPropProp(prop) does not work.')
		assert(pr.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'pr.getPropProp(prop) does not work.')
		assert(Element.getPropProp(pr, prop) == prop, ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(pr, prop) does not work.')
		assert(Element.getPropProp('DistapPP_ID', prop) == prop, ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''DistapPP_ID'', prop) does not work.')
	 
		tag = pr.getPropTag(prop);
		assert(DistapPP_ID.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'DistapPP_ID.getPropProp(tag) does not work.')
		assert(pr.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'pr.getPropProp(tag) does not work.')
		assert(Element.getPropProp(pr, tag) == prop, ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(pr, tag) does not work.')
		assert(Element.getPropProp('DistapPP_ID', prop) == prop, ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''DistapPP_ID'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:DistapPP_ID.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		assert(strcmp(DistapPP_ID.getPropTag(prop), tag), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'DistapPP_ID.getPropTag(prop) does not work.')
		assert(strcmp(pr.getPropTag(prop), tag), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'pr.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(pr, prop), tag), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(pr, prop) does not work.')
		assert(strcmp(Element.getPropTag('DistapPP_ID', prop), tag), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''DistapPP_ID'', prop) does not work.')
	 
		assert(strcmp(DistapPP_ID.getPropTag(tag), tag), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'DistapPP_ID.getPropTag(tag) does not work.')
		assert(strcmp(pr.getPropTag(tag), tag), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'pr.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(pr, tag), tag), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(pr, tag) does not work.')
		assert(strcmp(Element.getPropTag('DistapPP_ID', prop), tag), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''DistapPP_ID'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:DistapPP_ID.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		assert(Category.existsCategory(DistapPP_ID.getPropCategory(prop)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'DistapPP_ID.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(pr.getPropCategory(prop)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'pr.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pr, prop)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(pr, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pr, prop)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''DistapPP_ID'', prop) does not work.')
	 
		assert(Category.existsCategory(DistapPP_ID.getPropCategory(tag)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'DistapPP_ID.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(pr.getPropCategory(tag)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'pr.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pr, tag)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(pr, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(pr, tag)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''DistapPP_ID'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:DistapPP_ID.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		assert(Format.existsFormat(DistapPP_ID.getPropFormat(prop)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'DistapPP_ID.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(pr.getPropFormat(prop)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'pr.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pr, prop)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(pr, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pr, prop)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''DistapPP_ID'', prop) does not work.')
	 
		assert(Format.existsFormat(DistapPP_ID.getPropFormat(tag)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'DistapPP_ID.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(pr.getPropFormat(tag)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'pr.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pr, tag)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(pr, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(pr, tag)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''DistapPP_ID'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:DistapPP_ID.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		assert(ischar(DistapPP_ID.getPropDescription(prop)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'DistapPP_ID.getPropDescription(prop) does not work.')
		assert(ischar(pr.getPropDescription(prop)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'pr.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(pr, prop)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(pr, prop) does not work.')
		assert(ischar(Element.getPropDescription(pr, prop)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''DistapPP_ID'', prop) does not work.')
	 
		assert(ischar(DistapPP_ID.getPropDescription(tag)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'DistapPP_ID.getPropDescription(tag) does not work.')
		assert(ischar(pr.getPropDescription(tag)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'pr.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(pr, tag)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(pr, tag) does not work.')
		assert(ischar(Element.getPropDescription(pr, tag)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''DistapPP_ID'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:DistapPP_ID.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		settings = DistapPP_ID.getPropSettings(prop);
		settings = pr.getPropSettings(prop);
		settings = Element.getPropSettings(pr, prop);
		settings = Element.getPropSettings('DistapPP_ID', prop);
	 
		settings = DistapPP_ID.getPropSettings(tag);
		settings = pr.getPropSettings(tag);
		settings = Element.getPropSettings(pr, tag);
		settings = Element.getPropSettings('DistapPP_ID', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:DistapPP_ID.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		default = DistapPP_ID.getPropDefault(prop);
		default = pr.getPropDefault(prop);
		default = Element.getPropDefault(pr, prop);
		default = Element.getPropDefault('DistapPP_ID', prop);
	 
		default = DistapPP_ID.getPropDefault(tag);
		default = pr.getPropDefault(tag);
		default = Element.getPropDefault(pr, tag);
		default = Element.getPropDefault('DistapPP_ID', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:DistapPP_ID.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		conditioned_default = DistapPP_ID.getPropDefaultConditioned(prop);
		conditioned_default = pr.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(pr, prop);
		conditioned_default = Element.getPropDefaultConditioned('DistapPP_ID', prop);
	 
		conditioned_default = DistapPP_ID.getPropDefaultConditioned(tag);
		conditioned_default = pr.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(pr, tag);
		conditioned_default = Element.getPropDefaultConditioned('DistapPP_ID', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:DistapPP_ID.getPropNumber()
		tag = pr.getPropTag(prop);
	 
		assert(~DistapPP_ID.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'DistapPP_ID.checkProp(prop, value) does not work.')
		assert(~pr.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'pr.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(pr, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pr, prop, value) does not work.')
		assert(~Element.checkProp('DistapPP_ID', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''DistapPP_ID'', prop, value) does not work.')
	 
		assert_with_error('DistapPP_ID.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':DistapPP_ID:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':DistapPP_ID:' BRAPH2.WRONG_INPUT], prop, pr)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':DistapPP_ID:' BRAPH2.WRONG_INPUT], prop, pr)
		assert_with_error('Element.checkProp(''DistapPP_ID'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':DistapPP_ID:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~DistapPP_ID.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'DistapPP_ID.checkProp(tag, value) does not work.')
		assert(~pr.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'pr.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(pr, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pr, tag, value) does not work.')
		assert(~Element.checkProp('DistapPP_ID', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''DistapPP_ID'', tag, value) does not work.')
	 
		assert_with_error('DistapPP_ID.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':DistapPP_ID:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':DistapPP_ID:' BRAPH2.WRONG_INPUT], tag, pr)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':DistapPP_ID:' BRAPH2.WRONG_INPUT], tag, pr)
		assert_with_error('Element.checkProp(''DistapPP_ID'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':DistapPP_ID:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(DistapPP_ID.checkProp(prop, Element.getPropDefaultConditioned(DistapPP_ID, prop)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'DistapPP_ID.checkProp(prop, <conditioned default value>) does not work.')
		assert(pr.checkProp(prop, Element.getPropDefaultConditioned(DistapPP_ID, prop)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'pr.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(pr, prop, Element.getPropDefaultConditioned(DistapPP_ID, prop)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pr, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('DistapPP_ID', prop, Element.getPropDefaultConditioned(DistapPP_ID, prop)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''DistapPP_ID'', prop, <conditioned default value>) does not work.')
	 
		assert(DistapPP_ID.checkProp(tag, Element.getPropDefaultConditioned(DistapPP_ID, prop)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'DistapPP_ID.checkProp(tag, <conditioned default value>) does not work.')
		assert(pr.checkProp(tag, Element.getPropDefaultConditioned(DistapPP_ID, prop)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'pr.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(pr, tag, Element.getPropDefaultConditioned(DistapPP_ID, prop)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(pr, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('DistapPP_ID', tag, Element.getPropDefaultConditioned(DistapPP_ID, prop)), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''DistapPP_ID'', tag, <conditioned default value>) does not work.')
	 
	end
	 
	
	warning('on', [BRAPH2.STR ':DistapPP_ID'])
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':DistapPP_ID'])
	
	pr = DistapPP_ID( ...
		DistapPP_ID.ELCLASS, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.NAME, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DESCRIPTION, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.TEMPLATE, DistapPP_ID.getPropDefault(DistapPP_ID.TEMPLATE), ...
		DistapPP_ID.ID, DistapPP_ID.getPropDefault(DistapPP_ID.ID), ...
		DistapPP_ID.LABEL, DistapPP_ID.getPropDefault(DistapPP_ID.LABEL), ...
		DistapPP_ID.NOTES, DistapPP_ID.getPropDefault(DistapPP_ID.NOTES), ...
		DistapPP_ID.TOSTRING, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.WAITBAR, DistapPP_ID.getPropDefault(DistapPP_ID.WAITBAR), ...
		DistapPP_ID.H_WAITBAR, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAWN, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.PARENT, DistapPP_ID.getPropDefault(DistapPP_ID.PARENT), ...
		DistapPP_ID.BKGCOLOR, DistapPP_ID.getPropDefault(DistapPP_ID.BKGCOLOR), ...
		DistapPP_ID.H, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.SHOW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.HIDE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DELETE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.CLOSE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.X_DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.UPDATE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.REDRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.EL, DistapPP_ID.getPropDefault(DistapPP_ID.EL), ...
		DistapPP_ID.PROP, DistapPP_ID.getPropDefault(DistapPP_ID.PROP), ...
		DistapPP_ID.HEIGHT, DistapPP_ID.getPropDefault(DistapPP_ID.HEIGHT), ...
		DistapPP_ID.TITLE, DistapPP_ID.getPropDefault(DistapPP_ID.TITLE), ...
		DistapPP_ID.LABEL_TITLE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.GUI_CB, DistapPP_ID.getPropDefault(DistapPP_ID.GUI_CB), ...
		DistapPP_ID.LISTENER_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CALC, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_DEL, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_SET, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_MEMORIZED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_LOCKED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.ENABLE, DistapPP_ID.getPropDefault(DistapPP_ID.ENABLE), ...
		DistapPP_ID.EDITFIELD, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.AXES, DistapPP_ID.getNoValue() ...
		);
	 
	for prop = 1:1:DistapPP_ID.getPropNumber()
	 
		% excluded props
		if any(prop == [DistapPP_ID.PARENT DistapPP_ID.H DistapPP_ID.LISTENER_CB DistapPP_ID.EDITFIELD DistapPP_ID.AXES])
			continue
		end
	 
		TAG = upper(DistapPP_ID.getPropTag(prop));
		switch DistapPP_ID.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					pr.getr(prop) == DistapPP_ID.getNoValue(), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['Being a ' DistapPP_ID.getCategoryName(DistapPP_ID.getPropCategory(prop)) ', DistapPP_ID.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in DistapPP_ID.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					pr.getr(TAG) == DistapPP_ID.getNoValue(), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['Being a ' DistapPP_ID.getCategoryName(DistapPP_ID.getPropCategory(prop)) ', DistapPP_ID.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in DistapPP_ID.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(pr.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(pr.getPropSettings(prop))
					assert( ...
						pr.checkFormat(pr.getPropFormat(prop), pr.get(prop)), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						['DistapPP_ID.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						pr.checkFormat(pr.getPropFormat(prop), pr.get(prop), pr.getPropSettings(prop)), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						['DistapPP_ID.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					pr.getr(prop) == DistapPP_ID.getNoValue(), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['Being a ' DistapPP_ID.getCategoryName(DistapPP_ID.getPropCategory(prop)) ', DistapPP_ID.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in DistapPP_ID.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					pr.getr(TAG) == DistapPP_ID.getNoValue(), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['Being a ' DistapPP_ID.getCategoryName(DistapPP_ID.getPropCategory(prop)) ', DistapPP_ID.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in DistapPP_ID.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':DistapPP_ID']);
				assert( ...
					~isa(pr.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(pr.getPropSettings(prop))
					assert( ...
						pr.checkFormat(pr.getPropFormat(prop), pr.get(prop)), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						['DistapPP_ID.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						pr.checkFormat(pr.getPropFormat(prop), pr.get(prop), pr.getPropSettings(prop)), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						['DistapPP_ID.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(pr.getr(prop), DistapPP_ID.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by DistapPP_ID.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in DistapPP_ID.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(pr.getr(TAG), DistapPP_ID.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.getr(' TAG ') must be inizialized to its default value ' ...
					'given by DistapPP_ID.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in DistapPP_ID.getr(' TAG ').'] ...
					)
		end
	end
	
	warning('on', [BRAPH2.STR ':DistapPP_ID'])
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':DistapPP_ID'])
	
	pr = DistapPP_ID( ...
		DistapPP_ID.ELCLASS, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.NAME, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DESCRIPTION, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.TEMPLATE, DistapPP_ID.getPropDefault(DistapPP_ID.TEMPLATE), ...
		DistapPP_ID.ID, DistapPP_ID.getPropDefault(DistapPP_ID.ID), ...
		DistapPP_ID.LABEL, DistapPP_ID.getPropDefault(DistapPP_ID.LABEL), ...
		DistapPP_ID.NOTES, DistapPP_ID.getPropDefault(DistapPP_ID.NOTES), ...
		DistapPP_ID.TOSTRING, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.WAITBAR, DistapPP_ID.getPropDefault(DistapPP_ID.WAITBAR), ...
		DistapPP_ID.H_WAITBAR, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAWN, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.PARENT, DistapPP_ID.getPropDefault(DistapPP_ID.PARENT), ...
		DistapPP_ID.BKGCOLOR, DistapPP_ID.getPropDefault(DistapPP_ID.BKGCOLOR), ...
		DistapPP_ID.H, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.SHOW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.HIDE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DELETE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.CLOSE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.X_DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.UPDATE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.REDRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.EL, DistapPP_ID.getPropDefault(DistapPP_ID.EL), ...
		DistapPP_ID.PROP, DistapPP_ID.getPropDefault(DistapPP_ID.PROP), ...
		DistapPP_ID.HEIGHT, DistapPP_ID.getPropDefault(DistapPP_ID.HEIGHT), ...
		DistapPP_ID.TITLE, DistapPP_ID.getPropDefault(DistapPP_ID.TITLE), ...
		DistapPP_ID.LABEL_TITLE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.GUI_CB, DistapPP_ID.getPropDefault(DistapPP_ID.GUI_CB), ...
		DistapPP_ID.LISTENER_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CALC, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_DEL, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_SET, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_MEMORIZED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_LOCKED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.ENABLE, DistapPP_ID.getPropDefault(DistapPP_ID.ENABLE), ...
		DistapPP_ID.EDITFIELD, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.AXES, DistapPP_ID.getNoValue() ...
		);
	 
	for prop = 1:1:DistapPP_ID.getPropNumber()
	 
		% excluded props
		if any(prop == [DistapPP_ID.PARENT DistapPP_ID.H DistapPP_ID.LISTENER_CB DistapPP_ID.EDITFIELD DistapPP_ID.AXES])
			continue
		end
	 
		TAG = upper(DistapPP_ID.getPropTag(prop));
		switch DistapPP_ID.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(pr.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(pr.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					pr.checkFormat(pr.getPropFormat(prop), pr.getr(prop),pr.getPropSettings(prop)), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':DistapPP_ID']);
				assert( ...
					~isa(pr.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':DistapPP_ID']);
	% 			assert( ...
	% 				~isa(pr.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
	% 				['DistapPP_ID.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(pr.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
	% 				['DistapPP_ID.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				pr.checkFormat(pr.getPropFormat(prop), pr.getr(prop),pr.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
	% 				['DistapPP_ID.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':DistapPP_ID']);
				assert( ...
					~isa(pr.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(pr.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					pr.checkFormat(pr.getPropFormat(prop), pr.getr(prop),pr.getPropSettings(prop)), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if pr.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:DistapPP_ID');
					delete(ancestor(pr.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(DistapPP_ID.getProps(Category.RESULT))
		for prop = 1:1:DistapPP_ID.getPropNumber()
	 
			% excluded props
			if any(prop == [DistapPP_ID.PARENT DistapPP_ID.H DistapPP_ID.LISTENER_CB DistapPP_ID.EDITFIELD DistapPP_ID.AXES])
				continue
			end
	 
			switch DistapPP_ID.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						pr.isLocked(prop), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						['DistapPP_ID.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~pr.isLocked(prop), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						['DistapPP_ID.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
	
	warning('on', [BRAPH2.STR ':DistapPP_ID'])
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':DistapPP_ID'])
	
	pr = DistapPP_ID();
	 
	for prop = 1:1:DistapPP_ID.getPropNumber()
		TAG = upper(DistapPP_ID.getPropTag(prop));
		assert( ...
			~pr.isLocked(prop), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			['DistapPP_ID.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~pr.isLocked(TAG), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			['DistapPP_ID.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	pr.lock()
	 
	for prop = 1:1:DistapPP_ID.getPropNumber()
		switch DistapPP_ID.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					pr.isLocked(prop), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~pr.isLocked(prop), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
	
	warning('on', [BRAPH2.STR ':DistapPP_ID'])
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':DistapPP_ID'])
	
	pr = DistapPP_ID();
	 
	warning_backup = warning('off', 'BRAPH2:DistapPP_ID');
	for prop = 1:1:DistapPP_ID.getPropNumber()
		pr.lock(prop)
		switch DistapPP_ID.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					pr.isLocked(prop), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~pr.isLocked(prop), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
	
	warning('on', [BRAPH2.STR ':DistapPP_ID'])
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':DistapPP_ID'])
	
	pr = DistapPP_ID();
	 
	for prop = 1:1:DistapPP_ID.getPropNumber()
		TAG = upper(DistapPP_ID.getPropTag(prop));
		assert( ...
			pr.isChecked(prop), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			['DistapPP_ID.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			pr.isChecked(TAG), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			['DistapPP_ID.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	pr.unchecked()
	 
	for prop = 1:1:DistapPP_ID.getPropNumber()
		assert( ...
			~pr.isChecked(prop), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			['DistapPP_ID.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	pr.checked()
	 
	for prop = 1:1:DistapPP_ID.getPropNumber()
		assert( ...
			pr.isChecked(prop), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			['DistapPP_ID.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
	
	warning('on', [BRAPH2.STR ':DistapPP_ID'])
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':DistapPP_ID'])
	
	% basic DistapPP_ID
	pr_0 = DistapPP_ID( ...
		DistapPP_ID.ELCLASS, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.NAME, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DESCRIPTION, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.TEMPLATE, DistapPP_ID.getPropDefault(DistapPP_ID.TEMPLATE), ...
		DistapPP_ID.ID, DistapPP_ID.getPropDefault(DistapPP_ID.ID), ...
		DistapPP_ID.LABEL, DistapPP_ID.getPropDefault(DistapPP_ID.LABEL), ...
		DistapPP_ID.NOTES, DistapPP_ID.getPropDefault(DistapPP_ID.NOTES), ...
		DistapPP_ID.TOSTRING, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.WAITBAR, DistapPP_ID.getPropDefault(DistapPP_ID.WAITBAR), ...
		DistapPP_ID.H_WAITBAR, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAWN, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.PARENT, DistapPP_ID.getPropDefault(DistapPP_ID.PARENT), ...
		DistapPP_ID.BKGCOLOR, DistapPP_ID.getPropDefault(DistapPP_ID.BKGCOLOR), ...
		DistapPP_ID.H, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.SHOW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.HIDE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DELETE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.CLOSE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.X_DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.UPDATE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.REDRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.EL, DistapPP_ID.getPropDefault(DistapPP_ID.EL), ...
		DistapPP_ID.PROP, DistapPP_ID.getPropDefault(DistapPP_ID.PROP), ...
		DistapPP_ID.HEIGHT, DistapPP_ID.getPropDefault(DistapPP_ID.HEIGHT), ...
		DistapPP_ID.TITLE, DistapPP_ID.getPropDefault(DistapPP_ID.TITLE), ...
		DistapPP_ID.LABEL_TITLE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.GUI_CB, DistapPP_ID.getPropDefault(DistapPP_ID.GUI_CB), ...
		DistapPP_ID.LISTENER_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CALC, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_DEL, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_SET, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_MEMORIZED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_LOCKED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.ENABLE, DistapPP_ID.getPropDefault(DistapPP_ID.ENABLE), ...
		DistapPP_ID.EDITFIELD, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.AXES, DistapPP_ID.getNoValue() ...
		);
	 
	% DistapPP_ID with 1st callbacks
	pr_1 = DistapPP_ID( ...
		DistapPP_ID.ELCLASS, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.NAME, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DESCRIPTION, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.TEMPLATE, pr_0.getCallback(4), ..., ...
		DistapPP_ID.ID, pr_0.getCallback(5), ..., ...
		DistapPP_ID.LABEL, DistapPP_ID.getPropDefault(DistapPP_ID.LABEL), ...
		DistapPP_ID.NOTES, DistapPP_ID.getPropDefault(DistapPP_ID.NOTES), ...
		DistapPP_ID.TOSTRING, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.WAITBAR, pr_0.getCallback(9), ..., ...
		DistapPP_ID.H_WAITBAR, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAWN, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.PARENT, pr_0.getCallback(13), ..., ...
		DistapPP_ID.BKGCOLOR, pr_0.getCallback(14), ..., ...
		DistapPP_ID.H, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.SHOW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.HIDE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DELETE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.CLOSE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.X_DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.UPDATE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.REDRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.EL, pr_0.getCallback(23), ..., ...
		DistapPP_ID.PROP, pr_0.getCallback(24), ..., ...
		DistapPP_ID.HEIGHT, pr_0.getCallback(25), ..., ...
		DistapPP_ID.TITLE, pr_0.getCallback(26), ..., ...
		DistapPP_ID.LABEL_TITLE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.GUI_CB, pr_0.getCallback(29), ..., ...
		DistapPP_ID.LISTENER_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CALC, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_DEL, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_SET, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_MEMORIZED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_LOCKED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.ENABLE, pr_0.getCallback(36), ..., ...
		DistapPP_ID.EDITFIELD, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.AXES, DistapPP_ID.getNoValue() ...
		);
	 
	prop_number = DistapPP_ID.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(DistapPP_ID.getPropTag(prop));
		switch DistapPP_ID.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(pr_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(pr_1.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(pr_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% DistapPP_ID with 2nd callbacks
	pr_2 = DistapPP_ID( ...
		DistapPP_ID.ELCLASS, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.NAME, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DESCRIPTION, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.TEMPLATE, pr_1.getCallback(4), ..., ...
		DistapPP_ID.ID, pr_1.getCallback(5), ..., ...
		DistapPP_ID.LABEL, DistapPP_ID.getPropDefault(DistapPP_ID.LABEL), ...
		DistapPP_ID.NOTES, DistapPP_ID.getPropDefault(DistapPP_ID.NOTES), ...
		DistapPP_ID.TOSTRING, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.WAITBAR, pr_1.getCallback(9), ..., ...
		DistapPP_ID.H_WAITBAR, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAWN, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.PARENT, pr_1.getCallback(13), ..., ...
		DistapPP_ID.BKGCOLOR, pr_1.getCallback(14), ..., ...
		DistapPP_ID.H, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.SHOW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.HIDE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DELETE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.CLOSE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.X_DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.UPDATE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.REDRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.EL, pr_1.getCallback(23), ..., ...
		DistapPP_ID.PROP, pr_1.getCallback(24), ..., ...
		DistapPP_ID.HEIGHT, pr_1.getCallback(25), ..., ...
		DistapPP_ID.TITLE, pr_1.getCallback(26), ..., ...
		DistapPP_ID.LABEL_TITLE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.GUI_CB, pr_1.getCallback(29), ..., ...
		DistapPP_ID.LISTENER_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CALC, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_DEL, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_SET, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_MEMORIZED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_LOCKED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.ENABLE, pr_1.getCallback(36), ..., ...
		DistapPP_ID.EDITFIELD, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.AXES, DistapPP_ID.getNoValue() ...
		);
	 
	prop_number = DistapPP_ID.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(DistapPP_ID.getPropTag(prop));
		switch DistapPP_ID.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(pr_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(pr_2.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(pr_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% DistapPP_ID with 3rd callbacks
	pr_3 = DistapPP_ID( ...
		DistapPP_ID.ELCLASS, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.NAME, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DESCRIPTION, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.TEMPLATE, pr_2.getCallback(4), ..., ...
		DistapPP_ID.ID, pr_2.getCallback(5), ..., ...
		DistapPP_ID.LABEL, DistapPP_ID.getPropDefault(DistapPP_ID.LABEL), ...
		DistapPP_ID.NOTES, DistapPP_ID.getPropDefault(DistapPP_ID.NOTES), ...
		DistapPP_ID.TOSTRING, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.WAITBAR, pr_2.getCallback(9), ..., ...
		DistapPP_ID.H_WAITBAR, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAWN, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.PARENT, pr_2.getCallback(13), ..., ...
		DistapPP_ID.BKGCOLOR, pr_2.getCallback(14), ..., ...
		DistapPP_ID.H, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.SHOW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.HIDE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DELETE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.CLOSE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.X_DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.UPDATE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.REDRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.EL, pr_2.getCallback(23), ..., ...
		DistapPP_ID.PROP, pr_2.getCallback(24), ..., ...
		DistapPP_ID.HEIGHT, pr_2.getCallback(25), ..., ...
		DistapPP_ID.TITLE, pr_2.getCallback(26), ..., ...
		DistapPP_ID.LABEL_TITLE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.GUI_CB, pr_2.getCallback(29), ..., ...
		DistapPP_ID.LISTENER_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CALC, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_DEL, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_SET, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_MEMORIZED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_LOCKED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.ENABLE, pr_2.getCallback(36), ..., ...
		DistapPP_ID.EDITFIELD, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.AXES, DistapPP_ID.getNoValue() ...
		);
	 
	prop_number = DistapPP_ID.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(DistapPP_ID.getPropTag(prop));
		switch DistapPP_ID.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(pr_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(pr_3.get(prop), pr_0.get(prop)) && ~isa(pr_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(pr_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	
	warning('on', [BRAPH2.STR ':DistapPP_ID'])
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':DistapPP_ID'])
	
	% copy empty element
	pr = DistapPP_ID();
	 
	pr_copy = pr.copy();
	 
	assert(pr_copy ~= pr, ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'DistapPP_ID.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(pr_copy, pr), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'DistapPP_ID.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:DistapPP_ID.getPropNumber()
		value = pr.getr(prop);
		value_copy = pr_copy.getr(prop);
		switch DistapPP_ID.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					'DistapPP_ID.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
							'DistapPP_ID.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
							'DistapPP_ID.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					pr_copy.isLocked(prop) == pr.isLocked(prop), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					'DistapPP_ID.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					pr_copy.isChecked(prop) == pr.isChecked(prop), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					'DistapPP_ID.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					pr_copy.getPropSeed(prop) == pr.getPropSeed(prop), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					'DistapPP_ID.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	pr = DistapPP_ID( ...
		DistapPP_ID.ELCLASS, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.NAME, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DESCRIPTION, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.TEMPLATE, DistapPP_ID.getPropDefault(DistapPP_ID.TEMPLATE), ...
		DistapPP_ID.ID, DistapPP_ID.getPropDefault(DistapPP_ID.ID), ...
		DistapPP_ID.LABEL, DistapPP_ID.getPropDefault(DistapPP_ID.LABEL), ...
		DistapPP_ID.NOTES, DistapPP_ID.getPropDefault(DistapPP_ID.NOTES), ...
		DistapPP_ID.TOSTRING, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.WAITBAR, DistapPP_ID.getPropDefault(DistapPP_ID.WAITBAR), ...
		DistapPP_ID.H_WAITBAR, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAWN, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.PARENT, DistapPP_ID.getPropDefault(DistapPP_ID.PARENT), ...
		DistapPP_ID.BKGCOLOR, DistapPP_ID.getPropDefault(DistapPP_ID.BKGCOLOR), ...
		DistapPP_ID.H, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.SHOW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.HIDE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DELETE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.CLOSE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.X_DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.UPDATE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.REDRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.EL, DistapPP_ID.getPropDefault(DistapPP_ID.EL), ...
		DistapPP_ID.PROP, DistapPP_ID.getPropDefault(DistapPP_ID.PROP), ...
		DistapPP_ID.HEIGHT, DistapPP_ID.getPropDefault(DistapPP_ID.HEIGHT), ...
		DistapPP_ID.TITLE, DistapPP_ID.getPropDefault(DistapPP_ID.TITLE), ...
		DistapPP_ID.LABEL_TITLE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.GUI_CB, DistapPP_ID.getPropDefault(DistapPP_ID.GUI_CB), ...
		DistapPP_ID.LISTENER_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CALC, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_DEL, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_SET, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_MEMORIZED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_LOCKED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.ENABLE, DistapPP_ID.getPropDefault(DistapPP_ID.ENABLE), ...
		DistapPP_ID.EDITFIELD, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.AXES, DistapPP_ID.getNoValue() ...
		);
	 
	for prop = 1:1:DistapPP_ID.getPropNumber()
		if DistapPP_ID.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':DistapPP_ID']);
			% pr.memorize(prop);
			% warning(warning_backup)
		elseif DistapPP_ID.getPropCategory(prop) == Category.EVANESCENT && pr.getPropFormat(prop) == Format.HANDLE
			pr.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:DistapPP_ID');
			delete(ancestor(pr.get(prop), 'figure'))
			warning(warning_backup)
		else
			pr.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	pr_copy = pr.copy();
	 
	for prop = 1:1:DistapPP_ID.getPropNumber()
		value = pr.getr(prop);
		value_copy = pr_copy.getr(prop);
		switch DistapPP_ID.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					'DistapPP_ID.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
							'DistapPP_ID.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
							'DistapPP_ID.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						pr_copy.isLocked(prop) == pr.isLocked(prop), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pr_copy.isChecked(prop) == pr.isChecked(prop), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pr_copy.getPropSeed(prop) == pr.getPropSeed(prop), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	pr_0 = DistapPP_ID( ...
		DistapPP_ID.ELCLASS, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.NAME, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DESCRIPTION, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.TEMPLATE, DistapPP_ID.getPropDefault(DistapPP_ID.TEMPLATE), ...
		DistapPP_ID.ID, DistapPP_ID.getPropDefault(DistapPP_ID.ID), ...
		DistapPP_ID.LABEL, DistapPP_ID.getPropDefault(DistapPP_ID.LABEL), ...
		DistapPP_ID.NOTES, DistapPP_ID.getPropDefault(DistapPP_ID.NOTES), ...
		DistapPP_ID.TOSTRING, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.WAITBAR, DistapPP_ID.getPropDefault(DistapPP_ID.WAITBAR), ...
		DistapPP_ID.H_WAITBAR, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAWN, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.PARENT, DistapPP_ID.getPropDefault(DistapPP_ID.PARENT), ...
		DistapPP_ID.BKGCOLOR, DistapPP_ID.getPropDefault(DistapPP_ID.BKGCOLOR), ...
		DistapPP_ID.H, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.SHOW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.HIDE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DELETE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.CLOSE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.X_DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.UPDATE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.REDRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.EL, DistapPP_ID.getPropDefault(DistapPP_ID.EL), ...
		DistapPP_ID.PROP, DistapPP_ID.getPropDefault(DistapPP_ID.PROP), ...
		DistapPP_ID.HEIGHT, DistapPP_ID.getPropDefault(DistapPP_ID.HEIGHT), ...
		DistapPP_ID.TITLE, DistapPP_ID.getPropDefault(DistapPP_ID.TITLE), ...
		DistapPP_ID.LABEL_TITLE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.GUI_CB, DistapPP_ID.getPropDefault(DistapPP_ID.GUI_CB), ...
		DistapPP_ID.LISTENER_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CALC, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_DEL, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_SET, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_MEMORIZED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_LOCKED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.ENABLE, DistapPP_ID.getPropDefault(DistapPP_ID.ENABLE), ...
		DistapPP_ID.EDITFIELD, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.AXES, DistapPP_ID.getNoValue() ...
		);
	 
	pr = DistapPP_ID( ...
		DistapPP_ID.ELCLASS, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.NAME, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DESCRIPTION, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.TEMPLATE, pr_0.getCallback(4), ..., ...
		DistapPP_ID.ID, pr_0.getCallback(5), ..., ...
		DistapPP_ID.LABEL, DistapPP_ID.getPropDefault(DistapPP_ID.LABEL), ...
		DistapPP_ID.NOTES, DistapPP_ID.getPropDefault(DistapPP_ID.NOTES), ...
		DistapPP_ID.TOSTRING, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.WAITBAR, pr_0.getCallback(9), ..., ...
		DistapPP_ID.H_WAITBAR, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAWN, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.PARENT, pr_0.getCallback(13), ..., ...
		DistapPP_ID.BKGCOLOR, pr_0.getCallback(14), ..., ...
		DistapPP_ID.H, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.SHOW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.HIDE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DELETE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.CLOSE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.X_DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.UPDATE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.REDRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.EL, pr_0.getCallback(23), ..., ...
		DistapPP_ID.PROP, pr_0.getCallback(24), ..., ...
		DistapPP_ID.HEIGHT, pr_0.getCallback(25), ..., ...
		DistapPP_ID.TITLE, pr_0.getCallback(26), ..., ...
		DistapPP_ID.LABEL_TITLE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.GUI_CB, pr_0.getCallback(29), ..., ...
		DistapPP_ID.LISTENER_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CALC, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_DEL, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_SET, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_MEMORIZED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_LOCKED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.ENABLE, pr_0.getCallback(36), ..., ...
		DistapPP_ID.EDITFIELD, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.AXES, DistapPP_ID.getNoValue() ...
		);
	 
	pr_copy = pr.copy();
	pr_0_copy = pr_copy.getr('ID').get('EL');
	 
	for prop = 1:1:DistapPP_ID.getPropNumber()
		value = pr.getr(prop);
		value_copy = pr_copy.getr(prop);
		switch DistapPP_ID.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					'DistapPP_ID.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
							'DistapPP_ID.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
							'DistapPP_ID.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == pr_0.getCallback(prop), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID.copy() does not work. The callback should be obtained from DistapPP_ID.getCallback().' ...
						)
					assert( ...
						value_copy == pr_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID.copy() does not work. The callback should be obtained from DistapPP_ID.getCallback().' ...
						)
				end
	 
					assert( ...
						pr_copy.isLocked(prop) == pr.isLocked(prop), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pr_copy.isChecked(prop) == pr.isChecked(prop), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						pr_copy.getPropSeed(prop) == pr.getPropSeed(prop), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	
	warning('on', [BRAPH2.STR ':DistapPP_ID'])
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':DistapPP_ID'])
	
	pr_template = DistapPP_ID();
	pr = DistapPP_ID('TEMPLATE', pr_template);
	 
	for prop = 1:1:DistapPP_ID.getPropNumber()
	 
		% excluded props
		if any(prop == [DistapPP_ID.PARENT DistapPP_ID.H DistapPP_ID.LISTENER_CB DistapPP_ID.EDITFIELD DistapPP_ID.AXES])
			continue
		end
	 
		TAG = upper(DistapPP_ID.getPropTag(prop));
		switch DistapPP_ID.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == DistapPP_ID.TEMPLATE
					assert( ...
						isa(pr.getr(prop), 'DistapPP_ID'), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID TEMPLATE does not work. DistapPP_ID.getr(''TEMPLATE'') should be a DistapPP_ID element.' ...
						)
					assert( ...
						isa(pr_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						'DistapPP_ID TEMPLATE does not work. DistapPP_ID_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(pr.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						['DistapPP_ID TEMPLATE does not work. DistapPP_ID.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						pr.getr(prop).get('EL') == pr_template && pr.getr(prop).get('PROP') == prop && strcmp(pr.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						['DistapPP_ID TEMPLATE does not work. DistapPP_ID.getr(' TAG ') should be a Callback to pr_template.' TAG '.'] ...
						)
					assert( ...
						isa(pr_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
						['DistapPP_ID TEMPLATE does not work. DistapPP_ID_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(pr.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID TEMPLATE does not work. DistapPP_ID.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(pr_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
					['DistapPP_ID TEMPLATE does not work. DistapPP_ID_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
	
	warning('on', [BRAPH2.STR ':DistapPP_ID'])
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':DistapPP_ID'])
	
	pr = DistapPP_ID( ...
		DistapPP_ID.ELCLASS, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.NAME, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DESCRIPTION, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.TEMPLATE, DistapPP_ID.getPropDefault(DistapPP_ID.TEMPLATE), ...
		DistapPP_ID.ID, DistapPP_ID.getPropDefault(DistapPP_ID.ID), ...
		DistapPP_ID.LABEL, DistapPP_ID.getPropDefault(DistapPP_ID.LABEL), ...
		DistapPP_ID.NOTES, DistapPP_ID.getPropDefault(DistapPP_ID.NOTES), ...
		DistapPP_ID.TOSTRING, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.WAITBAR, DistapPP_ID.getPropDefault(DistapPP_ID.WAITBAR), ...
		DistapPP_ID.H_WAITBAR, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAWN, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.PARENT, DistapPP_ID.getPropDefault(DistapPP_ID.PARENT), ...
		DistapPP_ID.BKGCOLOR, DistapPP_ID.getPropDefault(DistapPP_ID.BKGCOLOR), ...
		DistapPP_ID.H, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.SHOW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.HIDE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DELETE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.CLOSE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.X_DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.UPDATE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.REDRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.EL, DistapPP_ID.getPropDefault(DistapPP_ID.EL), ...
		DistapPP_ID.PROP, DistapPP_ID.getPropDefault(DistapPP_ID.PROP), ...
		DistapPP_ID.HEIGHT, DistapPP_ID.getPropDefault(DistapPP_ID.HEIGHT), ...
		DistapPP_ID.TITLE, DistapPP_ID.getPropDefault(DistapPP_ID.TITLE), ...
		DistapPP_ID.LABEL_TITLE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.GUI_CB, DistapPP_ID.getPropDefault(DistapPP_ID.GUI_CB), ...
		DistapPP_ID.LISTENER_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CALC, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_DEL, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_SET, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_MEMORIZED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_LOCKED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.ENABLE, DistapPP_ID.getPropDefault(DistapPP_ID.ENABLE), ...
		DistapPP_ID.EDITFIELD, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.AXES, DistapPP_ID.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'distappp_id_to_be_erased.b2'];
	 
	Element.save(pr, filename)
	 
	pr_loaded = Element.load(filename);
	 
	assert( ...
		isequal(pr.copy(), pr_loaded), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'DistapPP_ID.save(pr) and/or DistapPP_ID.load() do not work.' ...
		)
	 
	delete(filename)
	
	warning('on', [BRAPH2.STR ':DistapPP_ID'])
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':DistapPP_ID'])
	
	pr = DistapPP_ID( ...
		DistapPP_ID.ELCLASS, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.NAME, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DESCRIPTION, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.TEMPLATE, DistapPP_ID.getPropDefault(DistapPP_ID.TEMPLATE), ...
		DistapPP_ID.ID, DistapPP_ID.getPropDefault(DistapPP_ID.ID), ...
		DistapPP_ID.LABEL, DistapPP_ID.getPropDefault(DistapPP_ID.LABEL), ...
		DistapPP_ID.NOTES, DistapPP_ID.getPropDefault(DistapPP_ID.NOTES), ...
		DistapPP_ID.TOSTRING, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.WAITBAR, DistapPP_ID.getPropDefault(DistapPP_ID.WAITBAR), ...
		DistapPP_ID.H_WAITBAR, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DRAWN, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.PARENT, DistapPP_ID.getPropDefault(DistapPP_ID.PARENT), ...
		DistapPP_ID.BKGCOLOR, DistapPP_ID.getPropDefault(DistapPP_ID.BKGCOLOR), ...
		DistapPP_ID.H, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.SHOW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.HIDE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.DELETE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.CLOSE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.X_DRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.UPDATE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.REDRAW, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.EL, DistapPP_ID.getPropDefault(DistapPP_ID.EL), ...
		DistapPP_ID.PROP, DistapPP_ID.getPropDefault(DistapPP_ID.PROP), ...
		DistapPP_ID.HEIGHT, DistapPP_ID.getPropDefault(DistapPP_ID.HEIGHT), ...
		DistapPP_ID.TITLE, DistapPP_ID.getPropDefault(DistapPP_ID.TITLE), ...
		DistapPP_ID.LABEL_TITLE, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.GUI_CB, DistapPP_ID.getPropDefault(DistapPP_ID.GUI_CB), ...
		DistapPP_ID.LISTENER_CB, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_CALC, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.BUTTON_DEL, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_SET, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_MEMORIZED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.LISTENER_LOCKED, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.ENABLE, DistapPP_ID.getPropDefault(DistapPP_ID.ENABLE), ...
		DistapPP_ID.EDITFIELD, DistapPP_ID.getNoValue(), ...
		DistapPP_ID.AXES, DistapPP_ID.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(pr);
	[pr_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(pr_dec ~= pr, ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		'DistapPP_ID.encodeJSON() or DistapPP_ID.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) DistapPP_ID.getPropFormat(prop), num2cell(DistapPP_ID.getProps())) == Format.HANDLE) && all(cellfun(@(prop) DistapPP_ID.getPropFormat(prop), num2cell(DistapPP_ID.getProps())) == Format.NET)
		assert(isequal(pr_dec, pr), ...
			[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
			'DistapPP_ID.encodeJSON() or DistapPP_ID.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
	
	warning('on', [BRAPH2.STR ':DistapPP_ID'])
end

%% Test 12: Remove Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':DistapPP_ID'])
	
	warning('off', [BRAPH2.STR ':DistapPP_ID'])
	assert(length(findall(0, 'type', 'figure')) == 1)
	delete(findall(0, 'type', 'figure'))
	warning('on', [BRAPH2.STR ':DistapPP_ID'])
	
	warning('on', [BRAPH2.STR ':DistapPP_ID'])
end

%% Test 13: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':DistapPP_ID'])
	
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':DistapPP_ID:' BRAPH2.FAIL_TEST], ...
		[' When testing DistapPP_ID no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
	
	warning('on', [BRAPH2.STR ':DistapPP_ID'])
end

%% Test 14: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	warning('off', [BRAPH2.STR ':DistapPP_ID'])
	
	delete(findall(0, 'type', 'figure'))
	
	warning('on', [BRAPH2.STR ':DistapPP_ID'])
end

