%TEST_IMPORTERRAMANEXPERIMENT_TXT

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	im = ImporterRamanExperiment_TXT();
	 
	% get('ELCLASS')
	if isa(ImporterRamanExperiment_TXT, 'ConcreteElement')
		assert(strcmp(ImporterRamanExperiment_TXT().get('ELCLASS'), 'ImporterRamanExperiment_TXT'), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'ImporterRamanExperiment_TXT().get(''ELCLASS'') should return ''ImporterRamanExperiment_TXT''.')
	end
	 
	% getBuild()
	assert(ImporterRamanExperiment_TXT.getBuild() == 1 && ImporterRamanExperiment_TXT.getBuild() > 0, ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'ImporterRamanExperiment_TXT.getBuild() should return the ImporterRamanExperiment_TXT build number.')
	assert(im.getBuild() == 1 && im.getBuild() > 0 , ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'im.getBuild() should return the ImporterRamanExperiment_TXT build number.')
	assert(Element.getBuild(im) == 1 && Element.getBuild(im) > 0, ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(im) should return the ImporterRamanExperiment_TXT build number.')
	assert(Element.getBuild('ImporterRamanExperiment_TXT') == 1 && Element.getBuild('ImporterRamanExperiment_TXT') > 0, ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''ImporterRamanExperiment_TXT'') should return the ImporterRamanExperiment_TXT build number.')
	 
	% getClass()
	assert(strcmp(ImporterRamanExperiment_TXT.getClass(), 'ImporterRamanExperiment_TXT'), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'ImporterRamanExperiment_TXT.getClass() should return ''ImporterRamanExperiment_TXT''.')
	assert(strcmp(im.getClass(), 'ImporterRamanExperiment_TXT'), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'im.getClass() should return ''ImporterRamanExperiment_TXT''.')
	assert(strcmp(Element.getClass(im), 'ImporterRamanExperiment_TXT'), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(im) should return ''ImporterRamanExperiment_TXT''.')
	assert(strcmp(Element.getClass('ImporterRamanExperiment_TXT'), 'ImporterRamanExperiment_TXT'), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''ImporterRamanExperiment_TXT'') should return ''ImporterRamanExperiment_TXT''.')
	 
	% getSubclasses()
	assert(isequal(ImporterRamanExperiment_TXT.getSubclasses(), subclasses('ImporterRamanExperiment_TXT', [], [], true)), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'ImporterRamanExperiment_TXT.getSubclasses() should return the same result as subclasses(''ImporterRamanExperiment_TXT'', [], [], true).')
	assert(isequal(im.getSubclasses(), subclasses('ImporterRamanExperiment_TXT', [], [], true)), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''ImporterRamanExperiment_TXT'', [], [], true).')
	assert(isequal(Element.getSubclasses(im), subclasses('ImporterRamanExperiment_TXT', [], [], true)), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(im) should return the same result as subclasses(''ImporterRamanExperiment_TXT'', [], [], true).')
	assert(isequal(Element.getSubclasses('ImporterRamanExperiment_TXT'), subclasses('ImporterRamanExperiment_TXT', [], [], true)), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''ImporterRamanExperiment_TXT'') should return the same result as subclasses(''ImporterRamanExperiment_TXT'', [], [], true).')
	 
	% getProps()
	assert(isempty(ImporterRamanExperiment_TXT.getProps()) || isequal(ImporterRamanExperiment_TXT.getProps(), 1:1:length(ImporterRamanExperiment_TXT.getProps())), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'ImporterRamanExperiment_TXT.getProps() should return a row vector [1:1:N].')
	assert(isempty(ImporterRamanExperiment_TXT.getProps()) || isequal(im.getProps(), 1:1:length(ImporterRamanExperiment_TXT.getProps())), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'im.getProps() should return a row vector [1:1:N].')
	assert(isempty(ImporterRamanExperiment_TXT.getProps()) || isequal(Element.getProps(im), 1:1:length(ImporterRamanExperiment_TXT.getProps())), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(im) should return a row vector [1:1:N].')
	assert(isempty(ImporterRamanExperiment_TXT.getProps()) || isequal(Element.getProps('ImporterRamanExperiment_TXT'), 1:1:length(ImporterRamanExperiment_TXT.getProps())), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''ImporterRamanExperiment_TXT'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) ImporterRamanExperiment_TXT.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(ImporterRamanExperiment_TXT.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ImporterRamanExperiment_TXT.getProps())), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'ImporterRamanExperiment_TXT.getProps(category) does not work.')
	tmp = cellfun(@(category) im.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(ImporterRamanExperiment_TXT.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ImporterRamanExperiment_TXT.getProps())), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'im.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(im, category), categories, 'UniformOutput', false);
	assert(isempty(ImporterRamanExperiment_TXT.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ImporterRamanExperiment_TXT.getProps())), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(im, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('ImporterRamanExperiment_TXT', category), categories, 'UniformOutput', false);
	assert(isempty(ImporterRamanExperiment_TXT.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(ImporterRamanExperiment_TXT.getProps())), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''ImporterRamanExperiment_TXT'', category) does not work.')
	 
	% getPropNumber()
	assert(ImporterRamanExperiment_TXT.getPropNumber() == length(ImporterRamanExperiment_TXT.getProps()), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'ImporterRamanExperiment_TXT.getPropNumber() should return the number of properties.')
	assert(im.getPropNumber() == length(ImporterRamanExperiment_TXT.getProps()), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'im.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(im) == length(ImporterRamanExperiment_TXT.getProps()), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(im) should return the number of properties.')
	assert(Element.getPropNumber('ImporterRamanExperiment_TXT') == length(ImporterRamanExperiment_TXT.getProps()), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''ImporterRamanExperiment_TXT'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) ImporterRamanExperiment_TXT.getPropNumber(category), categories)) == ImporterRamanExperiment_TXT.getPropNumber(), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'ImporterRamanExperiment_TXT.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) im.getPropNumber(category), categories)) == ImporterRamanExperiment_TXT.getPropNumber(), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'im.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(im, category), categories)) == ImporterRamanExperiment_TXT.getPropNumber(), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(im, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('ImporterRamanExperiment_TXT', category), categories)) == ImporterRamanExperiment_TXT.getPropNumber(), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''ImporterRamanExperiment_TXT'', category) does not work.')
	 
	% existsProp(prop)
	assert(~ImporterRamanExperiment_TXT.existsProp(NaN), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'ImporterRamanExperiment_TXT.existsProp(prop) does not work.')
	assert(~im.existsProp(NaN), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'im.existsProp(prop) does not work.')
	assert(~Element.existsProp(im, NaN), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(im, prop) does not work.')
	assert(~Element.existsProp('ImporterRamanExperiment_TXT', NaN), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''ImporterRamanExperiment_TXT'', prop) does not work.')
	 
	assert_with_error('ImporterRamanExperiment_TXT.existsProp(NaN)', [BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.WRONG_INPUT], im)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.WRONG_INPUT], im)
	assert_with_error('Element.existsProp(''ImporterRamanExperiment_TXT'', NaN)', [BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		assert(ImporterRamanExperiment_TXT.existsProp(prop), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'ImporterRamanExperiment_TXT.existsProp(prop) does not work.')
		assert(im.existsProp(prop), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'im.existsProp(prop) does not work.')
		assert(Element.existsProp(im, prop), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(im, prop) does not work.')
		assert(Element.existsProp('ImporterRamanExperiment_TXT', prop), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''ImporterRamanExperiment_TXT'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~ImporterRamanExperiment_TXT.existsTag(''), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'ImporterRamanExperiment_TXT.existsTag(tag) does not work.')
	assert(~im.existsTag(''), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'im.existsTag(tag) does not work.')
	assert(~Element.existsTag(im, ''), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(im, tag) does not work.')
	assert(~Element.existsTag('ImporterRamanExperiment_TXT', ''), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''ImporterRamanExperiment_TXT'', tag) does not work.')
	 
	assert_with_error('ImporterRamanExperiment_TXT.existsTag('''')', [BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.WRONG_INPUT], im)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.WRONG_INPUT], im)
	assert_with_error('Element.existsTag(''ImporterRamanExperiment_TXT'', '''')', [BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		tag = im.getPropTag(prop);
		assert(ImporterRamanExperiment_TXT.existsTag(tag), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'ImporterRamanExperiment_TXT.existsTag(tag) does not work.')
		assert(im.existsTag(tag), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'im.existsTag(tag) does not work.')
		assert(Element.existsTag(im, tag), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(im, tga) does not work.')
		assert(Element.existsTag('ImporterRamanExperiment_TXT', tag), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''ImporterRamanExperiment_TXT'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		assert(ImporterRamanExperiment_TXT.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'ImporterRamanExperiment_TXT.getPropProp(prop) does not work.')
		assert(im.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'im.getPropProp(prop) does not work.')
		assert(Element.getPropProp(im, prop) == prop, ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(im, prop) does not work.')
		assert(Element.getPropProp('ImporterRamanExperiment_TXT', prop) == prop, ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''ImporterRamanExperiment_TXT'', prop) does not work.')
	 
		tag = im.getPropTag(prop);
		assert(ImporterRamanExperiment_TXT.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'ImporterRamanExperiment_TXT.getPropProp(tag) does not work.')
		assert(im.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'im.getPropProp(tag) does not work.')
		assert(Element.getPropProp(im, tag) == prop, ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(im, tag) does not work.')
		assert(Element.getPropProp('ImporterRamanExperiment_TXT', prop) == prop, ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''ImporterRamanExperiment_TXT'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		tag = im.getPropTag(prop);
	 
		assert(strcmp(ImporterRamanExperiment_TXT.getPropTag(prop), tag), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'ImporterRamanExperiment_TXT.getPropTag(prop) does not work.')
		assert(strcmp(im.getPropTag(prop), tag), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'im.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(im, prop), tag), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(im, prop) does not work.')
		assert(strcmp(Element.getPropTag('ImporterRamanExperiment_TXT', prop), tag), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''ImporterRamanExperiment_TXT'', prop) does not work.')
	 
		assert(strcmp(ImporterRamanExperiment_TXT.getPropTag(tag), tag), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'ImporterRamanExperiment_TXT.getPropTag(tag) does not work.')
		assert(strcmp(im.getPropTag(tag), tag), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'im.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(im, tag), tag), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(im, tag) does not work.')
		assert(strcmp(Element.getPropTag('ImporterRamanExperiment_TXT', prop), tag), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''ImporterRamanExperiment_TXT'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		tag = im.getPropTag(prop);
	 
		assert(Category.existsCategory(ImporterRamanExperiment_TXT.getPropCategory(prop)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'ImporterRamanExperiment_TXT.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(im.getPropCategory(prop)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'im.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(im, prop)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(im, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(im, prop)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''ImporterRamanExperiment_TXT'', prop) does not work.')
	 
		assert(Category.existsCategory(ImporterRamanExperiment_TXT.getPropCategory(tag)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'ImporterRamanExperiment_TXT.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(im.getPropCategory(tag)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'im.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(im, tag)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(im, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(im, tag)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''ImporterRamanExperiment_TXT'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		tag = im.getPropTag(prop);
	 
		assert(Format.existsFormat(ImporterRamanExperiment_TXT.getPropFormat(prop)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'ImporterRamanExperiment_TXT.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(im.getPropFormat(prop)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'im.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(im, prop)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(im, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(im, prop)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''ImporterRamanExperiment_TXT'', prop) does not work.')
	 
		assert(Format.existsFormat(ImporterRamanExperiment_TXT.getPropFormat(tag)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'ImporterRamanExperiment_TXT.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(im.getPropFormat(tag)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'im.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(im, tag)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(im, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(im, tag)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''ImporterRamanExperiment_TXT'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		tag = im.getPropTag(prop);
	 
		assert(ischar(ImporterRamanExperiment_TXT.getPropDescription(prop)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'ImporterRamanExperiment_TXT.getPropDescription(prop) does not work.')
		assert(ischar(im.getPropDescription(prop)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'im.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(im, prop)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(im, prop) does not work.')
		assert(ischar(Element.getPropDescription(im, prop)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''ImporterRamanExperiment_TXT'', prop) does not work.')
	 
		assert(ischar(ImporterRamanExperiment_TXT.getPropDescription(tag)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'ImporterRamanExperiment_TXT.getPropDescription(tag) does not work.')
		assert(ischar(im.getPropDescription(tag)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'im.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(im, tag)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(im, tag) does not work.')
		assert(ischar(Element.getPropDescription(im, tag)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''ImporterRamanExperiment_TXT'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		tag = im.getPropTag(prop);
	 
		settings = ImporterRamanExperiment_TXT.getPropSettings(prop);
		settings = im.getPropSettings(prop);
		settings = Element.getPropSettings(im, prop);
		settings = Element.getPropSettings('ImporterRamanExperiment_TXT', prop);
	 
		settings = ImporterRamanExperiment_TXT.getPropSettings(tag);
		settings = im.getPropSettings(tag);
		settings = Element.getPropSettings(im, tag);
		settings = Element.getPropSettings('ImporterRamanExperiment_TXT', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		tag = im.getPropTag(prop);
	 
		default = ImporterRamanExperiment_TXT.getPropDefault(prop);
		default = im.getPropDefault(prop);
		default = Element.getPropDefault(im, prop);
		default = Element.getPropDefault('ImporterRamanExperiment_TXT', prop);
	 
		default = ImporterRamanExperiment_TXT.getPropDefault(tag);
		default = im.getPropDefault(tag);
		default = Element.getPropDefault(im, tag);
		default = Element.getPropDefault('ImporterRamanExperiment_TXT', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		tag = im.getPropTag(prop);
	 
		conditioned_default = ImporterRamanExperiment_TXT.getPropDefaultConditioned(prop);
		conditioned_default = im.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(im, prop);
		conditioned_default = Element.getPropDefaultConditioned('ImporterRamanExperiment_TXT', prop);
	 
		conditioned_default = ImporterRamanExperiment_TXT.getPropDefaultConditioned(tag);
		conditioned_default = im.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(im, tag);
		conditioned_default = Element.getPropDefaultConditioned('ImporterRamanExperiment_TXT', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		tag = im.getPropTag(prop);
	 
		assert(~ImporterRamanExperiment_TXT.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'ImporterRamanExperiment_TXT.checkProp(prop, value) does not work.')
		assert(~im.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'im.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(im, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(im, prop, value) does not work.')
		assert(~Element.checkProp('ImporterRamanExperiment_TXT', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ImporterRamanExperiment_TXT'', prop, value) does not work.')
	 
		assert_with_error('ImporterRamanExperiment_TXT.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.WRONG_INPUT], prop, im)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.WRONG_INPUT], prop, im)
		assert_with_error('Element.checkProp(''ImporterRamanExperiment_TXT'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~ImporterRamanExperiment_TXT.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'ImporterRamanExperiment_TXT.checkProp(tag, value) does not work.')
		assert(~im.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'im.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(im, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(im, tag, value) does not work.')
		assert(~Element.checkProp('ImporterRamanExperiment_TXT', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ImporterRamanExperiment_TXT'', tag, value) does not work.')
	 
		assert_with_error('ImporterRamanExperiment_TXT.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.WRONG_INPUT], tag, im)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.WRONG_INPUT], tag, im)
		assert_with_error('Element.checkProp(''ImporterRamanExperiment_TXT'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(ImporterRamanExperiment_TXT.checkProp(prop, Element.getPropDefaultConditioned(ImporterRamanExperiment_TXT, prop)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'ImporterRamanExperiment_TXT.checkProp(prop, <conditioned default value>) does not work.')
		assert(im.checkProp(prop, Element.getPropDefaultConditioned(ImporterRamanExperiment_TXT, prop)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'im.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(im, prop, Element.getPropDefaultConditioned(ImporterRamanExperiment_TXT, prop)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(im, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('ImporterRamanExperiment_TXT', prop, Element.getPropDefaultConditioned(ImporterRamanExperiment_TXT, prop)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ImporterRamanExperiment_TXT'', prop, <conditioned default value>) does not work.')
	 
		assert(ImporterRamanExperiment_TXT.checkProp(tag, Element.getPropDefaultConditioned(ImporterRamanExperiment_TXT, prop)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'ImporterRamanExperiment_TXT.checkProp(tag, <conditioned default value>) does not work.')
		assert(im.checkProp(tag, Element.getPropDefaultConditioned(ImporterRamanExperiment_TXT, prop)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'im.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(im, tag, Element.getPropDefaultConditioned(ImporterRamanExperiment_TXT, prop)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(im, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('ImporterRamanExperiment_TXT', tag, Element.getPropDefaultConditioned(ImporterRamanExperiment_TXT, prop)), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''ImporterRamanExperiment_TXT'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im = ImporterRamanExperiment_TXT( ...
		ImporterRamanExperiment_TXT.ELCLASS, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.NAME, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.DESCRIPTION, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.TEMPLATE, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.TEMPLATE), ...
		ImporterRamanExperiment_TXT.ID, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.ID), ...
		ImporterRamanExperiment_TXT.LABEL, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.LABEL), ...
		ImporterRamanExperiment_TXT.NOTES, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.NOTES), ...
		ImporterRamanExperiment_TXT.TOSTRING, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.WAITBAR, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.WAITBAR), ...
		ImporterRamanExperiment_TXT.DIRECTORY, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.DIRECTORY), ...
		ImporterRamanExperiment_TXT.GET_DIR, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.RE, ImporterRamanExperiment_TXT.getNoValue() ...
		);
	 
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
	 
		% excluded props
		if any(prop == [ImporterRamanExperiment_TXT.GET_DIR])
			continue
		end
	 
		TAG = upper(ImporterRamanExperiment_TXT.getPropTag(prop));
		switch ImporterRamanExperiment_TXT.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					im.getr(prop) == ImporterRamanExperiment_TXT.getNoValue(), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['Being a ' ImporterRamanExperiment_TXT.getCategoryName(ImporterRamanExperiment_TXT.getPropCategory(prop)) ', ImporterRamanExperiment_TXT.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ImporterRamanExperiment_TXT.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					im.getr(TAG) == ImporterRamanExperiment_TXT.getNoValue(), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['Being a ' ImporterRamanExperiment_TXT.getCategoryName(ImporterRamanExperiment_TXT.getPropCategory(prop)) ', ImporterRamanExperiment_TXT.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ImporterRamanExperiment_TXT.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(im.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(im.getPropSettings(prop))
					assert( ...
						im.checkFormat(im.getPropFormat(prop), im.get(prop)), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						['ImporterRamanExperiment_TXT.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						im.checkFormat(im.getPropFormat(prop), im.get(prop), im.getPropSettings(prop)), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						['ImporterRamanExperiment_TXT.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					im.getr(prop) == ImporterRamanExperiment_TXT.getNoValue(), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['Being a ' ImporterRamanExperiment_TXT.getCategoryName(ImporterRamanExperiment_TXT.getPropCategory(prop)) ', ImporterRamanExperiment_TXT.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ImporterRamanExperiment_TXT.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					im.getr(TAG) == ImporterRamanExperiment_TXT.getNoValue(), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['Being a ' ImporterRamanExperiment_TXT.getCategoryName(ImporterRamanExperiment_TXT.getPropCategory(prop)) ', ImporterRamanExperiment_TXT.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in ImporterRamanExperiment_TXT.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':ImporterRamanExperiment_TXT']);
				assert( ...
					~isa(im.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(im.getPropSettings(prop))
					assert( ...
						im.checkFormat(im.getPropFormat(prop), im.get(prop)), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						['ImporterRamanExperiment_TXT.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						im.checkFormat(im.getPropFormat(prop), im.get(prop), im.getPropSettings(prop)), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						['ImporterRamanExperiment_TXT.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(im.getr(prop), ImporterRamanExperiment_TXT.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by ImporterRamanExperiment_TXT.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in ImporterRamanExperiment_TXT.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(im.getr(TAG), ImporterRamanExperiment_TXT.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.getr(' TAG ') must be inizialized to its default value ' ...
					'given by ImporterRamanExperiment_TXT.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in ImporterRamanExperiment_TXT.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im = ImporterRamanExperiment_TXT( ...
		ImporterRamanExperiment_TXT.ELCLASS, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.NAME, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.DESCRIPTION, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.TEMPLATE, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.TEMPLATE), ...
		ImporterRamanExperiment_TXT.ID, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.ID), ...
		ImporterRamanExperiment_TXT.LABEL, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.LABEL), ...
		ImporterRamanExperiment_TXT.NOTES, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.NOTES), ...
		ImporterRamanExperiment_TXT.TOSTRING, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.WAITBAR, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.WAITBAR), ...
		ImporterRamanExperiment_TXT.DIRECTORY, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.DIRECTORY), ...
		ImporterRamanExperiment_TXT.GET_DIR, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.RE, ImporterRamanExperiment_TXT.getNoValue() ...
		);
	 
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
	 
		% excluded props
		if any(prop == [ImporterRamanExperiment_TXT.GET_DIR])
			continue
		end
	 
		TAG = upper(ImporterRamanExperiment_TXT.getPropTag(prop));
		switch ImporterRamanExperiment_TXT.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(im.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(im.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(im.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(im.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					im.checkFormat(im.getPropFormat(prop), im.getr(prop),im.getPropSettings(prop)), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':ImporterRamanExperiment_TXT']);
				assert( ...
					~isa(im.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(im.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':ImporterRamanExperiment_TXT']);
	% 			assert( ...
	% 				~isa(im.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
	% 				['ImporterRamanExperiment_TXT.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(im.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
	% 				['ImporterRamanExperiment_TXT.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				im.checkFormat(im.getPropFormat(prop), im.getr(prop),im.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
	% 				['ImporterRamanExperiment_TXT.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':ImporterRamanExperiment_TXT']);
				assert( ...
					~isa(im.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(im.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(im.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(im.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					im.checkFormat(im.getPropFormat(prop), im.getr(prop),im.getPropSettings(prop)), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if im.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:ImporterRamanExperiment_TXT');
					delete(ancestor(im.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(ImporterRamanExperiment_TXT.getProps(Category.RESULT))
		for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
	 
			% excluded props
			if any(prop == [ImporterRamanExperiment_TXT.GET_DIR])
				continue
			end
	 
			switch ImporterRamanExperiment_TXT.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						im.isLocked(prop), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						['ImporterRamanExperiment_TXT.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~im.isLocked(prop), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						['ImporterRamanExperiment_TXT.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im = ImporterRamanExperiment_TXT();
	 
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		TAG = upper(ImporterRamanExperiment_TXT.getPropTag(prop));
		assert( ...
			~im.isLocked(prop), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			['ImporterRamanExperiment_TXT.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~im.isLocked(TAG), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			['ImporterRamanExperiment_TXT.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	im.lock()
	 
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		switch ImporterRamanExperiment_TXT.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					im.isLocked(prop), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~im.isLocked(prop), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im = ImporterRamanExperiment_TXT();
	 
	warning_backup = warning('off', 'BRAPH2:ImporterRamanExperiment_TXT');
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		im.lock(prop)
		switch ImporterRamanExperiment_TXT.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					im.isLocked(prop), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~im.isLocked(prop), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im = ImporterRamanExperiment_TXT();
	 
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		TAG = upper(ImporterRamanExperiment_TXT.getPropTag(prop));
		assert( ...
			im.isChecked(prop), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			['ImporterRamanExperiment_TXT.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			im.isChecked(TAG), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			['ImporterRamanExperiment_TXT.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	im.unchecked()
	 
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		assert( ...
			~im.isChecked(prop), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			['ImporterRamanExperiment_TXT.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	im.checked()
	 
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		assert( ...
			im.isChecked(prop), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			['ImporterRamanExperiment_TXT.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic ImporterRamanExperiment_TXT
	im_0 = ImporterRamanExperiment_TXT( ...
		ImporterRamanExperiment_TXT.ELCLASS, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.NAME, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.DESCRIPTION, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.TEMPLATE, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.TEMPLATE), ...
		ImporterRamanExperiment_TXT.ID, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.ID), ...
		ImporterRamanExperiment_TXT.LABEL, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.LABEL), ...
		ImporterRamanExperiment_TXT.NOTES, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.NOTES), ...
		ImporterRamanExperiment_TXT.TOSTRING, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.WAITBAR, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.WAITBAR), ...
		ImporterRamanExperiment_TXT.DIRECTORY, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.DIRECTORY), ...
		ImporterRamanExperiment_TXT.GET_DIR, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.RE, ImporterRamanExperiment_TXT.getNoValue() ...
		);
	 
	% ImporterRamanExperiment_TXT with 1st callbacks
	im_1 = ImporterRamanExperiment_TXT( ...
		ImporterRamanExperiment_TXT.ELCLASS, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.NAME, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.DESCRIPTION, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.TEMPLATE, im_0.getCallback(4), ..., ...
		ImporterRamanExperiment_TXT.ID, im_0.getCallback(5), ..., ...
		ImporterRamanExperiment_TXT.LABEL, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.LABEL), ...
		ImporterRamanExperiment_TXT.NOTES, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.NOTES), ...
		ImporterRamanExperiment_TXT.TOSTRING, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.WAITBAR, im_0.getCallback(9), ..., ...
		ImporterRamanExperiment_TXT.DIRECTORY, im_0.getCallback(10), ..., ...
		ImporterRamanExperiment_TXT.GET_DIR, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.RE, ImporterRamanExperiment_TXT.getNoValue() ...
		);
	 
	prop_number = ImporterRamanExperiment_TXT.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ImporterRamanExperiment_TXT.getPropTag(prop));
		switch ImporterRamanExperiment_TXT.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(im_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(im_1.get(prop), im_0.get(prop)) && ~isa(im_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(im_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% ImporterRamanExperiment_TXT with 2nd callbacks
	im_2 = ImporterRamanExperiment_TXT( ...
		ImporterRamanExperiment_TXT.ELCLASS, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.NAME, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.DESCRIPTION, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.TEMPLATE, im_1.getCallback(4), ..., ...
		ImporterRamanExperiment_TXT.ID, im_1.getCallback(5), ..., ...
		ImporterRamanExperiment_TXT.LABEL, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.LABEL), ...
		ImporterRamanExperiment_TXT.NOTES, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.NOTES), ...
		ImporterRamanExperiment_TXT.TOSTRING, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.WAITBAR, im_1.getCallback(9), ..., ...
		ImporterRamanExperiment_TXT.DIRECTORY, im_1.getCallback(10), ..., ...
		ImporterRamanExperiment_TXT.GET_DIR, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.RE, ImporterRamanExperiment_TXT.getNoValue() ...
		);
	 
	prop_number = ImporterRamanExperiment_TXT.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ImporterRamanExperiment_TXT.getPropTag(prop));
		switch ImporterRamanExperiment_TXT.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(im_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(im_2.get(prop), im_0.get(prop)) && ~isa(im_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(im_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% ImporterRamanExperiment_TXT with 3rd callbacks
	im_3 = ImporterRamanExperiment_TXT( ...
		ImporterRamanExperiment_TXT.ELCLASS, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.NAME, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.DESCRIPTION, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.TEMPLATE, im_2.getCallback(4), ..., ...
		ImporterRamanExperiment_TXT.ID, im_2.getCallback(5), ..., ...
		ImporterRamanExperiment_TXT.LABEL, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.LABEL), ...
		ImporterRamanExperiment_TXT.NOTES, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.NOTES), ...
		ImporterRamanExperiment_TXT.TOSTRING, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.WAITBAR, im_2.getCallback(9), ..., ...
		ImporterRamanExperiment_TXT.DIRECTORY, im_2.getCallback(10), ..., ...
		ImporterRamanExperiment_TXT.GET_DIR, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.RE, ImporterRamanExperiment_TXT.getNoValue() ...
		);
	 
	prop_number = ImporterRamanExperiment_TXT.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(ImporterRamanExperiment_TXT.getPropTag(prop));
		switch ImporterRamanExperiment_TXT.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(im_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(im_3.get(prop), im_0.get(prop)) && ~isa(im_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(im_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	im = ImporterRamanExperiment_TXT();
	 
	im_copy = im.copy();
	 
	assert(im_copy ~= im, ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'ImporterRamanExperiment_TXT.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(im_copy, im), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'ImporterRamanExperiment_TXT.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		value = im.getr(prop);
		value_copy = im_copy.getr(prop);
		switch ImporterRamanExperiment_TXT.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					'ImporterRamanExperiment_TXT.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
							'ImporterRamanExperiment_TXT.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
							'ImporterRamanExperiment_TXT.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					im_copy.isLocked(prop) == im.isLocked(prop), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					'ImporterRamanExperiment_TXT.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					im_copy.isChecked(prop) == im.isChecked(prop), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					'ImporterRamanExperiment_TXT.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					im_copy.getPropSeed(prop) == im.getPropSeed(prop), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					'ImporterRamanExperiment_TXT.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	im = ImporterRamanExperiment_TXT( ...
		ImporterRamanExperiment_TXT.ELCLASS, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.NAME, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.DESCRIPTION, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.TEMPLATE, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.TEMPLATE), ...
		ImporterRamanExperiment_TXT.ID, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.ID), ...
		ImporterRamanExperiment_TXT.LABEL, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.LABEL), ...
		ImporterRamanExperiment_TXT.NOTES, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.NOTES), ...
		ImporterRamanExperiment_TXT.TOSTRING, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.WAITBAR, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.WAITBAR), ...
		ImporterRamanExperiment_TXT.DIRECTORY, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.DIRECTORY), ...
		ImporterRamanExperiment_TXT.GET_DIR, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.RE, ImporterRamanExperiment_TXT.getNoValue() ...
		);
	 
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		if ImporterRamanExperiment_TXT.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':ImporterRamanExperiment_TXT']);
			% im.memorize(prop);
			% warning(warning_backup)
		elseif ImporterRamanExperiment_TXT.getPropCategory(prop) == Category.EVANESCENT && im.getPropFormat(prop) == Format.HANDLE
			im.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:ImporterRamanExperiment_TXT');
			delete(ancestor(im.get(prop), 'figure'))
			warning(warning_backup)
		else
			im.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	im_copy = im.copy();
	 
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		value = im.getr(prop);
		value_copy = im_copy.getr(prop);
		switch ImporterRamanExperiment_TXT.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					'ImporterRamanExperiment_TXT.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
							'ImporterRamanExperiment_TXT.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
							'ImporterRamanExperiment_TXT.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						im_copy.isLocked(prop) == im.isLocked(prop), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						im_copy.isChecked(prop) == im.isChecked(prop), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						im_copy.getPropSeed(prop) == im.getPropSeed(prop), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	im_0 = ImporterRamanExperiment_TXT( ...
		ImporterRamanExperiment_TXT.ELCLASS, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.NAME, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.DESCRIPTION, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.TEMPLATE, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.TEMPLATE), ...
		ImporterRamanExperiment_TXT.ID, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.ID), ...
		ImporterRamanExperiment_TXT.LABEL, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.LABEL), ...
		ImporterRamanExperiment_TXT.NOTES, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.NOTES), ...
		ImporterRamanExperiment_TXT.TOSTRING, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.WAITBAR, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.WAITBAR), ...
		ImporterRamanExperiment_TXT.DIRECTORY, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.DIRECTORY), ...
		ImporterRamanExperiment_TXT.GET_DIR, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.RE, ImporterRamanExperiment_TXT.getNoValue() ...
		);
	 
	im = ImporterRamanExperiment_TXT( ...
		ImporterRamanExperiment_TXT.ELCLASS, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.NAME, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.DESCRIPTION, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.TEMPLATE, im_0.getCallback(4), ..., ...
		ImporterRamanExperiment_TXT.ID, im_0.getCallback(5), ..., ...
		ImporterRamanExperiment_TXT.LABEL, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.LABEL), ...
		ImporterRamanExperiment_TXT.NOTES, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.NOTES), ...
		ImporterRamanExperiment_TXT.TOSTRING, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.WAITBAR, im_0.getCallback(9), ..., ...
		ImporterRamanExperiment_TXT.DIRECTORY, im_0.getCallback(10), ..., ...
		ImporterRamanExperiment_TXT.GET_DIR, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.RE, ImporterRamanExperiment_TXT.getNoValue() ...
		);
	 
	im_copy = im.copy();
	im_0_copy = im_copy.getr('ID').get('EL');
	 
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
		value = im.getr(prop);
		value_copy = im_copy.getr(prop);
		switch ImporterRamanExperiment_TXT.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					'ImporterRamanExperiment_TXT.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
							'ImporterRamanExperiment_TXT.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
							'ImporterRamanExperiment_TXT.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == im_0.getCallback(prop), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT.copy() does not work. The callback should be obtained from ImporterRamanExperiment_TXT.getCallback().' ...
						)
					assert( ...
						value_copy == im_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT.copy() does not work. The callback should be obtained from ImporterRamanExperiment_TXT.getCallback().' ...
						)
				end
	 
					assert( ...
						im_copy.isLocked(prop) == im.isLocked(prop), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						im_copy.isChecked(prop) == im.isChecked(prop), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						im_copy.getPropSeed(prop) == im.getPropSeed(prop), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im_template = ImporterRamanExperiment_TXT();
	im = ImporterRamanExperiment_TXT('TEMPLATE', im_template);
	 
	for prop = 1:1:ImporterRamanExperiment_TXT.getPropNumber()
	 
		% excluded props
		if any(prop == [ImporterRamanExperiment_TXT.GET_DIR])
			continue
		end
	 
		TAG = upper(ImporterRamanExperiment_TXT.getPropTag(prop));
		switch ImporterRamanExperiment_TXT.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == ImporterRamanExperiment_TXT.TEMPLATE
					assert( ...
						isa(im.getr(prop), 'ImporterRamanExperiment_TXT'), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT TEMPLATE does not work. ImporterRamanExperiment_TXT.getr(''TEMPLATE'') should be a ImporterRamanExperiment_TXT element.' ...
						)
					assert( ...
						isa(im_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						'ImporterRamanExperiment_TXT TEMPLATE does not work. ImporterRamanExperiment_TXT_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(im.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						['ImporterRamanExperiment_TXT TEMPLATE does not work. ImporterRamanExperiment_TXT.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						im.getr(prop).get('EL') == im_template && im.getr(prop).get('PROP') == prop && strcmp(im.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						['ImporterRamanExperiment_TXT TEMPLATE does not work. ImporterRamanExperiment_TXT.getr(' TAG ') should be a Callback to im_template.' TAG '.'] ...
						)
					assert( ...
						isa(im_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
						['ImporterRamanExperiment_TXT TEMPLATE does not work. ImporterRamanExperiment_TXT_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(im.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT TEMPLATE does not work. ImporterRamanExperiment_TXT.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(im_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
					['ImporterRamanExperiment_TXT TEMPLATE does not work. ImporterRamanExperiment_TXT_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im = ImporterRamanExperiment_TXT( ...
		ImporterRamanExperiment_TXT.ELCLASS, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.NAME, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.DESCRIPTION, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.TEMPLATE, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.TEMPLATE), ...
		ImporterRamanExperiment_TXT.ID, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.ID), ...
		ImporterRamanExperiment_TXT.LABEL, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.LABEL), ...
		ImporterRamanExperiment_TXT.NOTES, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.NOTES), ...
		ImporterRamanExperiment_TXT.TOSTRING, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.WAITBAR, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.WAITBAR), ...
		ImporterRamanExperiment_TXT.DIRECTORY, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.DIRECTORY), ...
		ImporterRamanExperiment_TXT.GET_DIR, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.RE, ImporterRamanExperiment_TXT.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'importerramanexperiment_txt_to_be_erased.b2'];
	 
	Element.save(im, filename)
	 
	im_loaded = Element.load(filename);
	 
	assert( ...
		isequal(im.copy(), im_loaded), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'ImporterRamanExperiment_TXT.save(im) and/or ImporterRamanExperiment_TXT.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im = ImporterRamanExperiment_TXT( ...
		ImporterRamanExperiment_TXT.ELCLASS, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.NAME, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.DESCRIPTION, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.TEMPLATE, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.TEMPLATE), ...
		ImporterRamanExperiment_TXT.ID, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.ID), ...
		ImporterRamanExperiment_TXT.LABEL, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.LABEL), ...
		ImporterRamanExperiment_TXT.NOTES, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.NOTES), ...
		ImporterRamanExperiment_TXT.TOSTRING, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.WAITBAR, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.WAITBAR), ...
		ImporterRamanExperiment_TXT.DIRECTORY, ImporterRamanExperiment_TXT.getPropDefault(ImporterRamanExperiment_TXT.DIRECTORY), ...
		ImporterRamanExperiment_TXT.GET_DIR, ImporterRamanExperiment_TXT.getNoValue(), ...
		ImporterRamanExperiment_TXT.RE, ImporterRamanExperiment_TXT.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(im);
	[im_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(im_dec ~= im, ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		'ImporterRamanExperiment_TXT.encodeJSON() or ImporterRamanExperiment_TXT.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) ImporterRamanExperiment_TXT.getPropFormat(prop), num2cell(ImporterRamanExperiment_TXT.getProps())) == Format.HANDLE) && all(cellfun(@(prop) ImporterRamanExperiment_TXT.getPropFormat(prop), num2cell(ImporterRamanExperiment_TXT.getProps())) == Format.NET)
		assert(isequal(im_dec, im), ...
			[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
			'ImporterRamanExperiment_TXT.encodeJSON() or ImporterRamanExperiment_TXT.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: GUI
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	im_re = ImporterRamanExperiment_TXT( ...
	'DIRECTORY', [fileparts(which('RamanExperiment')) filesep 'TXT'], ...
	    'WAITBAR', true ...
	    );
	re = im_re.get('RE');
	
	gui = GUIElement('PE', re, 'CLOSEREQ', false);
	gui.get('DRAW')
	gui.get('SHOW')
	
	gui.get('CLOSE')
end

%% Test 13: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':ImporterRamanExperiment_TXT:' BRAPH2.FAIL_TEST], ...
		[' When testing ImporterRamanExperiment_TXT no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 14: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

