distribution_name = 'DiSTAP VAE';
distribution_moniker = 'distap_vae';
pipeline_folders = {
    'distap_vae'
    };
braph2_version = 'heads/develop';

% Add here all included and excluded folders and elements
% '-folder'                 the folder and its elements will be excluded
%
% '+folder'                 the folder is included, but not its elements
%   '+_ElementName.gen.m'   the element is included,
%                           if the folder is included
%
% '+folder*'                the folder and its elements are included
%   '-_ElementName.gen.m'   the element is excluded,
%                           if the folder and its elements are included
% (by default, the folders are included as '+folder*')
rollcall = { ...
    '+util', '+_Exporter.gen.m', '+_Importer.gen.m', ...
    '+ds*', '-ds_examples', ...
    '-atlas', ...
    '-gt',  ...
    '+cohort*', ...
    '-analysis', ...
    '+nn*', ...
    '+gui*', ...
    '-brainsurfs', ...
    '-atlases', ...
    '-graphs', ...
    '-measures', ...
    '+neuralnetworks*', ...
    '+pipelines', ...
    '+distap_vae*', ...
    '+test*', ...
    '-sandbox' ...
    };
files_to_delete = { ...
    ['neuralnetworks' filesep 'test_NNClassifierMLP.m'], ...
    ['neuralnetworks' filesep 'test_NNClassifierMLP_CrossValidation.m'], ...
    ['neuralnetworks' filesep 'test_NNClassifierMLP_CrossValidationPF_ROC.m'], ...
    ['neuralnetworks' filesep 'test_NNClassifierMLP_Evaluator.m'], ...
    ['neuralnetworks' filesep 'test_NNClassifierMLP_EvaluatorPF_ROC.m'], ...
    ['neuralnetworks' filesep 'test_NNRegressorMLP.m'], ...
    ['neuralnetworks' filesep 'test_NNRegressorMLP_CrossValidation.m'], ...
    ['neuralnetworks' filesep 'test_NNRegressorMLP_CrossValidationPF_Scatter.m'], ...
    ['neuralnetworks' filesep 'test_NNRegressorMLP_Evaluator.m'], ...
    ['neuralnetworks' filesep 'test_NNRegressorMLP_EvaluatorPF_Scatter.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportance.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportance_CV.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceAcrossMeasures.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceAcrossMeasures_CV.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBrainSurface.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBrainSurface_CV.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBrainSurfacePF.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBrainSurfacePF_BB.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBrainSurfacePF_BS.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBrainSurfacePF_BU.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBrainSurfacePF_GB.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBrainSurfacePF_GS.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBrainSurfacePF_GU.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBrainSurfacePF_NB.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBrainSurfacePF_NS.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBrainSurfacePF_NU.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBrainSurfacePP_Data.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBrainSurfacePP_Graph.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBrainSurfacePP_Measure.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBSPF_xSPP_Layer.m'], ...
    ['neuralnetworks' filesep 'test_NNxMLP_FeatureImportanceBSPF_xUPP_Layer.m'], ...
    ['neuralnetworks' filesep 'test_NNDataPoint_Graph_CLA.m'], ...
    ['neuralnetworks' filesep 'test_NNDataPoint_Graph_REG.m'], ...
    ['neuralnetworks' filesep 'test_NNDataPoint_Measure_CLA.m'], ...
    ['neuralnetworks' filesep 'test_NNDataPoint_Measure_REG.m'], ...
    ['neuralnetworks' filesep 'test_NNDataPointMLP_Shuffled.m'], ...
    };