distribution_name = 'DiSTAP';
distribution_moniker = 'distap';
pipeline_folders = {
    'RamanSpectra'
    'VariationalAutoencoders_MNIST'
    };
braph2_version = 'heads/develop';

% Add here all included and excluded folders and elements
% '-folder'                 the folder and its elements will be excluded
%
% '+folder'                 the folder is included, but not its elements
%   '+_ElementName.gen.m'   the element is included,
%                           if the folder is included
%
% '+folder*'                the folder and its elements are included
%   '-_ElementName.gen.m'   the element is excluded,
%                           if the folder and its elements are included
% (by default, the folders are included as '+folder*')
rollcall = { ...
    '+util*', ...
    '+ds*', '-ds_examples', ...
    '-atlas', ...
    '-gt',  ...
    '+cohort*', ...
    '-analysis', ...
    '+nn*', ...
    '+gui*', '-gui_examples', ...
    '-brainsurfs', ...
    '-atlases', ...
    '-graphs', ...
    '-measures', ...
    '-neuralnetworks', ...
    '+pipelines', ...
    '+RamanSpectra*', '+VariationalAutoencoders_MNIST*', ...
    '+test*', ...
    '-sandbox' ...
    };
files_to_delete = { ...
    % % % ['neuralnetworks' filesep 'test_NNClassifierMLP.m'], ...
    % % % ['neuralnetworks' filesep 'test_NNClassifierMLP_CrossValidation.m'], ...
    };