%TEST_NNVARIATIONALAUTOENCODERS

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	nnvae = NNVariationalAutoencoders();
	 
	% get('ELCLASS')
	if isa(NNVariationalAutoencoders, 'ConcreteElement')
		assert(strcmp(NNVariationalAutoencoders().get('ELCLASS'), 'NNVariationalAutoencoders'), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoders().get(''ELCLASS'') should return ''NNVariationalAutoencoders''.')
	end
	 
	% getBuild()
	assert(NNVariationalAutoencoders.getBuild() == 1 && NNVariationalAutoencoders.getBuild() > 0, ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoders.getBuild() should return the NNVariationalAutoencoders build number.')
	assert(nnvae.getBuild() == 1 && nnvae.getBuild() > 0 , ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'nnvae.getBuild() should return the NNVariationalAutoencoders build number.')
	assert(Element.getBuild(nnvae) == 1 && Element.getBuild(nnvae) > 0, ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(nnvae) should return the NNVariationalAutoencoders build number.')
	assert(Element.getBuild('NNVariationalAutoencoders') == 1 && Element.getBuild('NNVariationalAutoencoders') > 0, ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''NNVariationalAutoencoders'') should return the NNVariationalAutoencoders build number.')
	 
	% getClass()
	assert(strcmp(NNVariationalAutoencoders.getClass(), 'NNVariationalAutoencoders'), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoders.getClass() should return ''NNVariationalAutoencoders''.')
	assert(strcmp(nnvae.getClass(), 'NNVariationalAutoencoders'), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'nnvae.getClass() should return ''NNVariationalAutoencoders''.')
	assert(strcmp(Element.getClass(nnvae), 'NNVariationalAutoencoders'), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(nnvae) should return ''NNVariationalAutoencoders''.')
	assert(strcmp(Element.getClass('NNVariationalAutoencoders'), 'NNVariationalAutoencoders'), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''NNVariationalAutoencoders'') should return ''NNVariationalAutoencoders''.')
	 
	% getSubclasses()
	assert(isequal(NNVariationalAutoencoders.getSubclasses(), subclasses('NNVariationalAutoencoders', [], [], true)), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoders.getSubclasses() should return the same result as subclasses(''NNVariationalAutoencoders'', [], [], true).')
	assert(isequal(nnvae.getSubclasses(), subclasses('NNVariationalAutoencoders', [], [], true)), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''NNVariationalAutoencoders'', [], [], true).')
	assert(isequal(Element.getSubclasses(nnvae), subclasses('NNVariationalAutoencoders', [], [], true)), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(nnvae) should return the same result as subclasses(''NNVariationalAutoencoders'', [], [], true).')
	assert(isequal(Element.getSubclasses('NNVariationalAutoencoders'), subclasses('NNVariationalAutoencoders', [], [], true)), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''NNVariationalAutoencoders'') should return the same result as subclasses(''NNVariationalAutoencoders'', [], [], true).')
	 
	% getProps()
	assert(isempty(NNVariationalAutoencoders.getProps()) || isequal(NNVariationalAutoencoders.getProps(), 1:1:length(NNVariationalAutoencoders.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoders.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNVariationalAutoencoders.getProps()) || isequal(nnvae.getProps(), 1:1:length(NNVariationalAutoencoders.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'nnvae.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNVariationalAutoencoders.getProps()) || isequal(Element.getProps(nnvae), 1:1:length(NNVariationalAutoencoders.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(nnvae) should return a row vector [1:1:N].')
	assert(isempty(NNVariationalAutoencoders.getProps()) || isequal(Element.getProps('NNVariationalAutoencoders'), 1:1:length(NNVariationalAutoencoders.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNVariationalAutoencoders'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) NNVariationalAutoencoders.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNVariationalAutoencoders.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNVariationalAutoencoders.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoders.getProps(category) does not work.')
	tmp = cellfun(@(category) nnvae.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNVariationalAutoencoders.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNVariationalAutoencoders.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'nnvae.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(nnvae, category), categories, 'UniformOutput', false);
	assert(isempty(NNVariationalAutoencoders.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNVariationalAutoencoders.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(nnvae, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('NNVariationalAutoencoders', category), categories, 'UniformOutput', false);
	assert(isempty(NNVariationalAutoencoders.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNVariationalAutoencoders.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNVariationalAutoencoders'', category) does not work.')
	 
	% getPropNumber()
	assert(NNVariationalAutoencoders.getPropNumber() == length(NNVariationalAutoencoders.getProps()), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoders.getPropNumber() should return the number of properties.')
	assert(nnvae.getPropNumber() == length(NNVariationalAutoencoders.getProps()), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'nnvae.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(nnvae) == length(NNVariationalAutoencoders.getProps()), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(nnvae) should return the number of properties.')
	assert(Element.getPropNumber('NNVariationalAutoencoders') == length(NNVariationalAutoencoders.getProps()), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNVariationalAutoencoders'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) NNVariationalAutoencoders.getPropNumber(category), categories)) == NNVariationalAutoencoders.getPropNumber(), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoders.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) nnvae.getPropNumber(category), categories)) == NNVariationalAutoencoders.getPropNumber(), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'nnvae.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(nnvae, category), categories)) == NNVariationalAutoencoders.getPropNumber(), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(nnvae, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('NNVariationalAutoencoders', category), categories)) == NNVariationalAutoencoders.getPropNumber(), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNVariationalAutoencoders'', category) does not work.')
	 
	% existsProp(prop)
	assert(~NNVariationalAutoencoders.existsProp(NaN), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoders.existsProp(prop) does not work.')
	assert(~nnvae.existsProp(NaN), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'nnvae.existsProp(prop) does not work.')
	assert(~Element.existsProp(nnvae, NaN), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(nnvae, prop) does not work.')
	assert(~Element.existsProp('NNVariationalAutoencoders', NaN), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''NNVariationalAutoencoders'', prop) does not work.')
	 
	assert_with_error('NNVariationalAutoencoders.existsProp(NaN)', [BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.WRONG_INPUT], nnvae)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.WRONG_INPUT], nnvae)
	assert_with_error('Element.existsProp(''NNVariationalAutoencoders'', NaN)', [BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		assert(NNVariationalAutoencoders.existsProp(prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoders.existsProp(prop) does not work.')
		assert(nnvae.existsProp(prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'nnvae.existsProp(prop) does not work.')
		assert(Element.existsProp(nnvae, prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(nnvae, prop) does not work.')
		assert(Element.existsProp('NNVariationalAutoencoders', prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''NNVariationalAutoencoders'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~NNVariationalAutoencoders.existsTag(''), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoders.existsTag(tag) does not work.')
	assert(~nnvae.existsTag(''), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'nnvae.existsTag(tag) does not work.')
	assert(~Element.existsTag(nnvae, ''), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(nnvae, tag) does not work.')
	assert(~Element.existsTag('NNVariationalAutoencoders', ''), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''NNVariationalAutoencoders'', tag) does not work.')
	 
	assert_with_error('NNVariationalAutoencoders.existsTag('''')', [BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.WRONG_INPUT], nnvae)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.WRONG_INPUT], nnvae)
	assert_with_error('Element.existsTag(''NNVariationalAutoencoders'', '''')', [BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		tag = nnvae.getPropTag(prop);
		assert(NNVariationalAutoencoders.existsTag(tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoders.existsTag(tag) does not work.')
		assert(nnvae.existsTag(tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'nnvae.existsTag(tag) does not work.')
		assert(Element.existsTag(nnvae, tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(nnvae, tga) does not work.')
		assert(Element.existsTag('NNVariationalAutoencoders', tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''NNVariationalAutoencoders'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		assert(NNVariationalAutoencoders.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoders.getPropProp(prop) does not work.')
		assert(nnvae.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropProp(prop) does not work.')
		assert(Element.getPropProp(nnvae, prop) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(nnvae, prop) does not work.')
		assert(Element.getPropProp('NNVariationalAutoencoders', prop) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNVariationalAutoencoders'', prop) does not work.')
	 
		tag = nnvae.getPropTag(prop);
		assert(NNVariationalAutoencoders.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoders.getPropProp(tag) does not work.')
		assert(nnvae.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropProp(tag) does not work.')
		assert(Element.getPropProp(nnvae, tag) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(nnvae, tag) does not work.')
		assert(Element.getPropProp('NNVariationalAutoencoders', prop) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNVariationalAutoencoders'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		assert(strcmp(NNVariationalAutoencoders.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoders.getPropTag(prop) does not work.')
		assert(strcmp(nnvae.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(nnvae, prop), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(nnvae, prop) does not work.')
		assert(strcmp(Element.getPropTag('NNVariationalAutoencoders', prop), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNVariationalAutoencoders'', prop) does not work.')
	 
		assert(strcmp(NNVariationalAutoencoders.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoders.getPropTag(tag) does not work.')
		assert(strcmp(nnvae.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(nnvae, tag), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(nnvae, tag) does not work.')
		assert(strcmp(Element.getPropTag('NNVariationalAutoencoders', prop), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNVariationalAutoencoders'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		assert(Category.existsCategory(NNVariationalAutoencoders.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoders.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(nnvae.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nnvae, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(nnvae, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nnvae, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNVariationalAutoencoders'', prop) does not work.')
	 
		assert(Category.existsCategory(NNVariationalAutoencoders.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoders.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(nnvae.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nnvae, tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(nnvae, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nnvae, tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNVariationalAutoencoders'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		assert(Format.existsFormat(NNVariationalAutoencoders.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoders.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(nnvae.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nnvae, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(nnvae, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nnvae, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNVariationalAutoencoders'', prop) does not work.')
	 
		assert(Format.existsFormat(NNVariationalAutoencoders.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoders.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(nnvae.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nnvae, tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(nnvae, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nnvae, tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNVariationalAutoencoders'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		assert(ischar(NNVariationalAutoencoders.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoders.getPropDescription(prop) does not work.')
		assert(ischar(nnvae.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(nnvae, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(nnvae, prop) does not work.')
		assert(ischar(Element.getPropDescription(nnvae, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNVariationalAutoencoders'', prop) does not work.')
	 
		assert(ischar(NNVariationalAutoencoders.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoders.getPropDescription(tag) does not work.')
		assert(ischar(nnvae.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(nnvae, tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(nnvae, tag) does not work.')
		assert(ischar(Element.getPropDescription(nnvae, tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNVariationalAutoencoders'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		settings = NNVariationalAutoencoders.getPropSettings(prop);
		settings = nnvae.getPropSettings(prop);
		settings = Element.getPropSettings(nnvae, prop);
		settings = Element.getPropSettings('NNVariationalAutoencoders', prop);
	 
		settings = NNVariationalAutoencoders.getPropSettings(tag);
		settings = nnvae.getPropSettings(tag);
		settings = Element.getPropSettings(nnvae, tag);
		settings = Element.getPropSettings('NNVariationalAutoencoders', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		default = NNVariationalAutoencoders.getPropDefault(prop);
		default = nnvae.getPropDefault(prop);
		default = Element.getPropDefault(nnvae, prop);
		default = Element.getPropDefault('NNVariationalAutoencoders', prop);
	 
		default = NNVariationalAutoencoders.getPropDefault(tag);
		default = nnvae.getPropDefault(tag);
		default = Element.getPropDefault(nnvae, tag);
		default = Element.getPropDefault('NNVariationalAutoencoders', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		conditioned_default = NNVariationalAutoencoders.getPropDefaultConditioned(prop);
		conditioned_default = nnvae.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(nnvae, prop);
		conditioned_default = Element.getPropDefaultConditioned('NNVariationalAutoencoders', prop);
	 
		conditioned_default = NNVariationalAutoencoders.getPropDefaultConditioned(tag);
		conditioned_default = nnvae.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(nnvae, tag);
		conditioned_default = Element.getPropDefaultConditioned('NNVariationalAutoencoders', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		assert(~NNVariationalAutoencoders.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoders.checkProp(prop, value) does not work.')
		assert(~nnvae.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'nnvae.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(nnvae, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nnvae, prop, value) does not work.')
		assert(~Element.checkProp('NNVariationalAutoencoders', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNVariationalAutoencoders'', prop, value) does not work.')
	 
		assert_with_error('NNVariationalAutoencoders.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.WRONG_INPUT], prop, nnvae)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.WRONG_INPUT], prop, nnvae)
		assert_with_error('Element.checkProp(''NNVariationalAutoencoders'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~NNVariationalAutoencoders.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoders.checkProp(tag, value) does not work.')
		assert(~nnvae.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'nnvae.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(nnvae, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nnvae, tag, value) does not work.')
		assert(~Element.checkProp('NNVariationalAutoencoders', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNVariationalAutoencoders'', tag, value) does not work.')
	 
		assert_with_error('NNVariationalAutoencoders.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.WRONG_INPUT], tag, nnvae)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.WRONG_INPUT], tag, nnvae)
		assert_with_error('Element.checkProp(''NNVariationalAutoencoders'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(NNVariationalAutoencoders.checkProp(prop, Element.getPropDefaultConditioned(NNVariationalAutoencoders, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoders.checkProp(prop, <conditioned default value>) does not work.')
		assert(nnvae.checkProp(prop, Element.getPropDefaultConditioned(NNVariationalAutoencoders, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'nnvae.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(nnvae, prop, Element.getPropDefaultConditioned(NNVariationalAutoencoders, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nnvae, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNVariationalAutoencoders', prop, Element.getPropDefaultConditioned(NNVariationalAutoencoders, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNVariationalAutoencoders'', prop, <conditioned default value>) does not work.')
	 
		assert(NNVariationalAutoencoders.checkProp(tag, Element.getPropDefaultConditioned(NNVariationalAutoencoders, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoders.checkProp(tag, <conditioned default value>) does not work.')
		assert(nnvae.checkProp(tag, Element.getPropDefaultConditioned(NNVariationalAutoencoders, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'nnvae.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(nnvae, tag, Element.getPropDefaultConditioned(NNVariationalAutoencoders, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nnvae, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNVariationalAutoencoders', tag, Element.getPropDefaultConditioned(NNVariationalAutoencoders, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNVariationalAutoencoders'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNVariationalAutoencoders( ...
		NNVariationalAutoencoders.ELCLASS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.NAME, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.DESCRIPTION, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TEMPLATE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.TEMPLATE), ...
		NNVariationalAutoencoders.ID, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.ID), ...
		NNVariationalAutoencoders.LABEL, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.LABEL), ...
		NNVariationalAutoencoders.NOTES, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.NOTES), ...
		NNVariationalAutoencoders.TOSTRING, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.D, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.D), ...
		NNVariationalAutoencoders.DP_CLASSES, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.DP_CLASSES), ...
		NNVariationalAutoencoders.EPOCHS, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.EPOCHS), ...
		NNVariationalAutoencoders.BATCH, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.BATCH), ...
		NNVariationalAutoencoders.SHUFFLE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SHUFFLE), ...
		NNVariationalAutoencoders.SOLVER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SOLVER), ...
		NNVariationalAutoencoders.MODEL, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.INPUTS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TARGETS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TRAIN, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.VERBOSE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.VERBOSE), ...
		NNVariationalAutoencoders.PLOT_TRAINING, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.PLOT_TRAINING), ...
		NNVariationalAutoencoders.PREDICT, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.LEARN_RATE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.LEARN_RATE), ...
		NNVariationalAutoencoders.NUM_LATENT_REP, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.NUM_LATENT_REP), ...
		NNVariationalAutoencoders.SIZE_IMG, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SIZE_IMG), ...
		NNVariationalAutoencoders.ENCODER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.ENCODER), ...
		NNVariationalAutoencoders.DECODER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.DECODER), ...
		NNVariationalAutoencoders.ELBO_LOSS, NNVariationalAutoencoders.getNoValue() ...
		);
	 
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNVariationalAutoencoders.getPropTag(prop));
		switch NNVariationalAutoencoders.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					nnvae.getr(prop) == NNVariationalAutoencoders.getNoValue(), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNVariationalAutoencoders.getCategoryName(NNVariationalAutoencoders.getPropCategory(prop)) ', NNVariationalAutoencoders.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNVariationalAutoencoders.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					nnvae.getr(TAG) == NNVariationalAutoencoders.getNoValue(), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNVariationalAutoencoders.getCategoryName(NNVariationalAutoencoders.getPropCategory(prop)) ', NNVariationalAutoencoders.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNVariationalAutoencoders.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(nnvae.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(nnvae.getPropSettings(prop))
					assert( ...
						nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.get(prop)), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoders.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.get(prop), nnvae.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoders.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					nnvae.getr(prop) == NNVariationalAutoencoders.getNoValue(), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNVariationalAutoencoders.getCategoryName(NNVariationalAutoencoders.getPropCategory(prop)) ', NNVariationalAutoencoders.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNVariationalAutoencoders.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					nnvae.getr(TAG) == NNVariationalAutoencoders.getNoValue(), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNVariationalAutoencoders.getCategoryName(NNVariationalAutoencoders.getPropCategory(prop)) ', NNVariationalAutoencoders.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNVariationalAutoencoders.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':NNVariationalAutoencoders']);
				assert( ...
					~isa(nnvae.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(nnvae.getPropSettings(prop))
					assert( ...
						nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.get(prop)), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoders.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.get(prop), nnvae.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoders.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(nnvae.getr(prop), NNVariationalAutoencoders.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by NNVariationalAutoencoders.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNVariationalAutoencoders.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(nnvae.getr(TAG), NNVariationalAutoencoders.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.getr(' TAG ') must be inizialized to its default value ' ...
					'given by NNVariationalAutoencoders.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNVariationalAutoencoders.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNVariationalAutoencoders( ...
		NNVariationalAutoencoders.ELCLASS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.NAME, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.DESCRIPTION, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TEMPLATE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.TEMPLATE), ...
		NNVariationalAutoencoders.ID, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.ID), ...
		NNVariationalAutoencoders.LABEL, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.LABEL), ...
		NNVariationalAutoencoders.NOTES, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.NOTES), ...
		NNVariationalAutoencoders.TOSTRING, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.D, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.D), ...
		NNVariationalAutoencoders.DP_CLASSES, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.DP_CLASSES), ...
		NNVariationalAutoencoders.EPOCHS, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.EPOCHS), ...
		NNVariationalAutoencoders.BATCH, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.BATCH), ...
		NNVariationalAutoencoders.SHUFFLE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SHUFFLE), ...
		NNVariationalAutoencoders.SOLVER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SOLVER), ...
		NNVariationalAutoencoders.MODEL, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.INPUTS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TARGETS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TRAIN, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.VERBOSE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.VERBOSE), ...
		NNVariationalAutoencoders.PLOT_TRAINING, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.PLOT_TRAINING), ...
		NNVariationalAutoencoders.PREDICT, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.LEARN_RATE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.LEARN_RATE), ...
		NNVariationalAutoencoders.NUM_LATENT_REP, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.NUM_LATENT_REP), ...
		NNVariationalAutoencoders.SIZE_IMG, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SIZE_IMG), ...
		NNVariationalAutoencoders.ENCODER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.ENCODER), ...
		NNVariationalAutoencoders.DECODER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.DECODER), ...
		NNVariationalAutoencoders.ELBO_LOSS, NNVariationalAutoencoders.getNoValue() ...
		);
	 
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNVariationalAutoencoders.getPropTag(prop));
		switch NNVariationalAutoencoders.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(nnvae.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(nnvae.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(nnvae.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(nnvae.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.getr(prop),nnvae.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNVariationalAutoencoders']);
				assert( ...
					~isa(nnvae.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(nnvae.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNVariationalAutoencoders']);
	% 			assert( ...
	% 				~isa(nnvae.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
	% 				['NNVariationalAutoencoders.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(nnvae.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
	% 				['NNVariationalAutoencoders.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.getr(prop),nnvae.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
	% 				['NNVariationalAutoencoders.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':NNVariationalAutoencoders']);
				assert( ...
					~isa(nnvae.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(nnvae.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(nnvae.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(nnvae.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.getr(prop),nnvae.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if nnvae.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:NNVariationalAutoencoders');
					delete(ancestor(nnvae.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(NNVariationalAutoencoders.getProps(Category.RESULT))
		for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
	 
			% excluded props
			if any(prop == [])
				continue
			end
	 
			switch NNVariationalAutoencoders.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						nnvae.isLocked(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoders.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~nnvae.isLocked(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoders.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNVariationalAutoencoders();
	 
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		TAG = upper(NNVariationalAutoencoders.getPropTag(prop));
		assert( ...
			~nnvae.isLocked(prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			['NNVariationalAutoencoders.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~nnvae.isLocked(TAG), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			['NNVariationalAutoencoders.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	nnvae.lock()
	 
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		switch NNVariationalAutoencoders.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					nnvae.isLocked(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~nnvae.isLocked(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNVariationalAutoencoders();
	 
	warning_backup = warning('off', 'BRAPH2:NNVariationalAutoencoders');
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		nnvae.lock(prop)
		switch NNVariationalAutoencoders.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					nnvae.isLocked(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~nnvae.isLocked(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNVariationalAutoencoders();
	 
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		TAG = upper(NNVariationalAutoencoders.getPropTag(prop));
		assert( ...
			nnvae.isChecked(prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			['NNVariationalAutoencoders.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			nnvae.isChecked(TAG), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			['NNVariationalAutoencoders.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	nnvae.unchecked()
	 
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		assert( ...
			~nnvae.isChecked(prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			['NNVariationalAutoencoders.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	nnvae.checked()
	 
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		assert( ...
			nnvae.isChecked(prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			['NNVariationalAutoencoders.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic NNVariationalAutoencoders
	nnvae_0 = NNVariationalAutoencoders( ...
		NNVariationalAutoencoders.ELCLASS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.NAME, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.DESCRIPTION, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TEMPLATE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.TEMPLATE), ...
		NNVariationalAutoencoders.ID, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.ID), ...
		NNVariationalAutoencoders.LABEL, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.LABEL), ...
		NNVariationalAutoencoders.NOTES, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.NOTES), ...
		NNVariationalAutoencoders.TOSTRING, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.D, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.D), ...
		NNVariationalAutoencoders.DP_CLASSES, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.DP_CLASSES), ...
		NNVariationalAutoencoders.EPOCHS, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.EPOCHS), ...
		NNVariationalAutoencoders.BATCH, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.BATCH), ...
		NNVariationalAutoencoders.SHUFFLE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SHUFFLE), ...
		NNVariationalAutoencoders.SOLVER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SOLVER), ...
		NNVariationalAutoencoders.MODEL, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.INPUTS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TARGETS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TRAIN, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.VERBOSE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.VERBOSE), ...
		NNVariationalAutoencoders.PLOT_TRAINING, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.PLOT_TRAINING), ...
		NNVariationalAutoencoders.PREDICT, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.LEARN_RATE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.LEARN_RATE), ...
		NNVariationalAutoencoders.NUM_LATENT_REP, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.NUM_LATENT_REP), ...
		NNVariationalAutoencoders.SIZE_IMG, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SIZE_IMG), ...
		NNVariationalAutoencoders.ENCODER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.ENCODER), ...
		NNVariationalAutoencoders.DECODER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.DECODER), ...
		NNVariationalAutoencoders.ELBO_LOSS, NNVariationalAutoencoders.getNoValue() ...
		);
	 
	% NNVariationalAutoencoders with 1st callbacks
	nnvae_1 = NNVariationalAutoencoders( ...
		NNVariationalAutoencoders.ELCLASS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.NAME, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.DESCRIPTION, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TEMPLATE, nnvae_0.getCallback(4), ..., ...
		NNVariationalAutoencoders.ID, nnvae_0.getCallback(5), ..., ...
		NNVariationalAutoencoders.LABEL, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.LABEL), ...
		NNVariationalAutoencoders.NOTES, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.NOTES), ...
		NNVariationalAutoencoders.TOSTRING, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.D, nnvae_0.getCallback(9), ..., ...
		NNVariationalAutoencoders.DP_CLASSES, nnvae_0.getCallback(10), ..., ...
		NNVariationalAutoencoders.EPOCHS, nnvae_0.getCallback(11), ..., ...
		NNVariationalAutoencoders.BATCH, nnvae_0.getCallback(12), ..., ...
		NNVariationalAutoencoders.SHUFFLE, nnvae_0.getCallback(13), ..., ...
		NNVariationalAutoencoders.SOLVER, nnvae_0.getCallback(14), ..., ...
		NNVariationalAutoencoders.MODEL, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.INPUTS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TARGETS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TRAIN, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.VERBOSE, nnvae_0.getCallback(19), ..., ...
		NNVariationalAutoencoders.PLOT_TRAINING, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.PLOT_TRAINING), ...
		NNVariationalAutoencoders.PREDICT, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.LEARN_RATE, nnvae_0.getCallback(22), ..., ...
		NNVariationalAutoencoders.NUM_LATENT_REP, nnvae_0.getCallback(23), ..., ...
		NNVariationalAutoencoders.SIZE_IMG, nnvae_0.getCallback(24), ..., ...
		NNVariationalAutoencoders.ENCODER, nnvae_0.getCallback(25), ..., ...
		NNVariationalAutoencoders.DECODER, nnvae_0.getCallback(26), ..., ...
		NNVariationalAutoencoders.ELBO_LOSS, NNVariationalAutoencoders.getNoValue() ...
		);
	 
	prop_number = NNVariationalAutoencoders.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNVariationalAutoencoders.getPropTag(prop));
		switch NNVariationalAutoencoders.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(nnvae_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(nnvae_1.get(prop), nnvae_0.get(prop)) && ~isa(nnvae_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(nnvae_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNVariationalAutoencoders with 2nd callbacks
	nnvae_2 = NNVariationalAutoencoders( ...
		NNVariationalAutoencoders.ELCLASS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.NAME, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.DESCRIPTION, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TEMPLATE, nnvae_1.getCallback(4), ..., ...
		NNVariationalAutoencoders.ID, nnvae_1.getCallback(5), ..., ...
		NNVariationalAutoencoders.LABEL, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.LABEL), ...
		NNVariationalAutoencoders.NOTES, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.NOTES), ...
		NNVariationalAutoencoders.TOSTRING, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.D, nnvae_1.getCallback(9), ..., ...
		NNVariationalAutoencoders.DP_CLASSES, nnvae_1.getCallback(10), ..., ...
		NNVariationalAutoencoders.EPOCHS, nnvae_1.getCallback(11), ..., ...
		NNVariationalAutoencoders.BATCH, nnvae_1.getCallback(12), ..., ...
		NNVariationalAutoencoders.SHUFFLE, nnvae_1.getCallback(13), ..., ...
		NNVariationalAutoencoders.SOLVER, nnvae_1.getCallback(14), ..., ...
		NNVariationalAutoencoders.MODEL, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.INPUTS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TARGETS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TRAIN, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.VERBOSE, nnvae_1.getCallback(19), ..., ...
		NNVariationalAutoencoders.PLOT_TRAINING, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.PLOT_TRAINING), ...
		NNVariationalAutoencoders.PREDICT, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.LEARN_RATE, nnvae_1.getCallback(22), ..., ...
		NNVariationalAutoencoders.NUM_LATENT_REP, nnvae_1.getCallback(23), ..., ...
		NNVariationalAutoencoders.SIZE_IMG, nnvae_1.getCallback(24), ..., ...
		NNVariationalAutoencoders.ENCODER, nnvae_1.getCallback(25), ..., ...
		NNVariationalAutoencoders.DECODER, nnvae_1.getCallback(26), ..., ...
		NNVariationalAutoencoders.ELBO_LOSS, NNVariationalAutoencoders.getNoValue() ...
		);
	 
	prop_number = NNVariationalAutoencoders.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNVariationalAutoencoders.getPropTag(prop));
		switch NNVariationalAutoencoders.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(nnvae_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(nnvae_2.get(prop), nnvae_0.get(prop)) && ~isa(nnvae_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(nnvae_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNVariationalAutoencoders with 3rd callbacks
	nnvae_3 = NNVariationalAutoencoders( ...
		NNVariationalAutoencoders.ELCLASS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.NAME, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.DESCRIPTION, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TEMPLATE, nnvae_2.getCallback(4), ..., ...
		NNVariationalAutoencoders.ID, nnvae_2.getCallback(5), ..., ...
		NNVariationalAutoencoders.LABEL, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.LABEL), ...
		NNVariationalAutoencoders.NOTES, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.NOTES), ...
		NNVariationalAutoencoders.TOSTRING, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.D, nnvae_2.getCallback(9), ..., ...
		NNVariationalAutoencoders.DP_CLASSES, nnvae_2.getCallback(10), ..., ...
		NNVariationalAutoencoders.EPOCHS, nnvae_2.getCallback(11), ..., ...
		NNVariationalAutoencoders.BATCH, nnvae_2.getCallback(12), ..., ...
		NNVariationalAutoencoders.SHUFFLE, nnvae_2.getCallback(13), ..., ...
		NNVariationalAutoencoders.SOLVER, nnvae_2.getCallback(14), ..., ...
		NNVariationalAutoencoders.MODEL, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.INPUTS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TARGETS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TRAIN, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.VERBOSE, nnvae_2.getCallback(19), ..., ...
		NNVariationalAutoencoders.PLOT_TRAINING, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.PLOT_TRAINING), ...
		NNVariationalAutoencoders.PREDICT, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.LEARN_RATE, nnvae_2.getCallback(22), ..., ...
		NNVariationalAutoencoders.NUM_LATENT_REP, nnvae_2.getCallback(23), ..., ...
		NNVariationalAutoencoders.SIZE_IMG, nnvae_2.getCallback(24), ..., ...
		NNVariationalAutoencoders.ENCODER, nnvae_2.getCallback(25), ..., ...
		NNVariationalAutoencoders.DECODER, nnvae_2.getCallback(26), ..., ...
		NNVariationalAutoencoders.ELBO_LOSS, NNVariationalAutoencoders.getNoValue() ...
		);
	 
	prop_number = NNVariationalAutoencoders.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNVariationalAutoencoders.getPropTag(prop));
		switch NNVariationalAutoencoders.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(nnvae_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(nnvae_3.get(prop), nnvae_0.get(prop)) && ~isa(nnvae_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(nnvae_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	nnvae = NNVariationalAutoencoders();
	 
	nnvae_copy = nnvae.copy();
	 
	assert(nnvae_copy ~= nnvae, ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoders.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(nnvae_copy, nnvae), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoders.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		value = nnvae.getr(prop);
		value_copy = nnvae_copy.getr(prop);
		switch NNVariationalAutoencoders.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					'NNVariationalAutoencoders.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
							'NNVariationalAutoencoders.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
							'NNVariationalAutoencoders.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					nnvae_copy.isLocked(prop) == nnvae.isLocked(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					'NNVariationalAutoencoders.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					nnvae_copy.isChecked(prop) == nnvae.isChecked(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					'NNVariationalAutoencoders.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					nnvae_copy.getPropSeed(prop) == nnvae.getPropSeed(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					'NNVariationalAutoencoders.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	nnvae = NNVariationalAutoencoders( ...
		NNVariationalAutoencoders.ELCLASS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.NAME, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.DESCRIPTION, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TEMPLATE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.TEMPLATE), ...
		NNVariationalAutoencoders.ID, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.ID), ...
		NNVariationalAutoencoders.LABEL, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.LABEL), ...
		NNVariationalAutoencoders.NOTES, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.NOTES), ...
		NNVariationalAutoencoders.TOSTRING, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.D, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.D), ...
		NNVariationalAutoencoders.DP_CLASSES, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.DP_CLASSES), ...
		NNVariationalAutoencoders.EPOCHS, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.EPOCHS), ...
		NNVariationalAutoencoders.BATCH, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.BATCH), ...
		NNVariationalAutoencoders.SHUFFLE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SHUFFLE), ...
		NNVariationalAutoencoders.SOLVER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SOLVER), ...
		NNVariationalAutoencoders.MODEL, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.INPUTS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TARGETS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TRAIN, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.VERBOSE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.VERBOSE), ...
		NNVariationalAutoencoders.PLOT_TRAINING, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.PLOT_TRAINING), ...
		NNVariationalAutoencoders.PREDICT, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.LEARN_RATE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.LEARN_RATE), ...
		NNVariationalAutoencoders.NUM_LATENT_REP, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.NUM_LATENT_REP), ...
		NNVariationalAutoencoders.SIZE_IMG, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SIZE_IMG), ...
		NNVariationalAutoencoders.ENCODER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.ENCODER), ...
		NNVariationalAutoencoders.DECODER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.DECODER), ...
		NNVariationalAutoencoders.ELBO_LOSS, NNVariationalAutoencoders.getNoValue() ...
		);
	 
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		if NNVariationalAutoencoders.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':NNVariationalAutoencoders']);
			% nnvae.memorize(prop);
			% warning(warning_backup)
		elseif NNVariationalAutoencoders.getPropCategory(prop) == Category.EVANESCENT && nnvae.getPropFormat(prop) == Format.HANDLE
			nnvae.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:NNVariationalAutoencoders');
			delete(ancestor(nnvae.get(prop), 'figure'))
			warning(warning_backup)
		else
			nnvae.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	nnvae_copy = nnvae.copy();
	 
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		value = nnvae.getr(prop);
		value_copy = nnvae_copy.getr(prop);
		switch NNVariationalAutoencoders.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					'NNVariationalAutoencoders.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
							'NNVariationalAutoencoders.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
							'NNVariationalAutoencoders.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						nnvae_copy.isLocked(prop) == nnvae.isLocked(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nnvae_copy.isChecked(prop) == nnvae.isChecked(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nnvae_copy.getPropSeed(prop) == nnvae.getPropSeed(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	nnvae_0 = NNVariationalAutoencoders( ...
		NNVariationalAutoencoders.ELCLASS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.NAME, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.DESCRIPTION, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TEMPLATE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.TEMPLATE), ...
		NNVariationalAutoencoders.ID, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.ID), ...
		NNVariationalAutoencoders.LABEL, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.LABEL), ...
		NNVariationalAutoencoders.NOTES, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.NOTES), ...
		NNVariationalAutoencoders.TOSTRING, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.D, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.D), ...
		NNVariationalAutoencoders.DP_CLASSES, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.DP_CLASSES), ...
		NNVariationalAutoencoders.EPOCHS, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.EPOCHS), ...
		NNVariationalAutoencoders.BATCH, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.BATCH), ...
		NNVariationalAutoencoders.SHUFFLE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SHUFFLE), ...
		NNVariationalAutoencoders.SOLVER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SOLVER), ...
		NNVariationalAutoencoders.MODEL, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.INPUTS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TARGETS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TRAIN, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.VERBOSE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.VERBOSE), ...
		NNVariationalAutoencoders.PLOT_TRAINING, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.PLOT_TRAINING), ...
		NNVariationalAutoencoders.PREDICT, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.LEARN_RATE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.LEARN_RATE), ...
		NNVariationalAutoencoders.NUM_LATENT_REP, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.NUM_LATENT_REP), ...
		NNVariationalAutoencoders.SIZE_IMG, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SIZE_IMG), ...
		NNVariationalAutoencoders.ENCODER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.ENCODER), ...
		NNVariationalAutoencoders.DECODER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.DECODER), ...
		NNVariationalAutoencoders.ELBO_LOSS, NNVariationalAutoencoders.getNoValue() ...
		);
	 
	nnvae = NNVariationalAutoencoders( ...
		NNVariationalAutoencoders.ELCLASS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.NAME, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.DESCRIPTION, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TEMPLATE, nnvae_0.getCallback(4), ..., ...
		NNVariationalAutoencoders.ID, nnvae_0.getCallback(5), ..., ...
		NNVariationalAutoencoders.LABEL, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.LABEL), ...
		NNVariationalAutoencoders.NOTES, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.NOTES), ...
		NNVariationalAutoencoders.TOSTRING, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.D, nnvae_0.getCallback(9), ..., ...
		NNVariationalAutoencoders.DP_CLASSES, nnvae_0.getCallback(10), ..., ...
		NNVariationalAutoencoders.EPOCHS, nnvae_0.getCallback(11), ..., ...
		NNVariationalAutoencoders.BATCH, nnvae_0.getCallback(12), ..., ...
		NNVariationalAutoencoders.SHUFFLE, nnvae_0.getCallback(13), ..., ...
		NNVariationalAutoencoders.SOLVER, nnvae_0.getCallback(14), ..., ...
		NNVariationalAutoencoders.MODEL, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.INPUTS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TARGETS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TRAIN, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.VERBOSE, nnvae_0.getCallback(19), ..., ...
		NNVariationalAutoencoders.PLOT_TRAINING, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.PLOT_TRAINING), ...
		NNVariationalAutoencoders.PREDICT, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.LEARN_RATE, nnvae_0.getCallback(22), ..., ...
		NNVariationalAutoencoders.NUM_LATENT_REP, nnvae_0.getCallback(23), ..., ...
		NNVariationalAutoencoders.SIZE_IMG, nnvae_0.getCallback(24), ..., ...
		NNVariationalAutoencoders.ENCODER, nnvae_0.getCallback(25), ..., ...
		NNVariationalAutoencoders.DECODER, nnvae_0.getCallback(26), ..., ...
		NNVariationalAutoencoders.ELBO_LOSS, NNVariationalAutoencoders.getNoValue() ...
		);
	 
	nnvae_copy = nnvae.copy();
	nnvae_0_copy = nnvae_copy.getr('ID').get('EL');
	 
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
		value = nnvae.getr(prop);
		value_copy = nnvae_copy.getr(prop);
		switch NNVariationalAutoencoders.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					'NNVariationalAutoencoders.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
							'NNVariationalAutoencoders.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
							'NNVariationalAutoencoders.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == nnvae_0.getCallback(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders.copy() does not work. The callback should be obtained from NNVariationalAutoencoders.getCallback().' ...
						)
					assert( ...
						value_copy == nnvae_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders.copy() does not work. The callback should be obtained from NNVariationalAutoencoders.getCallback().' ...
						)
				end
	 
					assert( ...
						nnvae_copy.isLocked(prop) == nnvae.isLocked(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nnvae_copy.isChecked(prop) == nnvae.isChecked(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nnvae_copy.getPropSeed(prop) == nnvae.getPropSeed(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae_template = NNVariationalAutoencoders();
	nnvae = NNVariationalAutoencoders('TEMPLATE', nnvae_template);
	 
	for prop = 1:1:NNVariationalAutoencoders.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNVariationalAutoencoders.getPropTag(prop));
		switch NNVariationalAutoencoders.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == NNVariationalAutoencoders.TEMPLATE
					assert( ...
						isa(nnvae.getr(prop), 'NNVariationalAutoencoders'), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders TEMPLATE does not work. NNVariationalAutoencoders.getr(''TEMPLATE'') should be a NNVariationalAutoencoders element.' ...
						)
					assert( ...
						isa(nnvae_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoders TEMPLATE does not work. NNVariationalAutoencoders_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(nnvae.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoders TEMPLATE does not work. NNVariationalAutoencoders.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						nnvae.getr(prop).get('EL') == nnvae_template && nnvae.getr(prop).get('PROP') == prop && strcmp(nnvae.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoders TEMPLATE does not work. NNVariationalAutoencoders.getr(' TAG ') should be a Callback to nnvae_template.' TAG '.'] ...
						)
					assert( ...
						isa(nnvae_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoders TEMPLATE does not work. NNVariationalAutoencoders_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(nnvae.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders TEMPLATE does not work. NNVariationalAutoencoders.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(nnvae_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoders TEMPLATE does not work. NNVariationalAutoencoders_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNVariationalAutoencoders( ...
		NNVariationalAutoencoders.ELCLASS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.NAME, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.DESCRIPTION, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TEMPLATE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.TEMPLATE), ...
		NNVariationalAutoencoders.ID, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.ID), ...
		NNVariationalAutoencoders.LABEL, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.LABEL), ...
		NNVariationalAutoencoders.NOTES, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.NOTES), ...
		NNVariationalAutoencoders.TOSTRING, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.D, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.D), ...
		NNVariationalAutoencoders.DP_CLASSES, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.DP_CLASSES), ...
		NNVariationalAutoencoders.EPOCHS, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.EPOCHS), ...
		NNVariationalAutoencoders.BATCH, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.BATCH), ...
		NNVariationalAutoencoders.SHUFFLE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SHUFFLE), ...
		NNVariationalAutoencoders.SOLVER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SOLVER), ...
		NNVariationalAutoencoders.MODEL, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.INPUTS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TARGETS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TRAIN, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.VERBOSE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.VERBOSE), ...
		NNVariationalAutoencoders.PLOT_TRAINING, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.PLOT_TRAINING), ...
		NNVariationalAutoencoders.PREDICT, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.LEARN_RATE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.LEARN_RATE), ...
		NNVariationalAutoencoders.NUM_LATENT_REP, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.NUM_LATENT_REP), ...
		NNVariationalAutoencoders.SIZE_IMG, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SIZE_IMG), ...
		NNVariationalAutoencoders.ENCODER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.ENCODER), ...
		NNVariationalAutoencoders.DECODER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.DECODER), ...
		NNVariationalAutoencoders.ELBO_LOSS, NNVariationalAutoencoders.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'nnvariationalautoencoders_to_be_erased.b2'];
	 
	Element.save(nnvae, filename)
	 
	nnvae_loaded = Element.load(filename);
	 
	assert( ...
		isequal(nnvae.copy(), nnvae_loaded), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoders.save(nnvae) and/or NNVariationalAutoencoders.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNVariationalAutoencoders( ...
		NNVariationalAutoencoders.ELCLASS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.NAME, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.DESCRIPTION, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TEMPLATE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.TEMPLATE), ...
		NNVariationalAutoencoders.ID, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.ID), ...
		NNVariationalAutoencoders.LABEL, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.LABEL), ...
		NNVariationalAutoencoders.NOTES, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.NOTES), ...
		NNVariationalAutoencoders.TOSTRING, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.D, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.D), ...
		NNVariationalAutoencoders.DP_CLASSES, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.DP_CLASSES), ...
		NNVariationalAutoencoders.EPOCHS, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.EPOCHS), ...
		NNVariationalAutoencoders.BATCH, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.BATCH), ...
		NNVariationalAutoencoders.SHUFFLE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SHUFFLE), ...
		NNVariationalAutoencoders.SOLVER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SOLVER), ...
		NNVariationalAutoencoders.MODEL, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.INPUTS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TARGETS, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.TRAIN, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.VERBOSE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.VERBOSE), ...
		NNVariationalAutoencoders.PLOT_TRAINING, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.PLOT_TRAINING), ...
		NNVariationalAutoencoders.PREDICT, NNVariationalAutoencoders.getNoValue(), ...
		NNVariationalAutoencoders.LEARN_RATE, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.LEARN_RATE), ...
		NNVariationalAutoencoders.NUM_LATENT_REP, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.NUM_LATENT_REP), ...
		NNVariationalAutoencoders.SIZE_IMG, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.SIZE_IMG), ...
		NNVariationalAutoencoders.ENCODER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.ENCODER), ...
		NNVariationalAutoencoders.DECODER, NNVariationalAutoencoders.getPropDefault(NNVariationalAutoencoders.DECODER), ...
		NNVariationalAutoencoders.ELBO_LOSS, NNVariationalAutoencoders.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(nnvae);
	[nnvae_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(nnvae_dec ~= nnvae, ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoders.encodeJSON() or NNVariationalAutoencoders.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) NNVariationalAutoencoders.getPropFormat(prop), num2cell(NNVariationalAutoencoders.getProps())) == Format.HANDLE) && all(cellfun(@(prop) NNVariationalAutoencoders.getPropFormat(prop), num2cell(NNVariationalAutoencoders.getProps())) == Format.NET)
		assert(isequal(nnvae_dec, nnvae), ...
			[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoders.encodeJSON() or NNVariationalAutoencoders.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':NNVariationalAutoencoders:' BRAPH2.FAIL_TEST], ...
		[' When testing NNVariationalAutoencoders no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 13: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

