%TEST_NNDATASETTRANSFORM

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	dtran = NNDatasetTransform();
	 
	% get('ELCLASS')
	if isa(NNDatasetTransform, 'ConcreteElement')
		assert(strcmp(NNDatasetTransform().get('ELCLASS'), 'NNDatasetTransform'), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'NNDatasetTransform().get(''ELCLASS'') should return ''NNDatasetTransform''.')
	end
	 
	% getBuild()
	assert(NNDatasetTransform.getBuild() == 1 && NNDatasetTransform.getBuild() > 0, ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'NNDatasetTransform.getBuild() should return the NNDatasetTransform build number.')
	assert(dtran.getBuild() == 1 && dtran.getBuild() > 0 , ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'dtran.getBuild() should return the NNDatasetTransform build number.')
	assert(Element.getBuild(dtran) == 1 && Element.getBuild(dtran) > 0, ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(dtran) should return the NNDatasetTransform build number.')
	assert(Element.getBuild('NNDatasetTransform') == 1 && Element.getBuild('NNDatasetTransform') > 0, ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''NNDatasetTransform'') should return the NNDatasetTransform build number.')
	 
	% getClass()
	assert(strcmp(NNDatasetTransform.getClass(), 'NNDatasetTransform'), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'NNDatasetTransform.getClass() should return ''NNDatasetTransform''.')
	assert(strcmp(dtran.getClass(), 'NNDatasetTransform'), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'dtran.getClass() should return ''NNDatasetTransform''.')
	assert(strcmp(Element.getClass(dtran), 'NNDatasetTransform'), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(dtran) should return ''NNDatasetTransform''.')
	assert(strcmp(Element.getClass('NNDatasetTransform'), 'NNDatasetTransform'), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''NNDatasetTransform'') should return ''NNDatasetTransform''.')
	 
	% getSubclasses()
	assert(isequal(NNDatasetTransform.getSubclasses(), subclasses('NNDatasetTransform', [], [], true)), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'NNDatasetTransform.getSubclasses() should return the same result as subclasses(''NNDatasetTransform'', [], [], true).')
	assert(isequal(dtran.getSubclasses(), subclasses('NNDatasetTransform', [], [], true)), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''NNDatasetTransform'', [], [], true).')
	assert(isequal(Element.getSubclasses(dtran), subclasses('NNDatasetTransform', [], [], true)), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(dtran) should return the same result as subclasses(''NNDatasetTransform'', [], [], true).')
	assert(isequal(Element.getSubclasses('NNDatasetTransform'), subclasses('NNDatasetTransform', [], [], true)), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''NNDatasetTransform'') should return the same result as subclasses(''NNDatasetTransform'', [], [], true).')
	 
	% getProps()
	assert(isempty(NNDatasetTransform.getProps()) || isequal(NNDatasetTransform.getProps(), 1:1:length(NNDatasetTransform.getProps())), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'NNDatasetTransform.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNDatasetTransform.getProps()) || isequal(dtran.getProps(), 1:1:length(NNDatasetTransform.getProps())), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'dtran.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNDatasetTransform.getProps()) || isequal(Element.getProps(dtran), 1:1:length(NNDatasetTransform.getProps())), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(dtran) should return a row vector [1:1:N].')
	assert(isempty(NNDatasetTransform.getProps()) || isequal(Element.getProps('NNDatasetTransform'), 1:1:length(NNDatasetTransform.getProps())), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNDatasetTransform'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) NNDatasetTransform.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNDatasetTransform.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDatasetTransform.getProps())), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'NNDatasetTransform.getProps(category) does not work.')
	tmp = cellfun(@(category) dtran.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNDatasetTransform.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDatasetTransform.getProps())), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'dtran.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(dtran, category), categories, 'UniformOutput', false);
	assert(isempty(NNDatasetTransform.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDatasetTransform.getProps())), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(dtran, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('NNDatasetTransform', category), categories, 'UniformOutput', false);
	assert(isempty(NNDatasetTransform.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDatasetTransform.getProps())), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNDatasetTransform'', category) does not work.')
	 
	% getPropNumber()
	assert(NNDatasetTransform.getPropNumber() == length(NNDatasetTransform.getProps()), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'NNDatasetTransform.getPropNumber() should return the number of properties.')
	assert(dtran.getPropNumber() == length(NNDatasetTransform.getProps()), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'dtran.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(dtran) == length(NNDatasetTransform.getProps()), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(dtran) should return the number of properties.')
	assert(Element.getPropNumber('NNDatasetTransform') == length(NNDatasetTransform.getProps()), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNDatasetTransform'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) NNDatasetTransform.getPropNumber(category), categories)) == NNDatasetTransform.getPropNumber(), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'NNDatasetTransform.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) dtran.getPropNumber(category), categories)) == NNDatasetTransform.getPropNumber(), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'dtran.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(dtran, category), categories)) == NNDatasetTransform.getPropNumber(), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(dtran, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('NNDatasetTransform', category), categories)) == NNDatasetTransform.getPropNumber(), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNDatasetTransform'', category) does not work.')
	 
	% existsProp(prop)
	assert(~NNDatasetTransform.existsProp(NaN), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'NNDatasetTransform.existsProp(prop) does not work.')
	assert(~dtran.existsProp(NaN), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'dtran.existsProp(prop) does not work.')
	assert(~Element.existsProp(dtran, NaN), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(dtran, prop) does not work.')
	assert(~Element.existsProp('NNDatasetTransform', NaN), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''NNDatasetTransform'', prop) does not work.')
	 
	assert_with_error('NNDatasetTransform.existsProp(NaN)', [BRAPH2.STR ':NNDatasetTransform:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':NNDatasetTransform:' BRAPH2.WRONG_INPUT], dtran)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':NNDatasetTransform:' BRAPH2.WRONG_INPUT], dtran)
	assert_with_error('Element.existsProp(''NNDatasetTransform'', NaN)', [BRAPH2.STR ':NNDatasetTransform:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		assert(NNDatasetTransform.existsProp(prop), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'NNDatasetTransform.existsProp(prop) does not work.')
		assert(dtran.existsProp(prop), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'dtran.existsProp(prop) does not work.')
		assert(Element.existsProp(dtran, prop), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(dtran, prop) does not work.')
		assert(Element.existsProp('NNDatasetTransform', prop), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''NNDatasetTransform'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~NNDatasetTransform.existsTag(''), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'NNDatasetTransform.existsTag(tag) does not work.')
	assert(~dtran.existsTag(''), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'dtran.existsTag(tag) does not work.')
	assert(~Element.existsTag(dtran, ''), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(dtran, tag) does not work.')
	assert(~Element.existsTag('NNDatasetTransform', ''), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''NNDatasetTransform'', tag) does not work.')
	 
	assert_with_error('NNDatasetTransform.existsTag('''')', [BRAPH2.STR ':NNDatasetTransform:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':NNDatasetTransform:' BRAPH2.WRONG_INPUT], dtran)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':NNDatasetTransform:' BRAPH2.WRONG_INPUT], dtran)
	assert_with_error('Element.existsTag(''NNDatasetTransform'', '''')', [BRAPH2.STR ':NNDatasetTransform:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		tag = dtran.getPropTag(prop);
		assert(NNDatasetTransform.existsTag(tag), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'NNDatasetTransform.existsTag(tag) does not work.')
		assert(dtran.existsTag(tag), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'dtran.existsTag(tag) does not work.')
		assert(Element.existsTag(dtran, tag), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(dtran, tga) does not work.')
		assert(Element.existsTag('NNDatasetTransform', tag), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''NNDatasetTransform'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		assert(NNDatasetTransform.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'NNDatasetTransform.getPropProp(prop) does not work.')
		assert(dtran.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'dtran.getPropProp(prop) does not work.')
		assert(Element.getPropProp(dtran, prop) == prop, ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(dtran, prop) does not work.')
		assert(Element.getPropProp('NNDatasetTransform', prop) == prop, ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNDatasetTransform'', prop) does not work.')
	 
		tag = dtran.getPropTag(prop);
		assert(NNDatasetTransform.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'NNDatasetTransform.getPropProp(tag) does not work.')
		assert(dtran.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'dtran.getPropProp(tag) does not work.')
		assert(Element.getPropProp(dtran, tag) == prop, ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(dtran, tag) does not work.')
		assert(Element.getPropProp('NNDatasetTransform', prop) == prop, ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNDatasetTransform'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		tag = dtran.getPropTag(prop);
	 
		assert(strcmp(NNDatasetTransform.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'NNDatasetTransform.getPropTag(prop) does not work.')
		assert(strcmp(dtran.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'dtran.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(dtran, prop), tag), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(dtran, prop) does not work.')
		assert(strcmp(Element.getPropTag('NNDatasetTransform', prop), tag), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNDatasetTransform'', prop) does not work.')
	 
		assert(strcmp(NNDatasetTransform.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'NNDatasetTransform.getPropTag(tag) does not work.')
		assert(strcmp(dtran.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'dtran.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(dtran, tag), tag), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(dtran, tag) does not work.')
		assert(strcmp(Element.getPropTag('NNDatasetTransform', prop), tag), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNDatasetTransform'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		tag = dtran.getPropTag(prop);
	 
		assert(Category.existsCategory(NNDatasetTransform.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'NNDatasetTransform.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(dtran.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'dtran.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dtran, prop)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(dtran, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dtran, prop)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNDatasetTransform'', prop) does not work.')
	 
		assert(Category.existsCategory(NNDatasetTransform.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'NNDatasetTransform.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(dtran.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'dtran.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dtran, tag)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(dtran, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dtran, tag)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNDatasetTransform'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		tag = dtran.getPropTag(prop);
	 
		assert(Format.existsFormat(NNDatasetTransform.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'NNDatasetTransform.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(dtran.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'dtran.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dtran, prop)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(dtran, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dtran, prop)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNDatasetTransform'', prop) does not work.')
	 
		assert(Format.existsFormat(NNDatasetTransform.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'NNDatasetTransform.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(dtran.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'dtran.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dtran, tag)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(dtran, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dtran, tag)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNDatasetTransform'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		tag = dtran.getPropTag(prop);
	 
		assert(ischar(NNDatasetTransform.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'NNDatasetTransform.getPropDescription(prop) does not work.')
		assert(ischar(dtran.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'dtran.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(dtran, prop)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(dtran, prop) does not work.')
		assert(ischar(Element.getPropDescription(dtran, prop)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNDatasetTransform'', prop) does not work.')
	 
		assert(ischar(NNDatasetTransform.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'NNDatasetTransform.getPropDescription(tag) does not work.')
		assert(ischar(dtran.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'dtran.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(dtran, tag)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(dtran, tag) does not work.')
		assert(ischar(Element.getPropDescription(dtran, tag)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNDatasetTransform'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		tag = dtran.getPropTag(prop);
	 
		settings = NNDatasetTransform.getPropSettings(prop);
		settings = dtran.getPropSettings(prop);
		settings = Element.getPropSettings(dtran, prop);
		settings = Element.getPropSettings('NNDatasetTransform', prop);
	 
		settings = NNDatasetTransform.getPropSettings(tag);
		settings = dtran.getPropSettings(tag);
		settings = Element.getPropSettings(dtran, tag);
		settings = Element.getPropSettings('NNDatasetTransform', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		tag = dtran.getPropTag(prop);
	 
		default = NNDatasetTransform.getPropDefault(prop);
		default = dtran.getPropDefault(prop);
		default = Element.getPropDefault(dtran, prop);
		default = Element.getPropDefault('NNDatasetTransform', prop);
	 
		default = NNDatasetTransform.getPropDefault(tag);
		default = dtran.getPropDefault(tag);
		default = Element.getPropDefault(dtran, tag);
		default = Element.getPropDefault('NNDatasetTransform', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		tag = dtran.getPropTag(prop);
	 
		conditioned_default = NNDatasetTransform.getPropDefaultConditioned(prop);
		conditioned_default = dtran.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(dtran, prop);
		conditioned_default = Element.getPropDefaultConditioned('NNDatasetTransform', prop);
	 
		conditioned_default = NNDatasetTransform.getPropDefaultConditioned(tag);
		conditioned_default = dtran.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(dtran, tag);
		conditioned_default = Element.getPropDefaultConditioned('NNDatasetTransform', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		tag = dtran.getPropTag(prop);
	 
		assert(~NNDatasetTransform.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'NNDatasetTransform.checkProp(prop, value) does not work.')
		assert(~dtran.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'dtran.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(dtran, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dtran, prop, value) does not work.')
		assert(~Element.checkProp('NNDatasetTransform', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDatasetTransform'', prop, value) does not work.')
	 
		assert_with_error('NNDatasetTransform.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetTransform:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetTransform:' BRAPH2.WRONG_INPUT], prop, dtran)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetTransform:' BRAPH2.WRONG_INPUT], prop, dtran)
		assert_with_error('Element.checkProp(''NNDatasetTransform'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetTransform:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~NNDatasetTransform.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'NNDatasetTransform.checkProp(tag, value) does not work.')
		assert(~dtran.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'dtran.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(dtran, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dtran, tag, value) does not work.')
		assert(~Element.checkProp('NNDatasetTransform', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDatasetTransform'', tag, value) does not work.')
	 
		assert_with_error('NNDatasetTransform.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetTransform:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetTransform:' BRAPH2.WRONG_INPUT], tag, dtran)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetTransform:' BRAPH2.WRONG_INPUT], tag, dtran)
		assert_with_error('Element.checkProp(''NNDatasetTransform'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetTransform:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(NNDatasetTransform.checkProp(prop, Element.getPropDefaultConditioned(NNDatasetTransform, prop)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'NNDatasetTransform.checkProp(prop, <conditioned default value>) does not work.')
		assert(dtran.checkProp(prop, Element.getPropDefaultConditioned(NNDatasetTransform, prop)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'dtran.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(dtran, prop, Element.getPropDefaultConditioned(NNDatasetTransform, prop)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dtran, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNDatasetTransform', prop, Element.getPropDefaultConditioned(NNDatasetTransform, prop)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDatasetTransform'', prop, <conditioned default value>) does not work.')
	 
		assert(NNDatasetTransform.checkProp(tag, Element.getPropDefaultConditioned(NNDatasetTransform, prop)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'NNDatasetTransform.checkProp(tag, <conditioned default value>) does not work.')
		assert(dtran.checkProp(tag, Element.getPropDefaultConditioned(NNDatasetTransform, prop)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'dtran.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(dtran, tag, Element.getPropDefaultConditioned(NNDatasetTransform, prop)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dtran, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNDatasetTransform', tag, Element.getPropDefaultConditioned(NNDatasetTransform, prop)), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDatasetTransform'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dtran = NNDatasetTransform( ...
		NNDatasetTransform.ELCLASS, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.NAME, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.DESCRIPTION, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.TEMPLATE, NNDatasetTransform.getPropDefault(NNDatasetTransform.TEMPLATE), ...
		NNDatasetTransform.ID, NNDatasetTransform.getPropDefault(NNDatasetTransform.ID), ...
		NNDatasetTransform.LABEL, NNDatasetTransform.getPropDefault(NNDatasetTransform.LABEL), ...
		NNDatasetTransform.NOTES, NNDatasetTransform.getPropDefault(NNDatasetTransform.NOTES), ...
		NNDatasetTransform.TOSTRING, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.D, NNDatasetTransform.getPropDefault(NNDatasetTransform.D), ...
		NNDatasetTransform.TRANSFORMED_D, NNDatasetTransform.getPropDefault(NNDatasetTransform.TRANSFORMED_D) ...
		);
	 
	for prop = 1:1:NNDatasetTransform.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNDatasetTransform.getPropTag(prop));
		switch NNDatasetTransform.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					dtran.getr(prop) == NNDatasetTransform.getNoValue(), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDatasetTransform.getCategoryName(NNDatasetTransform.getPropCategory(prop)) ', NNDatasetTransform.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDatasetTransform.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					dtran.getr(TAG) == NNDatasetTransform.getNoValue(), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDatasetTransform.getCategoryName(NNDatasetTransform.getPropCategory(prop)) ', NNDatasetTransform.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDatasetTransform.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(dtran.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(dtran.getPropSettings(prop))
					assert( ...
						dtran.checkFormat(dtran.getPropFormat(prop), dtran.get(prop)), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						['NNDatasetTransform.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						dtran.checkFormat(dtran.getPropFormat(prop), dtran.get(prop), dtran.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						['NNDatasetTransform.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					dtran.getr(prop) == NNDatasetTransform.getNoValue(), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDatasetTransform.getCategoryName(NNDatasetTransform.getPropCategory(prop)) ', NNDatasetTransform.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDatasetTransform.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					dtran.getr(TAG) == NNDatasetTransform.getNoValue(), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDatasetTransform.getCategoryName(NNDatasetTransform.getPropCategory(prop)) ', NNDatasetTransform.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDatasetTransform.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':NNDatasetTransform']);
				assert( ...
					~isa(dtran.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(dtran.getPropSettings(prop))
					assert( ...
						dtran.checkFormat(dtran.getPropFormat(prop), dtran.get(prop)), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						['NNDatasetTransform.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						dtran.checkFormat(dtran.getPropFormat(prop), dtran.get(prop), dtran.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						['NNDatasetTransform.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(dtran.getr(prop), NNDatasetTransform.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by NNDatasetTransform.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNDatasetTransform.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(dtran.getr(TAG), NNDatasetTransform.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.getr(' TAG ') must be inizialized to its default value ' ...
					'given by NNDatasetTransform.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNDatasetTransform.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dtran = NNDatasetTransform( ...
		NNDatasetTransform.ELCLASS, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.NAME, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.DESCRIPTION, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.TEMPLATE, NNDatasetTransform.getPropDefault(NNDatasetTransform.TEMPLATE), ...
		NNDatasetTransform.ID, NNDatasetTransform.getPropDefault(NNDatasetTransform.ID), ...
		NNDatasetTransform.LABEL, NNDatasetTransform.getPropDefault(NNDatasetTransform.LABEL), ...
		NNDatasetTransform.NOTES, NNDatasetTransform.getPropDefault(NNDatasetTransform.NOTES), ...
		NNDatasetTransform.TOSTRING, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.D, NNDatasetTransform.getPropDefault(NNDatasetTransform.D), ...
		NNDatasetTransform.TRANSFORMED_D, NNDatasetTransform.getPropDefault(NNDatasetTransform.TRANSFORMED_D) ...
		);
	 
	for prop = 1:1:NNDatasetTransform.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNDatasetTransform.getPropTag(prop));
		switch NNDatasetTransform.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(dtran.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(dtran.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(dtran.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(dtran.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					dtran.checkFormat(dtran.getPropFormat(prop), dtran.getr(prop),dtran.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNDatasetTransform']);
				assert( ...
					~isa(dtran.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(dtran.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNDatasetTransform']);
	% 			assert( ...
	% 				~isa(dtran.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
	% 				['NNDatasetTransform.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(dtran.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
	% 				['NNDatasetTransform.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				dtran.checkFormat(dtran.getPropFormat(prop), dtran.getr(prop),dtran.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
	% 				['NNDatasetTransform.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':NNDatasetTransform']);
				assert( ...
					~isa(dtran.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(dtran.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(dtran.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(dtran.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					dtran.checkFormat(dtran.getPropFormat(prop), dtran.getr(prop),dtran.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if dtran.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:NNDatasetTransform');
					delete(ancestor(dtran.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(NNDatasetTransform.getProps(Category.RESULT))
		for prop = 1:1:NNDatasetTransform.getPropNumber()
	 
			% excluded props
			if any(prop == [])
				continue
			end
	 
			switch NNDatasetTransform.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						dtran.isLocked(prop), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						['NNDatasetTransform.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~dtran.isLocked(prop), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						['NNDatasetTransform.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dtran = NNDatasetTransform();
	 
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		TAG = upper(NNDatasetTransform.getPropTag(prop));
		assert( ...
			~dtran.isLocked(prop), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			['NNDatasetTransform.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~dtran.isLocked(TAG), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			['NNDatasetTransform.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	dtran.lock()
	 
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		switch NNDatasetTransform.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					dtran.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~dtran.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dtran = NNDatasetTransform();
	 
	warning_backup = warning('off', 'BRAPH2:NNDatasetTransform');
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		dtran.lock(prop)
		switch NNDatasetTransform.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					dtran.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~dtran.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dtran = NNDatasetTransform();
	 
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		TAG = upper(NNDatasetTransform.getPropTag(prop));
		assert( ...
			dtran.isChecked(prop), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			['NNDatasetTransform.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			dtran.isChecked(TAG), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			['NNDatasetTransform.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	dtran.unchecked()
	 
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		assert( ...
			~dtran.isChecked(prop), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			['NNDatasetTransform.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	dtran.checked()
	 
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		assert( ...
			dtran.isChecked(prop), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			['NNDatasetTransform.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic NNDatasetTransform
	dtran_0 = NNDatasetTransform( ...
		NNDatasetTransform.ELCLASS, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.NAME, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.DESCRIPTION, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.TEMPLATE, NNDatasetTransform.getPropDefault(NNDatasetTransform.TEMPLATE), ...
		NNDatasetTransform.ID, NNDatasetTransform.getPropDefault(NNDatasetTransform.ID), ...
		NNDatasetTransform.LABEL, NNDatasetTransform.getPropDefault(NNDatasetTransform.LABEL), ...
		NNDatasetTransform.NOTES, NNDatasetTransform.getPropDefault(NNDatasetTransform.NOTES), ...
		NNDatasetTransform.TOSTRING, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.D, NNDatasetTransform.getPropDefault(NNDatasetTransform.D), ...
		NNDatasetTransform.TRANSFORMED_D, NNDatasetTransform.getPropDefault(NNDatasetTransform.TRANSFORMED_D) ...
		);
	 
	% NNDatasetTransform with 1st callbacks
	dtran_1 = NNDatasetTransform( ...
		NNDatasetTransform.ELCLASS, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.NAME, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.DESCRIPTION, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.TEMPLATE, dtran_0.getCallback(4), ..., ...
		NNDatasetTransform.ID, dtran_0.getCallback(5), ..., ...
		NNDatasetTransform.LABEL, NNDatasetTransform.getPropDefault(NNDatasetTransform.LABEL), ...
		NNDatasetTransform.NOTES, NNDatasetTransform.getPropDefault(NNDatasetTransform.NOTES), ...
		NNDatasetTransform.TOSTRING, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.D, dtran_0.getCallback(9), ..., ...
		NNDatasetTransform.TRANSFORMED_D, dtran_0.getCallback(10) ... ...
		);
	 
	prop_number = NNDatasetTransform.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNDatasetTransform.getPropTag(prop));
		switch NNDatasetTransform.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(dtran_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(dtran_1.get(prop), dtran_0.get(prop)) && ~isa(dtran_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(dtran_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNDatasetTransform with 2nd callbacks
	dtran_2 = NNDatasetTransform( ...
		NNDatasetTransform.ELCLASS, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.NAME, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.DESCRIPTION, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.TEMPLATE, dtran_1.getCallback(4), ..., ...
		NNDatasetTransform.ID, dtran_1.getCallback(5), ..., ...
		NNDatasetTransform.LABEL, NNDatasetTransform.getPropDefault(NNDatasetTransform.LABEL), ...
		NNDatasetTransform.NOTES, NNDatasetTransform.getPropDefault(NNDatasetTransform.NOTES), ...
		NNDatasetTransform.TOSTRING, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.D, dtran_1.getCallback(9), ..., ...
		NNDatasetTransform.TRANSFORMED_D, dtran_1.getCallback(10) ... ...
		);
	 
	prop_number = NNDatasetTransform.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNDatasetTransform.getPropTag(prop));
		switch NNDatasetTransform.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(dtran_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(dtran_2.get(prop), dtran_0.get(prop)) && ~isa(dtran_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(dtran_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNDatasetTransform with 3rd callbacks
	dtran_3 = NNDatasetTransform( ...
		NNDatasetTransform.ELCLASS, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.NAME, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.DESCRIPTION, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.TEMPLATE, dtran_2.getCallback(4), ..., ...
		NNDatasetTransform.ID, dtran_2.getCallback(5), ..., ...
		NNDatasetTransform.LABEL, NNDatasetTransform.getPropDefault(NNDatasetTransform.LABEL), ...
		NNDatasetTransform.NOTES, NNDatasetTransform.getPropDefault(NNDatasetTransform.NOTES), ...
		NNDatasetTransform.TOSTRING, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.D, dtran_2.getCallback(9), ..., ...
		NNDatasetTransform.TRANSFORMED_D, dtran_2.getCallback(10) ... ...
		);
	 
	prop_number = NNDatasetTransform.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNDatasetTransform.getPropTag(prop));
		switch NNDatasetTransform.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(dtran_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(dtran_3.get(prop), dtran_0.get(prop)) && ~isa(dtran_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(dtran_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	dtran = NNDatasetTransform();
	 
	dtran_copy = dtran.copy();
	 
	assert(dtran_copy ~= dtran, ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'NNDatasetTransform.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(dtran_copy, dtran), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'NNDatasetTransform.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		value = dtran.getr(prop);
		value_copy = dtran_copy.getr(prop);
		switch NNDatasetTransform.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					'NNDatasetTransform.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
							'NNDatasetTransform.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
							'NNDatasetTransform.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					dtran_copy.isLocked(prop) == dtran.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					'NNDatasetTransform.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					dtran_copy.isChecked(prop) == dtran.isChecked(prop), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					'NNDatasetTransform.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					dtran_copy.getPropSeed(prop) == dtran.getPropSeed(prop), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					'NNDatasetTransform.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	dtran = NNDatasetTransform( ...
		NNDatasetTransform.ELCLASS, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.NAME, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.DESCRIPTION, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.TEMPLATE, NNDatasetTransform.getPropDefault(NNDatasetTransform.TEMPLATE), ...
		NNDatasetTransform.ID, NNDatasetTransform.getPropDefault(NNDatasetTransform.ID), ...
		NNDatasetTransform.LABEL, NNDatasetTransform.getPropDefault(NNDatasetTransform.LABEL), ...
		NNDatasetTransform.NOTES, NNDatasetTransform.getPropDefault(NNDatasetTransform.NOTES), ...
		NNDatasetTransform.TOSTRING, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.D, NNDatasetTransform.getPropDefault(NNDatasetTransform.D), ...
		NNDatasetTransform.TRANSFORMED_D, NNDatasetTransform.getPropDefault(NNDatasetTransform.TRANSFORMED_D) ...
		);
	 
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		if NNDatasetTransform.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':NNDatasetTransform']);
			% dtran.memorize(prop);
			% warning(warning_backup)
		elseif NNDatasetTransform.getPropCategory(prop) == Category.EVANESCENT && dtran.getPropFormat(prop) == Format.HANDLE
			dtran.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:NNDatasetTransform');
			delete(ancestor(dtran.get(prop), 'figure'))
			warning(warning_backup)
		else
			dtran.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	dtran_copy = dtran.copy();
	 
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		value = dtran.getr(prop);
		value_copy = dtran_copy.getr(prop);
		switch NNDatasetTransform.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					'NNDatasetTransform.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
							'NNDatasetTransform.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
							'NNDatasetTransform.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						dtran_copy.isLocked(prop) == dtran.isLocked(prop), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dtran_copy.isChecked(prop) == dtran.isChecked(prop), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dtran_copy.getPropSeed(prop) == dtran.getPropSeed(prop), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	dtran_0 = NNDatasetTransform( ...
		NNDatasetTransform.ELCLASS, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.NAME, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.DESCRIPTION, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.TEMPLATE, NNDatasetTransform.getPropDefault(NNDatasetTransform.TEMPLATE), ...
		NNDatasetTransform.ID, NNDatasetTransform.getPropDefault(NNDatasetTransform.ID), ...
		NNDatasetTransform.LABEL, NNDatasetTransform.getPropDefault(NNDatasetTransform.LABEL), ...
		NNDatasetTransform.NOTES, NNDatasetTransform.getPropDefault(NNDatasetTransform.NOTES), ...
		NNDatasetTransform.TOSTRING, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.D, NNDatasetTransform.getPropDefault(NNDatasetTransform.D), ...
		NNDatasetTransform.TRANSFORMED_D, NNDatasetTransform.getPropDefault(NNDatasetTransform.TRANSFORMED_D) ...
		);
	 
	dtran = NNDatasetTransform( ...
		NNDatasetTransform.ELCLASS, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.NAME, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.DESCRIPTION, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.TEMPLATE, dtran_0.getCallback(4), ..., ...
		NNDatasetTransform.ID, dtran_0.getCallback(5), ..., ...
		NNDatasetTransform.LABEL, NNDatasetTransform.getPropDefault(NNDatasetTransform.LABEL), ...
		NNDatasetTransform.NOTES, NNDatasetTransform.getPropDefault(NNDatasetTransform.NOTES), ...
		NNDatasetTransform.TOSTRING, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.D, dtran_0.getCallback(9), ..., ...
		NNDatasetTransform.TRANSFORMED_D, dtran_0.getCallback(10) ... ...
		);
	 
	dtran_copy = dtran.copy();
	dtran_0_copy = dtran_copy.getr('ID').get('EL');
	 
	for prop = 1:1:NNDatasetTransform.getPropNumber()
		value = dtran.getr(prop);
		value_copy = dtran_copy.getr(prop);
		switch NNDatasetTransform.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					'NNDatasetTransform.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
							'NNDatasetTransform.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
							'NNDatasetTransform.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == dtran_0.getCallback(prop), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform.copy() does not work. The callback should be obtained from NNDatasetTransform.getCallback().' ...
						)
					assert( ...
						value_copy == dtran_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform.copy() does not work. The callback should be obtained from NNDatasetTransform.getCallback().' ...
						)
				end
	 
					assert( ...
						dtran_copy.isLocked(prop) == dtran.isLocked(prop), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dtran_copy.isChecked(prop) == dtran.isChecked(prop), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dtran_copy.getPropSeed(prop) == dtran.getPropSeed(prop), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dtran_template = NNDatasetTransform();
	dtran = NNDatasetTransform('TEMPLATE', dtran_template);
	 
	for prop = 1:1:NNDatasetTransform.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNDatasetTransform.getPropTag(prop));
		switch NNDatasetTransform.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == NNDatasetTransform.TEMPLATE
					assert( ...
						isa(dtran.getr(prop), 'NNDatasetTransform'), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform TEMPLATE does not work. NNDatasetTransform.getr(''TEMPLATE'') should be a NNDatasetTransform element.' ...
						)
					assert( ...
						isa(dtran_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						'NNDatasetTransform TEMPLATE does not work. NNDatasetTransform_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(dtran.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						['NNDatasetTransform TEMPLATE does not work. NNDatasetTransform.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						dtran.getr(prop).get('EL') == dtran_template && dtran.getr(prop).get('PROP') == prop && strcmp(dtran.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						['NNDatasetTransform TEMPLATE does not work. NNDatasetTransform.getr(' TAG ') should be a Callback to dtran_template.' TAG '.'] ...
						)
					assert( ...
						isa(dtran_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
						['NNDatasetTransform TEMPLATE does not work. NNDatasetTransform_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(dtran.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform TEMPLATE does not work. NNDatasetTransform.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(dtran_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
					['NNDatasetTransform TEMPLATE does not work. NNDatasetTransform_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dtran = NNDatasetTransform( ...
		NNDatasetTransform.ELCLASS, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.NAME, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.DESCRIPTION, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.TEMPLATE, NNDatasetTransform.getPropDefault(NNDatasetTransform.TEMPLATE), ...
		NNDatasetTransform.ID, NNDatasetTransform.getPropDefault(NNDatasetTransform.ID), ...
		NNDatasetTransform.LABEL, NNDatasetTransform.getPropDefault(NNDatasetTransform.LABEL), ...
		NNDatasetTransform.NOTES, NNDatasetTransform.getPropDefault(NNDatasetTransform.NOTES), ...
		NNDatasetTransform.TOSTRING, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.D, NNDatasetTransform.getPropDefault(NNDatasetTransform.D), ...
		NNDatasetTransform.TRANSFORMED_D, NNDatasetTransform.getPropDefault(NNDatasetTransform.TRANSFORMED_D) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'nndatasettransform_to_be_erased.b2'];
	 
	Element.save(dtran, filename)
	 
	dtran_loaded = Element.load(filename);
	 
	assert( ...
		isequal(dtran.copy(), dtran_loaded), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'NNDatasetTransform.save(dtran) and/or NNDatasetTransform.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dtran = NNDatasetTransform( ...
		NNDatasetTransform.ELCLASS, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.NAME, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.DESCRIPTION, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.TEMPLATE, NNDatasetTransform.getPropDefault(NNDatasetTransform.TEMPLATE), ...
		NNDatasetTransform.ID, NNDatasetTransform.getPropDefault(NNDatasetTransform.ID), ...
		NNDatasetTransform.LABEL, NNDatasetTransform.getPropDefault(NNDatasetTransform.LABEL), ...
		NNDatasetTransform.NOTES, NNDatasetTransform.getPropDefault(NNDatasetTransform.NOTES), ...
		NNDatasetTransform.TOSTRING, NNDatasetTransform.getNoValue(), ...
		NNDatasetTransform.D, NNDatasetTransform.getPropDefault(NNDatasetTransform.D), ...
		NNDatasetTransform.TRANSFORMED_D, NNDatasetTransform.getPropDefault(NNDatasetTransform.TRANSFORMED_D) ...
		);
	 
	[json, struct, el_list] = encodeJSON(dtran);
	[dtran_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(dtran_dec ~= dtran, ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		'NNDatasetTransform.encodeJSON() or NNDatasetTransform.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) NNDatasetTransform.getPropFormat(prop), num2cell(NNDatasetTransform.getProps())) == Format.HANDLE) && all(cellfun(@(prop) NNDatasetTransform.getPropFormat(prop), num2cell(NNDatasetTransform.getProps())) == Format.NET)
		assert(isequal(dtran_dec, dtran), ...
			[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
			'NNDatasetTransform.encodeJSON() or NNDatasetTransform.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':NNDatasetTransform:' BRAPH2.FAIL_TEST], ...
		[' When testing NNDatasetTransform no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 13: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

