%TEST_NNDATASETNORMALIZE

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	dnorm = NNDatasetNormalize();
	 
	% get('ELCLASS')
	if isa(NNDatasetNormalize, 'ConcreteElement')
		assert(strcmp(NNDatasetNormalize().get('ELCLASS'), 'NNDatasetNormalize'), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'NNDatasetNormalize().get(''ELCLASS'') should return ''NNDatasetNormalize''.')
	end
	 
	% getBuild()
	assert(NNDatasetNormalize.getBuild() == 1 && NNDatasetNormalize.getBuild() > 0, ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'NNDatasetNormalize.getBuild() should return the NNDatasetNormalize build number.')
	assert(dnorm.getBuild() == 1 && dnorm.getBuild() > 0 , ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'dnorm.getBuild() should return the NNDatasetNormalize build number.')
	assert(Element.getBuild(dnorm) == 1 && Element.getBuild(dnorm) > 0, ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(dnorm) should return the NNDatasetNormalize build number.')
	assert(Element.getBuild('NNDatasetNormalize') == 1 && Element.getBuild('NNDatasetNormalize') > 0, ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''NNDatasetNormalize'') should return the NNDatasetNormalize build number.')
	 
	% getClass()
	assert(strcmp(NNDatasetNormalize.getClass(), 'NNDatasetNormalize'), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'NNDatasetNormalize.getClass() should return ''NNDatasetNormalize''.')
	assert(strcmp(dnorm.getClass(), 'NNDatasetNormalize'), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'dnorm.getClass() should return ''NNDatasetNormalize''.')
	assert(strcmp(Element.getClass(dnorm), 'NNDatasetNormalize'), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(dnorm) should return ''NNDatasetNormalize''.')
	assert(strcmp(Element.getClass('NNDatasetNormalize'), 'NNDatasetNormalize'), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''NNDatasetNormalize'') should return ''NNDatasetNormalize''.')
	 
	% getSubclasses()
	assert(isequal(NNDatasetNormalize.getSubclasses(), subclasses('NNDatasetNormalize', [], [], true)), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'NNDatasetNormalize.getSubclasses() should return the same result as subclasses(''NNDatasetNormalize'', [], [], true).')
	assert(isequal(dnorm.getSubclasses(), subclasses('NNDatasetNormalize', [], [], true)), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''NNDatasetNormalize'', [], [], true).')
	assert(isequal(Element.getSubclasses(dnorm), subclasses('NNDatasetNormalize', [], [], true)), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(dnorm) should return the same result as subclasses(''NNDatasetNormalize'', [], [], true).')
	assert(isequal(Element.getSubclasses('NNDatasetNormalize'), subclasses('NNDatasetNormalize', [], [], true)), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''NNDatasetNormalize'') should return the same result as subclasses(''NNDatasetNormalize'', [], [], true).')
	 
	% getProps()
	assert(isempty(NNDatasetNormalize.getProps()) || isequal(NNDatasetNormalize.getProps(), 1:1:length(NNDatasetNormalize.getProps())), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'NNDatasetNormalize.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNDatasetNormalize.getProps()) || isequal(dnorm.getProps(), 1:1:length(NNDatasetNormalize.getProps())), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'dnorm.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNDatasetNormalize.getProps()) || isequal(Element.getProps(dnorm), 1:1:length(NNDatasetNormalize.getProps())), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(dnorm) should return a row vector [1:1:N].')
	assert(isempty(NNDatasetNormalize.getProps()) || isequal(Element.getProps('NNDatasetNormalize'), 1:1:length(NNDatasetNormalize.getProps())), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNDatasetNormalize'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) NNDatasetNormalize.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNDatasetNormalize.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDatasetNormalize.getProps())), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'NNDatasetNormalize.getProps(category) does not work.')
	tmp = cellfun(@(category) dnorm.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNDatasetNormalize.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDatasetNormalize.getProps())), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'dnorm.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(dnorm, category), categories, 'UniformOutput', false);
	assert(isempty(NNDatasetNormalize.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDatasetNormalize.getProps())), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(dnorm, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('NNDatasetNormalize', category), categories, 'UniformOutput', false);
	assert(isempty(NNDatasetNormalize.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDatasetNormalize.getProps())), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNDatasetNormalize'', category) does not work.')
	 
	% getPropNumber()
	assert(NNDatasetNormalize.getPropNumber() == length(NNDatasetNormalize.getProps()), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'NNDatasetNormalize.getPropNumber() should return the number of properties.')
	assert(dnorm.getPropNumber() == length(NNDatasetNormalize.getProps()), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'dnorm.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(dnorm) == length(NNDatasetNormalize.getProps()), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(dnorm) should return the number of properties.')
	assert(Element.getPropNumber('NNDatasetNormalize') == length(NNDatasetNormalize.getProps()), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNDatasetNormalize'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) NNDatasetNormalize.getPropNumber(category), categories)) == NNDatasetNormalize.getPropNumber(), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'NNDatasetNormalize.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) dnorm.getPropNumber(category), categories)) == NNDatasetNormalize.getPropNumber(), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'dnorm.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(dnorm, category), categories)) == NNDatasetNormalize.getPropNumber(), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(dnorm, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('NNDatasetNormalize', category), categories)) == NNDatasetNormalize.getPropNumber(), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNDatasetNormalize'', category) does not work.')
	 
	% existsProp(prop)
	assert(~NNDatasetNormalize.existsProp(NaN), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'NNDatasetNormalize.existsProp(prop) does not work.')
	assert(~dnorm.existsProp(NaN), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'dnorm.existsProp(prop) does not work.')
	assert(~Element.existsProp(dnorm, NaN), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(dnorm, prop) does not work.')
	assert(~Element.existsProp('NNDatasetNormalize', NaN), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''NNDatasetNormalize'', prop) does not work.')
	 
	assert_with_error('NNDatasetNormalize.existsProp(NaN)', [BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.WRONG_INPUT], dnorm)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.WRONG_INPUT], dnorm)
	assert_with_error('Element.existsProp(''NNDatasetNormalize'', NaN)', [BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		assert(NNDatasetNormalize.existsProp(prop), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'NNDatasetNormalize.existsProp(prop) does not work.')
		assert(dnorm.existsProp(prop), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'dnorm.existsProp(prop) does not work.')
		assert(Element.existsProp(dnorm, prop), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(dnorm, prop) does not work.')
		assert(Element.existsProp('NNDatasetNormalize', prop), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''NNDatasetNormalize'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~NNDatasetNormalize.existsTag(''), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'NNDatasetNormalize.existsTag(tag) does not work.')
	assert(~dnorm.existsTag(''), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'dnorm.existsTag(tag) does not work.')
	assert(~Element.existsTag(dnorm, ''), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(dnorm, tag) does not work.')
	assert(~Element.existsTag('NNDatasetNormalize', ''), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''NNDatasetNormalize'', tag) does not work.')
	 
	assert_with_error('NNDatasetNormalize.existsTag('''')', [BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.WRONG_INPUT], dnorm)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.WRONG_INPUT], dnorm)
	assert_with_error('Element.existsTag(''NNDatasetNormalize'', '''')', [BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		tag = dnorm.getPropTag(prop);
		assert(NNDatasetNormalize.existsTag(tag), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'NNDatasetNormalize.existsTag(tag) does not work.')
		assert(dnorm.existsTag(tag), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'dnorm.existsTag(tag) does not work.')
		assert(Element.existsTag(dnorm, tag), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(dnorm, tga) does not work.')
		assert(Element.existsTag('NNDatasetNormalize', tag), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''NNDatasetNormalize'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		assert(NNDatasetNormalize.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'NNDatasetNormalize.getPropProp(prop) does not work.')
		assert(dnorm.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'dnorm.getPropProp(prop) does not work.')
		assert(Element.getPropProp(dnorm, prop) == prop, ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(dnorm, prop) does not work.')
		assert(Element.getPropProp('NNDatasetNormalize', prop) == prop, ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNDatasetNormalize'', prop) does not work.')
	 
		tag = dnorm.getPropTag(prop);
		assert(NNDatasetNormalize.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'NNDatasetNormalize.getPropProp(tag) does not work.')
		assert(dnorm.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'dnorm.getPropProp(tag) does not work.')
		assert(Element.getPropProp(dnorm, tag) == prop, ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(dnorm, tag) does not work.')
		assert(Element.getPropProp('NNDatasetNormalize', prop) == prop, ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNDatasetNormalize'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		tag = dnorm.getPropTag(prop);
	 
		assert(strcmp(NNDatasetNormalize.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'NNDatasetNormalize.getPropTag(prop) does not work.')
		assert(strcmp(dnorm.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'dnorm.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(dnorm, prop), tag), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(dnorm, prop) does not work.')
		assert(strcmp(Element.getPropTag('NNDatasetNormalize', prop), tag), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNDatasetNormalize'', prop) does not work.')
	 
		assert(strcmp(NNDatasetNormalize.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'NNDatasetNormalize.getPropTag(tag) does not work.')
		assert(strcmp(dnorm.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'dnorm.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(dnorm, tag), tag), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(dnorm, tag) does not work.')
		assert(strcmp(Element.getPropTag('NNDatasetNormalize', prop), tag), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNDatasetNormalize'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		tag = dnorm.getPropTag(prop);
	 
		assert(Category.existsCategory(NNDatasetNormalize.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'NNDatasetNormalize.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(dnorm.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'dnorm.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dnorm, prop)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(dnorm, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dnorm, prop)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNDatasetNormalize'', prop) does not work.')
	 
		assert(Category.existsCategory(NNDatasetNormalize.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'NNDatasetNormalize.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(dnorm.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'dnorm.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dnorm, tag)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(dnorm, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dnorm, tag)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNDatasetNormalize'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		tag = dnorm.getPropTag(prop);
	 
		assert(Format.existsFormat(NNDatasetNormalize.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'NNDatasetNormalize.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(dnorm.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'dnorm.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dnorm, prop)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(dnorm, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dnorm, prop)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNDatasetNormalize'', prop) does not work.')
	 
		assert(Format.existsFormat(NNDatasetNormalize.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'NNDatasetNormalize.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(dnorm.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'dnorm.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dnorm, tag)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(dnorm, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dnorm, tag)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNDatasetNormalize'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		tag = dnorm.getPropTag(prop);
	 
		assert(ischar(NNDatasetNormalize.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'NNDatasetNormalize.getPropDescription(prop) does not work.')
		assert(ischar(dnorm.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'dnorm.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(dnorm, prop)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(dnorm, prop) does not work.')
		assert(ischar(Element.getPropDescription(dnorm, prop)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNDatasetNormalize'', prop) does not work.')
	 
		assert(ischar(NNDatasetNormalize.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'NNDatasetNormalize.getPropDescription(tag) does not work.')
		assert(ischar(dnorm.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'dnorm.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(dnorm, tag)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(dnorm, tag) does not work.')
		assert(ischar(Element.getPropDescription(dnorm, tag)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNDatasetNormalize'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		tag = dnorm.getPropTag(prop);
	 
		settings = NNDatasetNormalize.getPropSettings(prop);
		settings = dnorm.getPropSettings(prop);
		settings = Element.getPropSettings(dnorm, prop);
		settings = Element.getPropSettings('NNDatasetNormalize', prop);
	 
		settings = NNDatasetNormalize.getPropSettings(tag);
		settings = dnorm.getPropSettings(tag);
		settings = Element.getPropSettings(dnorm, tag);
		settings = Element.getPropSettings('NNDatasetNormalize', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		tag = dnorm.getPropTag(prop);
	 
		default = NNDatasetNormalize.getPropDefault(prop);
		default = dnorm.getPropDefault(prop);
		default = Element.getPropDefault(dnorm, prop);
		default = Element.getPropDefault('NNDatasetNormalize', prop);
	 
		default = NNDatasetNormalize.getPropDefault(tag);
		default = dnorm.getPropDefault(tag);
		default = Element.getPropDefault(dnorm, tag);
		default = Element.getPropDefault('NNDatasetNormalize', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		tag = dnorm.getPropTag(prop);
	 
		conditioned_default = NNDatasetNormalize.getPropDefaultConditioned(prop);
		conditioned_default = dnorm.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(dnorm, prop);
		conditioned_default = Element.getPropDefaultConditioned('NNDatasetNormalize', prop);
	 
		conditioned_default = NNDatasetNormalize.getPropDefaultConditioned(tag);
		conditioned_default = dnorm.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(dnorm, tag);
		conditioned_default = Element.getPropDefaultConditioned('NNDatasetNormalize', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		tag = dnorm.getPropTag(prop);
	 
		assert(~NNDatasetNormalize.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'NNDatasetNormalize.checkProp(prop, value) does not work.')
		assert(~dnorm.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'dnorm.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(dnorm, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dnorm, prop, value) does not work.')
		assert(~Element.checkProp('NNDatasetNormalize', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDatasetNormalize'', prop, value) does not work.')
	 
		assert_with_error('NNDatasetNormalize.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.WRONG_INPUT], prop, dnorm)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.WRONG_INPUT], prop, dnorm)
		assert_with_error('Element.checkProp(''NNDatasetNormalize'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~NNDatasetNormalize.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'NNDatasetNormalize.checkProp(tag, value) does not work.')
		assert(~dnorm.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'dnorm.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(dnorm, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dnorm, tag, value) does not work.')
		assert(~Element.checkProp('NNDatasetNormalize', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDatasetNormalize'', tag, value) does not work.')
	 
		assert_with_error('NNDatasetNormalize.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.WRONG_INPUT], tag, dnorm)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.WRONG_INPUT], tag, dnorm)
		assert_with_error('Element.checkProp(''NNDatasetNormalize'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(NNDatasetNormalize.checkProp(prop, Element.getPropDefaultConditioned(NNDatasetNormalize, prop)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'NNDatasetNormalize.checkProp(prop, <conditioned default value>) does not work.')
		assert(dnorm.checkProp(prop, Element.getPropDefaultConditioned(NNDatasetNormalize, prop)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'dnorm.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(dnorm, prop, Element.getPropDefaultConditioned(NNDatasetNormalize, prop)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dnorm, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNDatasetNormalize', prop, Element.getPropDefaultConditioned(NNDatasetNormalize, prop)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDatasetNormalize'', prop, <conditioned default value>) does not work.')
	 
		assert(NNDatasetNormalize.checkProp(tag, Element.getPropDefaultConditioned(NNDatasetNormalize, prop)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'NNDatasetNormalize.checkProp(tag, <conditioned default value>) does not work.')
		assert(dnorm.checkProp(tag, Element.getPropDefaultConditioned(NNDatasetNormalize, prop)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'dnorm.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(dnorm, tag, Element.getPropDefaultConditioned(NNDatasetNormalize, prop)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dnorm, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNDatasetNormalize', tag, Element.getPropDefaultConditioned(NNDatasetNormalize, prop)), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDatasetNormalize'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dnorm = NNDatasetNormalize( ...
		NNDatasetNormalize.ELCLASS, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.NAME, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.DESCRIPTION, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.TEMPLATE, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.TEMPLATE), ...
		NNDatasetNormalize.ID, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.ID), ...
		NNDatasetNormalize.LABEL, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.LABEL), ...
		NNDatasetNormalize.NOTES, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.NOTES), ...
		NNDatasetNormalize.TOSTRING, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.D, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.D), ...
		NNDatasetNormalize.NORMALIZED_D, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.NORMALIZED_D) ...
		);
	 
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNDatasetNormalize.getPropTag(prop));
		switch NNDatasetNormalize.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					dnorm.getr(prop) == NNDatasetNormalize.getNoValue(), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDatasetNormalize.getCategoryName(NNDatasetNormalize.getPropCategory(prop)) ', NNDatasetNormalize.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDatasetNormalize.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					dnorm.getr(TAG) == NNDatasetNormalize.getNoValue(), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDatasetNormalize.getCategoryName(NNDatasetNormalize.getPropCategory(prop)) ', NNDatasetNormalize.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDatasetNormalize.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(dnorm.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(dnorm.getPropSettings(prop))
					assert( ...
						dnorm.checkFormat(dnorm.getPropFormat(prop), dnorm.get(prop)), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						['NNDatasetNormalize.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						dnorm.checkFormat(dnorm.getPropFormat(prop), dnorm.get(prop), dnorm.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						['NNDatasetNormalize.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					dnorm.getr(prop) == NNDatasetNormalize.getNoValue(), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDatasetNormalize.getCategoryName(NNDatasetNormalize.getPropCategory(prop)) ', NNDatasetNormalize.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDatasetNormalize.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					dnorm.getr(TAG) == NNDatasetNormalize.getNoValue(), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDatasetNormalize.getCategoryName(NNDatasetNormalize.getPropCategory(prop)) ', NNDatasetNormalize.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDatasetNormalize.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':NNDatasetNormalize']);
				assert( ...
					~isa(dnorm.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(dnorm.getPropSettings(prop))
					assert( ...
						dnorm.checkFormat(dnorm.getPropFormat(prop), dnorm.get(prop)), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						['NNDatasetNormalize.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						dnorm.checkFormat(dnorm.getPropFormat(prop), dnorm.get(prop), dnorm.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						['NNDatasetNormalize.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(dnorm.getr(prop), NNDatasetNormalize.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by NNDatasetNormalize.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNDatasetNormalize.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(dnorm.getr(TAG), NNDatasetNormalize.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.getr(' TAG ') must be inizialized to its default value ' ...
					'given by NNDatasetNormalize.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNDatasetNormalize.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dnorm = NNDatasetNormalize( ...
		NNDatasetNormalize.ELCLASS, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.NAME, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.DESCRIPTION, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.TEMPLATE, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.TEMPLATE), ...
		NNDatasetNormalize.ID, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.ID), ...
		NNDatasetNormalize.LABEL, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.LABEL), ...
		NNDatasetNormalize.NOTES, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.NOTES), ...
		NNDatasetNormalize.TOSTRING, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.D, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.D), ...
		NNDatasetNormalize.NORMALIZED_D, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.NORMALIZED_D) ...
		);
	 
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNDatasetNormalize.getPropTag(prop));
		switch NNDatasetNormalize.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(dnorm.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(dnorm.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(dnorm.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(dnorm.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					dnorm.checkFormat(dnorm.getPropFormat(prop), dnorm.getr(prop),dnorm.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNDatasetNormalize']);
				assert( ...
					~isa(dnorm.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(dnorm.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNDatasetNormalize']);
	% 			assert( ...
	% 				~isa(dnorm.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
	% 				['NNDatasetNormalize.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(dnorm.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
	% 				['NNDatasetNormalize.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				dnorm.checkFormat(dnorm.getPropFormat(prop), dnorm.getr(prop),dnorm.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
	% 				['NNDatasetNormalize.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':NNDatasetNormalize']);
				assert( ...
					~isa(dnorm.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(dnorm.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(dnorm.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(dnorm.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					dnorm.checkFormat(dnorm.getPropFormat(prop), dnorm.getr(prop),dnorm.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if dnorm.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:NNDatasetNormalize');
					delete(ancestor(dnorm.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(NNDatasetNormalize.getProps(Category.RESULT))
		for prop = 1:1:NNDatasetNormalize.getPropNumber()
	 
			% excluded props
			if any(prop == [])
				continue
			end
	 
			switch NNDatasetNormalize.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						dnorm.isLocked(prop), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						['NNDatasetNormalize.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~dnorm.isLocked(prop), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						['NNDatasetNormalize.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dnorm = NNDatasetNormalize();
	 
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		TAG = upper(NNDatasetNormalize.getPropTag(prop));
		assert( ...
			~dnorm.isLocked(prop), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			['NNDatasetNormalize.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~dnorm.isLocked(TAG), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			['NNDatasetNormalize.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	dnorm.lock()
	 
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		switch NNDatasetNormalize.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					dnorm.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~dnorm.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dnorm = NNDatasetNormalize();
	 
	warning_backup = warning('off', 'BRAPH2:NNDatasetNormalize');
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		dnorm.lock(prop)
		switch NNDatasetNormalize.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					dnorm.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~dnorm.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dnorm = NNDatasetNormalize();
	 
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		TAG = upper(NNDatasetNormalize.getPropTag(prop));
		assert( ...
			dnorm.isChecked(prop), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			['NNDatasetNormalize.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			dnorm.isChecked(TAG), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			['NNDatasetNormalize.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	dnorm.unchecked()
	 
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		assert( ...
			~dnorm.isChecked(prop), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			['NNDatasetNormalize.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	dnorm.checked()
	 
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		assert( ...
			dnorm.isChecked(prop), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			['NNDatasetNormalize.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic NNDatasetNormalize
	dnorm_0 = NNDatasetNormalize( ...
		NNDatasetNormalize.ELCLASS, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.NAME, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.DESCRIPTION, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.TEMPLATE, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.TEMPLATE), ...
		NNDatasetNormalize.ID, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.ID), ...
		NNDatasetNormalize.LABEL, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.LABEL), ...
		NNDatasetNormalize.NOTES, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.NOTES), ...
		NNDatasetNormalize.TOSTRING, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.D, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.D), ...
		NNDatasetNormalize.NORMALIZED_D, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.NORMALIZED_D) ...
		);
	 
	% NNDatasetNormalize with 1st callbacks
	dnorm_1 = NNDatasetNormalize( ...
		NNDatasetNormalize.ELCLASS, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.NAME, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.DESCRIPTION, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.TEMPLATE, dnorm_0.getCallback(4), ..., ...
		NNDatasetNormalize.ID, dnorm_0.getCallback(5), ..., ...
		NNDatasetNormalize.LABEL, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.LABEL), ...
		NNDatasetNormalize.NOTES, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.NOTES), ...
		NNDatasetNormalize.TOSTRING, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.D, dnorm_0.getCallback(9), ..., ...
		NNDatasetNormalize.NORMALIZED_D, dnorm_0.getCallback(10) ... ...
		);
	 
	prop_number = NNDatasetNormalize.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNDatasetNormalize.getPropTag(prop));
		switch NNDatasetNormalize.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(dnorm_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(dnorm_1.get(prop), dnorm_0.get(prop)) && ~isa(dnorm_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(dnorm_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNDatasetNormalize with 2nd callbacks
	dnorm_2 = NNDatasetNormalize( ...
		NNDatasetNormalize.ELCLASS, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.NAME, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.DESCRIPTION, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.TEMPLATE, dnorm_1.getCallback(4), ..., ...
		NNDatasetNormalize.ID, dnorm_1.getCallback(5), ..., ...
		NNDatasetNormalize.LABEL, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.LABEL), ...
		NNDatasetNormalize.NOTES, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.NOTES), ...
		NNDatasetNormalize.TOSTRING, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.D, dnorm_1.getCallback(9), ..., ...
		NNDatasetNormalize.NORMALIZED_D, dnorm_1.getCallback(10) ... ...
		);
	 
	prop_number = NNDatasetNormalize.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNDatasetNormalize.getPropTag(prop));
		switch NNDatasetNormalize.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(dnorm_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(dnorm_2.get(prop), dnorm_0.get(prop)) && ~isa(dnorm_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(dnorm_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNDatasetNormalize with 3rd callbacks
	dnorm_3 = NNDatasetNormalize( ...
		NNDatasetNormalize.ELCLASS, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.NAME, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.DESCRIPTION, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.TEMPLATE, dnorm_2.getCallback(4), ..., ...
		NNDatasetNormalize.ID, dnorm_2.getCallback(5), ..., ...
		NNDatasetNormalize.LABEL, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.LABEL), ...
		NNDatasetNormalize.NOTES, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.NOTES), ...
		NNDatasetNormalize.TOSTRING, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.D, dnorm_2.getCallback(9), ..., ...
		NNDatasetNormalize.NORMALIZED_D, dnorm_2.getCallback(10) ... ...
		);
	 
	prop_number = NNDatasetNormalize.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNDatasetNormalize.getPropTag(prop));
		switch NNDatasetNormalize.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(dnorm_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(dnorm_3.get(prop), dnorm_0.get(prop)) && ~isa(dnorm_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(dnorm_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	dnorm = NNDatasetNormalize();
	 
	dnorm_copy = dnorm.copy();
	 
	assert(dnorm_copy ~= dnorm, ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'NNDatasetNormalize.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(dnorm_copy, dnorm), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'NNDatasetNormalize.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		value = dnorm.getr(prop);
		value_copy = dnorm_copy.getr(prop);
		switch NNDatasetNormalize.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					'NNDatasetNormalize.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
							'NNDatasetNormalize.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
							'NNDatasetNormalize.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					dnorm_copy.isLocked(prop) == dnorm.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					'NNDatasetNormalize.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					dnorm_copy.isChecked(prop) == dnorm.isChecked(prop), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					'NNDatasetNormalize.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					dnorm_copy.getPropSeed(prop) == dnorm.getPropSeed(prop), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					'NNDatasetNormalize.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	dnorm = NNDatasetNormalize( ...
		NNDatasetNormalize.ELCLASS, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.NAME, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.DESCRIPTION, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.TEMPLATE, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.TEMPLATE), ...
		NNDatasetNormalize.ID, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.ID), ...
		NNDatasetNormalize.LABEL, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.LABEL), ...
		NNDatasetNormalize.NOTES, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.NOTES), ...
		NNDatasetNormalize.TOSTRING, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.D, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.D), ...
		NNDatasetNormalize.NORMALIZED_D, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.NORMALIZED_D) ...
		);
	 
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		if NNDatasetNormalize.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':NNDatasetNormalize']);
			% dnorm.memorize(prop);
			% warning(warning_backup)
		elseif NNDatasetNormalize.getPropCategory(prop) == Category.EVANESCENT && dnorm.getPropFormat(prop) == Format.HANDLE
			dnorm.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:NNDatasetNormalize');
			delete(ancestor(dnorm.get(prop), 'figure'))
			warning(warning_backup)
		else
			dnorm.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	dnorm_copy = dnorm.copy();
	 
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		value = dnorm.getr(prop);
		value_copy = dnorm_copy.getr(prop);
		switch NNDatasetNormalize.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					'NNDatasetNormalize.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
							'NNDatasetNormalize.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
							'NNDatasetNormalize.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						dnorm_copy.isLocked(prop) == dnorm.isLocked(prop), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dnorm_copy.isChecked(prop) == dnorm.isChecked(prop), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dnorm_copy.getPropSeed(prop) == dnorm.getPropSeed(prop), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	dnorm_0 = NNDatasetNormalize( ...
		NNDatasetNormalize.ELCLASS, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.NAME, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.DESCRIPTION, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.TEMPLATE, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.TEMPLATE), ...
		NNDatasetNormalize.ID, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.ID), ...
		NNDatasetNormalize.LABEL, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.LABEL), ...
		NNDatasetNormalize.NOTES, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.NOTES), ...
		NNDatasetNormalize.TOSTRING, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.D, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.D), ...
		NNDatasetNormalize.NORMALIZED_D, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.NORMALIZED_D) ...
		);
	 
	dnorm = NNDatasetNormalize( ...
		NNDatasetNormalize.ELCLASS, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.NAME, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.DESCRIPTION, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.TEMPLATE, dnorm_0.getCallback(4), ..., ...
		NNDatasetNormalize.ID, dnorm_0.getCallback(5), ..., ...
		NNDatasetNormalize.LABEL, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.LABEL), ...
		NNDatasetNormalize.NOTES, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.NOTES), ...
		NNDatasetNormalize.TOSTRING, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.D, dnorm_0.getCallback(9), ..., ...
		NNDatasetNormalize.NORMALIZED_D, dnorm_0.getCallback(10) ... ...
		);
	 
	dnorm_copy = dnorm.copy();
	dnorm_0_copy = dnorm_copy.getr('ID').get('EL');
	 
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
		value = dnorm.getr(prop);
		value_copy = dnorm_copy.getr(prop);
		switch NNDatasetNormalize.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					'NNDatasetNormalize.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
							'NNDatasetNormalize.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
							'NNDatasetNormalize.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == dnorm_0.getCallback(prop), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize.copy() does not work. The callback should be obtained from NNDatasetNormalize.getCallback().' ...
						)
					assert( ...
						value_copy == dnorm_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize.copy() does not work. The callback should be obtained from NNDatasetNormalize.getCallback().' ...
						)
				end
	 
					assert( ...
						dnorm_copy.isLocked(prop) == dnorm.isLocked(prop), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dnorm_copy.isChecked(prop) == dnorm.isChecked(prop), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dnorm_copy.getPropSeed(prop) == dnorm.getPropSeed(prop), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dnorm_template = NNDatasetNormalize();
	dnorm = NNDatasetNormalize('TEMPLATE', dnorm_template);
	 
	for prop = 1:1:NNDatasetNormalize.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNDatasetNormalize.getPropTag(prop));
		switch NNDatasetNormalize.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == NNDatasetNormalize.TEMPLATE
					assert( ...
						isa(dnorm.getr(prop), 'NNDatasetNormalize'), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize TEMPLATE does not work. NNDatasetNormalize.getr(''TEMPLATE'') should be a NNDatasetNormalize element.' ...
						)
					assert( ...
						isa(dnorm_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						'NNDatasetNormalize TEMPLATE does not work. NNDatasetNormalize_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(dnorm.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						['NNDatasetNormalize TEMPLATE does not work. NNDatasetNormalize.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						dnorm.getr(prop).get('EL') == dnorm_template && dnorm.getr(prop).get('PROP') == prop && strcmp(dnorm.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						['NNDatasetNormalize TEMPLATE does not work. NNDatasetNormalize.getr(' TAG ') should be a Callback to dnorm_template.' TAG '.'] ...
						)
					assert( ...
						isa(dnorm_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
						['NNDatasetNormalize TEMPLATE does not work. NNDatasetNormalize_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(dnorm.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize TEMPLATE does not work. NNDatasetNormalize.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(dnorm_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
					['NNDatasetNormalize TEMPLATE does not work. NNDatasetNormalize_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dnorm = NNDatasetNormalize( ...
		NNDatasetNormalize.ELCLASS, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.NAME, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.DESCRIPTION, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.TEMPLATE, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.TEMPLATE), ...
		NNDatasetNormalize.ID, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.ID), ...
		NNDatasetNormalize.LABEL, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.LABEL), ...
		NNDatasetNormalize.NOTES, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.NOTES), ...
		NNDatasetNormalize.TOSTRING, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.D, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.D), ...
		NNDatasetNormalize.NORMALIZED_D, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.NORMALIZED_D) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'nndatasetnormalize_to_be_erased.b2'];
	 
	Element.save(dnorm, filename)
	 
	dnorm_loaded = Element.load(filename);
	 
	assert( ...
		isequal(dnorm.copy(), dnorm_loaded), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'NNDatasetNormalize.save(dnorm) and/or NNDatasetNormalize.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dnorm = NNDatasetNormalize( ...
		NNDatasetNormalize.ELCLASS, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.NAME, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.DESCRIPTION, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.TEMPLATE, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.TEMPLATE), ...
		NNDatasetNormalize.ID, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.ID), ...
		NNDatasetNormalize.LABEL, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.LABEL), ...
		NNDatasetNormalize.NOTES, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.NOTES), ...
		NNDatasetNormalize.TOSTRING, NNDatasetNormalize.getNoValue(), ...
		NNDatasetNormalize.D, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.D), ...
		NNDatasetNormalize.NORMALIZED_D, NNDatasetNormalize.getPropDefault(NNDatasetNormalize.NORMALIZED_D) ...
		);
	 
	[json, struct, el_list] = encodeJSON(dnorm);
	[dnorm_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(dnorm_dec ~= dnorm, ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		'NNDatasetNormalize.encodeJSON() or NNDatasetNormalize.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) NNDatasetNormalize.getPropFormat(prop), num2cell(NNDatasetNormalize.getProps())) == Format.HANDLE) && all(cellfun(@(prop) NNDatasetNormalize.getPropFormat(prop), num2cell(NNDatasetNormalize.getProps())) == Format.NET)
		assert(isequal(dnorm_dec, dnorm), ...
			[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
			'NNDatasetNormalize.encodeJSON() or NNDatasetNormalize.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':NNDatasetNormalize:' BRAPH2.FAIL_TEST], ...
		[' When testing NNDatasetNormalize no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 13: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

