%TEST_NNAUTOENCODER

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	nnvae = NNAutoencoder();
	 
	% get('ELCLASS')
	if isa(NNAutoencoder, 'ConcreteElement')
		assert(strcmp(NNAutoencoder().get('ELCLASS'), 'NNAutoencoder'), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNAutoencoder().get(''ELCLASS'') should return ''NNAutoencoder''.')
	end
	 
	% getBuild()
	assert(NNAutoencoder.getBuild() == 1 && NNAutoencoder.getBuild() > 0, ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNAutoencoder.getBuild() should return the NNAutoencoder build number.')
	assert(nnvae.getBuild() == 1 && nnvae.getBuild() > 0 , ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'nnvae.getBuild() should return the NNAutoencoder build number.')
	assert(Element.getBuild(nnvae) == 1 && Element.getBuild(nnvae) > 0, ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(nnvae) should return the NNAutoencoder build number.')
	assert(Element.getBuild('NNAutoencoder') == 1 && Element.getBuild('NNAutoencoder') > 0, ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''NNAutoencoder'') should return the NNAutoencoder build number.')
	 
	% getClass()
	assert(strcmp(NNAutoencoder.getClass(), 'NNAutoencoder'), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNAutoencoder.getClass() should return ''NNAutoencoder''.')
	assert(strcmp(nnvae.getClass(), 'NNAutoencoder'), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'nnvae.getClass() should return ''NNAutoencoder''.')
	assert(strcmp(Element.getClass(nnvae), 'NNAutoencoder'), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(nnvae) should return ''NNAutoencoder''.')
	assert(strcmp(Element.getClass('NNAutoencoder'), 'NNAutoencoder'), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''NNAutoencoder'') should return ''NNAutoencoder''.')
	 
	% getSubclasses()
	assert(isequal(NNAutoencoder.getSubclasses(), subclasses('NNAutoencoder', [], [], true)), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNAutoencoder.getSubclasses() should return the same result as subclasses(''NNAutoencoder'', [], [], true).')
	assert(isequal(nnvae.getSubclasses(), subclasses('NNAutoencoder', [], [], true)), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''NNAutoencoder'', [], [], true).')
	assert(isequal(Element.getSubclasses(nnvae), subclasses('NNAutoencoder', [], [], true)), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(nnvae) should return the same result as subclasses(''NNAutoencoder'', [], [], true).')
	assert(isequal(Element.getSubclasses('NNAutoencoder'), subclasses('NNAutoencoder', [], [], true)), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''NNAutoencoder'') should return the same result as subclasses(''NNAutoencoder'', [], [], true).')
	 
	% getProps()
	assert(isempty(NNAutoencoder.getProps()) || isequal(NNAutoencoder.getProps(), 1:1:length(NNAutoencoder.getProps())), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNAutoencoder.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNAutoencoder.getProps()) || isequal(nnvae.getProps(), 1:1:length(NNAutoencoder.getProps())), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'nnvae.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNAutoencoder.getProps()) || isequal(Element.getProps(nnvae), 1:1:length(NNAutoencoder.getProps())), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(nnvae) should return a row vector [1:1:N].')
	assert(isempty(NNAutoencoder.getProps()) || isequal(Element.getProps('NNAutoencoder'), 1:1:length(NNAutoencoder.getProps())), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNAutoencoder'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) NNAutoencoder.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNAutoencoder.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNAutoencoder.getProps())), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNAutoencoder.getProps(category) does not work.')
	tmp = cellfun(@(category) nnvae.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNAutoencoder.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNAutoencoder.getProps())), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'nnvae.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(nnvae, category), categories, 'UniformOutput', false);
	assert(isempty(NNAutoencoder.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNAutoencoder.getProps())), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(nnvae, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('NNAutoencoder', category), categories, 'UniformOutput', false);
	assert(isempty(NNAutoencoder.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNAutoencoder.getProps())), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNAutoencoder'', category) does not work.')
	 
	% getPropNumber()
	assert(NNAutoencoder.getPropNumber() == length(NNAutoencoder.getProps()), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNAutoencoder.getPropNumber() should return the number of properties.')
	assert(nnvae.getPropNumber() == length(NNAutoencoder.getProps()), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'nnvae.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(nnvae) == length(NNAutoencoder.getProps()), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(nnvae) should return the number of properties.')
	assert(Element.getPropNumber('NNAutoencoder') == length(NNAutoencoder.getProps()), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNAutoencoder'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) NNAutoencoder.getPropNumber(category), categories)) == NNAutoencoder.getPropNumber(), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNAutoencoder.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) nnvae.getPropNumber(category), categories)) == NNAutoencoder.getPropNumber(), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'nnvae.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(nnvae, category), categories)) == NNAutoencoder.getPropNumber(), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(nnvae, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('NNAutoencoder', category), categories)) == NNAutoencoder.getPropNumber(), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNAutoencoder'', category) does not work.')
	 
	% existsProp(prop)
	assert(~NNAutoencoder.existsProp(NaN), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNAutoencoder.existsProp(prop) does not work.')
	assert(~nnvae.existsProp(NaN), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'nnvae.existsProp(prop) does not work.')
	assert(~Element.existsProp(nnvae, NaN), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(nnvae, prop) does not work.')
	assert(~Element.existsProp('NNAutoencoder', NaN), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''NNAutoencoder'', prop) does not work.')
	 
	assert_with_error('NNAutoencoder.existsProp(NaN)', [BRAPH2.STR ':NNAutoencoder:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':NNAutoencoder:' BRAPH2.WRONG_INPUT], nnvae)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':NNAutoencoder:' BRAPH2.WRONG_INPUT], nnvae)
	assert_with_error('Element.existsProp(''NNAutoencoder'', NaN)', [BRAPH2.STR ':NNAutoencoder:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNAutoencoder.getPropNumber()
		assert(NNAutoencoder.existsProp(prop), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNAutoencoder.existsProp(prop) does not work.')
		assert(nnvae.existsProp(prop), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.existsProp(prop) does not work.')
		assert(Element.existsProp(nnvae, prop), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(nnvae, prop) does not work.')
		assert(Element.existsProp('NNAutoencoder', prop), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''NNAutoencoder'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~NNAutoencoder.existsTag(''), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNAutoencoder.existsTag(tag) does not work.')
	assert(~nnvae.existsTag(''), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'nnvae.existsTag(tag) does not work.')
	assert(~Element.existsTag(nnvae, ''), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(nnvae, tag) does not work.')
	assert(~Element.existsTag('NNAutoencoder', ''), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''NNAutoencoder'', tag) does not work.')
	 
	assert_with_error('NNAutoencoder.existsTag('''')', [BRAPH2.STR ':NNAutoencoder:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':NNAutoencoder:' BRAPH2.WRONG_INPUT], nnvae)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':NNAutoencoder:' BRAPH2.WRONG_INPUT], nnvae)
	assert_with_error('Element.existsTag(''NNAutoencoder'', '''')', [BRAPH2.STR ':NNAutoencoder:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNAutoencoder.getPropNumber()
		tag = nnvae.getPropTag(prop);
		assert(NNAutoencoder.existsTag(tag), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNAutoencoder.existsTag(tag) does not work.')
		assert(nnvae.existsTag(tag), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.existsTag(tag) does not work.')
		assert(Element.existsTag(nnvae, tag), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(nnvae, tga) does not work.')
		assert(Element.existsTag('NNAutoencoder', tag), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''NNAutoencoder'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:NNAutoencoder.getPropNumber()
		assert(NNAutoencoder.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNAutoencoder.getPropProp(prop) does not work.')
		assert(nnvae.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropProp(prop) does not work.')
		assert(Element.getPropProp(nnvae, prop) == prop, ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(nnvae, prop) does not work.')
		assert(Element.getPropProp('NNAutoencoder', prop) == prop, ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNAutoencoder'', prop) does not work.')
	 
		tag = nnvae.getPropTag(prop);
		assert(NNAutoencoder.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNAutoencoder.getPropProp(tag) does not work.')
		assert(nnvae.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropProp(tag) does not work.')
		assert(Element.getPropProp(nnvae, tag) == prop, ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(nnvae, tag) does not work.')
		assert(Element.getPropProp('NNAutoencoder', prop) == prop, ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNAutoencoder'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:NNAutoencoder.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		assert(strcmp(NNAutoencoder.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNAutoencoder.getPropTag(prop) does not work.')
		assert(strcmp(nnvae.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(nnvae, prop), tag), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(nnvae, prop) does not work.')
		assert(strcmp(Element.getPropTag('NNAutoencoder', prop), tag), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNAutoencoder'', prop) does not work.')
	 
		assert(strcmp(NNAutoencoder.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNAutoencoder.getPropTag(tag) does not work.')
		assert(strcmp(nnvae.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(nnvae, tag), tag), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(nnvae, tag) does not work.')
		assert(strcmp(Element.getPropTag('NNAutoencoder', prop), tag), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNAutoencoder'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:NNAutoencoder.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		assert(Category.existsCategory(NNAutoencoder.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNAutoencoder.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(nnvae.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nnvae, prop)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(nnvae, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nnvae, prop)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNAutoencoder'', prop) does not work.')
	 
		assert(Category.existsCategory(NNAutoencoder.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNAutoencoder.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(nnvae.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nnvae, tag)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(nnvae, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nnvae, tag)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNAutoencoder'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:NNAutoencoder.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		assert(Format.existsFormat(NNAutoencoder.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNAutoencoder.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(nnvae.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nnvae, prop)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(nnvae, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nnvae, prop)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNAutoencoder'', prop) does not work.')
	 
		assert(Format.existsFormat(NNAutoencoder.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNAutoencoder.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(nnvae.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nnvae, tag)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(nnvae, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nnvae, tag)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNAutoencoder'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:NNAutoencoder.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		assert(ischar(NNAutoencoder.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNAutoencoder.getPropDescription(prop) does not work.')
		assert(ischar(nnvae.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(nnvae, prop)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(nnvae, prop) does not work.')
		assert(ischar(Element.getPropDescription(nnvae, prop)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNAutoencoder'', prop) does not work.')
	 
		assert(ischar(NNAutoencoder.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNAutoencoder.getPropDescription(tag) does not work.')
		assert(ischar(nnvae.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(nnvae, tag)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(nnvae, tag) does not work.')
		assert(ischar(Element.getPropDescription(nnvae, tag)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNAutoencoder'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:NNAutoencoder.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		settings = NNAutoencoder.getPropSettings(prop);
		settings = nnvae.getPropSettings(prop);
		settings = Element.getPropSettings(nnvae, prop);
		settings = Element.getPropSettings('NNAutoencoder', prop);
	 
		settings = NNAutoencoder.getPropSettings(tag);
		settings = nnvae.getPropSettings(tag);
		settings = Element.getPropSettings(nnvae, tag);
		settings = Element.getPropSettings('NNAutoencoder', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:NNAutoencoder.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		default = NNAutoencoder.getPropDefault(prop);
		default = nnvae.getPropDefault(prop);
		default = Element.getPropDefault(nnvae, prop);
		default = Element.getPropDefault('NNAutoencoder', prop);
	 
		default = NNAutoencoder.getPropDefault(tag);
		default = nnvae.getPropDefault(tag);
		default = Element.getPropDefault(nnvae, tag);
		default = Element.getPropDefault('NNAutoencoder', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:NNAutoencoder.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		conditioned_default = NNAutoencoder.getPropDefaultConditioned(prop);
		conditioned_default = nnvae.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(nnvae, prop);
		conditioned_default = Element.getPropDefaultConditioned('NNAutoencoder', prop);
	 
		conditioned_default = NNAutoencoder.getPropDefaultConditioned(tag);
		conditioned_default = nnvae.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(nnvae, tag);
		conditioned_default = Element.getPropDefaultConditioned('NNAutoencoder', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:NNAutoencoder.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		assert(~NNAutoencoder.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNAutoencoder.checkProp(prop, value) does not work.')
		assert(~nnvae.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(nnvae, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nnvae, prop, value) does not work.')
		assert(~Element.checkProp('NNAutoencoder', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNAutoencoder'', prop, value) does not work.')
	 
		assert_with_error('NNAutoencoder.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNAutoencoder:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNAutoencoder:' BRAPH2.WRONG_INPUT], prop, nnvae)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNAutoencoder:' BRAPH2.WRONG_INPUT], prop, nnvae)
		assert_with_error('Element.checkProp(''NNAutoencoder'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNAutoencoder:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~NNAutoencoder.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNAutoencoder.checkProp(tag, value) does not work.')
		assert(~nnvae.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(nnvae, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nnvae, tag, value) does not work.')
		assert(~Element.checkProp('NNAutoencoder', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNAutoencoder'', tag, value) does not work.')
	 
		assert_with_error('NNAutoencoder.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNAutoencoder:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNAutoencoder:' BRAPH2.WRONG_INPUT], tag, nnvae)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNAutoencoder:' BRAPH2.WRONG_INPUT], tag, nnvae)
		assert_with_error('Element.checkProp(''NNAutoencoder'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNAutoencoder:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(NNAutoencoder.checkProp(prop, Element.getPropDefaultConditioned(NNAutoencoder, prop)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNAutoencoder.checkProp(prop, <conditioned default value>) does not work.')
		assert(nnvae.checkProp(prop, Element.getPropDefaultConditioned(NNAutoencoder, prop)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(nnvae, prop, Element.getPropDefaultConditioned(NNAutoencoder, prop)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nnvae, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNAutoencoder', prop, Element.getPropDefaultConditioned(NNAutoencoder, prop)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNAutoencoder'', prop, <conditioned default value>) does not work.')
	 
		assert(NNAutoencoder.checkProp(tag, Element.getPropDefaultConditioned(NNAutoencoder, prop)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNAutoencoder.checkProp(tag, <conditioned default value>) does not work.')
		assert(nnvae.checkProp(tag, Element.getPropDefaultConditioned(NNAutoencoder, prop)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(nnvae, tag, Element.getPropDefaultConditioned(NNAutoencoder, prop)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nnvae, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNAutoencoder', tag, Element.getPropDefaultConditioned(NNAutoencoder, prop)), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNAutoencoder'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNAutoencoder( ...
		NNAutoencoder.ELCLASS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.NAME, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.DESCRIPTION, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TEMPLATE, NNAutoencoder.getPropDefault(NNAutoencoder.TEMPLATE), ...
		NNAutoencoder.ID, NNAutoencoder.getPropDefault(NNAutoencoder.ID), ...
		NNAutoencoder.LABEL, NNAutoencoder.getPropDefault(NNAutoencoder.LABEL), ...
		NNAutoencoder.NOTES, NNAutoencoder.getPropDefault(NNAutoencoder.NOTES), ...
		NNAutoencoder.TOSTRING, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.D, NNAutoencoder.getPropDefault(NNAutoencoder.D), ...
		NNAutoencoder.DP_CLASSES, NNAutoencoder.getPropDefault(NNAutoencoder.DP_CLASSES), ...
		NNAutoencoder.EPOCHS, NNAutoencoder.getPropDefault(NNAutoencoder.EPOCHS), ...
		NNAutoencoder.BATCH, NNAutoencoder.getPropDefault(NNAutoencoder.BATCH), ...
		NNAutoencoder.SHUFFLE, NNAutoencoder.getPropDefault(NNAutoencoder.SHUFFLE), ...
		NNAutoencoder.SOLVER, NNAutoencoder.getPropDefault(NNAutoencoder.SOLVER), ...
		NNAutoencoder.MODEL, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.INPUTS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TARGETS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TRAIN, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.VERBOSE, NNAutoencoder.getPropDefault(NNAutoencoder.VERBOSE), ...
		NNAutoencoder.PLOT_TRAINING, NNAutoencoder.getPropDefault(NNAutoencoder.PLOT_TRAINING), ...
		NNAutoencoder.PREDICT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LEARN_RATE, NNAutoencoder.getPropDefault(NNAutoencoder.LEARN_RATE), ...
		NNAutoencoder.NUM_LATENT_REP, NNAutoencoder.getPropDefault(NNAutoencoder.NUM_LATENT_REP), ...
		NNAutoencoder.SIZE_INPUT, NNAutoencoder.getPropDefault(NNAutoencoder.SIZE_INPUT), ...
		NNAutoencoder.ITERATION_DIM, NNAutoencoder.getPropDefault(NNAutoencoder.ITERATION_DIM), ...
		NNAutoencoder.NUM_MBQ_OUTPUT, NNAutoencoder.getPropDefault(NNAutoencoder.NUM_MBQ_OUTPUT), ...
		NNAutoencoder.MINIBATCH_FORMAT_INPUT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.MINIBATCH_FORMAT_TARGET, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.ENCODER, NNAutoencoder.getPropDefault(NNAutoencoder.ENCODER), ...
		NNAutoencoder.DECODER, NNAutoencoder.getPropDefault(NNAutoencoder.DECODER), ...
		NNAutoencoder.MBQ, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LOSS_FN, NNAutoencoder.getNoValue() ...
		);
	 
	for prop = 1:1:NNAutoencoder.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNAutoencoder.getPropTag(prop));
		switch NNAutoencoder.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					nnvae.getr(prop) == NNAutoencoder.getNoValue(), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNAutoencoder.getCategoryName(NNAutoencoder.getPropCategory(prop)) ', NNAutoencoder.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNAutoencoder.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					nnvae.getr(TAG) == NNAutoencoder.getNoValue(), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNAutoencoder.getCategoryName(NNAutoencoder.getPropCategory(prop)) ', NNAutoencoder.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNAutoencoder.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(nnvae.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(nnvae.getPropSettings(prop))
					assert( ...
						nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.get(prop)), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						['NNAutoencoder.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.get(prop), nnvae.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						['NNAutoencoder.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					nnvae.getr(prop) == NNAutoencoder.getNoValue(), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNAutoencoder.getCategoryName(NNAutoencoder.getPropCategory(prop)) ', NNAutoencoder.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNAutoencoder.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					nnvae.getr(TAG) == NNAutoencoder.getNoValue(), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNAutoencoder.getCategoryName(NNAutoencoder.getPropCategory(prop)) ', NNAutoencoder.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNAutoencoder.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':NNAutoencoder']);
				assert( ...
					~isa(nnvae.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(nnvae.getPropSettings(prop))
					assert( ...
						nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.get(prop)), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						['NNAutoencoder.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.get(prop), nnvae.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						['NNAutoencoder.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(nnvae.getr(prop), NNAutoencoder.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by NNAutoencoder.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNAutoencoder.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(nnvae.getr(TAG), NNAutoencoder.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.getr(' TAG ') must be inizialized to its default value ' ...
					'given by NNAutoencoder.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNAutoencoder.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNAutoencoder( ...
		NNAutoencoder.ELCLASS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.NAME, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.DESCRIPTION, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TEMPLATE, NNAutoencoder.getPropDefault(NNAutoencoder.TEMPLATE), ...
		NNAutoencoder.ID, NNAutoencoder.getPropDefault(NNAutoencoder.ID), ...
		NNAutoencoder.LABEL, NNAutoencoder.getPropDefault(NNAutoencoder.LABEL), ...
		NNAutoencoder.NOTES, NNAutoencoder.getPropDefault(NNAutoencoder.NOTES), ...
		NNAutoencoder.TOSTRING, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.D, NNAutoencoder.getPropDefault(NNAutoencoder.D), ...
		NNAutoencoder.DP_CLASSES, NNAutoencoder.getPropDefault(NNAutoencoder.DP_CLASSES), ...
		NNAutoencoder.EPOCHS, NNAutoencoder.getPropDefault(NNAutoencoder.EPOCHS), ...
		NNAutoencoder.BATCH, NNAutoencoder.getPropDefault(NNAutoencoder.BATCH), ...
		NNAutoencoder.SHUFFLE, NNAutoencoder.getPropDefault(NNAutoencoder.SHUFFLE), ...
		NNAutoencoder.SOLVER, NNAutoencoder.getPropDefault(NNAutoencoder.SOLVER), ...
		NNAutoencoder.MODEL, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.INPUTS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TARGETS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TRAIN, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.VERBOSE, NNAutoencoder.getPropDefault(NNAutoencoder.VERBOSE), ...
		NNAutoencoder.PLOT_TRAINING, NNAutoencoder.getPropDefault(NNAutoencoder.PLOT_TRAINING), ...
		NNAutoencoder.PREDICT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LEARN_RATE, NNAutoencoder.getPropDefault(NNAutoencoder.LEARN_RATE), ...
		NNAutoencoder.NUM_LATENT_REP, NNAutoencoder.getPropDefault(NNAutoencoder.NUM_LATENT_REP), ...
		NNAutoencoder.SIZE_INPUT, NNAutoencoder.getPropDefault(NNAutoencoder.SIZE_INPUT), ...
		NNAutoencoder.ITERATION_DIM, NNAutoencoder.getPropDefault(NNAutoencoder.ITERATION_DIM), ...
		NNAutoencoder.NUM_MBQ_OUTPUT, NNAutoencoder.getPropDefault(NNAutoencoder.NUM_MBQ_OUTPUT), ...
		NNAutoencoder.MINIBATCH_FORMAT_INPUT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.MINIBATCH_FORMAT_TARGET, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.ENCODER, NNAutoencoder.getPropDefault(NNAutoencoder.ENCODER), ...
		NNAutoencoder.DECODER, NNAutoencoder.getPropDefault(NNAutoencoder.DECODER), ...
		NNAutoencoder.MBQ, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LOSS_FN, NNAutoencoder.getNoValue() ...
		);
	 
	for prop = 1:1:NNAutoencoder.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNAutoencoder.getPropTag(prop));
		switch NNAutoencoder.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(nnvae.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(nnvae.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(nnvae.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(nnvae.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.getr(prop),nnvae.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNAutoencoder']);
				assert( ...
					~isa(nnvae.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(nnvae.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNAutoencoder']);
	% 			assert( ...
	% 				~isa(nnvae.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
	% 				['NNAutoencoder.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(nnvae.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
	% 				['NNAutoencoder.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.getr(prop),nnvae.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
	% 				['NNAutoencoder.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':NNAutoencoder']);
				assert( ...
					~isa(nnvae.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(nnvae.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(nnvae.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(nnvae.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.getr(prop),nnvae.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if nnvae.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:NNAutoencoder');
					delete(ancestor(nnvae.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(NNAutoencoder.getProps(Category.RESULT))
		for prop = 1:1:NNAutoencoder.getPropNumber()
	 
			% excluded props
			if any(prop == [])
				continue
			end
	 
			switch NNAutoencoder.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						nnvae.isLocked(prop), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						['NNAutoencoder.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~nnvae.isLocked(prop), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						['NNAutoencoder.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNAutoencoder();
	 
	for prop = 1:1:NNAutoencoder.getPropNumber()
		TAG = upper(NNAutoencoder.getPropTag(prop));
		assert( ...
			~nnvae.isLocked(prop), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			['NNAutoencoder.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~nnvae.isLocked(TAG), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			['NNAutoencoder.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	nnvae.lock()
	 
	for prop = 1:1:NNAutoencoder.getPropNumber()
		switch NNAutoencoder.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					nnvae.isLocked(prop), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~nnvae.isLocked(prop), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNAutoencoder();
	 
	warning_backup = warning('off', 'BRAPH2:NNAutoencoder');
	for prop = 1:1:NNAutoencoder.getPropNumber()
		nnvae.lock(prop)
		switch NNAutoencoder.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					nnvae.isLocked(prop), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~nnvae.isLocked(prop), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNAutoencoder();
	 
	for prop = 1:1:NNAutoencoder.getPropNumber()
		TAG = upper(NNAutoencoder.getPropTag(prop));
		assert( ...
			nnvae.isChecked(prop), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			['NNAutoencoder.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			nnvae.isChecked(TAG), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			['NNAutoencoder.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	nnvae.unchecked()
	 
	for prop = 1:1:NNAutoencoder.getPropNumber()
		assert( ...
			~nnvae.isChecked(prop), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			['NNAutoencoder.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	nnvae.checked()
	 
	for prop = 1:1:NNAutoencoder.getPropNumber()
		assert( ...
			nnvae.isChecked(prop), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			['NNAutoencoder.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic NNAutoencoder
	nnvae_0 = NNAutoencoder( ...
		NNAutoencoder.ELCLASS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.NAME, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.DESCRIPTION, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TEMPLATE, NNAutoencoder.getPropDefault(NNAutoencoder.TEMPLATE), ...
		NNAutoencoder.ID, NNAutoencoder.getPropDefault(NNAutoencoder.ID), ...
		NNAutoencoder.LABEL, NNAutoencoder.getPropDefault(NNAutoencoder.LABEL), ...
		NNAutoencoder.NOTES, NNAutoencoder.getPropDefault(NNAutoencoder.NOTES), ...
		NNAutoencoder.TOSTRING, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.D, NNAutoencoder.getPropDefault(NNAutoencoder.D), ...
		NNAutoencoder.DP_CLASSES, NNAutoencoder.getPropDefault(NNAutoencoder.DP_CLASSES), ...
		NNAutoencoder.EPOCHS, NNAutoencoder.getPropDefault(NNAutoencoder.EPOCHS), ...
		NNAutoencoder.BATCH, NNAutoencoder.getPropDefault(NNAutoencoder.BATCH), ...
		NNAutoencoder.SHUFFLE, NNAutoencoder.getPropDefault(NNAutoencoder.SHUFFLE), ...
		NNAutoencoder.SOLVER, NNAutoencoder.getPropDefault(NNAutoencoder.SOLVER), ...
		NNAutoencoder.MODEL, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.INPUTS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TARGETS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TRAIN, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.VERBOSE, NNAutoencoder.getPropDefault(NNAutoencoder.VERBOSE), ...
		NNAutoencoder.PLOT_TRAINING, NNAutoencoder.getPropDefault(NNAutoencoder.PLOT_TRAINING), ...
		NNAutoencoder.PREDICT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LEARN_RATE, NNAutoencoder.getPropDefault(NNAutoencoder.LEARN_RATE), ...
		NNAutoencoder.NUM_LATENT_REP, NNAutoencoder.getPropDefault(NNAutoencoder.NUM_LATENT_REP), ...
		NNAutoencoder.SIZE_INPUT, NNAutoencoder.getPropDefault(NNAutoencoder.SIZE_INPUT), ...
		NNAutoencoder.ITERATION_DIM, NNAutoencoder.getPropDefault(NNAutoencoder.ITERATION_DIM), ...
		NNAutoencoder.NUM_MBQ_OUTPUT, NNAutoencoder.getPropDefault(NNAutoencoder.NUM_MBQ_OUTPUT), ...
		NNAutoencoder.MINIBATCH_FORMAT_INPUT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.MINIBATCH_FORMAT_TARGET, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.ENCODER, NNAutoencoder.getPropDefault(NNAutoencoder.ENCODER), ...
		NNAutoencoder.DECODER, NNAutoencoder.getPropDefault(NNAutoencoder.DECODER), ...
		NNAutoencoder.MBQ, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LOSS_FN, NNAutoencoder.getNoValue() ...
		);
	 
	% NNAutoencoder with 1st callbacks
	nnvae_1 = NNAutoencoder( ...
		NNAutoencoder.ELCLASS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.NAME, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.DESCRIPTION, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TEMPLATE, nnvae_0.getCallback(4), ..., ...
		NNAutoencoder.ID, nnvae_0.getCallback(5), ..., ...
		NNAutoencoder.LABEL, NNAutoencoder.getPropDefault(NNAutoencoder.LABEL), ...
		NNAutoencoder.NOTES, NNAutoencoder.getPropDefault(NNAutoencoder.NOTES), ...
		NNAutoencoder.TOSTRING, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.D, nnvae_0.getCallback(9), ..., ...
		NNAutoencoder.DP_CLASSES, nnvae_0.getCallback(10), ..., ...
		NNAutoencoder.EPOCHS, nnvae_0.getCallback(11), ..., ...
		NNAutoencoder.BATCH, nnvae_0.getCallback(12), ..., ...
		NNAutoencoder.SHUFFLE, nnvae_0.getCallback(13), ..., ...
		NNAutoencoder.SOLVER, nnvae_0.getCallback(14), ..., ...
		NNAutoencoder.MODEL, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.INPUTS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TARGETS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TRAIN, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.VERBOSE, nnvae_0.getCallback(19), ..., ...
		NNAutoencoder.PLOT_TRAINING, NNAutoencoder.getPropDefault(NNAutoencoder.PLOT_TRAINING), ...
		NNAutoencoder.PREDICT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LEARN_RATE, nnvae_0.getCallback(22), ..., ...
		NNAutoencoder.NUM_LATENT_REP, nnvae_0.getCallback(23), ..., ...
		NNAutoencoder.SIZE_INPUT, nnvae_0.getCallback(24), ..., ...
		NNAutoencoder.ITERATION_DIM, nnvae_0.getCallback(25), ..., ...
		NNAutoencoder.NUM_MBQ_OUTPUT, nnvae_0.getCallback(26), ..., ...
		NNAutoencoder.MINIBATCH_FORMAT_INPUT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.MINIBATCH_FORMAT_TARGET, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.ENCODER, nnvae_0.getCallback(29), ..., ...
		NNAutoencoder.DECODER, nnvae_0.getCallback(30), ..., ...
		NNAutoencoder.MBQ, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LOSS_FN, NNAutoencoder.getNoValue() ...
		);
	 
	prop_number = NNAutoencoder.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNAutoencoder.getPropTag(prop));
		switch NNAutoencoder.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(nnvae_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(nnvae_1.get(prop), nnvae_0.get(prop)) && ~isa(nnvae_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(nnvae_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNAutoencoder with 2nd callbacks
	nnvae_2 = NNAutoencoder( ...
		NNAutoencoder.ELCLASS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.NAME, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.DESCRIPTION, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TEMPLATE, nnvae_1.getCallback(4), ..., ...
		NNAutoencoder.ID, nnvae_1.getCallback(5), ..., ...
		NNAutoencoder.LABEL, NNAutoencoder.getPropDefault(NNAutoencoder.LABEL), ...
		NNAutoencoder.NOTES, NNAutoencoder.getPropDefault(NNAutoencoder.NOTES), ...
		NNAutoencoder.TOSTRING, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.D, nnvae_1.getCallback(9), ..., ...
		NNAutoencoder.DP_CLASSES, nnvae_1.getCallback(10), ..., ...
		NNAutoencoder.EPOCHS, nnvae_1.getCallback(11), ..., ...
		NNAutoencoder.BATCH, nnvae_1.getCallback(12), ..., ...
		NNAutoencoder.SHUFFLE, nnvae_1.getCallback(13), ..., ...
		NNAutoencoder.SOLVER, nnvae_1.getCallback(14), ..., ...
		NNAutoencoder.MODEL, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.INPUTS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TARGETS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TRAIN, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.VERBOSE, nnvae_1.getCallback(19), ..., ...
		NNAutoencoder.PLOT_TRAINING, NNAutoencoder.getPropDefault(NNAutoencoder.PLOT_TRAINING), ...
		NNAutoencoder.PREDICT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LEARN_RATE, nnvae_1.getCallback(22), ..., ...
		NNAutoencoder.NUM_LATENT_REP, nnvae_1.getCallback(23), ..., ...
		NNAutoencoder.SIZE_INPUT, nnvae_1.getCallback(24), ..., ...
		NNAutoencoder.ITERATION_DIM, nnvae_1.getCallback(25), ..., ...
		NNAutoencoder.NUM_MBQ_OUTPUT, nnvae_1.getCallback(26), ..., ...
		NNAutoencoder.MINIBATCH_FORMAT_INPUT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.MINIBATCH_FORMAT_TARGET, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.ENCODER, nnvae_1.getCallback(29), ..., ...
		NNAutoencoder.DECODER, nnvae_1.getCallback(30), ..., ...
		NNAutoencoder.MBQ, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LOSS_FN, NNAutoencoder.getNoValue() ...
		);
	 
	prop_number = NNAutoencoder.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNAutoencoder.getPropTag(prop));
		switch NNAutoencoder.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(nnvae_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(nnvae_2.get(prop), nnvae_0.get(prop)) && ~isa(nnvae_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(nnvae_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNAutoencoder with 3rd callbacks
	nnvae_3 = NNAutoencoder( ...
		NNAutoencoder.ELCLASS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.NAME, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.DESCRIPTION, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TEMPLATE, nnvae_2.getCallback(4), ..., ...
		NNAutoencoder.ID, nnvae_2.getCallback(5), ..., ...
		NNAutoencoder.LABEL, NNAutoencoder.getPropDefault(NNAutoencoder.LABEL), ...
		NNAutoencoder.NOTES, NNAutoencoder.getPropDefault(NNAutoencoder.NOTES), ...
		NNAutoencoder.TOSTRING, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.D, nnvae_2.getCallback(9), ..., ...
		NNAutoencoder.DP_CLASSES, nnvae_2.getCallback(10), ..., ...
		NNAutoencoder.EPOCHS, nnvae_2.getCallback(11), ..., ...
		NNAutoencoder.BATCH, nnvae_2.getCallback(12), ..., ...
		NNAutoencoder.SHUFFLE, nnvae_2.getCallback(13), ..., ...
		NNAutoencoder.SOLVER, nnvae_2.getCallback(14), ..., ...
		NNAutoencoder.MODEL, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.INPUTS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TARGETS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TRAIN, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.VERBOSE, nnvae_2.getCallback(19), ..., ...
		NNAutoencoder.PLOT_TRAINING, NNAutoencoder.getPropDefault(NNAutoencoder.PLOT_TRAINING), ...
		NNAutoencoder.PREDICT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LEARN_RATE, nnvae_2.getCallback(22), ..., ...
		NNAutoencoder.NUM_LATENT_REP, nnvae_2.getCallback(23), ..., ...
		NNAutoencoder.SIZE_INPUT, nnvae_2.getCallback(24), ..., ...
		NNAutoencoder.ITERATION_DIM, nnvae_2.getCallback(25), ..., ...
		NNAutoencoder.NUM_MBQ_OUTPUT, nnvae_2.getCallback(26), ..., ...
		NNAutoencoder.MINIBATCH_FORMAT_INPUT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.MINIBATCH_FORMAT_TARGET, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.ENCODER, nnvae_2.getCallback(29), ..., ...
		NNAutoencoder.DECODER, nnvae_2.getCallback(30), ..., ...
		NNAutoencoder.MBQ, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LOSS_FN, NNAutoencoder.getNoValue() ...
		);
	 
	prop_number = NNAutoencoder.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNAutoencoder.getPropTag(prop));
		switch NNAutoencoder.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(nnvae_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(nnvae_3.get(prop), nnvae_0.get(prop)) && ~isa(nnvae_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(nnvae_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	nnvae = NNAutoencoder();
	 
	nnvae_copy = nnvae.copy();
	 
	assert(nnvae_copy ~= nnvae, ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNAutoencoder.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(nnvae_copy, nnvae), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNAutoencoder.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:NNAutoencoder.getPropNumber()
		value = nnvae.getr(prop);
		value_copy = nnvae_copy.getr(prop);
		switch NNAutoencoder.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					'NNAutoencoder.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
							'NNAutoencoder.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
							'NNAutoencoder.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					nnvae_copy.isLocked(prop) == nnvae.isLocked(prop), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					'NNAutoencoder.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					nnvae_copy.isChecked(prop) == nnvae.isChecked(prop), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					'NNAutoencoder.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					nnvae_copy.getPropSeed(prop) == nnvae.getPropSeed(prop), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					'NNAutoencoder.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	nnvae = NNAutoencoder( ...
		NNAutoencoder.ELCLASS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.NAME, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.DESCRIPTION, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TEMPLATE, NNAutoencoder.getPropDefault(NNAutoencoder.TEMPLATE), ...
		NNAutoencoder.ID, NNAutoencoder.getPropDefault(NNAutoencoder.ID), ...
		NNAutoencoder.LABEL, NNAutoencoder.getPropDefault(NNAutoencoder.LABEL), ...
		NNAutoencoder.NOTES, NNAutoencoder.getPropDefault(NNAutoencoder.NOTES), ...
		NNAutoencoder.TOSTRING, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.D, NNAutoencoder.getPropDefault(NNAutoencoder.D), ...
		NNAutoencoder.DP_CLASSES, NNAutoencoder.getPropDefault(NNAutoencoder.DP_CLASSES), ...
		NNAutoencoder.EPOCHS, NNAutoencoder.getPropDefault(NNAutoencoder.EPOCHS), ...
		NNAutoencoder.BATCH, NNAutoencoder.getPropDefault(NNAutoencoder.BATCH), ...
		NNAutoencoder.SHUFFLE, NNAutoencoder.getPropDefault(NNAutoencoder.SHUFFLE), ...
		NNAutoencoder.SOLVER, NNAutoencoder.getPropDefault(NNAutoencoder.SOLVER), ...
		NNAutoencoder.MODEL, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.INPUTS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TARGETS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TRAIN, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.VERBOSE, NNAutoencoder.getPropDefault(NNAutoencoder.VERBOSE), ...
		NNAutoencoder.PLOT_TRAINING, NNAutoencoder.getPropDefault(NNAutoencoder.PLOT_TRAINING), ...
		NNAutoencoder.PREDICT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LEARN_RATE, NNAutoencoder.getPropDefault(NNAutoencoder.LEARN_RATE), ...
		NNAutoencoder.NUM_LATENT_REP, NNAutoencoder.getPropDefault(NNAutoencoder.NUM_LATENT_REP), ...
		NNAutoencoder.SIZE_INPUT, NNAutoencoder.getPropDefault(NNAutoencoder.SIZE_INPUT), ...
		NNAutoencoder.ITERATION_DIM, NNAutoencoder.getPropDefault(NNAutoencoder.ITERATION_DIM), ...
		NNAutoencoder.NUM_MBQ_OUTPUT, NNAutoencoder.getPropDefault(NNAutoencoder.NUM_MBQ_OUTPUT), ...
		NNAutoencoder.MINIBATCH_FORMAT_INPUT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.MINIBATCH_FORMAT_TARGET, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.ENCODER, NNAutoencoder.getPropDefault(NNAutoencoder.ENCODER), ...
		NNAutoencoder.DECODER, NNAutoencoder.getPropDefault(NNAutoencoder.DECODER), ...
		NNAutoencoder.MBQ, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LOSS_FN, NNAutoencoder.getNoValue() ...
		);
	 
	for prop = 1:1:NNAutoencoder.getPropNumber()
		if NNAutoencoder.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':NNAutoencoder']);
			% nnvae.memorize(prop);
			% warning(warning_backup)
		elseif NNAutoencoder.getPropCategory(prop) == Category.EVANESCENT && nnvae.getPropFormat(prop) == Format.HANDLE
			nnvae.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:NNAutoencoder');
			delete(ancestor(nnvae.get(prop), 'figure'))
			warning(warning_backup)
		else
			nnvae.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	nnvae_copy = nnvae.copy();
	 
	for prop = 1:1:NNAutoencoder.getPropNumber()
		value = nnvae.getr(prop);
		value_copy = nnvae_copy.getr(prop);
		switch NNAutoencoder.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					'NNAutoencoder.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
							'NNAutoencoder.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
							'NNAutoencoder.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						nnvae_copy.isLocked(prop) == nnvae.isLocked(prop), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nnvae_copy.isChecked(prop) == nnvae.isChecked(prop), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nnvae_copy.getPropSeed(prop) == nnvae.getPropSeed(prop), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	nnvae_0 = NNAutoencoder( ...
		NNAutoencoder.ELCLASS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.NAME, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.DESCRIPTION, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TEMPLATE, NNAutoencoder.getPropDefault(NNAutoencoder.TEMPLATE), ...
		NNAutoencoder.ID, NNAutoencoder.getPropDefault(NNAutoencoder.ID), ...
		NNAutoencoder.LABEL, NNAutoencoder.getPropDefault(NNAutoencoder.LABEL), ...
		NNAutoencoder.NOTES, NNAutoencoder.getPropDefault(NNAutoencoder.NOTES), ...
		NNAutoencoder.TOSTRING, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.D, NNAutoencoder.getPropDefault(NNAutoencoder.D), ...
		NNAutoencoder.DP_CLASSES, NNAutoencoder.getPropDefault(NNAutoencoder.DP_CLASSES), ...
		NNAutoencoder.EPOCHS, NNAutoencoder.getPropDefault(NNAutoencoder.EPOCHS), ...
		NNAutoencoder.BATCH, NNAutoencoder.getPropDefault(NNAutoencoder.BATCH), ...
		NNAutoencoder.SHUFFLE, NNAutoencoder.getPropDefault(NNAutoencoder.SHUFFLE), ...
		NNAutoencoder.SOLVER, NNAutoencoder.getPropDefault(NNAutoencoder.SOLVER), ...
		NNAutoencoder.MODEL, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.INPUTS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TARGETS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TRAIN, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.VERBOSE, NNAutoencoder.getPropDefault(NNAutoencoder.VERBOSE), ...
		NNAutoencoder.PLOT_TRAINING, NNAutoencoder.getPropDefault(NNAutoencoder.PLOT_TRAINING), ...
		NNAutoencoder.PREDICT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LEARN_RATE, NNAutoencoder.getPropDefault(NNAutoencoder.LEARN_RATE), ...
		NNAutoencoder.NUM_LATENT_REP, NNAutoencoder.getPropDefault(NNAutoencoder.NUM_LATENT_REP), ...
		NNAutoencoder.SIZE_INPUT, NNAutoencoder.getPropDefault(NNAutoencoder.SIZE_INPUT), ...
		NNAutoencoder.ITERATION_DIM, NNAutoencoder.getPropDefault(NNAutoencoder.ITERATION_DIM), ...
		NNAutoencoder.NUM_MBQ_OUTPUT, NNAutoencoder.getPropDefault(NNAutoencoder.NUM_MBQ_OUTPUT), ...
		NNAutoencoder.MINIBATCH_FORMAT_INPUT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.MINIBATCH_FORMAT_TARGET, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.ENCODER, NNAutoencoder.getPropDefault(NNAutoencoder.ENCODER), ...
		NNAutoencoder.DECODER, NNAutoencoder.getPropDefault(NNAutoencoder.DECODER), ...
		NNAutoencoder.MBQ, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LOSS_FN, NNAutoencoder.getNoValue() ...
		);
	 
	nnvae = NNAutoencoder( ...
		NNAutoencoder.ELCLASS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.NAME, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.DESCRIPTION, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TEMPLATE, nnvae_0.getCallback(4), ..., ...
		NNAutoencoder.ID, nnvae_0.getCallback(5), ..., ...
		NNAutoencoder.LABEL, NNAutoencoder.getPropDefault(NNAutoencoder.LABEL), ...
		NNAutoencoder.NOTES, NNAutoencoder.getPropDefault(NNAutoencoder.NOTES), ...
		NNAutoencoder.TOSTRING, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.D, nnvae_0.getCallback(9), ..., ...
		NNAutoencoder.DP_CLASSES, nnvae_0.getCallback(10), ..., ...
		NNAutoencoder.EPOCHS, nnvae_0.getCallback(11), ..., ...
		NNAutoencoder.BATCH, nnvae_0.getCallback(12), ..., ...
		NNAutoencoder.SHUFFLE, nnvae_0.getCallback(13), ..., ...
		NNAutoencoder.SOLVER, nnvae_0.getCallback(14), ..., ...
		NNAutoencoder.MODEL, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.INPUTS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TARGETS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TRAIN, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.VERBOSE, nnvae_0.getCallback(19), ..., ...
		NNAutoencoder.PLOT_TRAINING, NNAutoencoder.getPropDefault(NNAutoencoder.PLOT_TRAINING), ...
		NNAutoencoder.PREDICT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LEARN_RATE, nnvae_0.getCallback(22), ..., ...
		NNAutoencoder.NUM_LATENT_REP, nnvae_0.getCallback(23), ..., ...
		NNAutoencoder.SIZE_INPUT, nnvae_0.getCallback(24), ..., ...
		NNAutoencoder.ITERATION_DIM, nnvae_0.getCallback(25), ..., ...
		NNAutoencoder.NUM_MBQ_OUTPUT, nnvae_0.getCallback(26), ..., ...
		NNAutoencoder.MINIBATCH_FORMAT_INPUT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.MINIBATCH_FORMAT_TARGET, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.ENCODER, nnvae_0.getCallback(29), ..., ...
		NNAutoencoder.DECODER, nnvae_0.getCallback(30), ..., ...
		NNAutoencoder.MBQ, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LOSS_FN, NNAutoencoder.getNoValue() ...
		);
	 
	nnvae_copy = nnvae.copy();
	nnvae_0_copy = nnvae_copy.getr('ID').get('EL');
	 
	for prop = 1:1:NNAutoencoder.getPropNumber()
		value = nnvae.getr(prop);
		value_copy = nnvae_copy.getr(prop);
		switch NNAutoencoder.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					'NNAutoencoder.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
							'NNAutoencoder.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
							'NNAutoencoder.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == nnvae_0.getCallback(prop), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder.copy() does not work. The callback should be obtained from NNAutoencoder.getCallback().' ...
						)
					assert( ...
						value_copy == nnvae_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder.copy() does not work. The callback should be obtained from NNAutoencoder.getCallback().' ...
						)
				end
	 
					assert( ...
						nnvae_copy.isLocked(prop) == nnvae.isLocked(prop), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nnvae_copy.isChecked(prop) == nnvae.isChecked(prop), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nnvae_copy.getPropSeed(prop) == nnvae.getPropSeed(prop), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae_template = NNAutoencoder();
	nnvae = NNAutoencoder('TEMPLATE', nnvae_template);
	 
	for prop = 1:1:NNAutoencoder.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNAutoencoder.getPropTag(prop));
		switch NNAutoencoder.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == NNAutoencoder.TEMPLATE
					assert( ...
						isa(nnvae.getr(prop), 'NNAutoencoder'), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder TEMPLATE does not work. NNAutoencoder.getr(''TEMPLATE'') should be a NNAutoencoder element.' ...
						)
					assert( ...
						isa(nnvae_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNAutoencoder TEMPLATE does not work. NNAutoencoder_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(nnvae.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						['NNAutoencoder TEMPLATE does not work. NNAutoencoder.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						nnvae.getr(prop).get('EL') == nnvae_template && nnvae.getr(prop).get('PROP') == prop && strcmp(nnvae.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						['NNAutoencoder TEMPLATE does not work. NNAutoencoder.getr(' TAG ') should be a Callback to nnvae_template.' TAG '.'] ...
						)
					assert( ...
						isa(nnvae_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
						['NNAutoencoder TEMPLATE does not work. NNAutoencoder_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(nnvae.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder TEMPLATE does not work. NNAutoencoder.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(nnvae_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNAutoencoder TEMPLATE does not work. NNAutoencoder_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNAutoencoder( ...
		NNAutoencoder.ELCLASS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.NAME, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.DESCRIPTION, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TEMPLATE, NNAutoencoder.getPropDefault(NNAutoencoder.TEMPLATE), ...
		NNAutoencoder.ID, NNAutoencoder.getPropDefault(NNAutoencoder.ID), ...
		NNAutoencoder.LABEL, NNAutoencoder.getPropDefault(NNAutoencoder.LABEL), ...
		NNAutoencoder.NOTES, NNAutoencoder.getPropDefault(NNAutoencoder.NOTES), ...
		NNAutoencoder.TOSTRING, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.D, NNAutoencoder.getPropDefault(NNAutoencoder.D), ...
		NNAutoencoder.DP_CLASSES, NNAutoencoder.getPropDefault(NNAutoencoder.DP_CLASSES), ...
		NNAutoencoder.EPOCHS, NNAutoencoder.getPropDefault(NNAutoencoder.EPOCHS), ...
		NNAutoencoder.BATCH, NNAutoencoder.getPropDefault(NNAutoencoder.BATCH), ...
		NNAutoencoder.SHUFFLE, NNAutoencoder.getPropDefault(NNAutoencoder.SHUFFLE), ...
		NNAutoencoder.SOLVER, NNAutoencoder.getPropDefault(NNAutoencoder.SOLVER), ...
		NNAutoencoder.MODEL, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.INPUTS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TARGETS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TRAIN, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.VERBOSE, NNAutoencoder.getPropDefault(NNAutoencoder.VERBOSE), ...
		NNAutoencoder.PLOT_TRAINING, NNAutoencoder.getPropDefault(NNAutoencoder.PLOT_TRAINING), ...
		NNAutoencoder.PREDICT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LEARN_RATE, NNAutoencoder.getPropDefault(NNAutoencoder.LEARN_RATE), ...
		NNAutoencoder.NUM_LATENT_REP, NNAutoencoder.getPropDefault(NNAutoencoder.NUM_LATENT_REP), ...
		NNAutoencoder.SIZE_INPUT, NNAutoencoder.getPropDefault(NNAutoencoder.SIZE_INPUT), ...
		NNAutoencoder.ITERATION_DIM, NNAutoencoder.getPropDefault(NNAutoencoder.ITERATION_DIM), ...
		NNAutoencoder.NUM_MBQ_OUTPUT, NNAutoencoder.getPropDefault(NNAutoencoder.NUM_MBQ_OUTPUT), ...
		NNAutoencoder.MINIBATCH_FORMAT_INPUT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.MINIBATCH_FORMAT_TARGET, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.ENCODER, NNAutoencoder.getPropDefault(NNAutoencoder.ENCODER), ...
		NNAutoencoder.DECODER, NNAutoencoder.getPropDefault(NNAutoencoder.DECODER), ...
		NNAutoencoder.MBQ, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LOSS_FN, NNAutoencoder.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'nnautoencoder_to_be_erased.b2'];
	 
	Element.save(nnvae, filename)
	 
	nnvae_loaded = Element.load(filename);
	 
	assert( ...
		isequal(nnvae.copy(), nnvae_loaded), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNAutoencoder.save(nnvae) and/or NNAutoencoder.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNAutoencoder( ...
		NNAutoencoder.ELCLASS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.NAME, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.DESCRIPTION, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TEMPLATE, NNAutoencoder.getPropDefault(NNAutoencoder.TEMPLATE), ...
		NNAutoencoder.ID, NNAutoencoder.getPropDefault(NNAutoencoder.ID), ...
		NNAutoencoder.LABEL, NNAutoencoder.getPropDefault(NNAutoencoder.LABEL), ...
		NNAutoencoder.NOTES, NNAutoencoder.getPropDefault(NNAutoencoder.NOTES), ...
		NNAutoencoder.TOSTRING, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.D, NNAutoencoder.getPropDefault(NNAutoencoder.D), ...
		NNAutoencoder.DP_CLASSES, NNAutoencoder.getPropDefault(NNAutoencoder.DP_CLASSES), ...
		NNAutoencoder.EPOCHS, NNAutoencoder.getPropDefault(NNAutoencoder.EPOCHS), ...
		NNAutoencoder.BATCH, NNAutoencoder.getPropDefault(NNAutoencoder.BATCH), ...
		NNAutoencoder.SHUFFLE, NNAutoencoder.getPropDefault(NNAutoencoder.SHUFFLE), ...
		NNAutoencoder.SOLVER, NNAutoencoder.getPropDefault(NNAutoencoder.SOLVER), ...
		NNAutoencoder.MODEL, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.INPUTS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TARGETS, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.TRAIN, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.VERBOSE, NNAutoencoder.getPropDefault(NNAutoencoder.VERBOSE), ...
		NNAutoencoder.PLOT_TRAINING, NNAutoencoder.getPropDefault(NNAutoencoder.PLOT_TRAINING), ...
		NNAutoencoder.PREDICT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LEARN_RATE, NNAutoencoder.getPropDefault(NNAutoencoder.LEARN_RATE), ...
		NNAutoencoder.NUM_LATENT_REP, NNAutoencoder.getPropDefault(NNAutoencoder.NUM_LATENT_REP), ...
		NNAutoencoder.SIZE_INPUT, NNAutoencoder.getPropDefault(NNAutoencoder.SIZE_INPUT), ...
		NNAutoencoder.ITERATION_DIM, NNAutoencoder.getPropDefault(NNAutoencoder.ITERATION_DIM), ...
		NNAutoencoder.NUM_MBQ_OUTPUT, NNAutoencoder.getPropDefault(NNAutoencoder.NUM_MBQ_OUTPUT), ...
		NNAutoencoder.MINIBATCH_FORMAT_INPUT, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.MINIBATCH_FORMAT_TARGET, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.ENCODER, NNAutoencoder.getPropDefault(NNAutoencoder.ENCODER), ...
		NNAutoencoder.DECODER, NNAutoencoder.getPropDefault(NNAutoencoder.DECODER), ...
		NNAutoencoder.MBQ, NNAutoencoder.getNoValue(), ...
		NNAutoencoder.LOSS_FN, NNAutoencoder.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(nnvae);
	[nnvae_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(nnvae_dec ~= nnvae, ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNAutoencoder.encodeJSON() or NNAutoencoder.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) NNAutoencoder.getPropFormat(prop), num2cell(NNAutoencoder.getProps())) == Format.HANDLE) && all(cellfun(@(prop) NNAutoencoder.getPropFormat(prop), num2cell(NNAutoencoder.getProps())) == Format.NET)
		assert(isequal(nnvae_dec, nnvae), ...
			[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNAutoencoder.encodeJSON() or NNAutoencoder.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':NNAutoencoder:' BRAPH2.FAIL_TEST], ...
		[' When testing NNAutoencoder no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 13: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

