%% EXAMPLE_NNVAE_SPECTRUM
% Script example pipeline for NN Variational Autoencoders with Raman
% Spectrum Data

clear variables %#ok<*NASGU>

%% Load Spectra Dataset
dproc = NNDatasetProcess_RamanSpectra( ...
    'RAW_DATA_DIR', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_LightStress' filesep 'data'], ...
    'TRANSFORMATION_RULE', 'First derivative', ...
    'NORMALIZATION_RULE', 'Scale', ...
    'SCALE_FACTOR', 100, ...
    'TARGETS_TO_REMOVE', {'ps', 'loc1'});

d_sp = dproc.get('D');

% announce memorizing start
fprintf('Memorizing all dataset inputs (may take a few minutes) ...%s', newline);
d_sp.memorize('INPUTS');
fprintf('Finished memorizing all dataset inputs.%s', newline);

fprintf('Memorizing all dataset targets (may take a few minutes) ...%s', newline);
d_sp.memorize('TARGETS');
fprintf('Finished memorizing all dataset targets.%s', newline);

%% Train a Variational Autoencoder
nnvae = NNVariationalAutoencoderMLP('D', d_sp, 'EPOCHS', 10, 'BATCH', 32);
nnvae.get('TRAIN')

%% Evaluate and Produce Manuscript figures
nne = NNVariationalAutoencoderEvaluator_RS( ...
    'NN', nnvae, ...
    'D', d_sp, ...
    'DPROC', dproc, ...
    'IDX_LABEL_SPECIES', 1, ...
    'IDX_LABEL_STRESS', 2, ...
    'IDX_LABEL_LOCATION', 3, ...
    'STRESS_SEQ', {'WL', 'HL', 'LL', 'SH'}, ...
    'DIRECTORY_UTIL_R', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_LightStress' filesep 'utilities'], ...
    'DIRECTORY_ANALYSIS', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_LightStress' filesep 'analysis'], ...
    'DIRECTORY_FIG', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_LightStress']);

nne.memorize('LATENT_REP');
nne.get('PLOT_R_PALETTE');
nne.get('PLOT_R_LS_QNORM_MED');