%% EXAMPLE_NNVAE_SPECTRUM
% Script example pipeline for NN Variational Autoencoders with Raman
% Spectrum Data

clear variables %#ok<*NASGU>

%% Load Spectra Dataset
dproc = NNDatasetProcess_RamanSpectra( ...
    'RAW_DATA_DIR', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_BacterialStress' filesep 'data'], ...
    'TRANSFORMATION_RULE', 'First derivative', ...
    'NORMALIZATION_RULE', 'Scale', ...
    'SCALE_FACTOR', 100, ...
    'STRESS_SEQ', {'buf', 'inf'}, ...
    'KIND_SEQ', {'CS24hr', 'CS48hr'}, ...
    'LOCATION_SEQ', {'loc'}, ...
    'TARGETS_TO_REMOVE', {'ps'});

d_sp = dproc.get('D');

% announce memorizing start
fprintf('Memorizing all dataset inputs (may take a few minutes) ...%s', newline);
d_sp.memorize('INPUTS');
fprintf('Finished memorizing all dataset inputs.%s', newline);

fprintf('Memorizing all dataset targets (may take a few minutes) ...%s', newline);
d_sp.memorize('TARGETS');
fprintf('Finished memorizing all dataset targets.%s', newline);

%% Train a Variational Autoencoder
nnvae = NNVariationalAutoencoderMLP('D', d_sp, 'EPOCHS', 100, 'BATCH', 32);
nnvae.get('TRAIN')

%% Evaluate and Produce Manuscript figures
nne = NNVariationalAutoencoderEvaluator_RS( ...
    'NN', nnvae, ...
    'D', d_sp, ...
    'DPROC', dproc, ...
    'IDX_LABEL_KIND', 1, ...
    'IDX_LABEL_STRESS', 2, ...
    'IDX_LABEL_LOCATION', 3, ...
    'STRESS_SEQ', {'buf', 'inf'}, ...
    'STRESS_LABEL', {'buffer-infiltrated', 'pathogen-infiltrated'}, ...
    'STRESS_COLOUR', {'#4DBBD5FF', '#E64B35FF'}, ...
    'STRESS_SHAPE', {'square', 'circle'}, ...
    'DIRECTORY_UTIL_R', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'utilities'], ...
    'DIRECTORY_ANALYSIS', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_BacterialStress' filesep 'analysis'], ...
    'DIRECTORY_FIG', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_BacterialStress']);

nne.memorize('LATENT_REP');
nne.get('PLOT_R_PALETTE');
nne.get('PLOT_R_LS_QNORM_MED');

% % % %% Extended Data Fig. 1: Load Spectra Dataset 
% % % dproc = NNDatasetProcess_RamanSpectra( ...
% % %     'RAW_DATA_DIR', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_BacterialStress' filesep 'data_ext_fig_1'], ...
% % %     'TRANSFORMATION_RULE', 'First derivative', ...
% % %     'NORMALIZATION_RULE', 'Scale', ...
% % %     'SCALE_FACTOR', 100, ...
% % %     'STRESS_SEQ', {'pseudo', 'mock'}, ...
% % %     'KIND_SEQ', {'AB24hr', 'AB48hr', 'AB72hr'}, ...
% % %     'LOCATION_SEQ', {'loc'}, ...
% % %     'TARGETS_TO_REMOVE', {'ps'});
% % % 
% % % d_sp = dproc.get('D');
% % % 
% % % % announce memorizing start
% % % fprintf('Memorizing all dataset inputs (may take a few minutes) ...%s', newline);
% % % d_sp.memorize('INPUTS');
% % % fprintf('Finished memorizing all dataset inputs.%s', newline);
% % % 
% % % fprintf('Memorizing all dataset targets (may take a few minutes) ...%s', newline);
% % % d_sp.memorize('TARGETS');
% % % fprintf('Finished memorizing all dataset targets.%s', newline);
% % % 
% % % %% Train a Variational Autoencoder
% % % nnvae = NNVariationalAutoencoderMLP('D', d_sp, 'EPOCHS', 100, 'BATCH', 32);
% % % nnvae.get('TRAIN')
% % % 
% % % %% Evaluate and Produce Manuscript figures
% % % nne = NNVariationalAutoencoderEvaluator_RS( ...
% % %     'NN', nnvae, ...
% % %     'D', d_sp, ...
% % %     'DPROC', dproc, ...
% % %     'IDX_LABEL_KIND', 1, ...
% % %     'IDX_LABEL_STRESS', 2, ...
% % %     'IDX_LABEL_LOCATION', 3, ...
% % %     'STRESS_SEQ', {'pseudo', 'mock'}, ...
% % %     'STRESS_LABEL', {'pseudo-infiltrated', 'mock-infiltrated'}, ...
% % %     'STRESS_COLOUR', {'#4DBBD5FF', '#E64B35FF'}, ...
% % %     'STRESS_SHAPE', {'square', 'circle'}, ...
% % %     'DIRECTORY_UTIL_R', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'utilities'], ...
% % %     'DIRECTORY_ANALYSIS', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_BacterialStress' filesep 'analysis'], ...
% % %     'DIRECTORY_FIG', [fileparts(which('NNDatasetProcess_RamanSpectra')) filesep 'study_BacterialStress']);
% % % 
% % % nne.memorize('LATENT_REP');
% % % nne.get('PLOT_R_PALETTE');
% % % nne.get('PLOT_R_LS_QNORM_MED');