%TEST_NNDATASETPROCESS_SPECTRUMSIGNAL

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	dproc = NNDatasetProcess_SpectrumSignal();
	 
	% get('ELCLASS')
	if isa(NNDatasetProcess_SpectrumSignal, 'ConcreteElement')
		assert(strcmp(NNDatasetProcess_SpectrumSignal().get('ELCLASS'), 'NNDatasetProcess_SpectrumSignal'), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_SpectrumSignal().get(''ELCLASS'') should return ''NNDatasetProcess_SpectrumSignal''.')
	end
	 
	% getBuild()
	assert(NNDatasetProcess_SpectrumSignal.getBuild() == 1 && NNDatasetProcess_SpectrumSignal.getBuild() > 0, ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_SpectrumSignal.getBuild() should return the NNDatasetProcess_SpectrumSignal build number.')
	assert(dproc.getBuild() == 1 && dproc.getBuild() > 0 , ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'dproc.getBuild() should return the NNDatasetProcess_SpectrumSignal build number.')
	assert(Element.getBuild(dproc) == 1 && Element.getBuild(dproc) > 0, ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(dproc) should return the NNDatasetProcess_SpectrumSignal build number.')
	assert(Element.getBuild('NNDatasetProcess_SpectrumSignal') == 1 && Element.getBuild('NNDatasetProcess_SpectrumSignal') > 0, ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''NNDatasetProcess_SpectrumSignal'') should return the NNDatasetProcess_SpectrumSignal build number.')
	 
	% getClass()
	assert(strcmp(NNDatasetProcess_SpectrumSignal.getClass(), 'NNDatasetProcess_SpectrumSignal'), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_SpectrumSignal.getClass() should return ''NNDatasetProcess_SpectrumSignal''.')
	assert(strcmp(dproc.getClass(), 'NNDatasetProcess_SpectrumSignal'), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'dproc.getClass() should return ''NNDatasetProcess_SpectrumSignal''.')
	assert(strcmp(Element.getClass(dproc), 'NNDatasetProcess_SpectrumSignal'), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(dproc) should return ''NNDatasetProcess_SpectrumSignal''.')
	assert(strcmp(Element.getClass('NNDatasetProcess_SpectrumSignal'), 'NNDatasetProcess_SpectrumSignal'), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''NNDatasetProcess_SpectrumSignal'') should return ''NNDatasetProcess_SpectrumSignal''.')
	 
	% getSubclasses()
	assert(isequal(NNDatasetProcess_SpectrumSignal.getSubclasses(), subclasses('NNDatasetProcess_SpectrumSignal', [], [], true)), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_SpectrumSignal.getSubclasses() should return the same result as subclasses(''NNDatasetProcess_SpectrumSignal'', [], [], true).')
	assert(isequal(dproc.getSubclasses(), subclasses('NNDatasetProcess_SpectrumSignal', [], [], true)), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''NNDatasetProcess_SpectrumSignal'', [], [], true).')
	assert(isequal(Element.getSubclasses(dproc), subclasses('NNDatasetProcess_SpectrumSignal', [], [], true)), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(dproc) should return the same result as subclasses(''NNDatasetProcess_SpectrumSignal'', [], [], true).')
	assert(isequal(Element.getSubclasses('NNDatasetProcess_SpectrumSignal'), subclasses('NNDatasetProcess_SpectrumSignal', [], [], true)), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''NNDatasetProcess_SpectrumSignal'') should return the same result as subclasses(''NNDatasetProcess_SpectrumSignal'', [], [], true).')
	 
	% getProps()
	assert(isempty(NNDatasetProcess_SpectrumSignal.getProps()) || isequal(NNDatasetProcess_SpectrumSignal.getProps(), 1:1:length(NNDatasetProcess_SpectrumSignal.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_SpectrumSignal.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNDatasetProcess_SpectrumSignal.getProps()) || isequal(dproc.getProps(), 1:1:length(NNDatasetProcess_SpectrumSignal.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'dproc.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNDatasetProcess_SpectrumSignal.getProps()) || isequal(Element.getProps(dproc), 1:1:length(NNDatasetProcess_SpectrumSignal.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(dproc) should return a row vector [1:1:N].')
	assert(isempty(NNDatasetProcess_SpectrumSignal.getProps()) || isequal(Element.getProps('NNDatasetProcess_SpectrumSignal'), 1:1:length(NNDatasetProcess_SpectrumSignal.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNDatasetProcess_SpectrumSignal'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) NNDatasetProcess_SpectrumSignal.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNDatasetProcess_SpectrumSignal.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDatasetProcess_SpectrumSignal.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_SpectrumSignal.getProps(category) does not work.')
	tmp = cellfun(@(category) dproc.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNDatasetProcess_SpectrumSignal.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDatasetProcess_SpectrumSignal.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'dproc.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(dproc, category), categories, 'UniformOutput', false);
	assert(isempty(NNDatasetProcess_SpectrumSignal.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDatasetProcess_SpectrumSignal.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(dproc, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('NNDatasetProcess_SpectrumSignal', category), categories, 'UniformOutput', false);
	assert(isempty(NNDatasetProcess_SpectrumSignal.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDatasetProcess_SpectrumSignal.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNDatasetProcess_SpectrumSignal'', category) does not work.')
	 
	% getPropNumber()
	assert(NNDatasetProcess_SpectrumSignal.getPropNumber() == length(NNDatasetProcess_SpectrumSignal.getProps()), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_SpectrumSignal.getPropNumber() should return the number of properties.')
	assert(dproc.getPropNumber() == length(NNDatasetProcess_SpectrumSignal.getProps()), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'dproc.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(dproc) == length(NNDatasetProcess_SpectrumSignal.getProps()), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(dproc) should return the number of properties.')
	assert(Element.getPropNumber('NNDatasetProcess_SpectrumSignal') == length(NNDatasetProcess_SpectrumSignal.getProps()), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNDatasetProcess_SpectrumSignal'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) NNDatasetProcess_SpectrumSignal.getPropNumber(category), categories)) == NNDatasetProcess_SpectrumSignal.getPropNumber(), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_SpectrumSignal.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) dproc.getPropNumber(category), categories)) == NNDatasetProcess_SpectrumSignal.getPropNumber(), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'dproc.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(dproc, category), categories)) == NNDatasetProcess_SpectrumSignal.getPropNumber(), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(dproc, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('NNDatasetProcess_SpectrumSignal', category), categories)) == NNDatasetProcess_SpectrumSignal.getPropNumber(), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNDatasetProcess_SpectrumSignal'', category) does not work.')
	 
	% existsProp(prop)
	assert(~NNDatasetProcess_SpectrumSignal.existsProp(NaN), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_SpectrumSignal.existsProp(prop) does not work.')
	assert(~dproc.existsProp(NaN), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'dproc.existsProp(prop) does not work.')
	assert(~Element.existsProp(dproc, NaN), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(dproc, prop) does not work.')
	assert(~Element.existsProp('NNDatasetProcess_SpectrumSignal', NaN), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''NNDatasetProcess_SpectrumSignal'', prop) does not work.')
	 
	assert_with_error('NNDatasetProcess_SpectrumSignal.existsProp(NaN)', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.WRONG_INPUT], dproc)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.WRONG_INPUT], dproc)
	assert_with_error('Element.existsProp(''NNDatasetProcess_SpectrumSignal'', NaN)', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		assert(NNDatasetProcess_SpectrumSignal.existsProp(prop), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_SpectrumSignal.existsProp(prop) does not work.')
		assert(dproc.existsProp(prop), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'dproc.existsProp(prop) does not work.')
		assert(Element.existsProp(dproc, prop), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(dproc, prop) does not work.')
		assert(Element.existsProp('NNDatasetProcess_SpectrumSignal', prop), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''NNDatasetProcess_SpectrumSignal'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~NNDatasetProcess_SpectrumSignal.existsTag(''), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_SpectrumSignal.existsTag(tag) does not work.')
	assert(~dproc.existsTag(''), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'dproc.existsTag(tag) does not work.')
	assert(~Element.existsTag(dproc, ''), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(dproc, tag) does not work.')
	assert(~Element.existsTag('NNDatasetProcess_SpectrumSignal', ''), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''NNDatasetProcess_SpectrumSignal'', tag) does not work.')
	 
	assert_with_error('NNDatasetProcess_SpectrumSignal.existsTag('''')', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.WRONG_INPUT], dproc)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.WRONG_INPUT], dproc)
	assert_with_error('Element.existsTag(''NNDatasetProcess_SpectrumSignal'', '''')', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		tag = dproc.getPropTag(prop);
		assert(NNDatasetProcess_SpectrumSignal.existsTag(tag), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_SpectrumSignal.existsTag(tag) does not work.')
		assert(dproc.existsTag(tag), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'dproc.existsTag(tag) does not work.')
		assert(Element.existsTag(dproc, tag), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(dproc, tga) does not work.')
		assert(Element.existsTag('NNDatasetProcess_SpectrumSignal', tag), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''NNDatasetProcess_SpectrumSignal'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		assert(NNDatasetProcess_SpectrumSignal.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_SpectrumSignal.getPropProp(prop) does not work.')
		assert(dproc.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'dproc.getPropProp(prop) does not work.')
		assert(Element.getPropProp(dproc, prop) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(dproc, prop) does not work.')
		assert(Element.getPropProp('NNDatasetProcess_SpectrumSignal', prop) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNDatasetProcess_SpectrumSignal'', prop) does not work.')
	 
		tag = dproc.getPropTag(prop);
		assert(NNDatasetProcess_SpectrumSignal.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_SpectrumSignal.getPropProp(tag) does not work.')
		assert(dproc.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'dproc.getPropProp(tag) does not work.')
		assert(Element.getPropProp(dproc, tag) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(dproc, tag) does not work.')
		assert(Element.getPropProp('NNDatasetProcess_SpectrumSignal', prop) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNDatasetProcess_SpectrumSignal'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		tag = dproc.getPropTag(prop);
	 
		assert(strcmp(NNDatasetProcess_SpectrumSignal.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_SpectrumSignal.getPropTag(prop) does not work.')
		assert(strcmp(dproc.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'dproc.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(dproc, prop), tag), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(dproc, prop) does not work.')
		assert(strcmp(Element.getPropTag('NNDatasetProcess_SpectrumSignal', prop), tag), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNDatasetProcess_SpectrumSignal'', prop) does not work.')
	 
		assert(strcmp(NNDatasetProcess_SpectrumSignal.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_SpectrumSignal.getPropTag(tag) does not work.')
		assert(strcmp(dproc.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'dproc.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(dproc, tag), tag), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(dproc, tag) does not work.')
		assert(strcmp(Element.getPropTag('NNDatasetProcess_SpectrumSignal', prop), tag), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNDatasetProcess_SpectrumSignal'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		tag = dproc.getPropTag(prop);
	 
		assert(Category.existsCategory(NNDatasetProcess_SpectrumSignal.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_SpectrumSignal.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(dproc.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'dproc.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dproc, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(dproc, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dproc, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNDatasetProcess_SpectrumSignal'', prop) does not work.')
	 
		assert(Category.existsCategory(NNDatasetProcess_SpectrumSignal.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_SpectrumSignal.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(dproc.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'dproc.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dproc, tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(dproc, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dproc, tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNDatasetProcess_SpectrumSignal'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		tag = dproc.getPropTag(prop);
	 
		assert(Format.existsFormat(NNDatasetProcess_SpectrumSignal.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_SpectrumSignal.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(dproc.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'dproc.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dproc, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(dproc, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dproc, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNDatasetProcess_SpectrumSignal'', prop) does not work.')
	 
		assert(Format.existsFormat(NNDatasetProcess_SpectrumSignal.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_SpectrumSignal.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(dproc.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'dproc.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dproc, tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(dproc, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dproc, tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNDatasetProcess_SpectrumSignal'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		tag = dproc.getPropTag(prop);
	 
		assert(ischar(NNDatasetProcess_SpectrumSignal.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_SpectrumSignal.getPropDescription(prop) does not work.')
		assert(ischar(dproc.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'dproc.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(dproc, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(dproc, prop) does not work.')
		assert(ischar(Element.getPropDescription(dproc, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNDatasetProcess_SpectrumSignal'', prop) does not work.')
	 
		assert(ischar(NNDatasetProcess_SpectrumSignal.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_SpectrumSignal.getPropDescription(tag) does not work.')
		assert(ischar(dproc.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'dproc.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(dproc, tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(dproc, tag) does not work.')
		assert(ischar(Element.getPropDescription(dproc, tag)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNDatasetProcess_SpectrumSignal'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		tag = dproc.getPropTag(prop);
	 
		settings = NNDatasetProcess_SpectrumSignal.getPropSettings(prop);
		settings = dproc.getPropSettings(prop);
		settings = Element.getPropSettings(dproc, prop);
		settings = Element.getPropSettings('NNDatasetProcess_SpectrumSignal', prop);
	 
		settings = NNDatasetProcess_SpectrumSignal.getPropSettings(tag);
		settings = dproc.getPropSettings(tag);
		settings = Element.getPropSettings(dproc, tag);
		settings = Element.getPropSettings('NNDatasetProcess_SpectrumSignal', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		tag = dproc.getPropTag(prop);
	 
		default = NNDatasetProcess_SpectrumSignal.getPropDefault(prop);
		default = dproc.getPropDefault(prop);
		default = Element.getPropDefault(dproc, prop);
		default = Element.getPropDefault('NNDatasetProcess_SpectrumSignal', prop);
	 
		default = NNDatasetProcess_SpectrumSignal.getPropDefault(tag);
		default = dproc.getPropDefault(tag);
		default = Element.getPropDefault(dproc, tag);
		default = Element.getPropDefault('NNDatasetProcess_SpectrumSignal', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		tag = dproc.getPropTag(prop);
	 
		conditioned_default = NNDatasetProcess_SpectrumSignal.getPropDefaultConditioned(prop);
		conditioned_default = dproc.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(dproc, prop);
		conditioned_default = Element.getPropDefaultConditioned('NNDatasetProcess_SpectrumSignal', prop);
	 
		conditioned_default = NNDatasetProcess_SpectrumSignal.getPropDefaultConditioned(tag);
		conditioned_default = dproc.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(dproc, tag);
		conditioned_default = Element.getPropDefaultConditioned('NNDatasetProcess_SpectrumSignal', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		tag = dproc.getPropTag(prop);
	 
		assert(~NNDatasetProcess_SpectrumSignal.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_SpectrumSignal.checkProp(prop, value) does not work.')
		assert(~dproc.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'dproc.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(dproc, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dproc, prop, value) does not work.')
		assert(~Element.checkProp('NNDatasetProcess_SpectrumSignal', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDatasetProcess_SpectrumSignal'', prop, value) does not work.')
	 
		assert_with_error('NNDatasetProcess_SpectrumSignal.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.WRONG_INPUT], prop, dproc)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.WRONG_INPUT], prop, dproc)
		assert_with_error('Element.checkProp(''NNDatasetProcess_SpectrumSignal'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~NNDatasetProcess_SpectrumSignal.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_SpectrumSignal.checkProp(tag, value) does not work.')
		assert(~dproc.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'dproc.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(dproc, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dproc, tag, value) does not work.')
		assert(~Element.checkProp('NNDatasetProcess_SpectrumSignal', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDatasetProcess_SpectrumSignal'', tag, value) does not work.')
	 
		assert_with_error('NNDatasetProcess_SpectrumSignal.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.WRONG_INPUT], tag, dproc)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.WRONG_INPUT], tag, dproc)
		assert_with_error('Element.checkProp(''NNDatasetProcess_SpectrumSignal'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(NNDatasetProcess_SpectrumSignal.checkProp(prop, Element.getPropDefaultConditioned(NNDatasetProcess_SpectrumSignal, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_SpectrumSignal.checkProp(prop, <conditioned default value>) does not work.')
		assert(dproc.checkProp(prop, Element.getPropDefaultConditioned(NNDatasetProcess_SpectrumSignal, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'dproc.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(dproc, prop, Element.getPropDefaultConditioned(NNDatasetProcess_SpectrumSignal, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dproc, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNDatasetProcess_SpectrumSignal', prop, Element.getPropDefaultConditioned(NNDatasetProcess_SpectrumSignal, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDatasetProcess_SpectrumSignal'', prop, <conditioned default value>) does not work.')
	 
		assert(NNDatasetProcess_SpectrumSignal.checkProp(tag, Element.getPropDefaultConditioned(NNDatasetProcess_SpectrumSignal, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_SpectrumSignal.checkProp(tag, <conditioned default value>) does not work.')
		assert(dproc.checkProp(tag, Element.getPropDefaultConditioned(NNDatasetProcess_SpectrumSignal, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'dproc.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(dproc, tag, Element.getPropDefaultConditioned(NNDatasetProcess_SpectrumSignal, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dproc, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNDatasetProcess_SpectrumSignal', tag, Element.getPropDefaultConditioned(NNDatasetProcess_SpectrumSignal, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDatasetProcess_SpectrumSignal'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dproc = NNDatasetProcess_SpectrumSignal( ...
		NNDatasetProcess_SpectrumSignal.ELCLASS, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NAME, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.DESCRIPTION, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TEMPLATE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.TEMPLATE), ...
		NNDatasetProcess_SpectrumSignal.ID, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.ID), ...
		NNDatasetProcess_SpectrumSignal.LABEL, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.LABEL), ...
		NNDatasetProcess_SpectrumSignal.NOTES, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.NOTES), ...
		NNDatasetProcess_SpectrumSignal.TOSTRING, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.D, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.RAW_DATA_DIR, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.RAW_DATA_DIR), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_START, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.WAVELENGTH_START), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_END, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.WAVELENGTH_END), ...
		NNDatasetProcess_SpectrumSignal.TRANSFORMATION_RULE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.TRANSFORMATION_RULE), ...
		NNDatasetProcess_SpectrumSignal.NORMALIZATION_RULE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.NORMALIZATION_RULE), ...
		NNDatasetProcess_SpectrumSignal.SCALE_FACTOR, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.SCALE_FACTOR), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TRANSFORM_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NORMALIZE_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_LABELS, NNDatasetProcess_SpectrumSignal.getNoValue() ...
		);
	 
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNDatasetProcess_SpectrumSignal.getPropTag(prop));
		switch NNDatasetProcess_SpectrumSignal.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					dproc.getr(prop) == NNDatasetProcess_SpectrumSignal.getNoValue(), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDatasetProcess_SpectrumSignal.getCategoryName(NNDatasetProcess_SpectrumSignal.getPropCategory(prop)) ', NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					dproc.getr(TAG) == NNDatasetProcess_SpectrumSignal.getNoValue(), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDatasetProcess_SpectrumSignal.getCategoryName(NNDatasetProcess_SpectrumSignal.getPropCategory(prop)) ', NNDatasetProcess_SpectrumSignal.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDatasetProcess_SpectrumSignal.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(dproc.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(dproc.getPropSettings(prop))
					assert( ...
						dproc.checkFormat(dproc.getPropFormat(prop), dproc.get(prop)), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess_SpectrumSignal.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						dproc.checkFormat(dproc.getPropFormat(prop), dproc.get(prop), dproc.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess_SpectrumSignal.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					dproc.getr(prop) == NNDatasetProcess_SpectrumSignal.getNoValue(), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDatasetProcess_SpectrumSignal.getCategoryName(NNDatasetProcess_SpectrumSignal.getPropCategory(prop)) ', NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					dproc.getr(TAG) == NNDatasetProcess_SpectrumSignal.getNoValue(), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDatasetProcess_SpectrumSignal.getCategoryName(NNDatasetProcess_SpectrumSignal.getPropCategory(prop)) ', NNDatasetProcess_SpectrumSignal.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDatasetProcess_SpectrumSignal.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal']);
				assert( ...
					~isa(dproc.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(dproc.getPropSettings(prop))
					assert( ...
						dproc.checkFormat(dproc.getPropFormat(prop), dproc.get(prop)), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess_SpectrumSignal.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						dproc.checkFormat(dproc.getPropFormat(prop), dproc.get(prop), dproc.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess_SpectrumSignal.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(dproc.getr(prop), NNDatasetProcess_SpectrumSignal.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by NNDatasetProcess_SpectrumSignal.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(dproc.getr(TAG), NNDatasetProcess_SpectrumSignal.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.getr(' TAG ') must be inizialized to its default value ' ...
					'given by NNDatasetProcess_SpectrumSignal.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNDatasetProcess_SpectrumSignal.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dproc = NNDatasetProcess_SpectrumSignal( ...
		NNDatasetProcess_SpectrumSignal.ELCLASS, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NAME, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.DESCRIPTION, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TEMPLATE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.TEMPLATE), ...
		NNDatasetProcess_SpectrumSignal.ID, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.ID), ...
		NNDatasetProcess_SpectrumSignal.LABEL, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.LABEL), ...
		NNDatasetProcess_SpectrumSignal.NOTES, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.NOTES), ...
		NNDatasetProcess_SpectrumSignal.TOSTRING, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.D, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.RAW_DATA_DIR, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.RAW_DATA_DIR), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_START, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.WAVELENGTH_START), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_END, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.WAVELENGTH_END), ...
		NNDatasetProcess_SpectrumSignal.TRANSFORMATION_RULE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.TRANSFORMATION_RULE), ...
		NNDatasetProcess_SpectrumSignal.NORMALIZATION_RULE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.NORMALIZATION_RULE), ...
		NNDatasetProcess_SpectrumSignal.SCALE_FACTOR, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.SCALE_FACTOR), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TRANSFORM_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NORMALIZE_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_LABELS, NNDatasetProcess_SpectrumSignal.getNoValue() ...
		);
	 
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNDatasetProcess_SpectrumSignal.getPropTag(prop));
		switch NNDatasetProcess_SpectrumSignal.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(dproc.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(dproc.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(dproc.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(dproc.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					dproc.checkFormat(dproc.getPropFormat(prop), dproc.getr(prop),dproc.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal']);
				assert( ...
					~isa(dproc.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(dproc.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal']);
	% 			assert( ...
	% 				~isa(dproc.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
	% 				['NNDatasetProcess_SpectrumSignal.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(dproc.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
	% 				['NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				dproc.checkFormat(dproc.getPropFormat(prop), dproc.getr(prop),dproc.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
	% 				['NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal']);
				assert( ...
					~isa(dproc.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(dproc.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(dproc.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(dproc.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					dproc.checkFormat(dproc.getPropFormat(prop), dproc.getr(prop),dproc.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if dproc.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:NNDatasetProcess_SpectrumSignal');
					delete(ancestor(dproc.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(NNDatasetProcess_SpectrumSignal.getProps(Category.RESULT))
		for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
	 
			% excluded props
			if any(prop == [])
				continue
			end
	 
			switch NNDatasetProcess_SpectrumSignal.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						dproc.isLocked(prop), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess_SpectrumSignal.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~dproc.isLocked(prop), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess_SpectrumSignal.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dproc = NNDatasetProcess_SpectrumSignal();
	 
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		TAG = upper(NNDatasetProcess_SpectrumSignal.getPropTag(prop));
		assert( ...
			~dproc.isLocked(prop), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			['NNDatasetProcess_SpectrumSignal.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~dproc.isLocked(TAG), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			['NNDatasetProcess_SpectrumSignal.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	dproc.lock()
	 
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		switch NNDatasetProcess_SpectrumSignal.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					dproc.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~dproc.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dproc = NNDatasetProcess_SpectrumSignal();
	 
	warning_backup = warning('off', 'BRAPH2:NNDatasetProcess_SpectrumSignal');
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		dproc.lock(prop)
		switch NNDatasetProcess_SpectrumSignal.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					dproc.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~dproc.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dproc = NNDatasetProcess_SpectrumSignal();
	 
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		TAG = upper(NNDatasetProcess_SpectrumSignal.getPropTag(prop));
		assert( ...
			dproc.isChecked(prop), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			['NNDatasetProcess_SpectrumSignal.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			dproc.isChecked(TAG), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			['NNDatasetProcess_SpectrumSignal.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	dproc.unchecked()
	 
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		assert( ...
			~dproc.isChecked(prop), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			['NNDatasetProcess_SpectrumSignal.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	dproc.checked()
	 
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		assert( ...
			dproc.isChecked(prop), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			['NNDatasetProcess_SpectrumSignal.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic NNDatasetProcess_SpectrumSignal
	dproc_0 = NNDatasetProcess_SpectrumSignal( ...
		NNDatasetProcess_SpectrumSignal.ELCLASS, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NAME, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.DESCRIPTION, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TEMPLATE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.TEMPLATE), ...
		NNDatasetProcess_SpectrumSignal.ID, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.ID), ...
		NNDatasetProcess_SpectrumSignal.LABEL, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.LABEL), ...
		NNDatasetProcess_SpectrumSignal.NOTES, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.NOTES), ...
		NNDatasetProcess_SpectrumSignal.TOSTRING, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.D, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.RAW_DATA_DIR, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.RAW_DATA_DIR), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_START, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.WAVELENGTH_START), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_END, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.WAVELENGTH_END), ...
		NNDatasetProcess_SpectrumSignal.TRANSFORMATION_RULE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.TRANSFORMATION_RULE), ...
		NNDatasetProcess_SpectrumSignal.NORMALIZATION_RULE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.NORMALIZATION_RULE), ...
		NNDatasetProcess_SpectrumSignal.SCALE_FACTOR, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.SCALE_FACTOR), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TRANSFORM_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NORMALIZE_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_LABELS, NNDatasetProcess_SpectrumSignal.getNoValue() ...
		);
	 
	% NNDatasetProcess_SpectrumSignal with 1st callbacks
	dproc_1 = NNDatasetProcess_SpectrumSignal( ...
		NNDatasetProcess_SpectrumSignal.ELCLASS, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NAME, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.DESCRIPTION, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TEMPLATE, dproc_0.getCallback(4), ..., ...
		NNDatasetProcess_SpectrumSignal.ID, dproc_0.getCallback(5), ..., ...
		NNDatasetProcess_SpectrumSignal.LABEL, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.LABEL), ...
		NNDatasetProcess_SpectrumSignal.NOTES, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.NOTES), ...
		NNDatasetProcess_SpectrumSignal.TOSTRING, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.D, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.RAW_DATA_DIR, dproc_0.getCallback(10), ..., ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_START, dproc_0.getCallback(11), ..., ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_END, dproc_0.getCallback(12), ..., ...
		NNDatasetProcess_SpectrumSignal.TRANSFORMATION_RULE, dproc_0.getCallback(13), ..., ...
		NNDatasetProcess_SpectrumSignal.NORMALIZATION_RULE, dproc_0.getCallback(14), ..., ...
		NNDatasetProcess_SpectrumSignal.SCALE_FACTOR, dproc_0.getCallback(15), ..., ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TRANSFORM_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NORMALIZE_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_LABELS, NNDatasetProcess_SpectrumSignal.getNoValue() ...
		);
	 
	prop_number = NNDatasetProcess_SpectrumSignal.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNDatasetProcess_SpectrumSignal.getPropTag(prop));
		switch NNDatasetProcess_SpectrumSignal.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(dproc_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(dproc_1.get(prop), dproc_0.get(prop)) && ~isa(dproc_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(dproc_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNDatasetProcess_SpectrumSignal with 2nd callbacks
	dproc_2 = NNDatasetProcess_SpectrumSignal( ...
		NNDatasetProcess_SpectrumSignal.ELCLASS, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NAME, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.DESCRIPTION, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TEMPLATE, dproc_1.getCallback(4), ..., ...
		NNDatasetProcess_SpectrumSignal.ID, dproc_1.getCallback(5), ..., ...
		NNDatasetProcess_SpectrumSignal.LABEL, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.LABEL), ...
		NNDatasetProcess_SpectrumSignal.NOTES, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.NOTES), ...
		NNDatasetProcess_SpectrumSignal.TOSTRING, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.D, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.RAW_DATA_DIR, dproc_1.getCallback(10), ..., ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_START, dproc_1.getCallback(11), ..., ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_END, dproc_1.getCallback(12), ..., ...
		NNDatasetProcess_SpectrumSignal.TRANSFORMATION_RULE, dproc_1.getCallback(13), ..., ...
		NNDatasetProcess_SpectrumSignal.NORMALIZATION_RULE, dproc_1.getCallback(14), ..., ...
		NNDatasetProcess_SpectrumSignal.SCALE_FACTOR, dproc_1.getCallback(15), ..., ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TRANSFORM_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NORMALIZE_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_LABELS, NNDatasetProcess_SpectrumSignal.getNoValue() ...
		);
	 
	prop_number = NNDatasetProcess_SpectrumSignal.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNDatasetProcess_SpectrumSignal.getPropTag(prop));
		switch NNDatasetProcess_SpectrumSignal.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(dproc_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(dproc_2.get(prop), dproc_0.get(prop)) && ~isa(dproc_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(dproc_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNDatasetProcess_SpectrumSignal with 3rd callbacks
	dproc_3 = NNDatasetProcess_SpectrumSignal( ...
		NNDatasetProcess_SpectrumSignal.ELCLASS, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NAME, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.DESCRIPTION, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TEMPLATE, dproc_2.getCallback(4), ..., ...
		NNDatasetProcess_SpectrumSignal.ID, dproc_2.getCallback(5), ..., ...
		NNDatasetProcess_SpectrumSignal.LABEL, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.LABEL), ...
		NNDatasetProcess_SpectrumSignal.NOTES, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.NOTES), ...
		NNDatasetProcess_SpectrumSignal.TOSTRING, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.D, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.RAW_DATA_DIR, dproc_2.getCallback(10), ..., ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_START, dproc_2.getCallback(11), ..., ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_END, dproc_2.getCallback(12), ..., ...
		NNDatasetProcess_SpectrumSignal.TRANSFORMATION_RULE, dproc_2.getCallback(13), ..., ...
		NNDatasetProcess_SpectrumSignal.NORMALIZATION_RULE, dproc_2.getCallback(14), ..., ...
		NNDatasetProcess_SpectrumSignal.SCALE_FACTOR, dproc_2.getCallback(15), ..., ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TRANSFORM_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NORMALIZE_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_LABELS, NNDatasetProcess_SpectrumSignal.getNoValue() ...
		);
	 
	prop_number = NNDatasetProcess_SpectrumSignal.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNDatasetProcess_SpectrumSignal.getPropTag(prop));
		switch NNDatasetProcess_SpectrumSignal.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(dproc_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(dproc_3.get(prop), dproc_0.get(prop)) && ~isa(dproc_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(dproc_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	dproc = NNDatasetProcess_SpectrumSignal();
	 
	dproc_copy = dproc.copy();
	 
	assert(dproc_copy ~= dproc, ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_SpectrumSignal.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(dproc_copy, dproc), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_SpectrumSignal.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		value = dproc.getr(prop);
		value_copy = dproc_copy.getr(prop);
		switch NNDatasetProcess_SpectrumSignal.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					'NNDatasetProcess_SpectrumSignal.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
							'NNDatasetProcess_SpectrumSignal.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
							'NNDatasetProcess_SpectrumSignal.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					dproc_copy.isLocked(prop) == dproc.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					'NNDatasetProcess_SpectrumSignal.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					dproc_copy.isChecked(prop) == dproc.isChecked(prop), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					'NNDatasetProcess_SpectrumSignal.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					dproc_copy.getPropSeed(prop) == dproc.getPropSeed(prop), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					'NNDatasetProcess_SpectrumSignal.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	dproc = NNDatasetProcess_SpectrumSignal( ...
		NNDatasetProcess_SpectrumSignal.ELCLASS, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NAME, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.DESCRIPTION, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TEMPLATE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.TEMPLATE), ...
		NNDatasetProcess_SpectrumSignal.ID, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.ID), ...
		NNDatasetProcess_SpectrumSignal.LABEL, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.LABEL), ...
		NNDatasetProcess_SpectrumSignal.NOTES, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.NOTES), ...
		NNDatasetProcess_SpectrumSignal.TOSTRING, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.D, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.RAW_DATA_DIR, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.RAW_DATA_DIR), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_START, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.WAVELENGTH_START), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_END, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.WAVELENGTH_END), ...
		NNDatasetProcess_SpectrumSignal.TRANSFORMATION_RULE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.TRANSFORMATION_RULE), ...
		NNDatasetProcess_SpectrumSignal.NORMALIZATION_RULE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.NORMALIZATION_RULE), ...
		NNDatasetProcess_SpectrumSignal.SCALE_FACTOR, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.SCALE_FACTOR), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TRANSFORM_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NORMALIZE_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_LABELS, NNDatasetProcess_SpectrumSignal.getNoValue() ...
		);
	 
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		if NNDatasetProcess_SpectrumSignal.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal']);
			% dproc.memorize(prop);
			% warning(warning_backup)
		elseif NNDatasetProcess_SpectrumSignal.getPropCategory(prop) == Category.EVANESCENT && dproc.getPropFormat(prop) == Format.HANDLE
			dproc.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:NNDatasetProcess_SpectrumSignal');
			delete(ancestor(dproc.get(prop), 'figure'))
			warning(warning_backup)
		else
			dproc.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	dproc_copy = dproc.copy();
	 
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		value = dproc.getr(prop);
		value_copy = dproc_copy.getr(prop);
		switch NNDatasetProcess_SpectrumSignal.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					'NNDatasetProcess_SpectrumSignal.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
							'NNDatasetProcess_SpectrumSignal.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
							'NNDatasetProcess_SpectrumSignal.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						dproc_copy.isLocked(prop) == dproc.isLocked(prop), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dproc_copy.isChecked(prop) == dproc.isChecked(prop), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dproc_copy.getPropSeed(prop) == dproc.getPropSeed(prop), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	dproc_0 = NNDatasetProcess_SpectrumSignal( ...
		NNDatasetProcess_SpectrumSignal.ELCLASS, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NAME, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.DESCRIPTION, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TEMPLATE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.TEMPLATE), ...
		NNDatasetProcess_SpectrumSignal.ID, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.ID), ...
		NNDatasetProcess_SpectrumSignal.LABEL, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.LABEL), ...
		NNDatasetProcess_SpectrumSignal.NOTES, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.NOTES), ...
		NNDatasetProcess_SpectrumSignal.TOSTRING, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.D, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.RAW_DATA_DIR, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.RAW_DATA_DIR), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_START, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.WAVELENGTH_START), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_END, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.WAVELENGTH_END), ...
		NNDatasetProcess_SpectrumSignal.TRANSFORMATION_RULE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.TRANSFORMATION_RULE), ...
		NNDatasetProcess_SpectrumSignal.NORMALIZATION_RULE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.NORMALIZATION_RULE), ...
		NNDatasetProcess_SpectrumSignal.SCALE_FACTOR, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.SCALE_FACTOR), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TRANSFORM_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NORMALIZE_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_LABELS, NNDatasetProcess_SpectrumSignal.getNoValue() ...
		);
	 
	dproc = NNDatasetProcess_SpectrumSignal( ...
		NNDatasetProcess_SpectrumSignal.ELCLASS, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NAME, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.DESCRIPTION, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TEMPLATE, dproc_0.getCallback(4), ..., ...
		NNDatasetProcess_SpectrumSignal.ID, dproc_0.getCallback(5), ..., ...
		NNDatasetProcess_SpectrumSignal.LABEL, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.LABEL), ...
		NNDatasetProcess_SpectrumSignal.NOTES, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.NOTES), ...
		NNDatasetProcess_SpectrumSignal.TOSTRING, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.D, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.RAW_DATA_DIR, dproc_0.getCallback(10), ..., ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_START, dproc_0.getCallback(11), ..., ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_END, dproc_0.getCallback(12), ..., ...
		NNDatasetProcess_SpectrumSignal.TRANSFORMATION_RULE, dproc_0.getCallback(13), ..., ...
		NNDatasetProcess_SpectrumSignal.NORMALIZATION_RULE, dproc_0.getCallback(14), ..., ...
		NNDatasetProcess_SpectrumSignal.SCALE_FACTOR, dproc_0.getCallback(15), ..., ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TRANSFORM_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NORMALIZE_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_LABELS, NNDatasetProcess_SpectrumSignal.getNoValue() ...
		);
	 
	dproc_copy = dproc.copy();
	dproc_0_copy = dproc_copy.getr('ID').get('EL');
	 
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
		value = dproc.getr(prop);
		value_copy = dproc_copy.getr(prop);
		switch NNDatasetProcess_SpectrumSignal.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					'NNDatasetProcess_SpectrumSignal.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
							'NNDatasetProcess_SpectrumSignal.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
							'NNDatasetProcess_SpectrumSignal.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == dproc_0.getCallback(prop), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal.copy() does not work. The callback should be obtained from NNDatasetProcess_SpectrumSignal.getCallback().' ...
						)
					assert( ...
						value_copy == dproc_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal.copy() does not work. The callback should be obtained from NNDatasetProcess_SpectrumSignal.getCallback().' ...
						)
				end
	 
					assert( ...
						dproc_copy.isLocked(prop) == dproc.isLocked(prop), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dproc_copy.isChecked(prop) == dproc.isChecked(prop), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dproc_copy.getPropSeed(prop) == dproc.getPropSeed(prop), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dproc_template = NNDatasetProcess_SpectrumSignal();
	dproc = NNDatasetProcess_SpectrumSignal('TEMPLATE', dproc_template);
	 
	for prop = 1:1:NNDatasetProcess_SpectrumSignal.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNDatasetProcess_SpectrumSignal.getPropTag(prop));
		switch NNDatasetProcess_SpectrumSignal.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == NNDatasetProcess_SpectrumSignal.TEMPLATE
					assert( ...
						isa(dproc.getr(prop), 'NNDatasetProcess_SpectrumSignal'), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal TEMPLATE does not work. NNDatasetProcess_SpectrumSignal.getr(''TEMPLATE'') should be a NNDatasetProcess_SpectrumSignal element.' ...
						)
					assert( ...
						isa(dproc_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess_SpectrumSignal TEMPLATE does not work. NNDatasetProcess_SpectrumSignal_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(dproc.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess_SpectrumSignal TEMPLATE does not work. NNDatasetProcess_SpectrumSignal.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						dproc.getr(prop).get('EL') == dproc_template && dproc.getr(prop).get('PROP') == prop && strcmp(dproc.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess_SpectrumSignal TEMPLATE does not work. NNDatasetProcess_SpectrumSignal.getr(' TAG ') should be a Callback to dproc_template.' TAG '.'] ...
						)
					assert( ...
						isa(dproc_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess_SpectrumSignal TEMPLATE does not work. NNDatasetProcess_SpectrumSignal_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(dproc.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal TEMPLATE does not work. NNDatasetProcess_SpectrumSignal.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(dproc_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess_SpectrumSignal TEMPLATE does not work. NNDatasetProcess_SpectrumSignal_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dproc = NNDatasetProcess_SpectrumSignal( ...
		NNDatasetProcess_SpectrumSignal.ELCLASS, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NAME, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.DESCRIPTION, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TEMPLATE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.TEMPLATE), ...
		NNDatasetProcess_SpectrumSignal.ID, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.ID), ...
		NNDatasetProcess_SpectrumSignal.LABEL, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.LABEL), ...
		NNDatasetProcess_SpectrumSignal.NOTES, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.NOTES), ...
		NNDatasetProcess_SpectrumSignal.TOSTRING, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.D, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.RAW_DATA_DIR, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.RAW_DATA_DIR), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_START, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.WAVELENGTH_START), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_END, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.WAVELENGTH_END), ...
		NNDatasetProcess_SpectrumSignal.TRANSFORMATION_RULE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.TRANSFORMATION_RULE), ...
		NNDatasetProcess_SpectrumSignal.NORMALIZATION_RULE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.NORMALIZATION_RULE), ...
		NNDatasetProcess_SpectrumSignal.SCALE_FACTOR, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.SCALE_FACTOR), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TRANSFORM_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NORMALIZE_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_LABELS, NNDatasetProcess_SpectrumSignal.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'nndatasetprocess_spectrumsignal_to_be_erased.b2'];
	 
	Element.save(dproc, filename)
	 
	dproc_loaded = Element.load(filename);
	 
	assert( ...
		isequal(dproc.copy(), dproc_loaded), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_SpectrumSignal.save(dproc) and/or NNDatasetProcess_SpectrumSignal.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dproc = NNDatasetProcess_SpectrumSignal( ...
		NNDatasetProcess_SpectrumSignal.ELCLASS, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NAME, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.DESCRIPTION, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TEMPLATE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.TEMPLATE), ...
		NNDatasetProcess_SpectrumSignal.ID, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.ID), ...
		NNDatasetProcess_SpectrumSignal.LABEL, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.LABEL), ...
		NNDatasetProcess_SpectrumSignal.NOTES, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.NOTES), ...
		NNDatasetProcess_SpectrumSignal.TOSTRING, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.D, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.RAW_DATA_DIR, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.RAW_DATA_DIR), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_START, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.WAVELENGTH_START), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH_END, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.WAVELENGTH_END), ...
		NNDatasetProcess_SpectrumSignal.TRANSFORMATION_RULE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.TRANSFORMATION_RULE), ...
		NNDatasetProcess_SpectrumSignal.NORMALIZATION_RULE, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.NORMALIZATION_RULE), ...
		NNDatasetProcess_SpectrumSignal.SCALE_FACTOR, NNDatasetProcess_SpectrumSignal.getPropDefault(NNDatasetProcess_SpectrumSignal.SCALE_FACTOR), ...
		NNDatasetProcess_SpectrumSignal.WAVELENGTH, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.TRANSFORM_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.NORMALIZE_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_DATA, NNDatasetProcess_SpectrumSignal.getNoValue(), ...
		NNDatasetProcess_SpectrumSignal.EXTRACT_LABELS, NNDatasetProcess_SpectrumSignal.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(dproc);
	[dproc_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(dproc_dec ~= dproc, ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess_SpectrumSignal.encodeJSON() or NNDatasetProcess_SpectrumSignal.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) NNDatasetProcess_SpectrumSignal.getPropFormat(prop), num2cell(NNDatasetProcess_SpectrumSignal.getProps())) == Format.HANDLE) && all(cellfun(@(prop) NNDatasetProcess_SpectrumSignal.getPropFormat(prop), num2cell(NNDatasetProcess_SpectrumSignal.getProps())) == Format.NET)
		assert(isequal(dproc_dec, dproc), ...
			[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess_SpectrumSignal.encodeJSON() or NNDatasetProcess_SpectrumSignal.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: Construction of an Empty Spectrum Dataset
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	dproc = NNDatasetProcess_SpectrumSignal();
	d_sp = dproc.get('D');
	
	assert(isequal(d_sp.get('DP_DICT').get('LENGTH'), 0), ...
	    [BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
	    'NNDatasetProcess_SpectrumSignal does not construct the dataset correctly. The input value is not derived correctly.' ...
	    )
end

%% Test 13: Construction of a MNIST Dataset
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	% % % dproc = NNDatasetProcess_MNIST( ...
	% % %     'MNIST_IMAGE_FILE', [fileparts(which('NNDatasetProcess_MNIST')) filesep 'mnist_data' filesep 'train-images-idx3-ubyte.gz'], ...
	% % %     'MNIST_LABEL_FILE', [fileparts(which('NNDatasetProcess_MNIST')) filesep 'mnist_data' filesep 'train-labels-idx1-ubyte.gz'] ...
	% % %     );
	% % % d_mnist = dproc.get('D');
	% % % 
	% % % assert(isequal(d_mnist.get('DP_DICT').get('LENGTH'), 60000), ...
	% % %     [BRAPH2.STR ':NNDatasetProcess_MNIST:' BRAPH2.FAIL_TEST], ...
	% % %     'NNDatasetProcess_MNIST does not construct the dataset correctly. The input value is not derived correctly.' ...
	% % %     )
end

%% Test 14: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':NNDatasetProcess_SpectrumSignal:' BRAPH2.FAIL_TEST], ...
		[' When testing NNDatasetProcess_SpectrumSignal no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 15: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

